"""Registered data providers with purpose, coverage, authority, cost, fallbacks."""

from __future__ import annotations

from typing import Any

PROVIDERS: dict[str, dict[str, Any]] = {
    "groww": {
        "name": "Groww API",
        "purpose": "Indian market prices",
        "supports": ["price", "ohlc", "volume", "historical_charts", "valuation", "pe", "fundamentals"],
        "does_not_support": ["conference_calls", "management_commentary"],
        "coverage": "India equities",
        "latency_ms": 80,
        "freshness": "intraday",
        "tier": 2,
        "cost": 1,
        "reliability": 0.95,
        "expected_value": "High",
        "fallback_providers": ["indianapi", "yahoo_finance"],
        "internal": False,
    },
    "indianapi": {
        "name": "IndianAPI",
        "purpose": "India market & fundamentals bridge",
        "supports": ["price", "fundamentals", "valuation", "pe", "peer_metrics"],
        "does_not_support": ["sec_filings"],
        "coverage": "India",
        "latency_ms": 100,
        "freshness": "daily",
        "tier": 2,
        "cost": 1,
        "reliability": 0.9,
        "expected_value": "High",
        "fallback_providers": ["yahoo_finance", "groww"],
        "internal": False,
    },
    "yahoo_finance": {
        "name": "Yahoo Finance",
        "purpose": "Global market data",
        "supports": ["price", "ohlc", "historical_charts", "valuation", "fundamentals"],
        "does_not_support": ["india_ir_pdfs"],
        "coverage": "Global",
        "latency_ms": 120,
        "freshness": "intraday",
        "tier": 2,
        "cost": 1,
        "reliability": 0.88,
        "expected_value": "Medium",
        "fallback_providers": ["finnhub", "polygon"],
        "internal": False,
    },
    "finnhub": {
        "name": "Finnhub",
        "purpose": "Market + news snippets",
        "supports": ["price", "news", "fundamentals"],
        "does_not_support": ["annual_report"],
        "coverage": "Global",
        "latency_ms": 110,
        "freshness": "intraday",
        "tier": 2,
        "cost": 2,
        "reliability": 0.87,
        "expected_value": "Medium",
        "fallback_providers": ["yahoo_finance"],
        "internal": False,
    },
    "polygon": {
        "name": "Polygon",
        "purpose": "Market ticks / aggregates",
        "supports": ["price", "ohlc", "volume"],
        "does_not_support": ["filings"],
        "coverage": "Global",
        "latency_ms": 90,
        "freshness": "live",
        "tier": 2,
        "cost": 2,
        "reliability": 0.9,
        "expected_value": "Medium",
        "fallback_providers": ["yahoo_finance"],
        "internal": False,
    },
    "fmp": {
        "name": "Financial Modeling Prep",
        "purpose": "Fundamentals & ratios",
        "supports": ["fundamentals", "financials", "peer_metrics", "valuation"],
        "does_not_support": ["conference_calls"],
        "coverage": "Global",
        "latency_ms": 130,
        "freshness": "daily",
        "tier": 2,
        "cost": 2,
        "reliability": 0.86,
        "expected_value": "High",
        "fallback_providers": ["indianapi", "yahoo_finance"],
        "internal": False,
    },
    "sec_edgar": {
        "name": "SEC EDGAR",
        "purpose": "US official filings",
        "supports": ["annual_report", "quarterly_report", "filings"],
        "does_not_support": ["india_ir"],
        "coverage": "US",
        "latency_ms": 200,
        "freshness": "daily",
        "tier": 1,
        "cost": 2,
        "reliability": 0.98,
        "expected_value": "Very High",
        "fallback_providers": ["company_ir"],
        "internal": False,
    },
    "nse": {
        "name": "NSE",
        "purpose": "India exchange official",
        "supports": ["annual_report", "quarterly_report", "filings", "price", "earnings"],
        "does_not_support": ["global_peers"],
        "coverage": "India",
        "latency_ms": 150,
        "freshness": "intraday",
        "tier": 1,
        "cost": 1,
        "reliability": 0.97,
        "expected_value": "Very High",
        "fallback_providers": ["bse", "company_ir"],
        "internal": False,
    },
    "bse": {
        "name": "BSE",
        "purpose": "India exchange official",
        "supports": ["annual_report", "quarterly_report", "filings", "earnings"],
        "does_not_support": ["global_peers"],
        "coverage": "India",
        "latency_ms": 160,
        "freshness": "intraday",
        "tier": 1,
        "cost": 1,
        "reliability": 0.96,
        "expected_value": "Very High",
        "fallback_providers": ["nse", "company_ir"],
        "internal": False,
    },
    "rbi": {
        "name": "RBI",
        "purpose": "India monetary / banking policy",
        "supports": ["macro", "rates", "policy"],
        "does_not_support": ["equity_prices"],
        "coverage": "India macro",
        "latency_ms": 180,
        "freshness": "daily",
        "tier": 1,
        "cost": 1,
        "reliability": 0.99,
        "expected_value": "Very High",
        "fallback_providers": ["fred", "imf"],
        "internal": False,
    },
    "sebi": {
        "name": "SEBI",
        "purpose": "India securities regulation",
        "supports": ["regulation", "policy"],
        "does_not_support": ["prices"],
        "coverage": "India",
        "latency_ms": 200,
        "freshness": "daily",
        "tier": 1,
        "cost": 1,
        "reliability": 0.98,
        "expected_value": "High",
        "fallback_providers": ["nse"],
        "internal": False,
    },
    "world_bank": {
        "name": "World Bank",
        "purpose": "Development macro series",
        "supports": ["macro"],
        "does_not_support": ["equity_prices"],
        "coverage": "Global",
        "latency_ms": 220,
        "freshness": "weekly",
        "tier": 1,
        "cost": 1,
        "reliability": 0.97,
        "expected_value": "High",
        "fallback_providers": ["imf", "fred"],
        "internal": False,
    },
    "imf": {
        "name": "IMF",
        "purpose": "Global macro outlook",
        "supports": ["macro"],
        "does_not_support": ["equity_prices"],
        "coverage": "Global",
        "latency_ms": 220,
        "freshness": "weekly",
        "tier": 1,
        "cost": 2,
        "reliability": 0.97,
        "expected_value": "High",
        "fallback_providers": ["fred", "world_bank"],
        "internal": False,
    },
    "fred": {
        "name": "FRED",
        "purpose": "US / global economic series",
        "supports": ["macro", "rates", "policy"],
        "does_not_support": ["company_filings"],
        "coverage": "Global",
        "latency_ms": 150,
        "freshness": "daily",
        "tier": 1,
        "cost": 2,
        "reliability": 0.98,
        "expected_value": "High",
        "fallback_providers": ["imf", "rbi"],
        "internal": False,
    },
    "company_ir": {
        "name": "Company IR",
        "purpose": "Official company communication",
        "supports": [
            "annual_report",
            "quarterly_report",
            "filings",
            "earnings",
            "presentation",
            "guidance",
            "transcript",
        ],
        "does_not_support": ["live_tape"],
        "coverage": "Issuer",
        "latency_ms": 250,
        "freshness": "quarterly",
        "tier": 1,
        "cost": 2,
        "reliability": 0.99,
        "expected_value": "Very High",
        "fallback_providers": ["nse", "bse"],
        "internal": False,
    },
    "annual_reports": {
        "name": "Annual Reports",
        "purpose": "Annual report corpus",
        "supports": ["annual_report", "filings"],
        "tier": 1,
        "cost": 2,
        "reliability": 0.98,
        "expected_value": "Very High",
        "fallback_providers": ["company_ir", "nse"],
        "freshness": "quarterly",
        "latency_ms": 240,
        "coverage": "Issuer",
        "internal": False,
    },
    "quarterly_reports": {
        "name": "Quarterly Reports",
        "purpose": "Quarterly results corpus",
        "supports": ["quarterly_report", "earnings", "guidance"],
        "tier": 1,
        "cost": 2,
        "reliability": 0.98,
        "expected_value": "Very High",
        "fallback_providers": ["company_ir", "nse"],
        "freshness": "quarterly",
        "latency_ms": 240,
        "coverage": "Issuer",
        "internal": False,
    },
    "investor_presentations": {
        "name": "Investor Presentations",
        "purpose": "IR decks",
        "supports": ["presentation", "guidance"],
        "tier": 1,
        "cost": 1,
        "reliability": 0.96,
        "expected_value": "High",
        "fallback_providers": ["company_ir"],
        "freshness": "quarterly",
        "latency_ms": 200,
        "coverage": "Issuer",
        "internal": False,
    },
    "conference_calls": {
        "name": "Conference Calls",
        "purpose": "Earnings call transcripts",
        "supports": ["transcript", "guidance"],
        "tier": 1,
        "cost": 2,
        "reliability": 0.95,
        "expected_value": "Very High",
        "fallback_providers": ["company_ir"],
        "freshness": "quarterly",
        "latency_ms": 220,
        "coverage": "Issuer",
        "internal": False,
    },
    "press_releases": {
        "name": "Press Releases",
        "purpose": "Official press",
        "supports": ["press", "news"],
        "tier": 1,
        "cost": 1,
        "reliability": 0.94,
        "expected_value": "High",
        "fallback_providers": ["company_ir", "nse"],
        "freshness": "daily",
        "latency_ms": 180,
        "coverage": "Issuer",
        "internal": False,
    },
    "exa": {
        "name": "Exa Neural Search",
        "purpose": "Semantic research / industry / publication discovery",
        "supports": ["research", "industry_report", "publications", "news", "web"],
        "does_not_support": ["live_prices", "filings_pdf"],
        "coverage": "Global web (research-weighted)",
        "latency_ms": 700,
        "freshness": "daily",
        "tier": 3,
        "cost": 2,
        "reliability": 0.9,
        "expected_value": "High",
        "fallback_providers": ["firecrawl", "tavily"],
        "internal": False,
        "env_key": "EXA_API_KEY",
        "role": "search",
    },
    "firecrawl": {
        "name": "Firecrawl",
        "purpose": "Deep web search + URL→markdown page enrichment",
        "supports": ["web", "markdown", "research", "news", "html"],
        "does_not_support": ["live_prices"],
        "coverage": "Global web pages",
        "latency_ms": 1200,
        "freshness": "live",
        "tier": 3,
        "cost": 2,
        "reliability": 0.88,
        "expected_value": "High",
        "fallback_providers": ["browserbase", "exa"],
        "internal": False,
        "env_key": "FIRECRAWL_API_KEY",
        "role": "enrichment",
    },
    "browserbase": {
        "name": "Browserbase",
        "purpose": "JS-heavy / blocked page fetch fallback (exchanges, IR portals)",
        "supports": ["html", "markdown", "js_render", "hard_hosts"],
        "does_not_support": ["semantic_search"],
        "coverage": "Hard public pages",
        "latency_ms": 2500,
        "freshness": "live",
        "tier": 4,
        "cost": 3,
        "reliability": 0.85,
        "expected_value": "Medium",
        "fallback_providers": ["playwright", "firecrawl"],
        "internal": False,
        "env_key": "BROWSERBASE_API_KEY",
        "role": "fallback_fetch",
    },
    "playwright": {
        "name": "Playwright Chromium",
        "purpose": "Self-hosted headless browser for JS IR/exchange pages + free web search",
        "supports": ["html", "js_render", "web", "investor_relations", "hard_hosts", "pdf_links"],
        "does_not_support": ["live_prices"],
        "coverage": "Public JS pages + DuckDuckGo HTML search",
        "latency_ms": 3000,
        "freshness": "live",
        "tier": 3,
        "cost": 0,
        "reliability": 0.86,
        "expected_value": "High",
        "fallback_providers": ["firecrawl", "browserbase", "exa"],
        "internal": False,
        "env_key": "FAA_PLAYWRIGHT",
        "role": "js_render_and_search",
    },
    "tavily": {
        "name": "Tavily Search",
        "purpose": "General + news web search coverage",
        "supports": ["news", "web", "research"],
        "coverage": "Global web",
        "latency_ms": 600,
        "freshness": "daily",
        "tier": 3,
        "cost": 2,
        "reliability": 0.9,
        "expected_value": "Medium",
        "fallback_providers": ["exa", "firecrawl"],
        "internal": False,
        "env_key": "TAVILY_API_KEY",
        "role": "search",
    },
    "fil": {
        "name": "FIL",
        "purpose": "Internal filing memory",
        "supports": ["annual_report", "quarterly_report", "filings", "earnings", "transcript"],
        "tier": 1,
        "cost": 0,
        "reliability": 0.99,
        "expected_value": "Very High",
        "fallback_providers": ["company_ir"],
        "freshness": "quarterly",
        "latency_ms": 10,
        "coverage": "Internal",
        "internal": True,
    },
    "ikg": {
        "name": "IKG",
        "purpose": "Internal knowledge graph",
        "supports": ["graph", "memory", "peer_metrics", "portfolio", "exposure"],
        "tier": 1,
        "cost": 0,
        "reliability": 0.98,
        "expected_value": "Very High",
        "fallback_providers": [],
        "freshness": "daily",
        "latency_ms": 8,
        "coverage": "Internal",
        "internal": True,
    },
    "pil": {
        "name": "PIL",
        "purpose": "Peer intelligence layer",
        "supports": ["peer_metrics", "valuation", "fundamentals"],
        "tier": 1,
        "cost": 0,
        "reliability": 0.97,
        "expected_value": "Very High",
        "fallback_providers": ["indianapi"],
        "freshness": "daily",
        "latency_ms": 12,
        "coverage": "Internal",
        "internal": True,
    },
    "eil": {
        "name": "EIL",
        "purpose": "Evidence intelligence layer",
        "supports": ["evidence", "citations", "news", "press"],
        "tier": 1,
        "cost": 0,
        "reliability": 0.97,
        "expected_value": "Very High",
        "fallback_providers": [],
        "freshness": "daily",
        "latency_ms": 12,
        "coverage": "Internal",
        "internal": True,
    },
    "ilm": {
        "name": "ILM",
        "purpose": "Institutional memory",
        "supports": ["memory", "graph", "portfolio", "exposure"],
        "tier": 1,
        "cost": 0,
        "reliability": 0.96,
        "expected_value": "Very High",
        "fallback_providers": [],
        "freshness": "existing_knowledge",
        "latency_ms": 8,
        "coverage": "Internal",
        "internal": True,
    },
}

INTERNAL_PROVIDERS: list[str] = [k for k, v in PROVIDERS.items() if v.get("internal")]


def provider_authority_score(provider_id: str) -> float:
    meta = PROVIDERS.get(provider_id) or {}
    tier = int(meta.get("tier") or 5)
    reliability = float(meta.get("reliability") or 0.7)
    # Tier 1 → ~1.0, Tier 5 → ~0.4
    return round(max(0.0, min(1.0, (1.15 - 0.15 * tier) * 0.7 + reliability * 0.3)), 4)


def get_provider(provider_id: str) -> dict[str, Any] | None:
    return PROVIDERS.get(provider_id)


def all_providers() -> list[str]:
    return list(PROVIDERS.keys())


def registry_stats() -> dict[str, Any]:
    internal = [k for k, v in PROVIDERS.items() if v.get("internal")]
    external = [k for k, v in PROVIDERS.items() if not v.get("internal")]
    return {
        "provider_count": len(PROVIDERS),
        "internal_count": len(internal),
        "external_count": len(external),
        "internal": internal,
        "external": external,
        "tier1_count": sum(1 for v in PROVIDERS.values() if v.get("tier") == 1),
    }
