"""Configurable source reliability and fact normalisation — never hardcoded in logic."""

from __future__ import annotations

# Initial trust scores by source category / doc type (configurable).
SOURCE_RELIABILITY: dict[str, float] = {
    "annual_report": 1.00,
    "quarterly_filing": 0.99,
    "quarterly_result": 0.99,
    "nse_filing": 0.99,
    "bse_filing": 0.99,
    "nse": 0.99,
    "bse": 0.99,
    "company_press_release": 0.95,
    "press_release": 0.95,
    "investor_presentation": 0.93,
    "conference_call": 0.92,
    "earnings_transcript": 0.92,
    "government_publication": 0.98,
    "sebi": 0.98,
    "rbi": 0.98,
    "mospi": 0.98,
    "mof": 0.98,
    "ministry_of_finance": 0.98,
    "pib": 0.95,
    "fred": 0.97,
    "imf": 0.96,
    "worldbank": 0.96,
    "credit_rating_agency": 0.90,
    "broker_research": 0.80,
    "news_article": 0.70,
    "company_ir": 0.94,
    "esg_report": 0.90,
    "unknown": 0.30,
}


# Canonical fact normalisation map: alias → canonical field
FACT_NORMALISATION: dict[str, str] = {
    "net_profit": "pat",
    "profit_after_tax": "pat",
    "pat": "pat",
    "profit after tax": "pat",
    "net profit": "pat",
    "revenue": "revenue",
    "sales": "revenue",
    "turnover": "revenue",
    "operating_revenue": "revenue",
    "operating revenue": "revenue",
    "total_income": "revenue",
    "ebitda": "ebitda",
    "operating_profit": "ebitda",
    "margins": "margins",
    "operating_margin": "margins",
    "ebitda_margin": "margins",
    "debt": "debt",
    "net_debt": "debt",
    "borrowings": "debt",
    "capex": "capex",
    "capital_expenditure": "capex",
    "guidance": "guidance",
    "outlook": "guidance",
    "risks": "risks",
    "risk": "risks",
    "opportunities": "opportunities",
    "shareholding": "shareholding",
    "promoter_holding": "shareholding",
    "business_model": "business_model",
    "products": "products",
    "management": "management",
    "board": "board",
    "ceo": "management",
}


# Timeline event keywords → event type
TIMELINE_EVENT_HINTS: dict[str, tuple[str, ...]] = {
    "ceo_appointment": ("ceo", "appointed", "managing director"),
    "acquisition": ("acquisition", "acquired", "buyout", "m&a"),
    "capacity_expansion": ("capacity", "expansion", "commissioning", "plant"),
    "dividend": ("dividend",),
    "split": ("stock split", "share split"),
    "bonus": ("bonus issue", "bonus share"),
    "buyback": ("buyback", "buy-back"),
    "guidance_revision": ("guidance", "outlook revised", "raises guidance", "cuts guidance"),
    "debt_raise": ("bond", "debenture", "debt raise", "refinance"),
    "credit_rating": ("rating", "moodys", "crisil", "icra", "care rating"),
    "board_change": ("board", "director appointed", "director resign"),
    "legal_action": ("litigation", "lawsuit", "legal", "sebi order"),
    "esg_milestone": ("esg", "sustainability", "net zero", "carbon"),
    "plant_commissioning": ("commissioned", "plant commissioning", "inaugurat"),
}


DEFAULT_SOURCES: list[dict] = [
    {"source_id": "src_company_ir", "name": "Company IR", "category": "company_ir", "authority_level": "primary"},
    {"source_id": "src_nse", "name": "NSE", "category": "nse", "organisation": "National Stock Exchange", "country": "IN"},
    {"source_id": "src_bse", "name": "BSE", "category": "bse", "organisation": "BSE Limited", "country": "IN"},
    {"source_id": "src_sebi", "name": "SEBI", "category": "sebi", "organisation": "SEBI", "country": "IN"},
    {"source_id": "src_rbi", "name": "RBI", "category": "rbi", "organisation": "Reserve Bank of India", "country": "IN"},
    {"source_id": "src_mospi", "name": "MOSPI", "category": "mospi", "organisation": "MOSPI", "country": "IN"},
    {"source_id": "src_mof", "name": "Ministry of Finance", "category": "mof", "organisation": "MoF", "country": "IN"},
    {"source_id": "src_pib", "name": "PIB", "category": "pib", "organisation": "Press Information Bureau", "country": "IN"},
    {"source_id": "src_fred", "name": "FRED", "category": "fred", "organisation": "St. Louis Fed", "country": "US"},
    {"source_id": "src_imf", "name": "IMF", "category": "imf", "organisation": "IMF", "country": "INTL"},
    {"source_id": "src_worldbank", "name": "World Bank", "category": "worldbank", "organisation": "World Bank", "country": "INTL"},
    {"source_id": "src_annual_report", "name": "Annual Report", "category": "annual_report", "authority_level": "statutory"},
    {"source_id": "src_quarterly", "name": "Quarterly Results", "category": "quarterly_result", "authority_level": "statutory"},
    {"source_id": "src_presentation", "name": "Investor Presentation", "category": "investor_presentation"},
    {"source_id": "src_call", "name": "Conference Call", "category": "conference_call"},
    {"source_id": "src_press", "name": "Company Press Release", "category": "press_release"},
    {"source_id": "src_broker", "name": "Broker Research", "category": "broker_research"},
    {"source_id": "src_news", "name": "News Article", "category": "news_article"},
    {"source_id": "src_unknown", "name": "Unknown Source", "category": "unknown"},
]
