/**
 * AGIB v3 Intelligence Map — frozen institutional topology catalog.
 * Soft-wire only. Architecture v1.0.1 LOCKED.
 */

export const PIPELINE_PATH = [
  'FIL',
  'FDI',
  'MII',
  'ACI',
  'EIL',
  'FRE',
  'IERE',
  'BOOKS',
  'PIL',
  'CIG',
  'IKG',
  'FIE',
  'ILM',
  'SSL',
  'IAF',
  'IRSP',
  'IC',
  'PIO',
  'IDE_V2',
  'CIO',
  'IRW',
  'AC',
  'IIS',
];

export const DATA_SOURCES = [
  { id: 'indianapi', name: 'IndianAPI', kind: 'market' },
  { id: 'groww', name: 'Groww API', kind: 'market' },
  { id: 'yahoo', name: 'Yahoo Finance', kind: 'market' },
  { id: 'finnhub', name: 'Finnhub', kind: 'market' },
  { id: 'fmp', name: 'FMP', kind: 'fundamentals' },
  { id: 'nse', name: 'NSE', kind: 'exchange' },
  { id: 'bse', name: 'BSE', kind: 'exchange' },
  { id: 'rbi', name: 'RBI', kind: 'macro' },
  { id: 'sebi', name: 'SEBI', kind: 'regulatory' },
  { id: 'company_ir', name: 'Company IR', kind: 'filings' },
  { id: 'annual', name: 'Annual Reports', kind: 'filings' },
  { id: 'quarterly', name: 'Quarterly Reports', kind: 'filings' },
  { id: 'calls', name: 'Conference Calls', kind: 'filings' },
  { id: 'presentations', name: 'Investor Presentations', kind: 'filings' },
  { id: 'broker', name: 'Broker Research', kind: 'research' },
  { id: 'news', name: 'News', kind: 'news' },
  { id: 'macro', name: 'Macro APIs', kind: 'macro' },
  { id: 'fred', name: 'FRED', kind: 'macro' },
  { id: 'imf', name: 'IMF', kind: 'macro' },
  { id: 'worldbank', name: 'World Bank', kind: 'macro' },
  { id: 'commodity', name: 'Commodity APIs', kind: 'macro' },
  { id: 'fx', name: 'Currency APIs', kind: 'macro' },
];

export const ANALYST_ROLES = [
  'Business',
  'Financial',
  'Valuation',
  'Risk',
  'Sector',
  'Macro',
  'Management',
  'Ownership',
  'Market',
];

/** @typedef {'sources'|'evidence'|'core'|'reasoning'|'decision'|'publication'|'validation'} ZoneId */

/**
 * @type {Array<{
 *  id: string,
 *  code: string,
 *  name: string,
 *  purpose: string,
 *  zone: ZoneId,
 *  accent: 'blue'|'green'|'gold'|'purple'|'orange'|'red',
 *  healthKey: string|null,
 *  route: string|null,
 *  docs: string,
 *  inputs: string[],
 *  outputs: string[],
 *  upstream: string[],
 *  downstream: string[],
 *  version: string,
 *  critical: boolean,
 * }>}
 */
export const LAYERS = [
  {
    id: 'FIL',
    code: 'FIL',
    name: 'Filing Intelligence',
    purpose: 'Reads filings into structured evidence.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'fil',
    route: '/filing-intelligence/health',
    docs: '/admin/institutional-stack',
    inputs: ['Annual reports', 'Quarterly filings', 'Company IR PDFs'],
    outputs: ['Evidence objects', 'Filing facts', 'Citation anchors'],
    upstream: ['DATA'],
    downstream: ['FDI', 'MII', 'ACI', 'EIL'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'FDI',
    code: 'FDI',
    name: 'Filing Diff',
    purpose: 'What materially changed vs prior period?',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'fdi',
    route: '/filing-diff/health',
    docs: '/admin/institutional-stack',
    inputs: ['Current filing package', 'Prior filing package'],
    outputs: ['Material deltas', 'Risk deltas', 'Narrative shifts'],
    upstream: ['FIL'],
    downstream: ['EIL', 'CIG', 'IAF'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'MII',
    code: 'MII',
    name: 'Management Intelligence',
    purpose: 'Guidance tone, credibility, and commitments.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'mii',
    route: '/management-intelligence/health',
    docs: '/admin/institutional-stack',
    inputs: ['Conference calls', 'MD&A', 'Presentations'],
    outputs: ['Guidance objects', 'Tone score', 'Commitment ledger'],
    upstream: ['FIL', 'DATA'],
    downstream: ['EIL', 'IAF', 'IC'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'ACI',
    code: 'ACI',
    name: 'Accounting Intelligence',
    purpose: 'Earnings quality, red flags, accounting risk.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'aci',
    route: '/accounting-intelligence/health',
    docs: '/admin/accounting-intelligence',
    inputs: ['Financial statements', 'Notes', 'Cash flow'],
    outputs: ['Quality score', 'Red flags', 'Adjustments'],
    upstream: ['FIL'],
    downstream: ['EIL', 'IAF', 'PIO'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'EIL',
    code: 'EIL',
    name: 'Evidence Intelligence',
    purpose: 'Verified evidence pack for downstream reasoners.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'eil',
    route: '/academy/evidence/health',
    docs: '/admin/evidence',
    inputs: ['FIL/FDI/MII/ACI outputs'],
    outputs: ['Evidence graph', 'Trust scores', 'Conflicts'],
    upstream: ['FIL', 'FDI', 'MII', 'ACI'],
    downstream: ['PIL', 'CIG', 'IKG', 'IAF'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'PIL',
    code: 'PIL',
    name: 'Peer Intelligence',
    purpose: 'Relative positioning vs sector peers.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'pil',
    route: '/peer-intelligence/health',
    docs: '/admin/portfolio-intelligence',
    inputs: ['Evidence pack', 'Peer universe', 'Market comps'],
    outputs: ['Peer ranks', 'Relative multiples', 'Gap map'],
    upstream: ['EIL', 'DATA'],
    downstream: ['CIG', 'IAF', 'PIO'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'FAA',
    code: 'FAA',
    name: 'Finance Acquisition Agent',
    purpose: 'Acquires external finance artifacts into the corpus.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'faa',
    route: '/faa/health',
    docs: '/admin/open-intelligence',
    inputs: ['Connector feeds', 'Schedulers'],
    outputs: ['Raw documents', 'Acquisition receipts'],
    upstream: ['DATA'],
    downstream: ['FRE', 'FIL', 'EIL'],
    version: '3.0',
    critical: false,
  },
  {
    id: 'FRE',
    code: 'FRE',
    name: 'Finance Retrieval Engine',
    purpose: 'Retrieves ranked finance context for reasoning.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'fre',
    route: '/fre/health',
    docs: '/admin/open-intelligence',
    inputs: ['Query', 'FAA corpus', 'Evidence index'],
    outputs: ['Ranked chunks', 'Source trails'],
    upstream: ['FAA', 'EIL'],
    downstream: ['IERE', 'CIG', 'IKG', 'IAF'],
    version: '3.0',
    critical: false,
  },
  {
    id: 'IERE',
    code: 'IERE',
    name: 'Institutional Evidence Retrieval',
    purpose: 'Ranks and assembles structured institutional evidence packs for every question.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'iere',
    route: '/evidence/health',
    docs: '/admin/intelligence-map',
    inputs: [
      'Question',
      'Knowledge Factory objects',
      'Institutional documents',
      'Live data',
      'Research Office',
    ],
    outputs: ['Ranked evidence packs', 'Citations', 'Evidence graph', 'PIT replay packs'],
    upstream: ['FRE', 'FIL', 'EIL', 'FAA'],
    downstream: ['AskAGI', 'IRSP', 'IAF', 'IRW'],
    version: '3.2',
    critical: true,
  },
  {
    id: 'CIG',
    code: 'CIG',
    name: 'Causal Intelligence Graph',
    purpose: 'Cause → effect chains across events and drivers.',
    zone: 'core',
    accent: 'green',
    healthKey: 'cig',
    route: '/causal-intelligence/health',
    docs: '/admin/causal-intelligence',
    inputs: ['Evidence', 'Events', 'Peer deltas'],
    outputs: ['Causal edges', 'Driver attributions'],
    upstream: ['EIL', 'PIL', 'FDI'],
    downstream: ['IKG', 'FIE', 'IAF'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'IKG',
    code: 'IKG',
    name: 'Institutional Knowledge Graph',
    purpose: 'Entities, relationships, and institutional memory links.',
    zone: 'core',
    accent: 'green',
    healthKey: 'ikg',
    route: '/knowledge-graph/health',
    docs: '/admin/knowledge-graph',
    inputs: ['Evidence', 'Causal edges', 'Company entities'],
    outputs: ['Graph nodes', 'Paths', 'Context packages'],
    upstream: ['EIL', 'CIG'],
    downstream: ['FIE', 'ILM', 'IAF'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'FIE',
    code: 'FIE',
    name: 'Forecast Intelligence',
    purpose: 'Scenario forecasts with confidence bands.',
    zone: 'core',
    accent: 'green',
    healthKey: 'fie',
    route: '/forecast/health',
    docs: '/admin/forecast-intelligence',
    inputs: ['Graph context', 'Causal drivers', 'History'],
    outputs: ['Scenarios', 'Probability bands', 'Watchpoints'],
    upstream: ['CIG', 'IKG'],
    downstream: ['ILM', 'SSL', 'IAF', 'IDE_V2'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'ILM',
    code: 'ILM',
    name: 'Learning & Memory',
    purpose: 'Institutional memory + model improvement events (MIE).',
    zone: 'core',
    accent: 'green',
    healthKey: 'ilm',
    route: '/ilm/health',
    docs: '/admin/institutional-memory',
    inputs: ['Decisions', 'Outcomes', 'Committee minutes'],
    outputs: ['Memory objects', 'Learning updates', 'Thesis revisions'],
    upstream: ['IKG', 'FIE', 'IDE_V2'],
    downstream: ['SSL', 'IAF', 'IDE_V2'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'SSL',
    code: 'SSL',
    name: 'Simulation & Strategy Lab',
    purpose: 'Portfolio and thesis stress simulations.',
    zone: 'core',
    accent: 'green',
    healthKey: 'ssl',
    route: '/simulation/health',
    docs: '/admin/simulation-lab',
    inputs: ['Forecasts', 'Portfolio state', 'Risk factors'],
    outputs: ['Simulation runs', 'Stress outcomes', 'Strategy deltas'],
    upstream: ['FIE', 'ILM', 'PIO'],
    downstream: ['IAF', 'PIO', 'IDE_V2'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'AIL',
    code: 'AIL',
    name: 'Intelligence Layer V2',
    purpose: 'Supporting analyst intelligence monitor.',
    zone: 'core',
    accent: 'green',
    healthKey: 'ail',
    route: '/ail/health',
    docs: '/admin/mission-control',
    inputs: ['Monitor universe', 'Evidence deltas'],
    outputs: ['Alerts', 'Living dossiers'],
    upstream: ['EIL', 'IKG'],
    downstream: ['IAF', 'CompanyAnalysis'],
    version: '3.0',
    critical: false,
  },
  {
    id: 'IAF',
    code: 'IAF',
    name: 'Institutional Analysts',
    purpose: 'Specialist opinions across institutional desks.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'iaf',
    route: '/institutional-analysts/health',
    docs: '/admin/investment-intelligence',
    inputs: ['Evidence', 'Peers', 'Forecasts', 'Graph paths'],
    outputs: ['Analyst memos', 'Votes', 'Conflicts'],
    upstream: ['EIL', 'PIL', 'CIG', 'FIE', 'SSL'],
    downstream: ['IC'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'IC',
    code: 'IC',
    name: 'Investment Committee',
    purpose: 'Deliberation, consensus, minority, minutes.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'ic',
    route: '/investment-committee/health',
    docs: '/admin/investment-office',
    inputs: ['Analyst memos', 'Conflicts', 'Risk notes'],
    outputs: ['Consensus', 'Minutes', 'Action items'],
    upstream: ['IAF'],
    downstream: ['PIO', 'IDE_V2', 'CIO'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'PIO',
    code: 'PIO',
    name: 'Portfolio Intelligence Office',
    purpose: 'Diversification, factor risk, suitability.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'pio',
    route: '/portfolio-intelligence/health',
    docs: '/admin/portfolio-intelligence',
    inputs: ['Committee view', 'Holdings', 'Simulations'],
    outputs: ['Portfolio quality', 'Overlap', 'Stress pack'],
    upstream: ['IC', 'SSL', 'PIL'],
    downstream: ['IDE_V2', 'CIO'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'IDE_V2',
    code: 'IDE V2',
    name: 'Decision Engine V2',
    purpose: 'Final institutional decision package (frozen tip).',
    zone: 'decision',
    accent: 'purple',
    healthKey: 'idev2',
    route: '/decision-engine-v2/health',
    docs: '/admin/decision-engine-v2',
    inputs: ['Committee', 'Portfolio', 'Forecast', 'Memory'],
    outputs: ['Decision package', 'Gates', 'Audit trail'],
    upstream: ['IC', 'PIO', 'FIE', 'ILM', 'SSL'],
    downstream: ['CIO', 'IRW', 'ILM'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'CompanyAnalysis',
    code: 'CA',
    name: 'Company Analysis',
    purpose: 'Company-specific institutional reasoning pack.',
    zone: 'decision',
    accent: 'purple',
    healthKey: 'company_analysis',
    route: '/company-analysis/health',
    docs: '/admin/company-analysis',
    inputs: ['Evidence', 'Dossier', 'Decision package'],
    outputs: ['Company report', 'Thesis snapshot'],
    upstream: ['EIL', 'IDE_V2', 'AIL'],
    downstream: ['IRW', 'AskAGI'],
    version: '3.0',
    critical: false,
  },
  {
    id: 'CIO',
    code: 'CIO',
    name: 'Chief Investment Office',
    purpose: 'Executive decision ownership and publication gate.',
    zone: 'publication',
    accent: 'purple',
    healthKey: 'investment_office',
    route: '/investment-office/health',
    docs: '/admin/investment-office',
    inputs: ['Decision package', 'Committee minutes'],
    outputs: ['CIO brief', 'Publication approval'],
    upstream: ['IDE_V2', 'IC', 'PIO'],
    downstream: ['IRW', 'IIS'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'IRW',
    code: 'IRW',
    name: 'Research Writer',
    purpose: 'Formats institutional research for Ask AGI / CMS.',
    zone: 'publication',
    accent: 'purple',
    healthKey: 'irw',
    route: '/research-writer/health',
    docs: '/admin/mission-control',
    inputs: ['Decision package', 'Evidence citations'],
    outputs: ['Markdown', 'PDF package', 'Citations'],
    upstream: ['CIO', 'IDE_V2', 'CompanyAnalysis'],
    downstream: ['IIS', 'AskAGI'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'IIS',
    code: 'IIS',
    name: 'Institutional Stack',
    purpose: 'End-to-end orchestration across the frozen pipeline.',
    zone: 'publication',
    accent: 'purple',
    healthKey: 'iis',
    route: '/institutional-stack/health',
    docs: '/admin/institutional-stack',
    inputs: ['All critical layers'],
    outputs: ['Stack package', 'Layer health', 'Ask AGI payload'],
    upstream: ['IRW', 'CIO', 'IDE_V2'],
    downstream: ['AskAGI'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'AskAGI',
    code: 'Ask AGI',
    name: 'Ask AGI Response',
    purpose: 'Final user-facing institutional answer surface.',
    zone: 'publication',
    accent: 'purple',
    healthKey: null,
    route: null,
    docs: '/ask-agi',
    inputs: [
      'Stack package',
      'Research writer output',
      'Reasoning / Editorial soft layers',
      'IERE evidence packs',
    ],
    outputs: ['Answer', 'Citations', 'Confidence'],
    upstream: ['IIS', 'IRW', 'AC', 'IRSP', 'BOOKS', 'IERE'],
    downstream: [],
    version: '3.0',
    critical: true,
  },
  // Soft reasoning / knowledge layers (not top-level engines)
  {
    id: 'IRSP',
    code: 'IRSP',
    name: 'Institutional Reasoning',
    purpose: 'Evidence-first reasoning habits: families, gold patterns, IC depth, adversarial.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'irsp',
    route: '/institutional-reasoning/health',
    docs: '/admin/intelligence-map',
    inputs: ['Query', 'Evidence pack', 'IERE ranked packs'],
    outputs: ['Reasoning plan', 'Executive when owns', 'Novelty / ECR'],
    upstream: ['IAF', 'EIL', 'IERE'],
    downstream: ['AC', 'AskAGI'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'AC',
    code: 'AC',
    name: 'Answer Construction',
    purpose: 'Orchestrates IAF → IR → contradiction → editorial into one Ask AGI answer.',
    zone: 'publication',
    accent: 'purple',
    healthKey: 'ac',
    route: '/answer-construction/health',
    docs: '/admin/intelligence-map',
    inputs: ['IAF', 'IRSP', 'Company analysis'],
    outputs: ['Institutional answer', 'Recommendation status'],
    upstream: ['IAF', 'IRSP', 'IRW'],
    downstream: ['AskAGI'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'EDITORIAL',
    code: 'Editorial',
    name: 'Editorial Rewrite',
    purpose: 'Gemini rewrite-only layer. AGIB remains the brain.',
    zone: 'publication',
    accent: 'purple',
    healthKey: 'editorial',
    route: '/editorial/health',
    docs: '/admin/intelligence-map',
    inputs: ['AGIB structured answer'],
    outputs: ['Plain-English rewrite'],
    upstream: ['AC'],
    downstream: ['AskAGI'],
    version: '1.0',
    critical: false,
  },
  {
    id: 'CXR',
    code: 'CXR',
    name: 'Contradiction Reasoning',
    purpose: 'Step-by-step conflict answers when evidence conflicts.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'cxr',
    route: '/contradiction-reasoning/health',
    docs: '/admin/intelligence-map',
    inputs: ['Conflicting evidence'],
    outputs: ['Step-by-step executive'],
    upstream: ['IRSP', 'EIL'],
    downstream: ['AC', 'AskAGI'],
    version: '1.0',
    critical: false,
  },
  {
    id: 'ECR',
    code: 'ECR',
    name: 'Evidence–Conclusion Ratio',
    purpose: 'Red-team soft attach: evidence density vs conclusion strength.',
    zone: 'validation',
    accent: 'red',
    healthKey: 'ecr',
    route: '/red-team/ecr/health',
    docs: '/admin/intelligence-map',
    inputs: ['Reasoned package'],
    outputs: ['ECR score', 'Calibration flags'],
    upstream: ['IRSP'],
    downstream: ['AC'],
    version: '1.0',
    critical: false,
  },
  {
    id: 'BOOKS',
    code: 'Books',
    name: 'Academy Books',
    purpose: 'Learned frameworks/concepts/formulas soft-wired into FAPI, IRW and KF.',
    zone: 'core',
    accent: 'green',
    healthKey: 'books',
    route: '/academy/books/health',
    docs: '/admin/academy',
    inputs: ['Personal library snapshot'],
    outputs: ['Frameworks', 'Terminology', 'Logic hints'],
    upstream: ['DATA'],
    downstream: ['IRW', 'FAPI', 'AskAGI'],
    version: '3.0',
    critical: false,
  },
  // Validation / quality — always visible even when gateway routes are missing
  {
    id: 'ACS',
    code: 'ACS',
    name: 'Academy Certification',
    purpose: 'Certification / quality attestation for academy packs.',
    zone: 'validation',
    accent: 'red',
    healthKey: 'acs',
    route: '/academy/certification/health',
    docs: '/admin/academy',
    inputs: ['Academy packages'],
    outputs: ['Certification status'],
    upstream: ['IIS'],
    downstream: [],
    version: '3.0',
    critical: false,
  },
  {
    id: 'IRS',
    code: 'IRS',
    name: 'Institutional Regression Suite',
    purpose: 'Regression gates across institutional answers.',
    zone: 'validation',
    accent: 'red',
    healthKey: 'irs',
    route: '/academy/regression/health',
    docs: '/admin/academy',
    inputs: ['Golden questions', 'Answer packs'],
    outputs: ['Regression report'],
    upstream: ['AskAGI', 'IIS'],
    downstream: [],
    version: '3.0',
    critical: false,
  },
  {
    id: 'IDE_V1',
    code: 'IDE V1',
    name: 'Decision Engine V1',
    purpose: 'Legacy decision engine (superseded by IDE V2).',
    zone: 'validation',
    accent: 'red',
    healthKey: 'idev1',
    route: '/decision-engine/health',
    docs: '/admin/decision-engine-v2',
    inputs: ['Legacy packages'],
    outputs: ['Legacy decisions'],
    upstream: ['IC'],
    downstream: [],
    version: '1.0',
    critical: false,
  },
  {
    id: 'LEO',
    code: 'LEO',
    name: 'Live Evidence Overlay',
    purpose: 'Live evidence packaging for Ask AGI.',
    zone: 'validation',
    accent: 'red',
    healthKey: 'leo',
    route: '/leo/health',
    docs: '/admin/live-evidence',
    inputs: ['Evidence stream'],
    outputs: ['Live packages'],
    upstream: ['EIL'],
    downstream: ['AskAGI'],
    version: '3.0',
    critical: false,
  },
  {
    id: 'CID',
    code: 'CID',
    name: 'Company Intelligence Dossier',
    purpose: 'Living company dossier surface.',
    zone: 'validation',
    accent: 'red',
    healthKey: 'cid',
    route: '/company-dossier/health',
    docs: '/admin/company-dossiers',
    inputs: ['Evidence', 'Events', 'Forecasts'],
    outputs: ['Dossier package'],
    upstream: ['EIL', 'FIE'],
    downstream: ['CompanyAnalysis'],
    version: '3.0',
    critical: false,
  },
  {
    id: 'DVC',
    code: 'DVC',
    name: 'Data Validation & Conflicts',
    purpose: 'Conflict detection and data quality validation.',
    zone: 'validation',
    accent: 'red',
    healthKey: 'dvc',
    route: '/dvc/health',
    docs: '/admin/data-quality',
    inputs: ['Provider feeds', 'Evidence'],
    outputs: ['Conflicts', 'Quality metrics'],
    upstream: ['DATA', 'EIL'],
    downstream: ['EIL', 'IAF'],
    version: '3.0',
    critical: false,
  },
];

export const ZONES = [
  {
    id: 'evidence',
    title: 'Data & Evidence',
    subtitle: 'Ingest · extract · verify',
    accent: 'blue',
  },
  {
    id: 'core',
    title: 'Intelligence Core',
    subtitle: 'Knowledge · forecast · memory',
    accent: 'green',
  },
  {
    id: 'reasoning',
    title: 'Institutional Reasoning',
    subtitle: 'Analysts · committee · portfolio',
    accent: 'gold',
  },
  {
    id: 'decision',
    title: 'Decision & Output',
    subtitle: 'IDE V2 · company packs',
    accent: 'purple',
  },
  {
    id: 'publication',
    title: 'Publication & QA',
    subtitle: 'CIO · writer · Ask AGI',
    accent: 'purple',
  },
];

export function layersByZone(zoneId) {
  return LAYERS.filter((l) => l.zone === zoneId);
}

export function findLayer(id) {
  return LAYERS.find((l) => l.id === id || l.code === id) || null;
}
