/**
 * AGIB v3 Intelligence Map — frozen institutional topology catalog.
 * Soft-wire only. Architecture v1.0.1 LOCKED.
 */

export const PIPELINE_PATH = [
  'FIL',
  'FDI',
  'MII',
  'ACI',
  'EIL',
  'FRE',
  'IERE',
  'BOOKS',
  'PIL',
  'CIG',
  'IKG',
  'FIE',
  'ILM',
  'SSL',
  'IAF',
  'IRSP',
  'IC',
  'PIO',
  'IDE_V2',
  'CIO',
  'IRW',
  'AC',
  'IIS',
];

export const DATA_SOURCES = [
  { id: 'indianapi', name: 'IndianAPI', kind: 'market' },
  { id: 'groww', name: 'Groww API', kind: 'market' },
  { id: 'yahoo', name: 'Yahoo Finance', kind: 'market' },
  { id: 'finnhub', name: 'Finnhub', kind: 'market' },
  { id: 'fmp', name: 'FMP', kind: 'fundamentals' },
  { id: 'nse', name: 'NSE', kind: 'exchange' },
  { id: 'bse', name: 'BSE', kind: 'exchange' },
  { id: 'rbi', name: 'RBI', kind: 'macro' },
  { id: 'sebi', name: 'SEBI', kind: 'regulatory' },
  { id: 'company_ir', name: 'Company IR', kind: 'filings' },
  { id: 'annual', name: 'Annual Reports', kind: 'filings' },
  { id: 'quarterly', name: 'Quarterly Reports', kind: 'filings' },
  { id: 'calls', name: 'Conference Calls', kind: 'filings' },
  { id: 'presentations', name: 'Investor Presentations', kind: 'filings' },
  { id: 'broker', name: 'Broker Research', kind: 'research' },
  { id: 'news', name: 'News', kind: 'news' },
  { id: 'macro', name: 'Macro APIs', kind: 'macro' },
  { id: 'fred', name: 'FRED', kind: 'macro' },
  { id: 'imf', name: 'IMF', kind: 'macro' },
  { id: 'worldbank', name: 'World Bank', kind: 'macro' },
  { id: 'commodity', name: 'Commodity APIs', kind: 'macro' },
  { id: 'fx', name: 'Currency APIs', kind: 'macro' },
];

export const ANALYST_ROLES = [
  'Business',
  'Financial',
  'Valuation',
  'Risk',
  'Sector',
  'Macro',
  'Management',
  'Ownership',
  'Market',
];

/** @typedef {'sources'|'evidence'|'core'|'reasoning'|'decision'|'publication'|'validation'|'platform'} ZoneId */

/** AGIB institutional research application stack (additive; soft-wire). */
export const APPLICATION_STACK_PATH = [
  'FSE',
  'FKB',
  'FIRE01',
  'FIRE02',
  'FIRE03',
  'FIRE04',
  'FIRE05',
  'FIRE06',
  'OfficeSDK',
  'PEB01',
  'IO01',
  'CIO01',
  'PO01',
  'WO01',
  'CW01',
  'AskAGI',
];

/**
 * @type {Array<{
 *  id: string,
 *  code: string,
 *  name: string,
 *  purpose: string,
 *  zone: ZoneId,
 *  accent: 'blue'|'green'|'gold'|'purple'|'orange'|'red',
 *  healthKey: string|null,
 *  route: string|null,
 *  docs: string,
 *  inputs: string[],
 *  outputs: string[],
 *  upstream: string[],
 *  downstream: string[],
 *  version: string,
 *  critical: boolean,
 * }>}
 */
export const LAYERS = [
  {
    id: 'FIL',
    code: 'FIL',
    name: 'Filing Intelligence',
    purpose: 'Reads filings into structured evidence.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'fil',
    route: '/filing-intelligence/health',
    docs: '/admin/institutional-stack',
    inputs: ['Annual reports', 'Quarterly filings', 'Company IR PDFs'],
    outputs: ['Evidence objects', 'Filing facts', 'Citation anchors'],
    upstream: ['DATA'],
    downstream: ['FDI', 'MII', 'ACI', 'EIL'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'FDI',
    code: 'FDI',
    name: 'Filing Diff',
    purpose: 'What materially changed vs prior period?',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'fdi',
    route: '/filing-diff/health',
    docs: '/admin/institutional-stack',
    inputs: ['Current filing package', 'Prior filing package'],
    outputs: ['Material deltas', 'Risk deltas', 'Narrative shifts'],
    upstream: ['FIL'],
    downstream: ['EIL', 'CIG', 'IAF'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'MII',
    code: 'MII',
    name: 'Management Intelligence',
    purpose: 'Guidance tone, credibility, and commitments.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'mii',
    route: '/management-intelligence/health',
    docs: '/admin/institutional-stack',
    inputs: ['Conference calls', 'MD&A', 'Presentations'],
    outputs: ['Guidance objects', 'Tone score', 'Commitment ledger'],
    upstream: ['FIL', 'DATA'],
    downstream: ['EIL', 'IAF', 'IC'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'ACI',
    code: 'ACI',
    name: 'Accounting Intelligence',
    purpose: 'Earnings quality, red flags, accounting risk.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'aci',
    route: '/accounting-intelligence/health',
    docs: '/admin/accounting-intelligence',
    inputs: ['Financial statements', 'Notes', 'Cash flow'],
    outputs: ['Quality score', 'Red flags', 'Adjustments'],
    upstream: ['FIL'],
    downstream: ['EIL', 'IAF', 'PIO'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'EIL',
    code: 'EIL',
    name: 'Evidence Intelligence',
    purpose: 'Verified evidence pack for downstream reasoners.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'eil',
    route: '/academy/evidence/health',
    docs: '/admin/evidence',
    inputs: ['FIL/FDI/MII/ACI outputs'],
    outputs: ['Evidence graph', 'Trust scores', 'Conflicts'],
    upstream: ['FIL', 'FDI', 'MII', 'ACI'],
    downstream: ['PIL', 'CIG', 'IKG', 'IAF'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'PIL',
    code: 'PIL',
    name: 'Peer Intelligence',
    purpose: 'Relative positioning vs sector peers.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'pil',
    route: '/peer-intelligence/health',
    docs: '/admin/portfolio-intelligence',
    inputs: ['Evidence pack', 'Peer universe', 'Market comps'],
    outputs: ['Peer ranks', 'Relative multiples', 'Gap map'],
    upstream: ['EIL', 'DATA'],
    downstream: ['CIG', 'IAF', 'PIO'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'FAA',
    code: 'FAA',
    name: 'Finance Acquisition Agent',
    purpose: 'Acquires external finance artifacts into the corpus.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'faa',
    route: '/faa/health',
    docs: '/admin/open-intelligence',
    inputs: ['Connector feeds', 'Schedulers'],
    outputs: ['Raw documents', 'Acquisition receipts'],
    upstream: ['DATA'],
    downstream: ['FRE', 'FIL', 'EIL'],
    version: '3.0',
    critical: false,
  },
  {
    id: 'FRE',
    code: 'FRE',
    name: 'Finance Retrieval Engine',
    purpose: 'Retrieves ranked finance context for reasoning.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'fre',
    route: '/fre/health',
    docs: '/admin/open-intelligence',
    inputs: ['Query', 'FAA corpus', 'Evidence index'],
    outputs: ['Ranked chunks', 'Source trails'],
    upstream: ['FAA', 'EIL'],
    downstream: ['IERE', 'CIG', 'IKG', 'IAF'],
    version: '3.0',
    critical: false,
  },
  {
    id: 'IERE',
    code: 'IERE',
    name: 'Institutional Evidence Retrieval',
    purpose: 'Ranks and assembles structured institutional evidence packs for every question.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'iere',
    route: '/evidence/health',
    docs: '/admin/intelligence-map',
    inputs: [
      'Question',
      'Knowledge Factory objects',
      'Institutional documents',
      'Live data',
      'Research Office',
    ],
    outputs: ['Ranked evidence packs', 'Citations', 'Evidence graph', 'PIT replay packs'],
    upstream: ['FRE', 'FIL', 'EIL', 'FAA'],
    downstream: ['AskAGI', 'IRSP', 'IAF', 'IRW'],
    version: '3.2',
    critical: true,
  },
  {
    id: 'CIG',
    code: 'CIG',
    name: 'Causal Intelligence Graph',
    purpose: 'Cause → effect chains across events and drivers.',
    zone: 'core',
    accent: 'green',
    healthKey: 'cig',
    route: '/causal-intelligence/health',
    docs: '/admin/causal-intelligence',
    inputs: ['Evidence', 'Events', 'Peer deltas'],
    outputs: ['Causal edges', 'Driver attributions'],
    upstream: ['EIL', 'PIL', 'FDI'],
    downstream: ['IKG', 'FIE', 'IAF'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'IKG',
    code: 'IKG',
    name: 'Institutional Knowledge Graph',
    purpose: 'Entities, relationships, and institutional memory links.',
    zone: 'core',
    accent: 'green',
    healthKey: 'ikg',
    route: '/knowledge-graph/health',
    docs: '/admin/knowledge-graph',
    inputs: ['Evidence', 'Causal edges', 'Company entities'],
    outputs: ['Graph nodes', 'Paths', 'Context packages'],
    upstream: ['EIL', 'CIG'],
    downstream: ['FIE', 'ILM', 'IAF'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'FIE',
    code: 'FIE',
    name: 'Forecast Intelligence',
    purpose: 'Scenario forecasts with confidence bands.',
    zone: 'core',
    accent: 'green',
    healthKey: 'fie',
    route: '/forecast/health',
    docs: '/admin/forecast-intelligence',
    inputs: ['Graph context', 'Causal drivers', 'History'],
    outputs: ['Scenarios', 'Probability bands', 'Watchpoints'],
    upstream: ['CIG', 'IKG'],
    downstream: ['ILM', 'SSL', 'IAF', 'IDE_V2'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'ILM',
    code: 'ILM',
    name: 'Learning & Memory',
    purpose: 'Institutional memory + model improvement events (MIE).',
    zone: 'core',
    accent: 'green',
    healthKey: 'ilm',
    route: '/ilm/health',
    docs: '/admin/institutional-memory',
    inputs: ['Decisions', 'Outcomes', 'Committee minutes'],
    outputs: ['Memory objects', 'Learning updates', 'Thesis revisions'],
    upstream: ['IKG', 'FIE', 'IDE_V2'],
    downstream: ['SSL', 'IAF', 'IDE_V2'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'SSL',
    code: 'SSL',
    name: 'Simulation & Strategy Lab',
    purpose: 'Portfolio and thesis stress simulations.',
    zone: 'core',
    accent: 'green',
    healthKey: 'ssl',
    route: '/simulation/health',
    docs: '/admin/simulation-lab',
    inputs: ['Forecasts', 'Portfolio state', 'Risk factors'],
    outputs: ['Simulation runs', 'Stress outcomes', 'Strategy deltas'],
    upstream: ['FIE', 'ILM', 'PIO'],
    downstream: ['IAF', 'PIO', 'IDE_V2'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'AIL',
    code: 'AIL',
    name: 'Intelligence Layer V2',
    purpose: 'Supporting analyst intelligence monitor.',
    zone: 'core',
    accent: 'green',
    healthKey: 'ail',
    route: '/ail/health',
    docs: '/admin/mission-control',
    inputs: ['Monitor universe', 'Evidence deltas'],
    outputs: ['Alerts', 'Living dossiers'],
    upstream: ['EIL', 'IKG'],
    downstream: ['IAF', 'CompanyAnalysis'],
    version: '3.0',
    critical: false,
  },
  {
    id: 'IAF',
    code: 'IAF',
    name: 'Institutional Analysts',
    purpose: 'Specialist opinions across institutional desks.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'iaf',
    route: '/institutional-analysts/health',
    docs: '/admin/investment-intelligence',
    inputs: ['Evidence', 'Peers', 'Forecasts', 'Graph paths'],
    outputs: ['Analyst memos', 'Votes', 'Conflicts'],
    upstream: ['EIL', 'PIL', 'CIG', 'FIE', 'SSL'],
    downstream: ['IC'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'IC',
    code: 'IC',
    name: 'Investment Committee',
    purpose: 'Deliberation, consensus, minority, minutes.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'ic',
    route: '/investment-committee/health',
    docs: '/admin/investment-office',
    inputs: ['Analyst memos', 'Conflicts', 'Risk notes'],
    outputs: ['Consensus', 'Minutes', 'Action items'],
    upstream: ['IAF'],
    downstream: ['PIO', 'IDE_V2', 'CIO'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'PIO',
    code: 'PIO',
    name: 'Portfolio Intelligence Office',
    purpose: 'Diversification, factor risk, suitability.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'pio',
    route: '/portfolio-intelligence/health',
    docs: '/admin/portfolio-intelligence',
    inputs: ['Committee view', 'Holdings', 'Simulations'],
    outputs: ['Portfolio quality', 'Overlap', 'Stress pack'],
    upstream: ['IC', 'SSL', 'PIL'],
    downstream: ['IDE_V2', 'CIO'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'IDE_V2',
    code: 'IDE V2',
    name: 'Decision Engine V2',
    purpose: 'Final institutional decision package (frozen tip).',
    zone: 'decision',
    accent: 'purple',
    healthKey: 'idev2',
    route: '/decision-engine-v2/health',
    docs: '/admin/decision-engine-v2',
    inputs: ['Committee', 'Portfolio', 'Forecast', 'Memory'],
    outputs: ['Decision package', 'Gates', 'Audit trail'],
    upstream: ['IC', 'PIO', 'FIE', 'ILM', 'SSL'],
    downstream: ['CIO', 'IRW', 'ILM'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'CompanyAnalysis',
    code: 'CA',
    name: 'Company Analysis',
    purpose: 'Company-specific institutional reasoning pack.',
    zone: 'decision',
    accent: 'purple',
    healthKey: 'company_analysis',
    route: '/company-analysis/health',
    docs: '/admin/company-analysis',
    inputs: ['Evidence', 'Dossier', 'Decision package'],
    outputs: ['Company report', 'Thesis snapshot'],
    upstream: ['EIL', 'IDE_V2', 'AIL'],
    downstream: ['IRW', 'AskAGI'],
    version: '3.0',
    critical: false,
  },
  {
    id: 'CIO',
    code: 'CIO',
    name: 'Chief Investment Office',
    purpose: 'Executive decision ownership and publication gate.',
    zone: 'publication',
    accent: 'purple',
    healthKey: 'investment_office',
    route: '/investment-office/health',
    docs: '/admin/investment-office',
    inputs: ['Decision package', 'Committee minutes'],
    outputs: ['CIO brief', 'Publication approval'],
    upstream: ['IDE_V2', 'IC', 'PIO'],
    downstream: ['IRW', 'IIS'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'IRW',
    code: 'IRW',
    name: 'Research Writer',
    purpose: 'Formats institutional research for Ask AGI / CMS.',
    zone: 'publication',
    accent: 'purple',
    healthKey: 'irw',
    route: '/research-writer/health',
    docs: '/admin/mission-control',
    inputs: ['Decision package', 'Evidence citations'],
    outputs: ['Markdown', 'PDF package', 'Citations'],
    upstream: ['CIO', 'IDE_V2', 'CompanyAnalysis'],
    downstream: ['IIS', 'AskAGI'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'IIS',
    code: 'IIS',
    name: 'Institutional Stack',
    purpose: 'End-to-end orchestration across the frozen pipeline.',
    zone: 'publication',
    accent: 'purple',
    healthKey: 'iis',
    route: '/institutional-stack/health',
    docs: '/admin/institutional-stack',
    inputs: ['All critical layers'],
    outputs: ['Stack package', 'Layer health', 'Ask AGI payload'],
    upstream: ['IRW', 'CIO', 'IDE_V2'],
    downstream: ['AskAGI'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'AskAGI',
    code: 'Ask AGI',
    name: 'Ask AGI Response',
    purpose: 'Final user-facing institutional answer surface.',
    zone: 'publication',
    accent: 'purple',
    healthKey: null,
    route: null,
    docs: '/ask-agi',
    inputs: [
      'Stack package',
      'Research writer output',
      'Reasoning / Editorial soft layers',
      'IERE evidence packs',
    ],
    outputs: ['Answer', 'Citations', 'Confidence'],
    upstream: ['IIS', 'IRW', 'AC', 'IRSP', 'BOOKS', 'IERE', 'IO01', 'CIO01', 'WO01', 'CW01'],
    downstream: [],
    version: '3.0',
    critical: true,
  },
  // Soft reasoning / knowledge layers (not top-level engines)
  {
    id: 'IRSP',
    code: 'IRSP',
    name: 'Institutional Reasoning',
    purpose: 'Evidence-first reasoning habits: families, gold patterns, IC depth, adversarial.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'irsp',
    route: '/institutional-reasoning/health',
    docs: '/admin/intelligence-map',
    inputs: ['Query', 'Evidence pack', 'IERE ranked packs'],
    outputs: ['Reasoning plan', 'Executive when owns', 'Novelty / ECR'],
    upstream: ['IAF', 'EIL', 'IERE'],
    downstream: ['AC', 'AskAGI'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'AC',
    code: 'AC',
    name: 'Answer Construction',
    purpose: 'Orchestrates IAF → IR → contradiction → editorial into one Ask AGI answer.',
    zone: 'publication',
    accent: 'purple',
    healthKey: 'ac',
    route: '/answer-construction/health',
    docs: '/admin/intelligence-map',
    inputs: ['IAF', 'IRSP', 'Company analysis'],
    outputs: ['Institutional answer', 'Recommendation status'],
    upstream: ['IAF', 'IRSP', 'IRW'],
    downstream: ['AskAGI'],
    version: '3.0',
    critical: true,
  },
  {
    id: 'EDITORIAL',
    code: 'Editorial',
    name: 'Editorial Rewrite',
    purpose: 'Gemini rewrite-only layer. AGIB remains the brain.',
    zone: 'publication',
    accent: 'purple',
    healthKey: 'editorial',
    route: '/editorial/health',
    docs: '/admin/intelligence-map',
    inputs: ['AGIB structured answer'],
    outputs: ['Plain-English rewrite'],
    upstream: ['AC'],
    downstream: ['AskAGI'],
    version: '1.0',
    critical: false,
  },
  {
    id: 'CXR',
    code: 'CXR',
    name: 'Contradiction Reasoning',
    purpose: 'Step-by-step conflict answers when evidence conflicts.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'cxr',
    route: '/contradiction-reasoning/health',
    docs: '/admin/intelligence-map',
    inputs: ['Conflicting evidence'],
    outputs: ['Step-by-step executive'],
    upstream: ['IRSP', 'EIL'],
    downstream: ['AC', 'AskAGI'],
    version: '1.0',
    critical: false,
  },
  {
    id: 'ECR',
    code: 'ECR',
    name: 'Evidence–Conclusion Ratio',
    purpose: 'Red-team soft attach: evidence density vs conclusion strength.',
    zone: 'validation',
    accent: 'red',
    healthKey: 'ecr',
    route: '/red-team/ecr/health',
    docs: '/admin/intelligence-map',
    inputs: ['Reasoned package'],
    outputs: ['ECR score', 'Calibration flags'],
    upstream: ['IRSP'],
    downstream: ['AC'],
    version: '1.0',
    critical: false,
  },
  {
    id: 'BOOKS',
    code: 'Books',
    name: 'Academy Books',
    purpose: 'Learned frameworks/concepts/formulas soft-wired into FAPI, IRW and KF.',
    zone: 'core',
    accent: 'green',
    healthKey: 'books',
    route: '/academy/books/health',
    docs: '/admin/academy',
    inputs: ['Personal library snapshot'],
    outputs: ['Frameworks', 'Terminology', 'Logic hints'],
    upstream: ['DATA'],
    downstream: ['IRW', 'FAPI', 'AskAGI'],
    version: '3.0',
    critical: false,
  },
  // Validation / quality — always visible even when gateway routes are missing
  {
    id: 'ACS',
    code: 'ACS',
    name: 'Academy Certification',
    purpose: 'Certification / quality attestation for academy packs.',
    zone: 'validation',
    accent: 'red',
    healthKey: 'acs',
    route: '/academy/certification/health',
    docs: '/admin/academy',
    inputs: ['Academy packages'],
    outputs: ['Certification status'],
    upstream: ['IIS'],
    downstream: [],
    version: '3.0',
    critical: false,
  },
  {
    id: 'IRS',
    code: 'IRS',
    name: 'Institutional Regression Suite',
    purpose: 'Regression gates across institutional answers.',
    zone: 'validation',
    accent: 'red',
    healthKey: 'irs',
    route: '/academy/regression/health',
    docs: '/admin/academy',
    inputs: ['Golden questions', 'Answer packs'],
    outputs: ['Regression report'],
    upstream: ['AskAGI', 'IIS'],
    downstream: [],
    version: '3.0',
    critical: false,
  },
  {
    id: 'IDE_V1',
    code: 'IDE V1',
    name: 'Decision Engine V1',
    purpose: 'Legacy decision engine (superseded by IDE V2).',
    zone: 'validation',
    accent: 'red',
    healthKey: 'idev1',
    route: '/decision-engine/health',
    docs: '/admin/decision-engine-v2',
    inputs: ['Legacy packages'],
    outputs: ['Legacy decisions'],
    upstream: ['IC'],
    downstream: [],
    version: '1.0',
    critical: false,
  },
  {
    id: 'LEO',
    code: 'LEO',
    name: 'Live Evidence Overlay',
    purpose: 'Live evidence packaging for Ask AGI.',
    zone: 'validation',
    accent: 'red',
    healthKey: 'leo',
    route: '/leo/health',
    docs: '/admin/live-evidence',
    inputs: ['Evidence stream'],
    outputs: ['Live packages'],
    upstream: ['EIL'],
    downstream: ['AskAGI'],
    version: '3.0',
    critical: false,
  },
  {
    id: 'CID',
    code: 'CID',
    name: 'Company Intelligence Dossier',
    purpose: 'Living company dossier surface.',
    zone: 'validation',
    accent: 'red',
    healthKey: 'cid',
    route: '/company-dossier/health',
    docs: '/admin/company-dossiers',
    inputs: ['Evidence', 'Events', 'Forecasts'],
    outputs: ['Dossier package'],
    upstream: ['EIL', 'FIE'],
    downstream: ['CompanyAnalysis'],
    version: '3.0',
    critical: false,
  },
  {
    id: 'DVC',
    code: 'DVC',
    name: 'Data Validation & Conflicts',
    purpose: 'Conflict detection and data quality validation.',
    zone: 'validation',
    accent: 'red',
    healthKey: 'dvc',
    route: '/dvc/health',
    docs: '/admin/data-quality',
    inputs: ['Provider feeds', 'Evidence'],
    outputs: ['Conflicts', 'Quality metrics'],
    upstream: ['DATA', 'EIL'],
    downstream: ['EIL', 'IAF'],
    version: '3.0',
    critical: false,
  },
  // Application stack — FSE → FKB → FIRE → offices (soft-wire; additive)
  {
    id: 'FSE',
    code: 'FSE',
    name: 'Financial Statements Engine',
    purpose: 'Canonical facts from statements — collect, parse, validate, warehouse.',
    zone: 'evidence',
    accent: 'blue',
    healthKey: 'fse',
    route: '/financial-statements/health',
    docs: '/admin/institutional-stack',
    inputs: ['Filings', 'Provider fundamentals'],
    outputs: ['Statement facts', 'Coverage gaps'],
    upstream: ['DATA', 'FIL'],
    downstream: ['FKB', 'FIRE01', 'FIRE02'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'FKB',
    code: 'FKB',
    name: 'Financial Knowledge Base',
    purpose: 'Definitions, ratios, thresholds, and quality weights.',
    zone: 'core',
    accent: 'green',
    healthKey: 'fkb',
    route: '/financial-knowledge/health',
    docs: '/admin/institutional-stack',
    inputs: ['Canonical definitions', 'Quality weights'],
    outputs: ['Knowledge catalog', 'Ratio specs'],
    upstream: ['FSE'],
    downstream: ['FIRE01', 'FIRE06', 'IO01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'FIRE01',
    code: 'FIRE-01',
    name: 'Financial Narrative',
    purpose: 'What changed in the numbers — trends and narrative.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'fire01',
    route: '/financial-intelligence/health',
    docs: '/admin/institutional-stack',
    inputs: ['FSE facts', 'FKB definitions'],
    outputs: ['Narrative package', 'Trend flags'],
    upstream: ['FSE', 'FKB'],
    downstream: ['FIRE04', 'IO01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'FIRE02',
    code: 'FIRE-02',
    name: 'Cross-Statement Drivers',
    purpose: 'Relationships and drivers across statements.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'fire02',
    route: '/financial-intelligence/drivers/health',
    docs: '/admin/institutional-stack',
    inputs: ['FSE facts'],
    outputs: ['Driver graph', 'Linkage flags'],
    upstream: ['FSE', 'FIRE01'],
    downstream: ['FIRE04', 'IO01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'FIRE03',
    code: 'FIRE-03',
    name: 'Business Disclosure',
    purpose: 'Business and management disclosure extraction.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'fire03',
    route: '/business-intelligence/health',
    docs: '/admin/institutional-stack',
    inputs: ['Filings', 'Calls', 'MD&A'],
    outputs: ['Disclosure objects', 'Business themes'],
    upstream: ['FIL', 'MII'],
    downstream: ['FIRE04', 'FIRE05', 'IO01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'FIRE04',
    code: 'FIRE-04',
    name: 'Evidence Fusion',
    purpose: 'Finance vs management alignment and conflict.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'fire04',
    route: '/evidence-fusion/health',
    docs: '/admin/institutional-stack',
    inputs: ['FIRE-01…03 packages'],
    outputs: ['Fusion package', 'Conflict flags'],
    upstream: ['FIRE01', 'FIRE02', 'FIRE03'],
    downstream: ['IO01', 'FIRE06'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'FIRE05',
    code: 'FIRE-05',
    name: 'Management Execution',
    purpose: 'Temporal delivery tracking vs prior commitments.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'fire05',
    route: '/management-execution/health',
    docs: '/admin/institutional-stack',
    inputs: ['Guidance', 'Outcomes', 'FIRE-03'],
    outputs: ['Execution score', 'Missed commitments'],
    upstream: ['FIRE03', 'MII'],
    downstream: ['IO01', 'PO01', 'WO01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'FIRE06',
    code: 'FIRE-06',
    name: 'Business Quality',
    purpose: 'Pillar-primary business quality synthesis.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'fire06',
    route: '/business-quality/health',
    docs: '/admin/business-quality',
    inputs: ['FIRE packages', 'FKB quality weights'],
    outputs: ['Quality score', 'Pillar breakdown'],
    upstream: ['FIRE01', 'FIRE04', 'FKB'],
    downstream: ['IO01', 'CIO01', 'PO01', 'WO01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'OfficeSDK',
    code: 'Office SDK',
    name: 'Office SDK',
    purpose: 'Shared OfficeRequest / Response / EvidenceBlock contracts.',
    zone: 'platform',
    accent: 'orange',
    healthKey: 'office_sdk',
    route: '/office-sdk/health',
    docs: '/admin/institutional-stack',
    inputs: ['Office payloads'],
    outputs: ['Normalized office responses'],
    upstream: ['IO01', 'CIO01', 'PO01', 'WO01'],
    downstream: ['PEB01', 'AskAGI'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'PEB01',
    code: 'PEB-01',
    name: 'Platform Event Bus',
    purpose: 'In-process typed pub/sub between offices.',
    zone: 'platform',
    accent: 'orange',
    healthKey: 'peb',
    route: '/platform-event-bus/health',
    docs: '/admin/institutional-stack',
    inputs: ['Office events'],
    outputs: ['Typed envelopes', 'Soft publish'],
    upstream: ['OfficeSDK', 'IO01', 'CIO01', 'PO01', 'WO01'],
    downstream: ['WO01', 'AskAGI'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'IO01',
    code: 'IO-01',
    name: 'Investment Office',
    purpose: 'Orchestrates FIRE-01…06 into Institutional Research Packages.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'io01',
    route: '/investment-office/health',
    docs: '/admin/institutional-stack',
    inputs: ['FIRE-01…06', 'Office SDK'],
    outputs: ['IRP', 'company.research.completed'],
    upstream: ['FIRE01', 'FIRE02', 'FIRE03', 'FIRE04', 'FIRE05', 'FIRE06', 'OfficeSDK'],
    downstream: ['CIO01', 'WO01', 'AskAGI', 'PEB01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'CIO01',
    code: 'CIO-01',
    name: 'Comparative Intelligence',
    purpose: 'Cross-company Institutional Comparison Reports.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'cio01',
    route: '/comparative-intelligence/health',
    docs: '/admin/comparative-intelligence',
    inputs: ['IO collectors', 'FIRE packages'],
    outputs: ['ICR', 'comparison.completed'],
    upstream: ['IO01', 'FIRE06', 'OfficeSDK'],
    downstream: ['WO01', 'AskAGI', 'PEB01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'PO01',
    code: 'PO-01',
    name: 'Portfolio Office',
    purpose: 'Immutable portfolio state — weights, exposures, quality.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'po01',
    route: '/portfolio-office/health',
    docs: '/admin/institutional-stack',
    inputs: ['Holdings', 'FIRE-05/06', 'Office SDK'],
    outputs: ['Snapshots', 'portfolio.updated'],
    upstream: ['FIRE05', 'FIRE06', 'OfficeSDK'],
    downstream: ['PKG01', 'WO01', 'AskAGI', 'PEB01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'WO01',
    code: 'WO-01',
    name: 'Watchlist Office',
    purpose: 'Event-driven research queues from PEB office events.',
    zone: 'reasoning',
    accent: 'gold',
    healthKey: 'wo01',
    route: '/watchlist-office/health',
    docs: '/admin/institutional-stack',
    inputs: ['PEB events', 'Office SDK'],
    outputs: ['Research queue', 'Watchlist deltas'],
    upstream: ['PEB01', 'IO01', 'CIO01', 'PO01', 'OfficeSDK'],
    downstream: ['CW01', 'AskAGI'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'CW01',
    code: 'CW-01',
    name: 'Company Workspace',
    purpose: 'Primary company UX — everything AGI knows, one place.',
    zone: 'publication',
    accent: 'purple',
    healthKey: 'cw01',
    route: '/company-workspace/health',
    docs: '/admin/company-workspace',
    inputs: ['FIRE-01…06', 'IO-01', 'WO-01', 'PO-01', 'Office SDK', 'PEB-01'],
    outputs: ['Company workspace', 'Unified timeline', 'Evidence references'],
    upstream: ['FIRE01', 'FIRE02', 'FIRE03', 'FIRE04', 'FIRE05', 'FIRE06', 'IO01', 'WO01', 'PO01', 'OfficeSDK', 'PEB01'],
    downstream: ['AskAGI', 'E2E01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'E2E01',
    code: 'E2E-01',
    name: 'Product Experience Validation',
    purpose: 'End-to-end institutional product experience validation — not an engine.',
    zone: 'publication',
    accent: 'green',
    healthKey: 'e2e01',
    route: '/product-experience/health',
    docs: '/admin/product-experience',
    inputs: ['Phase 2 /agi UI', 'CW-01', 'Ask AGI', 'PO-01', 'WO-01', 'IBS-01'],
    outputs: ['E2E scorecard', 'Workflow report', 'Institutional readiness'],
    upstream: ['CW01', 'AskAGI', 'IBS01'],
    downstream: ['RH01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'RH01',
    code: 'RH-01',
    name: 'AGI Release Health',
    purpose: 'Single release-gate dashboard before every ship.',
    zone: 'publication',
    accent: 'blue',
    healthKey: 'rh01',
    route: '/release-health/health',
    docs: '/admin/release-health',
    inputs: ['IST-01/02', 'IBS-01', 'E2E-01', 'pytest'],
    outputs: ['Ready for Release', 'Release scorecard'],
    upstream: ['E2E01', 'IBS01'],
    downstream: [],
    version: '1.0',
    critical: true,
  },
  {
    id: 'IRE01',
    code: 'IRE-01',
    name: 'Institutional Reporting Engine',
    purpose: 'Deterministic company recommendation reports from structured facts (no LLM).',
    zone: 'publication',
    accent: 'blue',
    healthKey: 'ire01',
    route: '/report/health',
    docs: '/docs/AGI_IRE_01_INSTITUTIONAL_REPORTING.md',
    inputs: ['InstitutionalReportInput', 'Evidence IDs', 'Ask AGI'],
    outputs: ['InstitutionalReport', 'Fixed section company report'],
    upstream: ['RH01'],
    downstream: ['IRE02'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'IRE02',
    code: 'IRE-02',
    name: 'Deterministic Reason Composer',
    purpose: 'Facts → Reason objects → report; every conclusion is explainable and evidenced.',
    zone: 'publication',
    accent: 'blue',
    healthKey: 'ire02',
    route: '/report/health',
    docs: '/docs/AGI_IRE_02_REASON_COMPOSER.md',
    inputs: ['InstitutionalReportInput', 'Evidence', 'Explanation engine'],
    outputs: ['Reason graph', 'Diagnostics', 'Explainable InstitutionalReport'],
    upstream: ['IRE01'],
    downstream: ['IDS01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'IDS01',
    code: 'IDS-01',
    name: 'Institutional Decision System',
    purpose: 'Versioned InstitutionalDecision owns BUY/HOLD/SELL; reports only render it.',
    zone: 'publication',
    accent: 'blue',
    healthKey: 'ids01',
    route: '/decision/health',
    docs: '/docs/AGI_IDS_01_INSTITUTIONAL_DECISION.md',
    inputs: ['Reason graph', 'Valuation', 'Risk', 'Quality factors'],
    outputs: ['InstitutionalDecision', 'Decision history', 'Upgrade/downgrade conditions'],
    upstream: ['IRE02'],
    downstream: ['IDS02'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'IDS02',
    code: 'IDS-02',
    name: 'Decision Calibration & Explainability',
    purpose:
      'Computes calibrated confidence from a CalibrationProfile — scorecard, contributors, drift, lineage.',
    zone: 'publication',
    accent: 'blue',
    healthKey: 'ids02',
    route: '/calibration/health',
    docs: '/docs/AGI_IDS_02_DECISION_CALIBRATION.md',
    inputs: ['InstitutionalDecision', 'Reason graph', 'Evidence', 'CalibrationProfile'],
    outputs: [
      'Calibrated confidence',
      'Confidence breakdown',
      'Decision scorecard',
      'Decision drift',
      'Lineage',
    ],
    upstream: ['IDS01'],
    downstream: ['KG01', 'AskAGI'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'KG01',
    code: 'KG-01',
    name: 'Institutional Knowledge Graph',
    purpose:
      'Single-company graph connecting evidence → metrics → reasons → decision → calibration with deterministic inference.',
    zone: 'publication',
    accent: 'green',
    healthKey: 'kg01',
    route: '/graph/health',
    docs: '/docs/AGI_KG_01_INSTITUTIONAL_KNOWLEDGE_GRAPH.md',
    inputs: ['Evidence', 'Metrics', 'Risks', 'Reasons', 'InstitutionalDecision'],
    outputs: ['Company graph', 'Inferred relationships', 'Impact scores', 'Traversal paths'],
    upstream: ['IDS02', 'IRE02'],
    downstream: ['FG01', 'AskAGI'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'FG01',
    code: 'FG-01',
    name: 'Forecast & Scenario Graph',
    purpose:
      'Deterministic scenario propagation through the company knowledge graph — base/bull/bear/stress with explicit probabilities.',
    zone: 'publication',
    accent: 'green',
    healthKey: 'fg01',
    route: '/scenario/health',
    docs: '/docs/AGI_FG_01_FORECAST_SCENARIO_GRAPH.md',
    inputs: ['Knowledge Graph', 'ScenarioAssumption', 'InstitutionalDecision'],
    outputs: ['ForecastScenario', 'Propagation', 'Sensitivity scorecard', 'Scenario comparison'],
    upstream: ['KG01'],
    downstream: ['PKG01', 'AskAGI'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'PKG01',
    code: 'PKG-01',
    name: 'Portfolio Knowledge Graph',
    purpose:
      'Phase 4.1 — Portfolio → Companies → Relationships. InstitutionalPortfolio with allocations, exposures, concentration, correlation proxies.',
    zone: 'publication',
    accent: 'gold',
    healthKey: 'pkg01',
    route: '/portfolio-graph/health',
    docs: '/docs/AGI_PKG_01_PORTFOLIO_KNOWLEDGE_GRAPH.md',
    inputs: ['Holdings', 'Company graphs', 'InstitutionalDecision', 'Portfolio Office state'],
    outputs: [
      'InstitutionalPortfolio',
      'Portfolio graph',
      'Allocations',
      'Exposures',
      'Concentration',
      'Correlation proxies',
    ],
    upstream: ['KG01', 'IDS01', 'PO01'],
    downstream: ['PRE01', 'CIO01', 'AskAGI'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'PRE01',
    code: 'PRE-01',
    name: 'Institutional Portfolio Risk Engine',
    purpose:
      'Phase 4.3 — Authoritative InstitutionalPortfolioRisk from portfolio graph. Concentration, liquidity, correlation proxies, factor exposure, deterministic stress. Consumed by CIO-01.',
    zone: 'publication',
    accent: 'gold',
    healthKey: 'pre01',
    route: '/portfolio-risk/health',
    docs: '/docs/AGI_PRE_01_PORTFOLIO_RISK.md',
    inputs: ['InstitutionalPortfolio', 'Holdings', 'Exposures', 'Company decisions (lineage)'],
    outputs: [
      'InstitutionalPortfolioRisk',
      'Concentration',
      'Liquidity',
      'Correlation proxies',
      'Factor exposure',
      'Stress results',
      'Risk scorecard',
    ],
    upstream: ['PKG01'],
    downstream: ['PCE01', 'CIO01', 'AskAGI'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'PCE01',
    code: 'PCE-01',
    name: 'Institutional Policy & Constraint Engine',
    purpose:
      'Phase 4.4 — Deterministic mandate compliance. InstitutionalPolicyAssessment with position/sector/cash/diversification/liquidity/risk constraints. Consumed by CIO-01.',
    zone: 'publication',
    accent: 'gold',
    healthKey: 'pce01',
    route: '/policy/health',
    docs: '/docs/AGI_PCE_01_POLICY_CONSTRAINT.md',
    inputs: [
      'InstitutionalPortfolio',
      'InstitutionalPortfolioRisk (PRE-01)',
      'Policy profiles / mandates',
    ],
    outputs: [
      'InstitutionalPolicyAssessment',
      'Violations',
      'Passed constraints',
      'Required actions',
      'Compliance score',
    ],
    upstream: ['PKG01', 'PRE01'],
    downstream: ['CIO01', 'ICE01', 'AskAGI'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'CIO01',
    code: 'CIO-01',
    name: 'Institutional Portfolio Decision System',
    purpose:
      'Phase 4.2 — Deterministic InstitutionalPortfolioDecision from portfolio graph + PRE-01 risk + PCE-01 policy + referential company decisions. Allocation/exposure actions without mutating company recommendations.',
    zone: 'publication',
    accent: 'gold',
    healthKey: 'cio01',
    route: '/portfolio-decision/health',
    docs: '/docs/AGI_CIO_01_PORTFOLIO_DECISION.md',
    inputs: [
      'InstitutionalPortfolio',
      'InstitutionalPortfolioRisk (PRE-01)',
      'InstitutionalPolicyAssessment (PCE-01)',
      'Company InstitutionalDecision (referential)',
      'Exposures',
    ],
    outputs: [
      'InstitutionalPortfolioDecision',
      'Allocation actions',
      'Exposure actions',
      'Portfolio calibration',
      'Monitoring plan',
      'Decision scorecard',
    ],
    upstream: ['PKG01', 'PRE01', 'PCE01', 'IDS01', 'IDS02'],
    downstream: ['ICE01', 'AskAGI'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'ICE01',
    code: 'ICE-01',
    name: 'Investment Committee Engine',
    purpose:
      'Phase 4.5 — Deterministic InstitutionalCommitteeResolution governing CIO-01 decisions. Structured Risk/Policy/Allocation desk votes, agenda, action items, follow-ups. Advisory governance — never mutates upstream.',
    zone: 'publication',
    accent: 'gold',
    healthKey: 'ice01',
    route: '/committee-engine/health',
    docs: '/docs/AGI_ICE_01_INVESTMENT_COMMITTEE.md',
    inputs: [
      'InstitutionalPortfolioDecision (CIO-01)',
      'InstitutionalPortfolioRisk (PRE-01)',
      'InstitutionalPolicyAssessment (PCE-01)',
    ],
    outputs: [
      'InstitutionalCommitteeResolution',
      'Votes',
      'Agenda',
      'Action items',
      'Follow-up schedule',
    ],
    upstream: ['CIO01', 'PRE01', 'PCE01'],
    downstream: ['UAG01', 'AskAGI'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'UAG01',
    code: 'UAG-01',
    name: 'Universal Ask AGI Orchestrator',
    purpose:
      'Phase 5.1 — Stateless orchestration over registered institutional objects. Intent classification, query planning, retrieval, evidence assembly. Does not generate investment recommendations or own business state.',
    zone: 'publication',
    accent: 'purple',
    healthKey: 'uag01',
    route: '/orchestrator/health',
    docs: '/docs/AGI_UAG_01_UNIVERSAL_ASK.md',
    inputs: [
      'User question',
      'Object Registry',
      'CompanyDecision',
      'PortfolioRisk',
      'PolicyAssessment',
      'PortfolioDecision',
      'CommitteeResolution',
    ],
    outputs: [
      'InstitutionalQuery',
      'InstitutionalResponse',
      'Execution plan',
      'Evidence lineage',
      'Diagnostics',
    ],
    upstream: ['PKG01', 'PRE01', 'PCE01', 'CIO01', 'ICE01', 'IDS01'],
    downstream: ['AskAGI', 'RW01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'RW01',
    code: 'RW-01',
    name: 'Institutional Research Workspace',
    purpose:
      'Phase 5.2 — Analyst workstation: company/portfolio/committee contexts with timeline, linked objects, evidence browser, and research notes. Ask AGI answers where to look; the workspace shows everything that matters. Presentation only — notes never mutate system intelligence.',
    zone: 'publication',
    accent: 'teal',
    healthKey: 'rw01',
    route: '/workspace/health',
    docs: '/docs/AGI_RW_01_RESEARCH_WORKSPACE.md',
    inputs: [
      'CompanyDecision',
      'PortfolioRisk',
      'PolicyAssessment',
      'PortfolioDecision',
      'CommitteeResolution',
      'Evidence',
      'Analyst notes',
    ],
    outputs: [
      'InstitutionalWorkspace',
      'WorkspaceTimeline',
      'LinkedObjectGraph',
      'EvidenceBrowser',
      'ResearchNotes',
      'Workspace diagnostics',
    ],
    upstream: ['UAG01', 'PKG01', 'PRE01', 'PCE01', 'CIO01', 'ICE01', 'CW01'],
    downstream: ['AskAGI', 'CCI01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'CCI01',
    code: 'CCI-01',
    name: 'Cross-Company Intelligence',
    purpose:
      'Phase 5.3 — Relationship reasoning and dependency propagation over KG-01. Answers how a company affects everything else. Does not own or duplicate the graph. Provider registry for competitor, sector, macro, and portfolio relationships.',
    zone: 'publication',
    accent: 'blue',
    healthKey: 'cci01',
    route: '/relationships/health',
    docs: '/docs/AGI_CCI_01_CROSS_COMPANY_INTELLIGENCE.md',
    inputs: [
      'KG-01 company graphs',
      'Peer Intelligence',
      'Portfolio holdings',
      'Macro drivers',
      'Relationship providers',
    ],
    outputs: [
      'InstitutionalRelationship',
      'Propagation paths',
      'Similarity ranks',
      'Clusters',
      'Impact maps',
    ],
    upstream: ['KG01', 'PKG01', 'RW01', 'UAG01'],
    downstream: ['AskAGI', 'RW01', 'PUB01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'PUB01',
    code: 'PUB-01',
    name: 'Publishing & Distribution',
    purpose:
      'Phase 5.4 — Compose institutional deliverables from immutable objects. Never analyzes or invents recommendations. Templates control formatting; publication manifests are the authoritative audit record. Distribution is decoupled from builders.',
    zone: 'publication',
    accent: 'green',
    healthKey: 'pub01',
    route: '/publications/health',
    docs: '/docs/AGI_PUB_01_PUBLISHING.md',
    inputs: [
      'CompanyDecision',
      'PortfolioRisk',
      'PolicyAssessment',
      'PortfolioDecision',
      'CommitteeResolution',
      'Observation',
      'Evidence',
    ],
    outputs: [
      'InstitutionalPublication',
      'PublicationManifest',
      'HTML / PDF / Markdown / JSON artifacts',
      'Distribution records',
    ],
    upstream: ['RW01', 'CCI01', 'UAG01', 'CIO01', 'ICE01', 'PRE01', 'PCE01'],
    downstream: ['AskAGI', 'RW01', 'MPC01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'MPC01',
    code: 'MPC-01',
    name: 'Multi-Portfolio & Client Platform',
    purpose:
      'Phase 5.5 — Tenancy and workflow for multiple portfolios, clients, and teams. Intelligence is global; mandates, permissions, and workspaces are local. Explicit InstitutionalExecutionContext flows through UAG, RW, PUB, CIO, and PCE.',
    zone: 'publication',
    accent: 'orange',
    healthKey: 'mpc01',
    route: '/platform/health',
    docs: '/docs/AGI_MPC_01_MULTI_PORTFOLIO.md',
    inputs: [
      'Portfolio registry',
      'Client registry',
      'Mandate profiles',
      'Role permissions',
      'User / role / portfolio selection',
    ],
    outputs: [
      'InstitutionalExecutionContext',
      'InstitutionalPortfolioWorkspace',
      'InstitutionalClient',
      'Scoped Ask / Research / Publications',
    ],
    upstream: ['PUB01', 'RW01', 'UAG01', 'PCE01', 'CIO01'],
    downstream: ['AskAGI', 'RW01', 'PRP01'],
    version: '1.0',
    critical: true,
  },
  {
    id: 'PRP01',
    code: 'PRP-01',
    name: 'Performance & Scale',
    purpose:
      'Production Readiness Programme — Redis/in-memory caches (query · object · workspace · publication · graph), parallel orchestration, async publication jobs, incremental graph updates, streaming, and Performance Center metrics. Architecture frozen at AGIB v1.0; no new intelligence engines.',
    zone: 'platform',
    accent: 'orange',
    healthKey: 'prp01',
    route: '/performance/health',
    docs: '/docs/AGI_PRP_01_PERFORMANCE_SCALE.md',
    inputs: [
      'Ask / workspace / publication hot paths',
      'Redis (optional) + in-memory fallback',
      'Background job queue',
      'Latency samples',
    ],
    outputs: [
      'Cache hit rate',
      'P95 latency',
      'Slow queries',
      'Queue depth / active workers',
      'Async publication jobs',
    ],
    upstream: ['UAG01', 'RW01', 'PUB01', 'MPC01', 'KG01'],
    downstream: ['AskAGI', 'MissionControl'],
    version: '1.0',
    critical: true,
  },
];

export const ZONES = [
  {
    id: 'evidence',
    title: 'Data & Evidence',
    subtitle: 'Ingest · extract · verify',
    accent: 'blue',
  },
  {
    id: 'core',
    title: 'Intelligence Core',
    subtitle: 'Knowledge · forecast · memory',
    accent: 'green',
  },
  {
    id: 'reasoning',
    title: 'Institutional Reasoning',
    subtitle: 'Analysts · committee · portfolio',
    accent: 'gold',
  },
  {
    id: 'decision',
    title: 'Decision & Output',
    subtitle: 'IDE V2 · company packs',
    accent: 'purple',
  },
  {
    id: 'publication',
    title: 'Publication & QA',
    subtitle: 'CIO · writer · Ask AGI',
    accent: 'purple',
  },
  {
    id: 'platform',
    title: 'Platform Contracts',
    subtitle: 'Office SDK · Event Bus',
    accent: 'orange',
  },
];

export function layersByZone(zoneId) {
  return LAYERS.filter((l) => l.zone === zoneId);
}

export function findLayer(id) {
  return LAYERS.find((l) => l.id === id || l.code === id) || null;
}
