"""Phase 2 workstream catalogue — specifications only until implementation PRs land."""

from __future__ import annotations

from typing import Any

WORKSTREAMS: tuple[dict[str, Any], ...] = (
    {
        "id": "P2.1",
        "code": "earnings_intelligence",
        "title": "Financial Statements & Earnings Intelligence",
        "package": "earnings_intelligence",
        "canonical_warehouse": "financial_statements_engine",
        "canonical_spec": "docs/FSE_01_FINANCIAL_STATEMENTS_ENGINE.md",
        "priority": 2,
        "status": "implemented",
        "note": "P2.1 NSE XBRL ingestion is the FSE-01 extraction adapter; consumers must read via financial_statements_engine.",
        "capabilities": [
            "nse_integrated_filing_discovery",
            "nse_corporates_financial_results",
            "indas_xbrl_income_statement",
            "indas_xbrl_balance_sheet",
            "indas_xbrl_cash_flow",
            "segment_reporting",
            "ttm_derivation",
            "quarterly_trend_analysis",
            "annual_history",
            "margin_trajectory",
            "cash_flow_quality",
            "forecast_confidence",
            # Forward estimate / consensus tracks remain for follow-on
            "revenue_forecasting",
            "eps_forecasting",
            "ebitda_forecasting",
            "margin_forecasting",
            "consensus_aggregation",
            "estimate_revision_tracking",
            "earnings_surprise_prediction",
            "guidance_extraction",
            "guidance_history",
            "estimate_dispersion",
            "historical_forecast_accuracy",
        ],
        "outputs": [
            "Financial Statements Pack",
            "TTM Metrics",
            "Revenue Outlook",
            "EPS Outlook",
            "Margin Outlook",
            "Forecast Confidence",
            "Cash Flow Quality",
            "Earnings Risk",
        ],
        "api_prefix": "/v1/earnings-intelligence",
    },
    {
        "id": "P2.2",
        "code": "valuation_intelligence",
        "title": "Valuation Intelligence",
        "package": "valuation_intelligence",
        "priority": 3,
        "status": "implemented",
        "capabilities": [
            "peer_universe_registry",
            "market_multiples",
            "relative_valuation",
            "historical_valuation_bands",
            "profitability_quality",
            "growth_cagr",
            "peg",
            "ev_ebitda",
            "ev_sales",
            "pe",
            "pb",
            "valuation_narrative",
            "cid_valuation_evidence",
            "sector_method_selection",
        ],
        "outputs": [
            "Current Multiples",
            "Peer Medians",
            "Premium / Discount",
            "Historical Percentile",
            "Valuation Narrative",
            "Valuation Confidence",
            "Evidence Lineage",
        ],
        "api_prefix": "/v1/valuation-intelligence",
    },
    {
        "id": "P2.3",
        "code": "ownership_intelligence",
        "title": "Ownership Intelligence",
        "package": "ownership_intelligence",
        "priority": 1,
        "status": "implemented",
        "capabilities": [
            "promoter_holding",
            "promoter_pledge",
            "fii_ownership",
            "dii_ownership",
            "mutual_fund_ownership",
            "insurance_ownership",
            "quarterly_ownership_evolution",
            "qoq_ownership_deltas",
            "ownership_concentration",
            "ownership_trend",
            "nse_master_ingest",
            "nse_xbrl_normalize",
            # Insider / block-bulk remain specified for follow-on collectors
            "insider_buying",
            "insider_selling",
            "block_deals",
            "bulk_deals",
        ],
        "outputs": [
            "Ownership Quality",
            "Institutional Accumulation",
            "Governance Signals",
            "Ownership Risk",
            "Ownership Stability",
            "Promoter Alignment",
            "Pledge Risk",
            "Ownership Trend",
        ],
        "api_prefix": "/v1/ownership-intelligence",
    },
    {
        "id": "P2.4",
        "code": "catalyst_intelligence",
        "title": "Catalyst Intelligence",
        "package": "catalyst_intelligence",
        "priority": 5,
        "status": "specified",
        "capabilities": [
            "earnings_catalysts",
            "policy_catalysts",
            "ma_buybacks",
            "capacity_product_launches",
            "regulatory_approvals",
            "commodity_fx_credit_cycle",
        ],
        "outputs": [
            "Catalyst Calendar",
            "Catalyst Impact",
            "Catalyst Probability",
            "Catalyst Timing",
        ],
        "api_prefix": "/v1/catalyst-intelligence",
    },
    {
        "id": "P2.5",
        "code": "sector_intelligence_playbooks",
        "title": "Sector Intelligence",
        "package": "sector_intelligence_playbooks",
        "priority": 4,
        "status": "specified",
        "capabilities": [
            "sector_kpis",
            "valuation_framework",
            "operating_metrics",
            "risk_model",
            "earnings_drivers",
            "peer_comparison_methodology",
        ],
        "sectors_v1": [
            "Banks",
            "NBFC",
            "IT",
            "Power",
            "Utilities",
            "Defence",
            "Auto",
            "Pharma",
            "Capital Goods",
            "FMCG",
            "Insurance",
            "Real Estate",
            "Telecom",
            "Metals",
            "Chemicals",
            "Consumer Internet",
        ],
        "outputs": ["Sector Playbook"],
        "api_prefix": "/v1/sector-playbooks",
    },
    {
        "id": "P2.6",
        "code": "live_market_context",
        "title": "Live Market Context",
        "package": "live_market_context",
        "priority": 0,
        "status": "specified",
        "capabilities": [
            "live_price",
            "volume",
            "delivery",
            "volatility",
            "relative_strength",
            "distance_to_intrinsic_value",
            "liquidity",
            "market_breadth",
        ],
        "outputs": ["Market Context Panel"],
        "api_prefix": "/v1/live-market-context",
        "rule": "Refresh market context only; never invalidate research unless governance requires it.",
    },
)


def workstream_board() -> dict[str, Any]:
    ordered = sorted(WORKSTREAMS, key=lambda w: int(w.get("priority") if w.get("priority") is not None else 99))
    return {
        "n": len(ordered),
        "workstreams": list(ordered),
        "implementation_order": [w["id"] for w in ordered],
        "recommended_first_build": ["P2.6", "P2.3", "P2.1"],
    }
