"""Macro regime playbooks — executable institutional guidance."""

from __future__ import annotations

from typing import Any

_PLAYBOOKS: dict[str, dict[str, Any]] = {
    "high_rates": {
        "definition": "Elevated policy/market rates with tight financial conditions",
        "primary_characteristics": ["High bond yields", "Tight liquidity", "Expensive capital"],
        "typical_market_behaviour": ["Duration compression", "Quality bid", "Leverage derated"],
        "typical_sector_rotation": ["Into banks/insurance", "Out of real estate/utilities/durables"],
        "typical_winners": ["banks", "insurance"],
        "typical_losers": ["real_estate", "utilities", "consumer", "nbfc"],
        "preferred_valuation_frameworks": ["residual_income", "roe", "pb", "roic", "cash_flow"],
        "frameworks_to_deemphasise": ["long_duration_dcf", "aggressive_terminal_growth", "ev_sales_growth"],
        "accounting_considerations": ["Interest coverage", "Refinancing walls", "Fair-value of financial assets"],
        "business_quality_considerations": ["Pricing power", "Low leverage", "Cash conversion"],
        "portfolio_positioning": ["Lower duration", "Higher quality", "Lower leverage"],
        "risk_checklist": ["Funding stress", "Duration risk", "Credit migration"],
        "common_mistakes": ["Using peak-growth DCFs unchanged", "Ignoring deposit beta lags for banks"],
        "historical_analogues": ["2013", "2022", "rate_hike_2022_23", "taper_2013"],
    },
    "low_rates": {
        "definition": "Low policy rates with easy financial conditions",
        "primary_characteristics": ["Low yields", "Ample liquidity", "Cheap capital"],
        "typical_market_behaviour": ["Duration extension", "Growth re-rating"],
        "typical_sector_rotation": ["Into growth/real estate/utilities", "Out of defensive cash"],
        "typical_winners": ["real_estate", "utilities", "internet", "auto"],
        "typical_losers": ["cash", "short_duration_defensives"],
        "preferred_valuation_frameworks": ["dcf", "growth", "ev_sales"],
        "frameworks_to_deemphasise": ["distress", "liquidation"],
        "accounting_considerations": ["Capitalised growth spend quality"],
        "business_quality_considerations": ["Durable growth", "Unit economics"],
        "portfolio_positioning": ["Raise duration selectively", "Growth beta"],
        "risk_checklist": ["Bubble valuations", "Leverage build-up"],
        "common_mistakes": ["Ignoring mean-reversion of rates"],
        "historical_analogues": ["2009-2010", "2020-2021", "recovery_2009_10"],
    },
    "high_inflation": {
        "definition": "Elevated and persistent inflation",
        "primary_characteristics": ["Rising CPI", "Input cost pressure", "Policy tightening risk"],
        "typical_market_behaviour": ["Multiple compression", "Commodity support"],
        "typical_sector_rotation": ["Into metals/energy", "Out of staples margins / discretionary"],
        "typical_winners": ["metals", "oil_gas"],
        "typical_losers": ["fmcg", "consumer", "utilities"],
        "preferred_valuation_frameworks": ["roic", "cash_flow", "midcycle_earnings"],
        "frameworks_to_deemphasise": ["static_historical_averages", "long_duration_dcf"],
        "accounting_considerations": ["Inventory gains quality", "Pricing lag"],
        "business_quality_considerations": ["Pricing power", "Cost pass-through"],
        "portfolio_positioning": ["Real assets / quality compounders"],
        "risk_checklist": ["Policy overtightening", "Margin air-pockets"],
        "common_mistakes": ["Treating inventory gains as franchise earnings"],
        "historical_analogues": ["2022", "FY14"],
    },
    "commodity_boom": {
        "definition": "Broad commodity price upcycle",
        "primary_characteristics": ["Rising oil/metals", "Exporter terms-of-trade support"],
        "typical_market_behaviour": ["Energy/metals leadership"],
        "typical_sector_rotation": ["Into oil_gas/metals/mining", "Out of airlines/chemicals consumers"],
        "typical_winners": ["oil_gas", "metals", "mining"],
        "typical_losers": ["logistics", "chemicals", "fmcg"],
        "preferred_valuation_frameworks": ["midcycle_dcf", "ev_ebitda", "capital_allocation"],
        "frameworks_to_deemphasise": ["peak_earnings_pe", "static_historical_averages"],
        "accounting_considerations": ["Inventory / stripping costs", "Sustaining capex"],
        "business_quality_considerations": ["Cost curve position", "Balance sheet"],
        "portfolio_positioning": ["Cycle-aware energy/metals", "Avoid peak multiple expansion"],
        "risk_checklist": ["Demand destruction", "Policy windfalls"],
        "common_mistakes": ["Capitalising peak margins"],
        "historical_analogues": ["2008_pre_crisis", "2021-2022"],
    },
    "liquidity_tightening": {
        "definition": "System liquidity withdrawal / tight surplus conditions",
        "primary_characteristics": ["Rising funding stress", "Risk-off"],
        "typical_market_behaviour": ["Deleveraging", "Flight to quality"],
        "typical_sector_rotation": ["Into quality banks/fmcg", "Out of high-beta NBFCs"],
        "typical_winners": ["banks", "fmcg"],
        "typical_losers": ["nbfc", "real_estate", "internet"],
        "preferred_valuation_frameworks": ["balance_sheet", "cash_flow", "roe"],
        "frameworks_to_deemphasise": ["growth_at_any_price"],
        "accounting_considerations": ["Going-concern / covenants"],
        "business_quality_considerations": ["Liquidity runway"],
        "portfolio_positioning": ["Cut leverage beta", "Raise quality"],
        "risk_checklist": ["Rollover risk", "Gap risk"],
        "common_mistakes": ["Assuming funding always rolls"],
        "historical_analogues": ["2013", "2018_nbfc", "2020_march"],
    },
    "risk_off": {
        "definition": "Risk aversion dominates markets",
        "primary_characteristics": ["Equity drawdowns", "USD bid", "Credit spreads wider"],
        "typical_market_behaviour": ["Correlation → 1", "Liquidity premium"],
        "typical_sector_rotation": ["Defensives", "Out of cyclicals/high beta"],
        "typical_winners": ["fmcg", "pharma", "it_services"],
        "typical_losers": ["auto", "metals", "real_estate"],
        "preferred_valuation_frameworks": ["balance_sheet", "cash_flow", "defensive_earnings"],
        "frameworks_to_deemphasise": ["momentum_growth"],
        "accounting_considerations": ["Asset impairments", "Working capital stress"],
        "business_quality_considerations": ["Recurring demand", "Net cash"],
        "portfolio_positioning": ["Raise cash/quality", "Cut beta"],
        "risk_checklist": ["Liquidity", "Counterparty"],
        "common_mistakes": ["Averaging down leverage"],
        "historical_analogues": ["gfc_2008", "covid_2020"],
    },
    "expansion": {
        "definition": "Broadening growth with supportive financial conditions",
        "primary_characteristics": ["Rising PMI/GDP", "Credit expansion"],
        "typical_market_behaviour": ["Cyclical leadership"],
        "typical_sector_rotation": ["Industrials/auto/metals"],
        "typical_winners": ["industrials", "auto", "banks", "metals"],
        "typical_losers": ["deep_defensives"],
        "preferred_valuation_frameworks": ["ev_ebitda", "pe", "dcf"],
        "frameworks_to_deemphasise": ["distress"],
        "accounting_considerations": ["Operating leverage optics"],
        "business_quality_considerations": ["Incremental ROIC"],
        "portfolio_positioning": ["Raise cyclical beta"],
        "risk_checklist": ["Late-cycle excess"],
        "common_mistakes": ["Chasing peak multiples"],
        "historical_analogues": ["recovery_2009_10", "post_covid_2021"],
    },
    "contraction": {
        "definition": "Falling activity / recessionary conditions",
        "primary_characteristics": ["Weak PMI", "Credit stress"],
        "typical_market_behaviour": ["Earnings cuts", "Multiple floors then recovery"],
        "typical_sector_rotation": ["Defensives / quality"],
        "typical_winners": ["fmcg", "pharma", "utilities"],
        "typical_losers": ["auto", "metals", "real_estate", "nbfc"],
        "preferred_valuation_frameworks": ["balance_sheet", "cash_flow", "through_cycle"],
        "frameworks_to_deemphasise": ["peak_cycle_multiples"],
        "accounting_considerations": ["Covenant headroom", "Impairments"],
        "business_quality_considerations": ["Survival first"],
        "portfolio_positioning": ["Defensive / net cash"],
        "risk_checklist": ["Solvency", "Demand collapse"],
        "common_mistakes": ["Buying cyclicals too early without liquidity"],
        "historical_analogues": ["gfc_2008", "covid_2020"],
    },
}


def regime_playbook(regime: str) -> dict[str, Any]:
    key = regime.strip().lower().replace(" ", "_")
    # aliases
    aliases = {
        "high_interest_rate": "high_rates",
        "high_interest_rates": "high_rates",
        "low_interest_rate": "low_rates",
        "commodity_bust": "contraction",
        "liquidity_expansion": "low_rates",
        "credit_expansion": "expansion",
        "credit_contraction": "liquidity_tightening",
        "yield_curve_inversion": "contraction",
        "recovery": "expansion",
        "peak": "high_rates",
        "risk_on": "expansion",
        "low_inflation": "low_rates",
    }
    key = aliases.get(key, key)
    pb = _PLAYBOOKS.get(key)
    if not pb:
        pb = {
            "definition": f"Institutional playbook for {key}",
            "primary_characteristics": [key],
            "typical_market_behaviour": ["Context-dependent"],
            "typical_sector_rotation": [],
            "typical_winners": [],
            "typical_losers": [],
            "preferred_valuation_frameworks": ["roic", "cash_flow"],
            "frameworks_to_deemphasise": [],
            "accounting_considerations": [],
            "business_quality_considerations": [],
            "portfolio_positioning": ["Maintain quality"],
            "risk_checklist": ["Regime uncertainty"],
            "common_mistakes": ["Overfitting single indicator"],
            "historical_analogues": [],
        }
    return {"regime": key, "executable": True, **pb}


def all_regime_playbooks() -> dict[str, dict[str, Any]]:
    return {k: regime_playbook(k) for k in _PLAYBOOKS}
