"""Canonical metric definitions (FKB-01). Knowledge only — no calculations."""

from __future__ import annotations

from typing import Any

from financial_knowledge.schema import (
    CAT_BALANCE,
    CAT_CASHFLOW,
    CAT_DERIVED,
    CAT_INCOME,
    STATEMENT_BALANCE,
    STATEMENT_CASHFLOW,
    STATEMENT_INCOME,
    STATEMENT_NONE,
)


def _m(
    id_: str,
    name: str,
    *,
    category: str,
    statement: str,
    description: str,
    interpretation: str,
    positive_direction: str,
    negative_direction: str,
    formula: str | None = None,
    units: str = "currency",
    dependencies: list[str] | None = None,
    related: list[str] | None = None,
    evidence_source: str = "financial_warehouse",
) -> dict[str, Any]:
    return {
        "id": id_,
        "display_name": name,
        "category": category,
        "financial_statement": statement,
        "formula": formula,
        "units": units,
        "description": description,
        "interpretation": interpretation,
        "positive_direction": positive_direction,
        "negative_direction": negative_direction,
        "dependencies": dependencies or [],
        "related_metrics": related or [],
        "primary_evidence_source": evidence_source,
        "performs_analysis": False,
    }


METRICS: dict[str, dict[str, Any]] = {
    "revenue": _m(
        "revenue",
        "Revenue",
        category=CAT_INCOME,
        statement=STATEMENT_INCOME,
        description="Income generated from ordinary business activities.",
        interpretation="Top-line scale of the operating franchise.",
        positive_direction="Higher revenue may indicate business expansion, subject to profitability and cash generation.",
        negative_direction="Declining revenue may indicate demand weakness, share loss, or portfolio exits.",
        related=["gross_profit", "ebitda", "operating_cash_flow"],
    ),
    "gross_profit": _m(
        "gross_profit",
        "Gross Profit",
        category=CAT_INCOME,
        statement=STATEMENT_INCOME,
        formula="Revenue - COGS",
        description="Revenue remaining after direct cost of goods sold.",
        interpretation="Core product/service economics before operating overhead.",
        positive_direction="Rising gross profit with stable or expanding margins supports pricing power.",
        negative_direction="Falling gross profit may signal cost inflation or pricing pressure.",
        dependencies=["revenue", "cogs"],
        related=["gross_margin"],
    ),
    "cogs": _m(
        "cogs",
        "Cost of Goods Sold",
        category=CAT_INCOME,
        statement=STATEMENT_INCOME,
        description="Direct costs attributable to goods or services sold.",
        interpretation="Primary driver of gross profitability.",
        positive_direction="Lower COGS relative to revenue generally improves gross margin.",
        negative_direction="Rising COGS intensity compresses gross margin.",
        related=["revenue", "gross_profit"],
    ),
    "ebitda": _m(
        "ebitda",
        "EBITDA",
        category=CAT_INCOME,
        statement=STATEMENT_INCOME,
        formula="EBIT + Depreciation + Amortisation (presentation-dependent)",
        description="Earnings before interest, tax, depreciation and amortisation.",
        interpretation="Proxy for operating cash generation before capital structure and tax.",
        positive_direction="Higher EBITDA may indicate stronger operating earnings power.",
        negative_direction="Declining EBITDA may indicate operating stress.",
        related=["ebit", "ebitda_margin", "total_debt"],
    ),
    "ebit": _m(
        "ebit",
        "EBIT",
        category=CAT_INCOME,
        statement=STATEMENT_INCOME,
        description="Operating profit after depreciation/amortisation, before interest and tax.",
        interpretation="Core operating profitability including capital consumption via D&A.",
        positive_direction="Rising EBIT with revenue growth can indicate operating leverage.",
        negative_direction="Falling EBIT may indicate margin or volume pressure.",
        related=["operating_margin", "interest_coverage"],
    ),
    "pat": _m(
        "pat",
        "PAT",
        category=CAT_INCOME,
        statement=STATEMENT_INCOME,
        description="Profit after tax attributable to owners (net income).",
        interpretation="Bottom-line accounting profit.",
        positive_direction="Higher PAT increases reported earnings, subject to cash conversion quality.",
        negative_direction="Falling PAT indicates profitability deterioration.",
        related=["net_income", "eps_basic", "operating_cash_flow"],
    ),
    "net_income": _m(
        "net_income",
        "Net Income",
        category=CAT_INCOME,
        statement=STATEMENT_INCOME,
        description="Profit after tax; canonical warehouse alias for PAT.",
        interpretation="Same economic concept as PAT in most AGIB contexts.",
        positive_direction="Higher net income increases reported earnings power.",
        negative_direction="Lower net income indicates earnings pressure.",
        related=["pat", "eps_basic", "roe"],
    ),
    "eps_basic": _m(
        "eps_basic",
        "EPS (Basic)",
        category=CAT_INCOME,
        statement=STATEMENT_INCOME,
        formula="PAT / Weighted average basic shares",
        units="per_share",
        description="Basic earnings per share.",
        interpretation="Per-share claim on accounting profit.",
        positive_direction="Rising EPS may indicate earnings growth or share reduction.",
        negative_direction="Falling EPS indicates per-share earnings weakness.",
        dependencies=["pat"],
        related=["dividends"],
    ),
    "operating_cash_flow": _m(
        "operating_cash_flow",
        "Operating Cash Flow",
        category=CAT_CASHFLOW,
        statement=STATEMENT_CASHFLOW,
        description="Cash generated or used by operating activities.",
        interpretation="Cash reality of reported operations.",
        positive_direction="Strong OCF supporting PAT indicates high earnings quality.",
        negative_direction="Weak OCF versus PAT indicates cash conversion risk.",
        related=["pat", "free_cash_flow", "working_capital"],
    ),
    "investing_cash_flow": _m(
        "investing_cash_flow",
        "Investing Cash Flow",
        category=CAT_CASHFLOW,
        statement=STATEMENT_CASHFLOW,
        description="Cash flows from investing activities including capex and acquisitions.",
        interpretation="Capital deployment into long-term assets and investments.",
        positive_direction="Context-dependent; lower outflow may mean less reinvestment.",
        negative_direction="Large outflows may indicate expansion or M&A (not inherently negative).",
        related=["capex", "free_cash_flow"],
    ),
    "financing_cash_flow": _m(
        "financing_cash_flow",
        "Financing Cash Flow",
        category=CAT_CASHFLOW,
        statement=STATEMENT_CASHFLOW,
        description="Cash flows from financing activities (debt, equity, dividends).",
        interpretation="How the firm funds itself and returns capital.",
        positive_direction="Context-dependent.",
        negative_direction="Context-dependent; heavy issuance may signal funding need.",
        related=["total_debt", "dividends", "share_buybacks"],
    ),
    "free_cash_flow": _m(
        "free_cash_flow",
        "Free Cash Flow",
        category=CAT_DERIVED,
        statement=STATEMENT_NONE,
        formula="Operating Cash Flow - Capex",
        description="Cash available after maintaining/expanding the asset base (definition-dependent).",
        interpretation="Key measure of discretionary cash generation.",
        positive_direction="Rising FCF supports dividends, buybacks, deleveraging, or flexibility.",
        negative_direction="Falling FCF may indicate cash conversion or capex pressure.",
        dependencies=["operating_cash_flow", "capex"],
        related=["fcf_conversion", "dividends"],
        evidence_source="derived_metrics",
    ),
    "capex": _m(
        "capex",
        "Capex",
        category=CAT_CASHFLOW,
        statement=STATEMENT_CASHFLOW,
        description="Capital expenditure on PPE and related long-term assets.",
        interpretation="Reinvestment intensity and expansion signal.",
        positive_direction="Context-dependent; growth capex can be constructive if returns follow.",
        negative_direction="Elevated capex without returns may pressure FCF.",
        related=["free_cash_flow", "roce"],
    ),
    "dividends": _m(
        "dividends",
        "Dividend",
        category=CAT_CASHFLOW,
        statement=STATEMENT_CASHFLOW,
        description="Cash returned to shareholders as dividends.",
        interpretation="Shareholder distribution policy component.",
        positive_direction="Sustainable dividends signal cash generation confidence.",
        negative_direction="Unsustainable payouts relative to FCF are a risk.",
        related=["dividend_payout", "free_cash_flow"],
    ),
    "share_buybacks": _m(
        "share_buybacks",
        "Share Buybacks",
        category=CAT_CASHFLOW,
        statement=STATEMENT_CASHFLOW,
        description="Cash used to repurchase shares.",
        interpretation="Alternative shareholder return versus dividends.",
        positive_direction="Buybacks funded by surplus FCF can be accretive.",
        negative_direction="Buybacks funded by leverage may weaken the balance sheet.",
        related=["dividends", "total_debt", "eps_basic"],
    ),
    "net_debt": _m(
        "net_debt",
        "Net Debt",
        category=CAT_BALANCE,
        statement=STATEMENT_BALANCE,
        formula="Total Debt - Cash",
        description="Debt outstanding net of cash and cash equivalents.",
        interpretation="Leverage after liquid resources.",
        positive_direction="Lower net debt generally improves financial flexibility.",
        negative_direction="Rising net debt increases leverage risk.",
        dependencies=["total_debt", "cash"],
        related=["debt_to_ebitda", "debt_to_equity"],
    ),
    "cash": _m(
        "cash",
        "Cash",
        category=CAT_BALANCE,
        statement=STATEMENT_BALANCE,
        description="Cash and cash equivalents.",
        interpretation="Immediate liquidity buffer.",
        positive_direction="Higher cash improves liquidity, subject to capital allocation opportunity cost.",
        negative_direction="Falling cash may indicate liquidity pressure if not planned deployment.",
        related=["net_debt", "current_ratio"],
    ),
    "total_debt": _m(
        "total_debt",
        "Total Debt",
        category=CAT_BALANCE,
        statement=STATEMENT_BALANCE,
        description="Interest-bearing debt obligations.",
        interpretation="Gross leverage claim on the firm.",
        positive_direction="Lower debt generally reduces solvency risk.",
        negative_direction="Rising debt increases leverage and interest burden.",
        related=["net_debt", "interest_coverage"],
    ),
    "inventory": _m(
        "inventory",
        "Inventory",
        category=CAT_BALANCE,
        statement=STATEMENT_BALANCE,
        description="Goods held for sale or in production.",
        interpretation="Working capital component; sector-sensitive.",
        positive_direction="Context-dependent; efficient inventory supports cash conversion.",
        negative_direction="Inventory build can signal demand weakness or overproduction.",
        related=["working_capital", "inventory_turnover"],
    ),
    "receivables": _m(
        "receivables",
        "Receivables",
        category=CAT_BALANCE,
        statement=STATEMENT_BALANCE,
        description="Amounts owed by customers.",
        interpretation="Credit extended to customers; working capital driver.",
        positive_direction="Stable receivables with revenue growth can be healthy.",
        negative_direction="Receivables growing faster than revenue may indicate WC deterioration.",
        related=["working_capital", "receivable_days"],
    ),
    "payables": _m(
        "payables",
        "Payables",
        category=CAT_BALANCE,
        statement=STATEMENT_BALANCE,
        description="Amounts owed to suppliers.",
        interpretation="Supplier financing component of working capital.",
        positive_direction="Longer payables can fund WC (within supplier relationships).",
        negative_direction="Forced shortening of payables can signal financing pressure.",
        related=["working_capital", "payable_days"],
    ),
    "working_capital": _m(
        "working_capital",
        "Working Capital",
        category=CAT_BALANCE,
        statement=STATEMENT_BALANCE,
        formula="Current Assets - Current Liabilities (definition-dependent)",
        description="Short-term operating capital tied in the business cycle.",
        interpretation="Liquidity and operating efficiency bridge between P&L and cash.",
        positive_direction="Improving efficiency (lower WC intensity) often aids cash conversion.",
        negative_direction="WC expansion ahead of sales can pressure cash.",
        related=["receivables", "inventory", "payables", "cash_conversion_cycle"],
    ),
    "capital_employed": _m(
        "capital_employed",
        "Capital Employed",
        category=CAT_DERIVED,
        statement=STATEMENT_NONE,
        formula="Equity + Net Debt (definition-dependent)",
        description="Capital invested in the enterprise.",
        interpretation="Denominator for ROCE-type return measures.",
        positive_direction="Efficient use of capital employed raises ROCE.",
        negative_direction="Capital intensity without returns depresses ROCE.",
        dependencies=["total_equity", "net_debt"],
        related=["roce", "roic"],
        evidence_source="derived_metrics",
    ),
    "total_equity": _m(
        "total_equity",
        "Equity",
        category=CAT_BALANCE,
        statement=STATEMENT_BALANCE,
        description="Shareholders' equity / net assets.",
        interpretation="Residual claim after liabilities.",
        positive_direction="Growing equity from retained earnings strengthens the balance sheet.",
        negative_direction="Eroding equity may indicate losses or distributions exceeding earnings.",
        related=["roe", "debt_to_equity"],
    ),
    "total_assets": _m(
        "total_assets",
        "Assets",
        category=CAT_BALANCE,
        statement=STATEMENT_BALANCE,
        description="Total resources controlled by the entity.",
        interpretation="Scale of the balance sheet.",
        positive_direction="Asset growth is constructive if returns are adequate.",
        negative_direction="Asset growth without returns indicates capital intensity risk.",
        related=["asset_turnover", "roa"],
    ),
    "total_liabilities": _m(
        "total_liabilities",
        "Liabilities",
        category=CAT_BALANCE,
        statement=STATEMENT_BALANCE,
        description="Present obligations of the entity.",
        interpretation="Claims on assets by creditors and other counterparties.",
        positive_direction="Lower liability burden generally improves solvency.",
        negative_direction="Rising liabilities increase claims priority ahead of equity.",
        related=["total_debt", "total_equity"],
    ),
    # Margin / return measures as first-class derived metrics (also catalogued as ratios).
    "gross_margin": _m(
        "gross_margin",
        "Gross Margin",
        category=CAT_DERIVED,
        statement=STATEMENT_NONE,
        formula="Gross Profit / Revenue",
        units="percent",
        description="Gross profit as a percentage of revenue.",
        interpretation="Product/service economics before operating overhead.",
        positive_direction="Higher gross margin indicates stronger pricing or cost position.",
        negative_direction="Lower gross margin indicates pricing or COGS pressure.",
        dependencies=["gross_profit", "revenue"],
        related=["revenue", "gross_profit"],
        evidence_source="derived_metrics",
    ),
    "operating_margin": _m(
        "operating_margin",
        "Operating Margin",
        category=CAT_DERIVED,
        statement=STATEMENT_NONE,
        formula="EBIT / Revenue",
        units="percent",
        description="Operating profit as a percentage of revenue.",
        interpretation="Core operating profitability including D&A.",
        positive_direction="Higher operating margin indicates operating leverage or efficiency.",
        negative_direction="Lower operating margin indicates margin pressure.",
        dependencies=["ebit", "revenue"],
        related=["revenue", "ebit"],
        evidence_source="derived_metrics",
    ),
    "ebitda_margin": _m(
        "ebitda_margin",
        "EBITDA Margin",
        category=CAT_DERIVED,
        statement=STATEMENT_NONE,
        formula="EBITDA / Revenue",
        units="percent",
        description="EBITDA as a percentage of revenue.",
        interpretation="Operating profitability before D&A.",
        positive_direction="Higher EBITDA margin indicates stronger operating earnings intensity.",
        negative_direction="Lower EBITDA margin indicates operating pressure.",
        dependencies=["ebitda", "revenue"],
        related=["revenue", "ebitda"],
        evidence_source="derived_metrics",
    ),
    "net_margin": _m(
        "net_margin",
        "Net Margin",
        category=CAT_DERIVED,
        statement=STATEMENT_NONE,
        formula="PAT / Revenue",
        units="percent",
        description="Net profit as a percentage of revenue.",
        interpretation="Bottom-line profitability intensity.",
        positive_direction="Higher net margin indicates stronger earnings conversion.",
        negative_direction="Lower net margin indicates profitability pressure.",
        dependencies=["pat", "revenue"],
        related=["pat", "revenue"],
        evidence_source="derived_metrics",
    ),
    "roe": _m(
        "roe",
        "ROE",
        category=CAT_DERIVED,
        statement=STATEMENT_NONE,
        formula="PAT / Equity",
        units="percent",
        description="Return on equity.",
        interpretation="Equity capital efficiency; sector norms differ.",
        positive_direction="Higher ROE indicates stronger equity returns (context-dependent).",
        negative_direction="Lower ROE indicates weaker equity returns.",
        dependencies=["pat", "total_equity"],
        related=["roce", "roic"],
        evidence_source="derived_metrics",
    ),
    "roce": _m(
        "roce",
        "ROCE",
        category=CAT_DERIVED,
        statement=STATEMENT_NONE,
        formula="EBIT / Capital Employed",
        units="percent",
        description="Return on capital employed.",
        interpretation="Preferred return lens for capital-intensive businesses.",
        positive_direction="Higher ROCE indicates better capital efficiency.",
        negative_direction="Lower ROCE indicates weaker capital efficiency.",
        dependencies=["ebit", "capital_employed"],
        related=["roe", "roic"],
        evidence_source="derived_metrics",
    ),
    "roic": _m(
        "roic",
        "ROIC",
        category=CAT_DERIVED,
        statement=STATEMENT_NONE,
        formula="NOPAT / Invested Capital",
        units="percent",
        description="Return on invested capital.",
        interpretation="After-tax operating return on invested capital.",
        positive_direction="Higher ROIC indicates value-creative capital deployment.",
        negative_direction="Lower ROIC indicates low-return capital use.",
        dependencies=["ebit", "total_equity", "net_debt"],
        related=["roe", "roce"],
        evidence_source="derived_metrics",
    ),
    "asset_turnover": _m(
        "asset_turnover",
        "Asset Turnover",
        category=CAT_DERIVED,
        statement=STATEMENT_NONE,
        formula="Revenue / Average Total Assets",
        units="ratio",
        description="Revenue generated per unit of assets.",
        interpretation="Capital intensity / efficiency signal.",
        positive_direction="Higher turnover indicates greater asset efficiency.",
        negative_direction="Lower turnover indicates higher capital intensity.",
        dependencies=["revenue", "total_assets"],
        related=["total_assets", "roce"],
        evidence_source="derived_metrics",
    ),
}


def all_metrics() -> list[dict[str, Any]]:
    return [METRICS[k] for k in sorted(METRICS)]


def get_metric(key: str) -> dict[str, Any] | None:
    k = key.strip().lower().replace(" ", "_").replace("-", "_")
    aliases = {
        "profit_after_tax": "pat",
        "dividend": "dividends",
        "assets": "total_assets",
        "liabilities": "total_liabilities",
        "equity": "total_equity",
        "ocf": "operating_cash_flow",
        "fcf": "free_cash_flow",
    }
    k = aliases.get(k, k)
    row = METRICS.get(k)
    return dict(row) if row else None
