"""Cross-book institutional synthesis — unified knowledge objects, not per-book paragraphs."""

from __future__ import annotations

from academy.books.v3.schema import (
    AuthorPerspective,
    CaseStudy,
    ChapterKnowledge,
    ConceptCard,
    FailurePattern,
    FormulaCard,
    FrameworkCard,
    InstitutionalKnowledgeObject,
    SectorKnowledge,
)


def seed_concepts() -> list[ConceptCard]:
    return [
        ConceptCard(
            concept_id="concept_roic",
            name="ROIC",
            definition=(
                "Return on invested capital measures operating profit generated per unit of "
                "capital permanently employed in the business."
            ),
            purpose="Judge whether the firm creates economic value above its hurdle rate.",
            business_meaning="Signals competitive advantage and reinvestment quality.",
            financial_meaning="NOPAT relative to invested capital; cash support must be checked.",
            investment_meaning="High durable ROIC supports compounding and can justify premium valuation only if sustainable.",
            indicators=["ROIC > WACC", "stability across cycle", "cash conversion of returns"],
            evidence_required=["multi-year ROIC series", "invested capital bridge", "FCF vs NOPAT"],
            questions=[
                "Is ROIC above cost of capital?",
                "Is it stable or peak-cycle?",
                "Is it cash-supported?",
                "Can capital be reinvested at similar returns?",
            ],
            examples=["Franchise compounders with durable excess returns."],
            counter_examples=["Peak commodity ROIC that mean-reverts.", "Accrual-inflated returns without cash."],
            limitations=["Accounting distortions", "sector capital intensity differences", "one-year snapshots mislead"],
            related_concepts=["wacc", "fcf", "moat", "compounding", "earnings_quality"],
            related_frameworks=["fw_roic_quality", "fw_capital_cycle"],
            related_formulas=["formula_roic"],
            analysts_using=["financial", "valuation", "business"],
            source_authors=["Damodaran", "Graham", "Klarman", "Fridson", "Fisher"],
            source_books=[
                "Investment Valuation",
                "Applied Corporate Finance",
                "Financial Statement Analysis",
                "Narrative and Numbers",
                "Security Analysis",
            ],
            difficulty="core",
            confidence=0.93,
        ),
        ConceptCard(
            concept_id="concept_intrinsic_value",
            name="Intrinsic Value",
            definition="Estimated worth of a business based on expected cash flows, risk, and growth — independent of market price.",
            purpose="Anchor price negotiation and margin-of-safety discipline.",
            business_meaning="Captures franchise durability and reinvestment economics.",
            financial_meaning="Present value of expected free cash flows under explicit assumptions.",
            investment_meaning="Compare price to value; never invert from market narrative alone.",
            indicators=["DCF range", "owner-earnings bridge", "scenario asymmetry"],
            evidence_required=["cash flow forecast rationale", "discount rate logic", "sensitivity"],
            questions=["What must be true for today's price?", "How wide is the value range?"],
            examples=["Conservative DCF below market with durable cash engine."],
            counter_examples=["Point-estimate precision theater on fragile forecasts."],
            limitations=["Garbage-in garbage-out", "terminal value dominance", "narrative bias"],
            related_concepts=["margin_of_safety", "dcf", "expectations"],
            related_frameworks=["fw_margin_of_safety", "fw_reverse_dcf"],
            related_formulas=["formula_dcf"],
            analysts_using=["valuation", "cio"],
            source_authors=["Damodaran", "Graham", "Klarman"],
            source_books=["Investment Valuation", "Security Analysis", "Margin of Safety"],
        ),
        ConceptCard(
            concept_id="concept_margin_of_safety",
            name="Margin of Safety",
            definition="Cushion between conservative intrinsic value and purchase price that absorbs error and adversity.",
            purpose="Survive being wrong about forecasts.",
            business_meaning="Demands durable economics before paying up.",
            financial_meaning="Downside cash-flow resilience under stress.",
            investment_meaning="Price discipline; uncertainty widens required cushion.",
            indicators=["discount to conservative value", "stress-case solvency"],
            evidence_required=["bear case", "balance sheet buffer"],
            questions=["What could go wrong?", "Is the cushion wide enough for that?"],
            examples=["Buying a quality franchise at a deep discount to trough assumptions."],
            counter_examples=["Paying full price for a perfect story."],
            limitations=["False precision on 'conservative' assumptions"],
            related_concepts=["intrinsic_value", "uncertainty", "downside"],
            related_frameworks=["fw_margin_of_safety"],
            analysts_using=["valuation", "risk"],
            source_authors=["Graham", "Klarman"],
            source_books=["Security Analysis", "Margin of Safety"],
        ),
        ConceptCard(
            concept_id="concept_moat",
            name="Economic Moat",
            definition="Structural advantage that allows returns above cost of capital for an extended period.",
            purpose="Assess durability of excess returns.",
            business_meaning="Brand, network, scale, switching costs, regulation, cost advantage.",
            financial_meaning="Persistent ROIC-WACC spread with cash support.",
            investment_meaning="Moat width and trend matter more than label.",
            indicators=["pricing power", "share stability", "ROIC persistence"],
            evidence_required=["competitive history", "customer retention", "unit economics"],
            questions=["What prevents imitation?", "Is the moat widening or eroding?"],
            examples=["Platforms with network effects; premium brands with pricing power."],
            counter_examples=["Temporary product cycles mistaken for moats."],
            limitations=["Moats erode; creative destruction is continuous."],
            related_concepts=["pricing_power", "roic", "network_effects", "switching_costs"],
            related_frameworks=["fw_moat", "fw_porter"],
            analysts_using=["business", "financial", "valuation"],
            source_authors=["Fisher", "Damodaran", "Porter"],
            source_books=["Common Stocks and Uncommon Profits", "Investment Valuation"],
        ),
        ConceptCard(
            concept_id="concept_earnings_quality",
            name="Earnings Quality",
            definition="Extent to which reported earnings are cash-supported, sustainable, and free of aggressive accounting.",
            purpose="Prevent valuation on illusory profits.",
            business_meaning="Operating reality vs presentation.",
            financial_meaning="Accruals, working capital, one-offs, revenue recognition.",
            investment_meaning="Low-quality earnings invalidate growth narratives and multiples.",
            indicators=["cash conversion", "accrual ratio", "non-recurring items"],
            evidence_required=["cash flow statement bridge", "notes review"],
            questions=["Do earnings convert to cash?", "What is normalized run-rate?"],
            examples=["Stable FCF/NI with clean accruals."],
            counter_examples=["Rising earnings with collapsing CFO."],
            limitations=["Industry working-capital norms differ."],
            related_concepts=["fcf", "roic", "accruals"],
            related_frameworks=["fw_earnings_quality"],
            related_formulas=["formula_cash_conversion"],
            analysts_using=["financial", "valuation"],
            source_authors=["Fridson", "Damodaran"],
            source_books=["Financial Statement Analysis", "Measuring Earnings"],
        ),
        ConceptCard(
            concept_id="concept_pricing_power",
            name="Pricing Power",
            definition="Ability to raise prices without material volume loss or mix destruction.",
            purpose="Link competitive position to margin durability.",
            business_meaning="Brand, switching costs, necessity, differentiation.",
            financial_meaning="Gross margin resilience through inflation and competition.",
            investment_meaning="Supports ROIC and premium valuation when durable.",
            indicators=["price/mix contribution", "margin through inflation spikes"],
            evidence_required=["cohort retention", "elasticity evidence", "peer margin gap"],
            questions=["Who sets price — firm or market?", "What happens in a downturn?"],
            examples=["Premium consumer franchises."],
            counter_examples=["Commodity producers as price takers."],
            related_concepts=["brand", "gross_margin", "moat"],
            related_frameworks=["fw_pricing_power"],
            analysts_using=["business", "financial"],
            source_authors=["Fisher", "Damodaran"],
        ),
        ConceptCard(
            concept_id="concept_capital_allocation",
            name="Capital Allocation",
            definition="Management choices on reinvestment, M&A, dividends, buybacks, and leverage.",
            purpose="Determine whether value is created or destroyed after operations.",
            business_meaning="Strategy expressed in cash deployment.",
            financial_meaning="ROIC on incremental capital; dilution vs buybacks; leverage risk.",
            investment_meaning="Great operators with poor allocation destroy shareholder value.",
            indicators=["incremental ROIC", "M&A returns", "buyback timing"],
            evidence_required=["uses of cash history", "acquisition post-mortems"],
            questions=["Where does each rupee of cash go?", "Does incremental capital earn above WACC?"],
            examples=["Disciplined buybacks below intrinsic value."],
            counter_examples=["Empire-building M&A at peak multiples."],
            related_concepts=["roic", "intrinsic_value", "management"],
            related_frameworks=["fw_capital_allocation"],
            analysts_using=["management", "financial", "business"],
            source_authors=["Damodaran", "Klarman"],
        ),
        ConceptCard(
            concept_id="concept_cost_of_capital",
            name="Cost of Capital",
            definition="Opportunity cost required by capital providers for risk borne — typically WACC for firm valuation.",
            purpose="Hurdle for project and firm value creation.",
            business_meaning="Riskiness of cash flows and capital structure.",
            financial_meaning="Blend of equity and after-tax debt costs.",
            investment_meaning="ROIC must clear this hurdle for economic profit.",
            indicators=["WACC vs ROIC spread", "beta/credit spreads"],
            evidence_required=["capital structure", "risk regime"],
            questions=["Is the hurdle rate consistent with risk?", "Has regime shifted?"],
            related_concepts=["roic", "wacc", "intrinsic_value"],
            related_formulas=["formula_wacc"],
            analysts_using=["valuation", "financial"],
            source_authors=["Damodaran"],
            source_books=["Investment Valuation", "Applied Corporate Finance"],
        ),
    ]


def seed_frameworks() -> list[FrameworkCard]:
    return [
        FrameworkCard(
            framework_id="fw_roic_quality",
            name="ROIC Quality Framework",
            purpose="Convert ROIC into a financial-quality judgment with cash and cycle checks.",
            creator="AGI Institutional Synthesis",
            objective="Avoid treating peak or accrual-inflated ROIC as durable quality.",
            inputs=["ROIC series", "WACC", "cash conversion", "invested capital bridge"],
            outputs=["Financial quality stance", "mean-reversion risk flag"],
            questions=["Above WACC?", "Stable?", "Cash-supported?", "Reinvestment runway?"],
            decision_logic=[
                "If ROIC > WACC AND stable AND cash-supported → increase financial quality",
                "If peak-cycle or accrual-driven → do not extrapolate",
            ],
            checklist=["Multi-year ROIC", "Cycle position", "FCF/NOPAT", "Capex intensity"],
            examples=["Compounder with decade-long excess returns."],
            counter_examples=["Commodity peak ROIC."],
            failure_modes=["Ignoring invested capital inflation", "One-year hero numbers"],
            related_frameworks=["fw_capital_cycle", "fw_earnings_quality"],
            related_concepts=["roic", "cash_conversion", "wacc"],
            analysts_using=["financial", "valuation", "business"],
            source_authors=["Damodaran", "Fridson"],
        ),
        FrameworkCard(
            framework_id="fw_margin_of_safety",
            name="Margin of Safety Framework",
            purpose="Require a purchase cushion versus conservative intrinsic value.",
            creator="Graham / Klarman — institutional synthesis",
            objective="Protect capital under uncertainty.",
            inputs=["Conservative intrinsic value", "price", "uncertainty score"],
            outputs=["Required cushion", "stance constraint"],
            questions=["How wrong can we be?", "What is the bear case?"],
            decision_logic=[
                "Higher uncertainty → wider required MOS",
                "Demanding embedded expectations → refuse full-price commitment",
            ],
            checklist=["Bear case", "Balance sheet buffer", "Assumption audit"],
            failure_modes=["Calling any discount 'safety' without value work"],
            related_frameworks=["fw_reverse_dcf"],
            related_concepts=["intrinsic_value", "margin_of_safety"],
            analysts_using=["valuation", "risk"],
            source_authors=["Graham", "Klarman"],
        ),
        FrameworkCard(
            framework_id="fw_moat",
            name="Moat Assessment Framework",
            purpose="Identify sources, evidence, and trajectory of competitive advantage.",
            creator="AGI Institutional Synthesis",
            objective="Separate temporary edge from durable excess returns.",
            inputs=["Industry structure", "pricing power", "retention", "ROIC persistence"],
            outputs=["Moat sources", "widening/eroding verdict"],
            questions=["What blocks imitation?", "Is advantage strengthening?"],
            decision_logic=[
                "Brand + pricing + retention → business quality up",
                "No evidence of persistence → do not award moat label",
            ],
            checklist=["Source map", "Evidence trail", "Threat scan", "ROIC link"],
            failure_modes=["Narrative moats without financial proof"],
            related_frameworks=["fw_porter", "fw_pricing_power"],
            related_concepts=["moat", "pricing_power", "roic"],
            analysts_using=["business", "financial"],
            source_authors=["Fisher", "Porter", "Damodaran"],
        ),
        FrameworkCard(
            framework_id="fw_porter",
            name="Industry Structure Framework",
            purpose="Map rivalry, buyers, suppliers, substitutes, and entry to profit potential.",
            creator="Porter — institutional adaptation",
            objective="Explain industry ROIC ceilings.",
            inputs=["Five forces evidence", "capacity trends", "regulation"],
            outputs=["Industry attractiveness", "profit pool risks"],
            questions=["Who captures the surplus?", "Is structure improving or worsening?"],
            decision_logic=["Hostile structure → lower sustainable ROIC assumption"],
            related_concepts=["capital_cycle", "moat"],
            analysts_using=["business", "sector"],
            source_authors=["Porter"],
        ),
        FrameworkCard(
            framework_id="fw_capital_cycle",
            name="Capital Cycle Framework",
            purpose="Track how high returns attract capital and destroy future returns.",
            creator="AGI Institutional Synthesis",
            objective="Time cyclical and capital-intensive industries.",
            inputs=["Industry ROIC", "capacity additions", "pricing", "capex wave"],
            outputs=["Cycle position", "compression risk"],
            questions=["Is capital flooding in?", "Where are we vs mid-cycle?"],
            decision_logic=["Elevated ROIC + capacity boom → caution"],
            related_concepts=["capital_cycle", "roic", "cyclicality"],
            analysts_using=["business", "macro", "valuation"],
            source_authors=["Damodaran"],
        ),
        FrameworkCard(
            framework_id="fw_earnings_quality",
            name="Earnings Quality Framework",
            purpose="Test whether earnings are cash-backed and sustainable.",
            creator="Fridson / Damodaran — synthesis",
            objective="Block valuation on low-quality profits.",
            inputs=["NI", "CFO", "accruals", "one-offs", "WC bridge"],
            outputs=["Quality score", "normalized earnings"],
            questions=["Do earnings convert?", "What is clean run-rate?"],
            decision_logic=["Weak conversion → lower confidence in growth/ROIC"],
            related_concepts=["earnings_quality", "fcf"],
            analysts_using=["financial", "valuation"],
            source_authors=["Fridson", "Damodaran"],
        ),
        FrameworkCard(
            framework_id="fw_reverse_dcf",
            name="Reverse DCF Framework",
            purpose="Infer what growth/margins the market price embeds.",
            creator="Damodaran — institutional adaptation",
            objective="Debate expectations, not slogans.",
            inputs=["Price", "base financials", "WACC", "fade assumptions"],
            outputs=["Implied growth/margin", "expectation stress"],
            questions=["What must go right?", "Is that plausible vs history?"],
            decision_logic=["Implausible implications → cautious stance"],
            related_concepts=["expectations", "intrinsic_value"],
            analysts_using=["valuation"],
            source_authors=["Damodaran"],
        ),
        FrameworkCard(
            framework_id="fw_pricing_power",
            name="Pricing Power Framework",
            purpose="Evidence whether the firm sets or takes prices.",
            creator="AGI Institutional Synthesis",
            objective="Link brand claims to margin economics.",
            inputs=["Price/mix", "elasticity proxies", "peer margins", "retention"],
            outputs=["Pricing power verdict"],
            decision_logic=["Strong brand + retention + margin resilience → raise business quality"],
            related_concepts=["pricing_power", "brand", "gross_margin"],
            analysts_using=["business", "financial"],
            source_authors=["Fisher", "Damodaran"],
        ),
        FrameworkCard(
            framework_id="fw_capital_allocation",
            name="Capital Allocation Framework",
            purpose="Judge management deployment of cash across reinvestment, M&A, and returns of capital.",
            creator="AGI Institutional Synthesis",
            objective="Separate operating skill from allocation skill.",
            inputs=["Cash uses", "incremental ROIC", "M&A outcomes", "leverage"],
            outputs=["Allocator grade", "value creation/destruction flag"],
            decision_logic=["Incremental ROIC < WACC persistently → value destruction risk"],
            related_concepts=["capital_allocation", "roic"],
            analysts_using=["management", "financial"],
            source_authors=["Damodaran", "Klarman"],
        ),
        FrameworkCard(
            framework_id="fw_relative_valuation",
            name="Relative Valuation Framework",
            purpose="Contextualize multiples vs peers, history, and fundamentals — never as standalone truth.",
            creator="Damodaran — institutional adaptation",
            objective="Explain why a multiple differs, not declare cheap/expensive from the multiple alone.",
            inputs=["Peer set", "history", "growth", "ROIC", "risk"],
            outputs=["Multiple context", "trap flags"],
            decision_logic=["Low multiple + falling ROIC + no catalyst → value-trap risk"],
            related_concepts=["multiples", "value_trap", "roic"],
            analysts_using=["valuation"],
            source_authors=["Damodaran"],
        ),
    ]


def seed_formulas() -> list[FormulaCard]:
    return [
        FormulaCard(
            formula_id="formula_roic",
            name="ROIC",
            expression="ROIC = NOPAT / Invested Capital",
            purpose="Measure return on capital employed in operations.",
            variables={
                "NOPAT": "Net operating profit after tax",
                "Invested Capital": "Operating assets net of non-interest operating liabilities",
            },
            interpretation="Above WACC with persistence suggests value creation.",
            good_range="Sustainably above WACC with cash support",
            bad_range="Below WACC or peak-only spikes",
            sector_adjustments=[
                "Banks: use ROE / RWA returns carefully — not classic ROIC",
                "Asset-light platforms: invested capital may be understated",
            ],
            limitations=["Accounting definitions vary", "Goodwill inflation"],
            examples=["Multi-year ROIC 18% vs WACC 10% with strong FCF."],
            related_frameworks=["fw_roic_quality"],
            related_concepts=["roic", "wacc"],
        ),
        FormulaCard(
            formula_id="formula_wacc",
            name="WACC",
            expression="WACC = (E/V)*Re + (D/V)*Rd*(1-t)",
            purpose="Estimate blended hurdle rate for firm cash flows.",
            variables={
                "E": "Equity value",
                "D": "Debt value",
                "V": "E+D",
                "Re": "Cost of equity",
                "Rd": "Cost of debt",
                "t": "Tax rate",
            },
            interpretation="Hurdle for ROIC and DCF discounting.",
            limitations=["Point estimates hide regime risk"],
            related_frameworks=["fw_roic_quality"],
            related_concepts=["cost_of_capital", "roic"],
        ),
        FormulaCard(
            formula_id="formula_dcf",
            name="DCF Intrinsic Value",
            expression="Value = Σ FCFt / (1+r)^t + Terminal / (1+r)^n",
            purpose="Estimate intrinsic value from expected free cash flows.",
            variables={"FCF": "Free cash flow", "r": "Discount rate", "Terminal": "Terminal value"},
            interpretation="Value range under scenarios — not a single false-precision number.",
            limitations=["Terminal value dominance", "forecast error"],
            related_frameworks=["fw_reverse_dcf", "fw_margin_of_safety"],
            related_concepts=["intrinsic_value", "fcf"],
        ),
        FormulaCard(
            formula_id="formula_cash_conversion",
            name="Cash Conversion",
            expression="Cash Conversion ≈ CFO / Net Income (or FCF / NOPAT)",
            purpose="Test whether earnings are cash-supported.",
            variables={"CFO": "Cash from operations", "NI": "Net income"},
            interpretation="Persistently weak conversion questions earnings quality and ROIC.",
            good_range="Near or above 1.0 over a cycle (sector-dependent)",
            bad_range="Materially below 1.0 without structural WC reason",
            related_frameworks=["fw_earnings_quality"],
            related_concepts=["earnings_quality", "fcf"],
        ),
        FormulaCard(
            formula_id="formula_economic_profit",
            name="Economic Profit",
            expression="Economic Profit = (ROIC - WACC) × Invested Capital",
            purpose="Quantify value created above hurdle.",
            variables={"ROIC": "Return on invested capital", "WACC": "Cost of capital"},
            interpretation="Positive spread creates value; negative destroys it.",
            related_frameworks=["fw_roic_quality"],
            related_concepts=["roic", "cost_of_capital"],
        ),
    ]


def seed_cases() -> list[CaseStudy]:
    return [
        CaseStudy(
            case_id="case_apple_premium",
            company="Apple",
            industry="Consumer Internet / Hardware Ecosystem",
            situation="Market awards premium valuation; question is whether ecosystem economics deserve it.",
            framework_applied=["fw_moat", "fw_pricing_power", "fw_roic_quality", "fw_reverse_dcf"],
            decision="Premium justified only while ecosystem lock-in, services mix, and cash returns sustain high ROIC.",
            outcome="Institutional lesson: premium is conditional on ecosystem strength, not brand lore.",
            why_it_worked="Switching costs, installed base, pricing power, and capital returns reinforced compounding.",
            why_it_failed="Would fail if ecosystem weakens, services stall, or hardware becomes commoditized.",
            lessons=[
                "Ask why premium is deserved, not whether PE is high.",
                "Model ecosystem weakening as a first-class bear case.",
                "Transferable lesson: platform lock-in + pricing power can sustain high ROIC.",
            ],
            related_companies=["MSFT", "GOOGL"],
            related_concepts=["network_effects", "pricing_power", "roic", "intrinsic_value"],
            case_type="mixed",
        ),
        CaseStudy(
            case_id="case_hdfc_moat_trajectory",
            company="HDFC Bank",
            industry="Banking",
            situation="Franchise strength remains high while incremental moat trajectory may no longer be strengthening.",
            framework_applied=["fw_moat", "fw_roic_quality", "fw_capital_allocation"],
            decision="Treat as durable franchise with trajectory vigilance — moat durable ≠ moat strengthening.",
            outcome="Lesson: separate level of advantage from direction of change.",
            why_it_worked="Low-cost deposit franchise and underwriting culture supported durable returns.",
            why_it_failed="Complacency on trajectory can overpay for yesterday's improvement rate.",
            lessons=[
                "Track moat trajectory, not only moat presence.",
                "Financial franchise patterns need credit-cycle stress.",
            ],
            related_companies=["ICICIBANK", "KOTAKBANK"],
            related_concepts=["moat", "financial_franchise", "credit_cycle"],
            case_type="mixed",
        ),
        CaseStudy(
            case_id="case_value_trap_cyclical",
            company="Generic Cyclical Producer",
            industry="Industrials / Commodities",
            situation="Low multiple at peak earnings looks 'cheap'.",
            framework_applied=["fw_capital_cycle", "fw_relative_valuation", "fw_roic_quality"],
            decision="Reject apparent cheapness; normalize earnings and map capacity cycle.",
            outcome="Classic value trap when peak EPS meets mid-cycle multiple thinking.",
            why_it_failed="Mean reversion of margins and ROIC crushed equity value.",
            lessons=[
                "Cheap multiples on peak earnings are often expensive.",
                "Capital cycle position dominates narrative bargains.",
            ],
            related_concepts=["value_trap", "capital_cycle", "mean_reversion"],
            case_type="failure",
        ),
        CaseStudy(
            case_id="case_earnings_quality_break",
            company="Accrual Growth Story",
            industry="IT Services / General",
            situation="Reported earnings accelerate while cash conversion deteriorates.",
            framework_applied=["fw_earnings_quality", "fw_reverse_dcf"],
            decision="Lower confidence; refuse to capitalize low-quality growth.",
            outcome="Multiple compression when cash reality asserts itself.",
            why_it_failed="Valuation on accruals, not cash.",
            lessons=["Always bridge earnings to cash before paying for growth."],
            related_concepts=["earnings_quality", "fcf", "expectations"],
            case_type="failure",
        ),
    ]


def seed_failures() -> list[FailurePattern]:
    return [
        FailurePattern(
            failure_id="fail_peak_roic_extrapolation",
            name="Peak ROIC Extrapolation",
            domains=["financial", "valuation"],
            lessons=["Do not capitalize peak-cycle returns", "Normalize across the cycle"],
            warning_signals=["Industry capacity boom", "Record margins", "ROIC far above history"],
            similar_companies=["Cyclical industrials at peak"],
        ),
        FailurePattern(
            failure_id="fail_narrative_moat",
            name="Narrative Moat Without Evidence",
            domains=["business", "valuation"],
            lessons=["Require ROIC/pricing/retention evidence", "Stories are not moats"],
            warning_signals=["Brand claims without margin proof", "Rising competition ignored"],
        ),
        FailurePattern(
            failure_id="fail_value_trap",
            name="Value Trap on Structural Decline",
            domains=["valuation", "risk", "business"],
            lessons=["Low multiple can be fair for melting ice cubes"],
            warning_signals=["Falling ROIC", "Share loss", "No capital allocation fix"],
        ),
        FailurePattern(
            failure_id="fail_empire_building",
            name="Empire-Building Allocation",
            domains=["management", "financial"],
            lessons=["Incremental ROIC on M&A matters more than deal theater"],
            warning_signals=["Large related acquisitions at peak multiples", "Rising goodwill without returns"],
        ),
        FailurePattern(
            failure_id="fail_leverage_cycle",
            name="Leverage into the Wrong Cycle",
            domains=["risk", "macro", "financial"],
            lessons=["Balance sheet optionality is a moat in downturns"],
            warning_signals=["Rising leverage at cycle peak", "Covenant pressure", "Refi walls"],
        ),
    ]


def seed_author_perspectives() -> list[AuthorPerspective]:
    return [
        AuthorPerspective(
            topic_id="author_roic_value",
            topic="High ROIC interpretation",
            perspectives=[
                {"author": "Damodaran", "view": "ROIC vs cost of capital drives value creation; growth only helps if ROIC > hurdle."},
                {"author": "Graham", "view": "Excess returns matter only with a purchase margin of safety versus intrinsic value."},
                {"author": "Klarman", "view": "Risk is permanent capital loss; high ROIC does not excuse paying for perfection."},
                {"author": "Fridson", "view": "Validate that returns are cash-supported and free of accounting distortion."},
                {"author": "Fisher", "view": "Business quality and growth runway make high returns durable — look beyond the ratio."},
            ],
            agreements=[
                "ROIC above cost of capital is necessary for economic value creation",
                "Sustainability and cash reality matter more than a single print",
            ],
            disagreements=[
                "Graham/Klarman emphasize price cushion; Fisher emphasizes franchise quality; Damodaran bridges both via DCF",
            ],
            unified_institutional_view=(
                "Interpret high ROIC as a candidate for financial quality only if it clears cost of capital, "
                "is stable across the cycle, is cash-supported, and is paired with reinvestment logic and a valuation "
                "stance that still demands margin of safety when expectations are demanding."
            ),
        ),
        AuthorPerspective(
            topic_id="author_intrinsic_vs_mos",
            topic="Intrinsic value and margin of safety",
            perspectives=[
                {"author": "Damodaran", "view": "Intrinsic value from expected cash flows and risk."},
                {"author": "Graham", "view": "Buy with a margin of safety below conservative value."},
                {"author": "Klarman", "view": "Risk control and asymmetry dominate point estimates."},
                {"author": "Fisher", "view": "Pay up only for exceptional business quality with long runways."},
            ],
            agreements=["Price and value are distinct", "Uncertainty requires humility"],
            disagreements=["Willingness to pay near full value for rare quality (Fisher) vs deep discount discipline (Graham/Klarman)"],
            unified_institutional_view=(
                "Estimate intrinsic value rigorously, then apply a margin of safety scaled to uncertainty; "
                "exceptional quality can narrow but never eliminate the need for downside thinking."
            ),
        ),
    ]


def seed_sectors() -> list[SectorKnowledge]:
    return [
        SectorKnowledge(
            sector_id="sector_banking",
            name="Banking",
            business=["Deposit franchise", "Underwriting culture", "Distribution"],
            financial=["NIM", "NPA/credit cost", "ROE/RWA", "Liquidity coverage"],
            valuation=["P/B vs ROE", "Credit-cycle adjusted earnings"],
            risk=["Credit cycle", "ALM", "Conduct/regulatory"],
            macro=["Rates", "Liquidity", "Growth/credit impulse"],
            frameworks=["fw_roic_quality", "fw_capital_cycle", "fw_earnings_quality"],
            kpis=["NIM", "GNPA", "PCR", "CASA", "ROE"],
        ),
        SectorKnowledge(
            sector_id="sector_insurance",
            name="Insurance",
            business=["Underwriting discipline", "Distribution", "Float economics"],
            financial=["Combined ratio", "VNB/EV", "Investment income quality"],
            valuation=["P/EV", "P/B", "Embedded value sensitivity"],
            risk=["Catastrophe", "Mispricing", "ALM mismatch"],
            macro=["Rates", "Inflation on claims"],
            frameworks=["fw_earnings_quality", "fw_capital_allocation"],
            kpis=["Combined ratio", "VNB margin", "Solvency"],
        ),
        SectorKnowledge(
            sector_id="sector_it_services",
            name="IT Services",
            business=["Client concentration", "Talent engine", "Service mix"],
            financial=["Utilization", "Wage inflation", "FCF conversion", "Deal TCV"],
            valuation=["PEG with quality", "FCF yield", "growth durability"],
            risk=["Vendor consolidation", "Automation", "Currency"],
            macro=["Global IT spend", "USD"],
            frameworks=["fw_earnings_quality", "fw_moat"],
            kpis=["EBIT margin", "Attrition", "Book-to-bill"],
        ),
        SectorKnowledge(
            sector_id="sector_fmcg",
            name="FMCG",
            business=["Brand", "Distribution", "Pricing power"],
            financial=["Gross margin", "Working capital", "ROIC"],
            valuation=["Premium multiple only with ROIC + growth proof"],
            risk=["Input costs", "Downtrading", "Channel shift"],
            macro=["Rural demand", "Inflation"],
            frameworks=["fw_pricing_power", "fw_moat", "fw_roic_quality"],
            kpis=["Volume growth", "Gross margin", "ROIC"],
        ),
        SectorKnowledge(
            sector_id="sector_industrials",
            name="Industrials",
            business=["Cost curve", "Capacity", "Order book"],
            financial=["Operating leverage", "Cycle-normalized ROIC"],
            valuation=["Mid-cycle earnings", "Avoid peak multiples"],
            risk=["Capex overbuild", "Commodity input"],
            macro=["Capex cycle", "Infrastructure spend"],
            frameworks=["fw_capital_cycle", "fw_relative_valuation"],
            kpis=["Capacity utilization", "Order inflow", "ROCE"],
        ),
        SectorKnowledge(
            sector_id="sector_utilities",
            name="Utilities",
            business=["Regulation", "Asset base", "PPA quality"],
            financial=["Regulated returns", "Leverage", "Cash conversion"],
            valuation=["P/B", "DCF on regulated cash flows"],
            risk=["Regulatory shift", "Fuel", "Interest rates"],
            macro=["Rates", "Power demand", "Policy"],
            frameworks=["fw_capital_allocation", "fw_margin_of_safety"],
            kpis=["ROE regulated", "Interest coverage", "PLF"],
        ),
        SectorKnowledge(
            sector_id="sector_consumer_internet",
            name="Consumer Internet",
            business=["Network effects", "Take rate", "Engagement"],
            financial=["Unit economics", "Contribution margin", "Cash burn/FCF path"],
            valuation=["Reverse DCF on path to FCF", "Cohort evidence"],
            risk=["Regulation", "Multi-homing", "Competition"],
            macro=["Discretionary spend", "Ad budgets"],
            frameworks=["fw_moat", "fw_reverse_dcf", "fw_pricing_power"],
            kpis=["MAU/DAU", "Take rate", "LTV/CAC", "FCF"],
        ),
        SectorKnowledge(
            sector_id="sector_energy",
            name="Energy",
            business=["Cost curve", "Reserves", "Integration"],
            financial=["Cyclic CFO", "Capex intensity", "Balance sheet"],
            valuation=["Normalized commodity deck", "NAV"],
            risk=["Price collapse", "Policy/transition"],
            macro=["Oil/gas prices", "FX", "Geopolitics"],
            frameworks=["fw_capital_cycle", "fw_relative_valuation"],
            kpis=["Lifting cost", "Net debt/EBITDA", "FCF yield"],
        ),
        SectorKnowledge(
            sector_id="sector_healthcare",
            name="Healthcare",
            business=["Pipeline/IP", "Regulation", "Channel"],
            financial=["R&D productivity", "Gross margin", "Cash conversion"],
            valuation=["Pipeline-adjusted DCF", "peer quality"],
            risk=["Patent cliff", "Regulatory rejection", "Pricing reform"],
            macro=["Policy", "FX for exporters"],
            frameworks=["fw_moat", "fw_earnings_quality"],
            kpis=["R&D / sales", "Gross margin", "Pipeline milestones"],
        ),
        SectorKnowledge(
            sector_id="sector_real_estate",
            name="Real Estate",
            business=["Location", "Development pipeline", "Leasing"],
            financial=["Pre-sales", "Leverage", "Cash flow timing"],
            valuation=["NAV", "replacement cost"],
            risk=["Funding freeze", "Demand freeze", "Regulatory"],
            macro=["Rates", "Income growth", "Credit"],
            frameworks=["fw_capital_cycle", "fw_margin_of_safety"],
            kpis=["Pre-sales", "Net debt", "Collections"],
        ),
    ]


def seed_institutional_objects() -> list[InstitutionalKnowledgeObject]:
    return [
        InstitutionalKnowledgeObject(
            object_id="iko_roic",
            topic="ROIC",
            unified_definition=(
                "Institutional ROIC knowledge: return on invested capital judged versus cost of capital, "
                "stability, cash support, and reinvestment runway — synthesized across valuation, accounting, "
                "and business-quality traditions."
            ),
            synthesis=(
                "Damodaran frames ROIC vs WACC as the engine of value; Graham and Klarman require that even "
                "excellent returns be purchased with a margin of safety; Fridson insists returns be cash-real; "
                "Fisher asks whether business quality makes high returns durable. AGI stores one object: high ROIC "
                "raises financial quality only when above hurdle, stable, cash-supported, and valued with humility."
            ),
            source_authors=["Damodaran", "Graham", "Klarman", "Fridson", "Fisher"],
            source_books=[
                "Investment Valuation",
                "Applied Corporate Finance",
                "Financial Statement Analysis",
                "Narrative and Numbers",
                "Security Analysis",
                "Measuring Earnings",
                "Understanding Financial Statements",
            ],
            frameworks=["fw_roic_quality", "fw_earnings_quality", "fw_capital_cycle"],
            formulas=["formula_roic", "formula_wacc", "formula_economic_profit"],
            decision_rules=["dr_roic_quality_up", "dr_capital_cycle_caution"],
            reasoning_chains=["rc_brand_to_value", "rc_earnings_quality"],
            cases=["case_apple_premium", "case_value_trap_cyclical"],
            mental_models=["mm_compounding", "mm_mean_reversion", "mm_margin_of_safety"],
            checklists=["cl_financial", "cl_valuation"],
            lessons=[
                "Never retrieve five book paragraphs — retrieve this unified object",
                "High ROIC ≠ automatic buy",
                "Cash and cycle decide whether ROIC is quality or mirage",
            ],
            counter_examples=["Peak commodity ROIC", "Accrual-inflated ROIC"],
            analysts=["financial", "valuation", "business"],
            confidence=0.94,
        ),
        InstitutionalKnowledgeObject(
            object_id="iko_margin_of_safety",
            topic="Margin of Safety",
            unified_definition="Cushion between conservative intrinsic value and price, scaled to uncertainty.",
            synthesis=(
                "Graham originated the discipline; Klarman operationalizes risk as permanent loss; Damodaran "
                "supplies the intrinsic-value machinery that makes the cushion measurable. Unified view: estimate "
                "value, stress it, then require a cushion wide enough for being wrong."
            ),
            source_authors=["Graham", "Klarman", "Damodaran"],
            source_books=["Security Analysis", "Margin of Safety", "Investment Valuation"],
            frameworks=["fw_margin_of_safety", "fw_reverse_dcf"],
            formulas=["formula_dcf"],
            decision_rules=["dr_mos_required"],
            mental_models=["mm_margin_of_safety", "mm_optionality"],
            checklists=["cl_valuation", "cl_risk"],
            lessons=["Uncertainty widens required MOS", "Quality narrows but does not erase downside work"],
            analysts=["valuation", "risk", "cio"],
        ),
        InstitutionalKnowledgeObject(
            object_id="iko_moat",
            topic="Economic Moat",
            unified_definition="Durable sources of excess returns evidenced in pricing, retention, and ROIC persistence.",
            synthesis=(
                "Fisher emphasizes business franchise quality; Porter explains industry structure; Damodaran links "
                "advantage to growth and value. AGI requires evidence trail and trajectory, not labels."
            ),
            source_authors=["Fisher", "Porter", "Damodaran"],
            frameworks=["fw_moat", "fw_porter", "fw_pricing_power"],
            decision_rules=["dr_business_quality_up"],
            reasoning_chains=["rc_brand_to_value"],
            cases=["case_apple_premium", "case_hdfc_moat_trajectory"],
            mental_models=["mm_network_effects", "mm_switching_costs", "mm_pricing_power"],
            checklists=["cl_business"],
            lessons=["Moat level ≠ moat trajectory", "No financial proof, no moat award"],
            analysts=["business", "financial", "valuation"],
        ),
    ]


def seed_chapter_knowledge() -> list[ChapterKnowledge]:
    """Representative structured chapter objects for ingested Damodaran / Mankiw corpus.

    Books are already ingested at file level; V3 stores structured knowledge per chapter theme,
    never raw PDF paragraphs.
    """
    return [
        ChapterKnowledge(
            chapter_id="ch_acf_capital_structure",
            book_id="Damodaran_Applied_Corporate_Finance",
            title="Capital Structure and Hurdle Rates",
            summary="How firms choose debt/equity and set hurdle rates for investment decisions.",
            purpose="Connect financing mix to cost of capital and project selection.",
            core_concepts=["cost_of_capital", "capital_allocation", "roic"],
            frameworks=["fw_roic_quality", "fw_capital_allocation"],
            formulas=["formula_wacc", "formula_roic"],
            decision_rules=["dr_roic_quality_up"],
            questions=["Does the project clear WACC?", "Is leverage matched to cash-flow risk?"],
            examples=["Accept projects with ROIC > WACC after risk adjustment."],
            counter_examples=["Growing via projects below hurdle to chase scale."],
            lessons=["Capital structure affects WACC; WACC gates value creation."],
            common_mistakes=["Using group WACC for dissimilar project risk"],
            when_to_apply=["Project appraisal", "Capital structure debates"],
            when_not_to_apply=["Banks where regulatory capital frameworks dominate classic WACC"],
            related_concepts=["wacc", "roic", "capital_allocation"],
            related_books=["Investment Valuation", "Understanding Financial Statements"],
        ),
        ChapterKnowledge(
            chapter_id="ch_me_earnings_quality",
            book_id="Damodaran_Measuring_Earnings",
            title="Measuring and Cleaning Earnings",
            summary="Normalize reported earnings for operating reality and sustainability.",
            purpose="Feed valuation and ROIC with clean earnings inputs.",
            core_concepts=["earnings_quality", "fcf"],
            frameworks=["fw_earnings_quality"],
            formulas=["formula_cash_conversion"],
            decision_rules=[],
            questions=["What is operating vs non-operating?", "What is sustainable?"],
            examples=["Strip one-offs before capitalizing growth."],
            counter_examples=["Valuing peak, unadjusted earnings."],
            case_studies=["case_earnings_quality_break"],
            lessons=["Dirty earnings poison DCF and multiples."],
            common_mistakes=["Ignoring working-capital drains"],
            when_to_apply=["Any earnings-based valuation"],
            when_not_to_apply=["Blind use without cash bridge"],
            related_concepts=["earnings_quality", "intrinsic_value"],
            related_books=["Financial Statement Analysis", "Understanding Financial Statements"],
        ),
        ChapterKnowledge(
            chapter_id="ch_ufs_statements",
            book_id="Damodaran_Understanding_Financial_Statements",
            title="Reading the Financial Statements",
            summary="Map income statement, balance sheet, and cash flow into investment questions.",
            purpose="Translate statements into ROIC, cash, and risk evidence.",
            core_concepts=["roic", "earnings_quality", "fcf"],
            frameworks=["fw_roic_quality", "fw_earnings_quality"],
            formulas=["formula_roic", "formula_cash_conversion"],
            lessons=["Statements are evidence, not the answer."],
            common_mistakes=["Analyzing NI without CFO"],
            when_to_apply=["Financial and valuation analysis kickoff"],
            related_concepts=["roic", "fcf"],
            related_books=["Measuring Earnings", "Applied Corporate Finance"],
        ),
        ChapterKnowledge(
            chapter_id="ch_ap_accounting_prep",
            book_id="Damodaran_Accounting_Prep",
            title="Accounting Foundations for Valuation",
            summary="Accounting building blocks required before valuation judgments.",
            purpose="Prevent garbage-in valuation from misunderstood accounts.",
            core_concepts=["earnings_quality", "invested_capital"],
            frameworks=["fw_earnings_quality"],
            lessons=["Accounting literacy is a precondition for ROIC and DCF."],
            related_books=["Understanding Financial Statements", "Measuring Earnings"],
        ),
        ChapterKnowledge(
            chapter_id="ch_mankiw_markets",
            book_id="Mankiw_Principles_of_Economics",
            title="Markets, Incentives, and Trade-offs",
            summary="Core economic reasoning: incentives, opportunity cost, supply-demand, efficiency.",
            purpose="Provide macro/micro primitives for industry and policy transmission.",
            core_concepts=["opportunity_cost", "incentives", "elasticity"],
            frameworks=["fw_porter", "fw_capital_cycle"],
            lessons=["Prices ration; incentives shape behavior; trade-offs are everywhere."],
            when_to_apply=["Macro and industry structure context"],
            related_concepts=["capital_cycle", "pricing_power"],
            related_books=["Applied Corporate Finance"],
        ),
    ]
