"""Core institutional knowledge seeds — mental models, trees, checklists, patterns, rules."""

from __future__ import annotations

from academy.books.v3.schema import (
    Checklist,
    DecisionRule,
    DecisionTree,
    MentalModelCard,
    PatternCard,
    ReasoningChain,
)


def seed_mental_models() -> list[MentalModelCard]:
    return [
        MentalModelCard(
            model_id="mm_margin_of_safety",
            name="Margin of Safety",
            definition="Buy only when intrinsic value exceeds price by a cushion large enough to absorb estimation error and adversity.",
            purpose="Protect capital when forecasts are imperfect.",
            questions=["How wide is the cushion?", "What could make intrinsic value wrong?"],
            examples=["Buying a franchise at a deep discount to conservative DCF."],
            counter_examples=["Paying full price for a perfect narrative with zero cushion."],
            related_concepts=["intrinsic_value", "uncertainty", "downside"],
        ),
        MentalModelCard(
            model_id="mm_optionality",
            name="Optionality",
            definition="Asymmetric upside from flexible strategic choices with limited downside commitment.",
            purpose="Value latent growth paths without forcing them into base-case forecasts.",
            questions=["What options exist?", "What is the cost to keep them alive?"],
            examples=["Platform adjacency launches; excess cash enabling opportunistic M&A."],
            counter_examples=["Treating speculative options as base-case cash flows."],
            related_concepts=["growth", "capital_allocation", "platform"],
        ),
        MentalModelCard(
            model_id="mm_compounding",
            name="Compounding",
            definition="Reinvestment at returns above cost of capital grows intrinsic value over time.",
            purpose="Identify businesses where time is an ally.",
            questions=["Can capital be reinvested at high ROIC?", "Is the opportunity set durable?"],
            examples=["High-ROIC compounders with runway."],
            counter_examples=["High ROIC with no reinvestment opportunities (cash trap)."],
            related_concepts=["roic", "reinvestment", "intrinsic_value"],
        ),
        MentalModelCard(
            model_id="mm_mean_reversion",
            name="Mean Reversion",
            definition="Extreme returns, margins, or multiples tend to normalize unless structural barriers prevent it.",
            purpose="Avoid extrapolating peaks and troughs forever.",
            questions=["What forces reversion?", "What could prevent it?"],
            examples=["Peak commodity margins reverting; distressed multiples recovering."],
            counter_examples=["Structural monopoly with durable pricing power."],
            related_concepts=["cyclicality", "margins", "valuation"],
        ),
        MentalModelCard(
            model_id="mm_creative_destruction",
            name="Creative Destruction",
            definition="Innovation displaces incumbents; moats erode when technology and preferences shift.",
            purpose="Stress-test durability of competitive advantage.",
            questions=["Who is disrupting this model?", "Is the firm adapting or defending yesterday?"],
            examples=["Digital platforms displacing physical distribution."],
            counter_examples=["Regulated natural monopolies with slow tech change."],
            related_concepts=["moat", "disruption", "industry_structure"],
        ),
        MentalModelCard(
            model_id="mm_network_effects",
            name="Network Effects",
            definition="Each incremental user increases value for existing users, raising switching costs and defensibility.",
            purpose="Identify self-reinforcing demand-side advantages.",
            questions=["Does value scale with users?", "Are there multi-homing risks?"],
            examples=["Payment networks; marketplaces with liquidity flywheels."],
            counter_examples=["Networks with weak engagement or easy multi-homing."],
            related_concepts=["platform", "switching_costs", "moat"],
        ),
        MentalModelCard(
            model_id="mm_economies_of_scale",
            name="Economies of Scale",
            definition="Unit costs fall as volume rises due to fixed-cost leverage and learning.",
            purpose="Assess cost advantage durability.",
            examples=["National logistics networks; manufacturing scale."],
            counter_examples=["Scale without cost advantage due to complexity diseconomies."],
            related_concepts=["cost_advantage", "operating_leverage"],
        ),
        MentalModelCard(
            model_id="mm_capital_cycle",
            name="Capital Cycle",
            definition="High returns attract capital; excess capacity destroys returns; scarcity restores them.",
            purpose="Time industry entry/exit around supply response.",
            examples=["Shipping, commodities, real estate development cycles."],
            counter_examples=["Industries with structural barriers to new supply."],
            related_concepts=["industry_structure", "roic", "cyclicality"],
        ),
        MentalModelCard(
            model_id="mm_pricing_power",
            name="Pricing Power",
            definition="Ability to raise prices without losing volume or mix quality.",
            purpose="Link brand/positioning to cash economics.",
            examples=["Premium consumer brands with low elasticity."],
            counter_examples=["Commodity producers as price takers."],
            related_concepts=["brand", "gross_margin", "moat"],
        ),
        MentalModelCard(
            model_id="mm_switching_costs",
            name="Switching Costs",
            definition="Friction that makes customers reluctant to change suppliers.",
            purpose="Assess retention and pricing durability.",
            examples=["Enterprise software embedded in workflows."],
            counter_examples=["Commoditized services with one-click switching."],
            related_concepts=["retention", "moat", "customer_economics"],
        ),
        MentalModelCard(
            model_id="mm_platform_economics",
            name="Platform Economics",
            definition="Value creation via matching sides of a market and taking a toll on interactions.",
            purpose="Analyze take-rate durability and competitive dynamics.",
            examples=["Marketplaces with strong liquidity."],
            counter_examples=["Thin platforms with weak chicken-and-egg dynamics."],
            related_concepts=["network_effects", "take_rate", "ecosystem"],
        ),
        MentalModelCard(
            model_id="mm_reflexivity",
            name="Reflexivity",
            definition="Perceptions affect fundamentals which then reinforce perceptions (and vice versa).",
            purpose="Avoid one-way causal thinking in markets and credit.",
            examples=["Credit booms; narrative-driven valuation spirals."],
            counter_examples=["Stable cash businesses with low narrative dependence."],
            related_concepts=["expectations", "credit_cycle", "market_psychology"],
        ),
    ]


def seed_decision_trees() -> list[DecisionTree]:
    return [
        DecisionTree(
            tree_id="dt_roic_quality",
            name="ROIC Quality Tree",
            purpose="Convert ROIC into a financial-quality decision.",
            root="ROIC",
            nodes=[
                {"id": "above_wacc", "question": "Above cost of capital?", "yes": "stable", "no": "value_destroying"},
                {"id": "stable", "question": "Stable over cycle?", "yes": "improving", "no": "cyclical_or_fragile"},
                {"id": "improving", "question": "Improving or durable high?", "yes": "cash_supported", "no": "peak_risk"},
                {"id": "cash_supported", "question": "Cash conversion supports returns?", "yes": "high_quality", "no": "earnings_quality_risk"},
            ],
            leaves={
                "high_quality": "Increase Financial Quality",
                "value_destroying": "Flag capital inefficiency",
                "cyclical_or_fragile": "Treat as cyclical / stress-test trough",
                "peak_risk": "Mean-reversion risk — do not extrapolate peak",
                "earnings_quality_risk": "Returns not cash-supported — lower confidence",
            },
            related_concepts=["roic", "cash_conversion", "cost_of_capital"],
            analysts_using=["financial", "valuation", "business"],
        ),
        DecisionTree(
            tree_id="dt_business_quality",
            name="Business Quality Tree",
            purpose="Link brand, pricing, and retention into business quality.",
            root="Brand / Position",
            nodes=[
                {"id": "pricing", "question": "Pricing power high?", "yes": "retention", "no": "commodity_pressure"},
                {"id": "retention", "question": "Customer retention high?", "yes": "reinvestment", "no": "churn_risk"},
                {"id": "reinvestment", "question": "Reinvestment runway exists?", "yes": "compounder", "no": "cash_cow"},
            ],
            leaves={
                "compounder": "Increase Business Quality — compounder pattern",
                "cash_cow": "High quality harvest — limited growth",
                "commodity_pressure": "Weak pricing — competitive pressure",
                "churn_risk": "Position fragile despite brand claims",
            },
            related_concepts=["brand", "pricing_power", "retention", "moat"],
            analysts_using=["business", "financial"],
        ),
        DecisionTree(
            tree_id="dt_valuation_stance",
            name="Valuation Stance Tree",
            purpose="Move from expectations to stance without cheap/expensive slogans.",
            root="Market Price",
            nodes=[
                {"id": "embedded", "question": "Embedded expectations demanding?", "yes": "mos", "no": "optionality"},
                {"id": "mos", "question": "Margin of safety adequate vs intrinsic?", "yes": "constructive", "no": "cautious"},
                {"id": "optionality", "question": "Asymmetry / optionality attractive?", "yes": "opportunistic", "no": "neutral"},
            ],
            leaves={
                "constructive": "Constructive if business/financial quality confirmed",
                "cautious": "Cautious — price embeds perfection",
                "opportunistic": "Opportunistic with defined downside",
                "neutral": "Neutral — wait for better asymmetry",
            },
            related_concepts=["intrinsic_value", "margin_of_safety", "expectations"],
            analysts_using=["valuation", "cio"],
        ),
    ]


def seed_reasoning_chains() -> list[ReasoningChain]:
    return [
        ReasoningChain(
            chain_id="rc_brand_to_value",
            name="Brand → Premium Valuation",
            purpose="Connect brand economics to valuation privilege.",
            steps=[
                "Brand strength",
                "Pricing power",
                "Gross margin durability",
                "High ROIC",
                "Intrinsic value growth",
                "Premium valuation sustainability (conditional)",
            ],
            related_concepts=["brand", "pricing_power", "roic", "intrinsic_value"],
            analysts_using=["business", "financial", "valuation"],
        ),
        ReasoningChain(
            chain_id="rc_capital_cycle",
            name="Capital Cycle Chain",
            purpose="Map supply response to returns and valuation.",
            steps=[
                "High industry ROIC",
                "Capital attraction",
                "Capacity expansion",
                "Price/margin pressure",
                "ROIC compression",
                "Valuation de-rating risk",
            ],
            related_concepts=["capital_cycle", "roic", "cyclicality"],
            analysts_using=["business", "macro", "valuation"],
        ),
        ReasoningChain(
            chain_id="rc_earnings_quality",
            name="Earnings → Cash → Value",
            purpose="Prevent accrual-driven valuation errors.",
            steps=[
                "Reported earnings growth",
                "Accrual / working-capital check",
                "Cash conversion",
                "Sustainable free cash flow",
                "Intrinsic value support",
            ],
            related_concepts=["earnings_quality", "cash_conversion", "fcf"],
            analysts_using=["financial", "valuation"],
        ),
    ]


def seed_checklists() -> list[Checklist]:
    return [
        Checklist(
            checklist_id="cl_business",
            name="Business Checklist",
            domain="business",
            items=[
                "Industry structure and rivalry clarity",
                "Customer problem and willingness to pay",
                "Moat sources identified and evidenced",
                "Management capital allocation track record",
                "Capital cycle position",
                "Disruption / creative destruction exposure",
            ],
            analysts_using=["business"],
        ),
        Checklist(
            checklist_id="cl_financial",
            name="Financial Checklist",
            domain="financial",
            items=[
                "Revenue quality and concentration",
                "Margin structure and durability",
                "ROIC vs cost of capital",
                "Cash conversion and FCF quality",
                "Balance sheet resilience",
                "Capital allocation discipline",
            ],
            analysts_using=["financial"],
        ),
        Checklist(
            checklist_id="cl_valuation",
            name="Valuation Checklist",
            domain="valuation",
            items=[
                "What price embeds (expectations)",
                "Relative valuation vs peers and history",
                "Intrinsic value under conservative assumptions",
                "Reverse DCF implied growth/margin",
                "Margin of safety vs uncertainty",
                "Scenario asymmetry",
            ],
            analysts_using=["valuation"],
        ),
        Checklist(
            checklist_id="cl_management",
            name="Management Checklist",
            domain="management",
            items=[
                "Capital allocation consistency",
                "Incentive alignment",
                "Governance quality",
                "Communication honesty vs spin",
                "Reinvestment vs distribution judgment",
            ],
            analysts_using=["management", "business"],
        ),
        Checklist(
            checklist_id="cl_risk",
            name="Risk Checklist",
            domain="risk",
            items=[
                "Operational concentration risks",
                "Balance sheet / liquidity stress",
                "Regulatory and legal exposure",
                "Tail scenarios and failure modes",
                "Second-order contagion",
            ],
            analysts_using=["risk"],
        ),
        Checklist(
            checklist_id="cl_macro",
            name="Macro Checklist",
            domain="macro",
            items=[
                "Rate and inflation transmission",
                "Credit conditions",
                "FX / commodity exposure",
                "Policy regime shifts",
                "Demand cycle position",
            ],
            analysts_using=["macro"],
        ),
        Checklist(
            checklist_id="cl_portfolio",
            name="Portfolio Checklist",
            domain="portfolio",
            items=[
                "Position sizing vs uncertainty",
                "Correlation and factor exposure",
                "Liquidity under stress",
                "Thesis kill criteria",
                "Opportunity cost vs alternatives",
            ],
            analysts_using=["cio", "ownership"],
        ),
    ]


def seed_patterns() -> list[PatternCard]:
    return [
        PatternCard(
            pattern_id="pat_compounder",
            name="Compounder",
            definition="High ROIC business with durable reinvestment runway and cash-supported growth.",
            recognition_signals=["ROIC > WACC", "stable/improving returns", "reinvestment opportunity", "strong FCF"],
            failure_modes=["Runway exhaustion", "capital cycle overcrowding", "moat erosion"],
            related_concepts=["roic", "compounding", "reinvestment"],
            related_frameworks=["fw_roic_quality", "fw_moat"],
            analysts_using=["business", "financial", "valuation"],
        ),
        PatternCard(
            pattern_id="pat_turnaround",
            name="Turnaround",
            definition="Impaired economics with a credible path to normalized returns.",
            recognition_signals=["Depressed returns", "new capital allocation", "cost/portfolio reset"],
            failure_modes=["False dawn", "balance sheet break", "industry permanently impaired"],
            related_concepts=["mean_reversion", "capital_allocation"],
            analysts_using=["business", "financial", "risk"],
        ),
        PatternCard(
            pattern_id="pat_value_trap",
            name="Value Trap",
            definition="Apparently cheap asset whose low multiple reflects permanent impairment.",
            recognition_signals=["Low multiple", "falling ROIC", "no catalysts", "structural decline"],
            failure_modes=["Catching falling knife", "ignoring capital destruction"],
            related_concepts=["mean_reversion", "intrinsic_value"],
            analysts_using=["valuation", "risk"],
        ),
        PatternCard(
            pattern_id="pat_cyclical",
            name="Cyclical",
            definition="Earnings and returns swing with the industry cycle.",
            recognition_signals=["Peak margins", "capacity additions", "inventory swings"],
            failure_modes=["Buying peak earnings", "using mid-cycle multiples on peak EPS"],
            related_concepts=["capital_cycle", "mean_reversion"],
            analysts_using=["financial", "valuation", "macro"],
        ),
        PatternCard(
            pattern_id="pat_commodity",
            name="Commodity",
            definition="Price-taking economics where cost curve and cycle dominate.",
            recognition_signals=["Little pricing power", "cost leadership decisive", "high earnings volatility"],
            failure_modes=["Paying franchise multiples for commodity cash flows"],
            related_concepts=["pricing_power", "capital_cycle"],
            analysts_using=["business", "financial"],
        ),
        PatternCard(
            pattern_id="pat_platform",
            name="Platform",
            definition="Multi-sided network with take-rate and liquidity economics.",
            recognition_signals=["Network effects", "ecosystem", "take-rate debates"],
            failure_modes=["Multi-homing", "regulatory attack", "cold-start failure"],
            related_concepts=["network_effects", "platform_economics"],
            analysts_using=["business", "valuation"],
        ),
        PatternCard(
            pattern_id="pat_capital_allocator",
            name="Capital Allocator",
            definition="Value creation driven by superior deployment of capital across opportunities.",
            recognition_signals=["Disciplined M&A", "buybacks at discounts", "portfolio pruning"],
            failure_modes=["Empire building", "overpaying for growth"],
            related_concepts=["capital_allocation", "intrinsic_value"],
            analysts_using=["management", "financial"],
        ),
        PatternCard(
            pattern_id="pat_network_effect",
            name="Network Effect Business",
            definition="Defensibility rises with scale of users/interactions.",
            recognition_signals=["Winner-take-most dynamics", "rising engagement with scale"],
            failure_modes=["Disintermediation", "regulation", "fake network effects"],
            related_concepts=["network_effects", "switching_costs"],
            analysts_using=["business"],
        ),
        PatternCard(
            pattern_id="pat_premium_consumer",
            name="Premium Consumer",
            definition="Brand-led pricing power in consumer categories.",
            recognition_signals=["Price premiums", "high gross margins", "loyal cohorts"],
            failure_modes=["Brand dilution", "channel shift", "aspirational demand fade"],
            related_concepts=["brand", "pricing_power"],
            analysts_using=["business", "financial"],
        ),
        PatternCard(
            pattern_id="pat_financial_franchise",
            name="Financial Franchise",
            definition="Deposit/distribution or underwriting franchise with durable spreads/fees.",
            recognition_signals=["Low-cost funding", "underwriting discipline", "distribution strength"],
            failure_modes=["Credit cycle blow-ups", "NIM compression", "conduct risk"],
            related_concepts=["franchise", "credit_cycle"],
            analysts_using=["business", "financial", "risk"],
        ),
    ]


def seed_decision_rules() -> list[DecisionRule]:
    return [
        DecisionRule(
            rule_id="dr_roic_quality_up",
            name="ROIC supports financial quality",
            if_conditions=[
                "ROIC > cost of capital",
                "ROIC stable across cycle",
                "Cash flow conversion strong",
            ],
            then_action="Increase Financial Quality",
            related_frameworks=["fw_roic_quality"],
            related_concepts=["roic", "cash_conversion"],
            analysts_using=["financial", "valuation"],
        ),
        DecisionRule(
            rule_id="dr_business_quality_up",
            name="Brand economics support business quality",
            if_conditions=[
                "Brand strong",
                "Pricing power high",
                "Customer retention high",
            ],
            then_action="Increase Business Quality",
            related_frameworks=["fw_moat", "fw_pricing_power"],
            related_concepts=["brand", "pricing_power", "retention"],
            analysts_using=["business"],
        ),
        DecisionRule(
            rule_id="dr_mos_required",
            name="Uncertainty requires margin of safety",
            if_conditions=[
                "Forecast uncertainty high",
                "Embedded expectations demanding",
            ],
            then_action="Require wider Margin of Safety before constructive stance",
            related_frameworks=["fw_margin_of_safety"],
            related_concepts=["margin_of_safety", "uncertainty"],
            analysts_using=["valuation", "risk"],
        ),
        DecisionRule(
            rule_id="dr_value_trap",
            name="Cheap multiple with falling returns",
            if_conditions=[
                "Multiple below history/peers",
                "ROIC declining structurally",
                "No credible reinvestment or turnaround path",
            ],
            then_action="Classify as Value Trap risk — do not treat as mean-reversion certainty",
            related_frameworks=["fw_relative_valuation"],
            related_concepts=["value_trap", "roic"],
            analysts_using=["valuation", "risk"],
        ),
        DecisionRule(
            rule_id="dr_capital_cycle_caution",
            name="Peak returns attract capacity",
            if_conditions=[
                "Industry ROIC elevated vs history",
                "Capacity additions accelerating",
            ],
            then_action="Increase Capital Cycle caution — expect return compression",
            related_frameworks=["fw_capital_cycle"],
            related_concepts=["capital_cycle", "roic"],
            analysts_using=["business", "macro"],
        ),
    ]
