"""Phase-1 institutional framework registry (deterministic, versioned)."""

from __future__ import annotations

from typing import Any

# available_from: ISO date — frameworks older than modern practice still valid historically
_FW: dict[str, dict[str, Any]] = {
    "FW_DCF": {
        "framework_id": "FW_DCF",
        "name": "Discounted Cash Flow (DCF)",
        "description": "Intrinsic value from projected free cash flows discounted at WACC/cost of equity.",
        "purpose": "Cash-generative operating businesses with forecastable FCFF/FCFE.",
        "applicable_sectors": ["it_services", "consumer_staples", "pharma", "industrials", "telecom"],
        "applicable_industries": ["software", "fmcg", "manufacturing"],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "analyse", "compare", "education"],
        "required_evidence": ["FINANCIAL_METRICS", "HISTORICAL_VALUATION"],
        "required_kpis": ["FCF", "revenue_growth", "margins", "WACC"],
        "required_documents": ["annual_report", "investor_presentation"],
        "forbidden_domains": ["banks", "insurance", "nbfc"],
        "known_limitations": ["Sensitive to terminal growth; weak for financials with book-value economics"],
        "confidence_rules": {"sector_match": 0.35, "evidence": 0.25},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_RESIDUAL_INCOME": {
        "framework_id": "FW_RESIDUAL_INCOME",
        "name": "Residual Income",
        "description": "Equity value = book value + PV of expected residual income (ROE − r) × BV.",
        "purpose": "Banks, NBFCs and book-value anchored financials.",
        "applicable_sectors": ["banks", "nbfc", "insurance"],
        "applicable_industries": ["banking", "lending"],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "explain", "education", "analyse"],
        "required_evidence": ["FINANCIAL_METRICS", "ACCOUNTING_NOTES"],
        "required_kpis": ["ROE", "book_value", "cost_of_equity", "NIM"],
        "required_documents": ["annual_report"],
        "forbidden_domains": [],
        "known_limitations": ["Depends on clean book value and sustainable ROE"],
        "confidence_rules": {"sector_match": 0.4, "evidence": 0.2},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_DDM": {
        "framework_id": "FW_DDM",
        "name": "Dividend Discount Model",
        "description": "Value from expected dividends discounted at cost of equity.",
        "purpose": "Mature dividend payers with stable payout.",
        "applicable_sectors": ["banks", "utilities", "consumer_staples"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "education"],
        "required_evidence": ["FINANCIAL_METRICS"],
        "required_kpis": ["DPS", "payout", "growth"],
        "required_documents": ["annual_report"],
        "forbidden_domains": [],
        "known_limitations": ["Weak when payout is irregular"],
        "confidence_rules": {"sector_match": 0.2},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_PB": {
        "framework_id": "FW_PB",
        "name": "Price to Book",
        "description": "Market price relative to accounting book / tangible book value.",
        "purpose": "Primary multiple for banks, insurers, NBFCs; secondary for asset-heavy firms.",
        "applicable_sectors": ["banks", "insurance", "nbfc"],
        "applicable_industries": ["banking", "lending", "insurance"],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "explain", "education", "compare", "analyse"],
        "required_evidence": ["FINANCIAL_METRICS", "HISTORICAL_VALUATION"],
        "required_kpis": ["P/B", "ROE", "book_value"],
        "required_documents": ["annual_report"],
        "forbidden_domains": [],
        "known_limitations": ["Accounting distortions in intangibles-heavy businesses"],
        "confidence_rules": {"sector_match": 0.4},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_EV_EBITDA": {
        "framework_id": "FW_EV_EBITDA",
        "name": "EV / EBITDA",
        "description": "Enterprise value to operating earnings before D&A.",
        "purpose": "Operating companies with meaningful EBITDA; not deposit-taking banks.",
        "applicable_sectors": [
            "it_services",
            "hospitals",
            "cement",
            "steel",
            "telecom",
            "industrials",
            "consumer_staples",
            "pharma",
        ],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "compare", "analyse", "education", "explain"],
        "required_evidence": ["FINANCIAL_METRICS", "HISTORICAL_VALUATION"],
        "required_kpis": ["EV", "EBITDA", "net_debt"],
        "required_documents": ["annual_report"],
        "forbidden_domains": ["banks", "insurance", "nbfc"],
        "known_limitations": ["Misleading for banks (deposits ≠ capital structure debt)"],
        "confidence_rules": {"sector_match": 0.35},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_EV_SALES": {
        "framework_id": "FW_EV_SALES",
        "name": "EV / Sales",
        "description": "Enterprise value relative to revenue — early-stage or low-margin peers.",
        "purpose": "Growth or thin-margin businesses where EBITDA is unstable.",
        "applicable_sectors": ["it_services", "telecom", "consumer_staples"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "compare"],
        "required_evidence": ["FINANCIAL_METRICS"],
        "required_kpis": ["EV", "revenue"],
        "required_documents": [],
        "forbidden_domains": ["banks"],
        "known_limitations": ["Ignores profitability"],
        "confidence_rules": {"sector_match": 0.15},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_PE": {
        "framework_id": "FW_PE",
        "name": "Price / Earnings",
        "description": "Equity market price to earnings.",
        "purpose": "Broad equity multiple; secondary to sector-specific anchors.",
        "applicable_sectors": ["it_services", "consumer_staples", "industrials", "pharma", "generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "compare", "analyse"],
        "required_evidence": ["FINANCIAL_METRICS"],
        "required_kpis": ["P/E", "EPS"],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": ["Distorted by one-offs and leverage differences"],
        "confidence_rules": {"sector_match": 0.15},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_SOTP": {
        "framework_id": "FW_SOTP",
        "name": "Sum of the Parts (SOTP)",
        "description": "Value each material segment / holding separately then aggregate.",
        "purpose": "Conglomerates and multi-business groups.",
        "applicable_sectors": ["conglomerates"],
        "applicable_industries": ["diversified"],
        "applicable_companies": ["RELIANCE"],
        "applicable_question_types": ["valuation", "analyse", "crossdomain", "explain"],
        "required_evidence": ["FINANCIAL_METRICS", "DOCUMENT_SECTIONS", "OWNERSHIP"],
        "required_kpis": ["segment_EBIT", "holdings_NAV"],
        "required_documents": ["annual_report", "investor_presentation"],
        "forbidden_domains": [],
        "known_limitations": ["Holding-company discount subjectivity"],
        "confidence_rules": {"sector_match": 0.45},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_REPLACEMENT_COST": {
        "framework_id": "FW_REPLACEMENT_COST",
        "name": "Replacement Cost",
        "description": "Value vs cost to replace productive capacity.",
        "purpose": "Asset-heavy cyclical industries.",
        "applicable_sectors": ["cement", "steel", "utilities", "industrials"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "analyse"],
        "required_evidence": ["FINANCIAL_METRICS"],
        "required_kpis": ["capacity", "capex_per_ton"],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": ["Hard to observe true replacement cost"],
        "confidence_rules": {"sector_match": 0.2},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_NAV": {
        "framework_id": "FW_NAV",
        "name": "Net Asset Value",
        "description": "Mark assets to market / appraisal value less liabilities.",
        "purpose": "Real estate, investment holdings, asset plays.",
        "applicable_sectors": ["real_estate", "conglomerates"],
        "applicable_industries": ["realty"],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "analyse"],
        "required_evidence": ["FINANCIAL_METRICS", "OWNERSHIP"],
        "required_kpis": ["NAV", "discount_to_NAV"],
        "required_documents": ["annual_report"],
        "forbidden_domains": [],
        "known_limitations": ["Appraisal lag"],
        "confidence_rules": {"sector_match": 0.4},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_ROIC": {
        "framework_id": "FW_ROIC",
        "name": "ROIC",
        "description": "Return on invested capital vs WACC as quality / value driver.",
        "purpose": "Capital-intensive and compounder analysis.",
        "applicable_sectors": ["industrials", "consumer_staples", "cement", "pharma", "it_services"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["analyse", "explain", "education", "compare"],
        "required_evidence": ["FINANCIAL_METRICS"],
        "required_kpis": ["ROIC", "WACC", "invested_capital"],
        "required_documents": [],
        "forbidden_domains": ["banks"],
        "known_limitations": ["Definition sensitivity"],
        "confidence_rules": {"sector_match": 0.25},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_ROE": {
        "framework_id": "FW_ROE",
        "name": "ROE",
        "description": "Return on equity — core bank and franchise quality metric.",
        "purpose": "Link P/B to sustainable ROE for financials; secondary elsewhere.",
        "applicable_sectors": ["banks", "nbfc", "insurance", "generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "explain", "analyse", "education"],
        "required_evidence": ["FINANCIAL_METRICS"],
        "required_kpis": ["ROE"],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": ["Leverage can inflate ROE"],
        "confidence_rules": {"sector_match": 0.3},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_ROCE": {
        "framework_id": "FW_ROCE",
        "name": "ROCE",
        "description": "Return on capital employed.",
        "purpose": "Industrial / manufacturing capital efficiency.",
        "applicable_sectors": ["industrials", "cement", "steel", "auto"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["analyse", "compare"],
        "required_evidence": ["FINANCIAL_METRICS"],
        "required_kpis": ["ROCE"],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"sector_match": 0.2},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_CAPITAL_ALLOCATION": {
        "framework_id": "FW_CAPITAL_ALLOCATION",
        "name": "Capital Allocation",
        "description": "Assess reinvestment, M&A, buybacks, dividends vs opportunity set.",
        "purpose": "Management quality and long-term compounding.",
        "applicable_sectors": ["industrials", "conglomerates", "it_services", "consumer_staples", "generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["analyse", "documents", "explain"],
        "required_evidence": ["DOCUMENT_SECTIONS", "FINANCIAL_METRICS", "CORPORATE_EVENTS"],
        "required_kpis": ["capex", "buybacks", "M&A"],
        "required_documents": ["annual_report", "investor_presentation"],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.3},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_ACCOUNTING_QUALITY": {
        "framework_id": "FW_ACCOUNTING_QUALITY",
        "name": "Accounting Quality",
        "description": "Accruals, earnings quality, footnote risk.",
        "purpose": "Accounting / cash-conversion questions.",
        "applicable_sectors": ["generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["accounting", "analyse", "explain", "education"],
        "required_evidence": ["ACCOUNTING_NOTES", "FINANCIAL_METRICS", "DOCUMENT_SECTIONS"],
        "required_kpis": ["accruals", "CFO", "earnings"],
        "required_documents": ["annual_report", "notes"],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.4},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_CASH_FLOW_QUALITY": {
        "framework_id": "FW_CASH_FLOW_QUALITY",
        "name": "Cash Flow Quality",
        "description": "CFO vs earnings, WC, FCF conversion.",
        "purpose": "Growth-quality and earnings-sustainability analysis.",
        "applicable_sectors": ["generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["accounting", "analyse", "explain"],
        "required_evidence": ["FINANCIAL_METRICS", "ACCOUNTING_NOTES"],
        "required_kpis": ["CFO", "FCF", "WC"],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.35},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_BUSINESS_QUALITY": {
        "framework_id": "FW_BUSINESS_QUALITY",
        "name": "Business Quality",
        "description": "Franchise strength, unit economics, durability of returns.",
        "purpose": "Quality assessment beyond multiples.",
        "applicable_sectors": ["generic", "consumer_staples", "it_services", "banks"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["analyse", "explain", "education"],
        "required_evidence": ["FINANCIAL_METRICS", "DOCUMENT_SECTIONS"],
        "required_kpis": ["margins", "returns"],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.2},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_ECONOMIC_MOAT": {
        "framework_id": "FW_ECONOMIC_MOAT",
        "name": "Economic Moat",
        "description": "Sources and durability of competitive advantage.",
        "purpose": "Moat / franchise persistence questions.",
        "applicable_sectors": ["consumer_staples", "it_services", "pharma", "generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["analyse", "explain", "industry"],
        "required_evidence": ["DOCUMENT_SECTIONS", "RELATIONSHIP_GRAPH", "HISTORICAL_VALUATION"],
        "required_kpis": ["market_share", "pricing_power"],
        "required_documents": ["annual_report"],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.35},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_PORTERS_FIVE": {
        "framework_id": "FW_PORTERS_FIVE",
        "name": "Porter's Five Forces",
        "description": "Industry rivalry, substitutes, buyers, suppliers, entrants.",
        "purpose": "Industry structure analysis.",
        "applicable_sectors": ["generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["industry", "compare", "explain"],
        "required_evidence": ["RELATIONSHIP_GRAPH", "DOCUMENT_SECTIONS"],
        "required_kpis": [],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.3},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_INDUSTRY_STRUCTURE": {
        "framework_id": "FW_INDUSTRY_STRUCTURE",
        "name": "Industry Structure",
        "description": "Capacity, concentration, cycle position, cost curves.",
        "purpose": "Sector / industry questions.",
        "applicable_sectors": ["cement", "steel", "airlines", "hospitals", "telecom", "generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["industry", "compare", "analyse", "explain"],
        "required_evidence": ["RELATIONSHIP_GRAPH", "MACRO_INDICATORS"],
        "required_kpis": ["capacity", "utilisation", "HHI"],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.3},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_MACRO_TRANSMISSION": {
        "framework_id": "FW_MACRO_TRANSMISSION",
        "name": "Macro Transmission",
        "description": "Trace rates, FX, commodity, inflation shocks through sectors.",
        "purpose": "Macro and cross-domain transmission questions.",
        "applicable_sectors": ["generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["macro", "crossdomain", "government", "explain"],
        "required_evidence": ["MACRO_INDICATORS", "GOVERNMENT_POLICIES", "RELATIONSHIP_GRAPH"],
        "required_kpis": ["repo", "CPI", "FX", "crude"],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.45},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_SCENARIO": {
        "framework_id": "FW_SCENARIO",
        "name": "Scenario Analysis",
        "description": "Multiple state-contingent outcomes with drivers.",
        "purpose": "Uncertainty / simultaneous-shock questions.",
        "applicable_sectors": ["generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["macro", "crossdomain", "analyse", "portfolio"],
        "required_evidence": ["MACRO_INDICATORS", "FINANCIAL_METRICS"],
        "required_kpis": [],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.25},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_HISTORICAL_VALUATION": {
        "framework_id": "FW_HISTORICAL_VALUATION",
        "name": "Historical Valuation",
        "description": "Current multiples / spreads vs own and peer history.",
        "purpose": "Expensive/cheap and regime context.",
        "applicable_sectors": ["generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "explain", "analyse", "historicalreplay", "compare"],
        "required_evidence": ["HISTORICAL_VALUATION", "FINANCIAL_METRICS"],
        "required_kpis": ["P/B", "P/E", "EV/EBITDA"],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.25},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_PEER_COMPARISON": {
        "framework_id": "FW_PEER_COMPARISON",
        "name": "Peer Comparison",
        "description": "Relative fundamentals and multiples across peers.",
        "purpose": "Compare questions.",
        "applicable_sectors": ["generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["compare", "analyse", "valuation"],
        "required_evidence": ["FINANCIAL_METRICS", "HISTORICAL_VALUATION"],
        "required_kpis": [],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.4},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_RISK": {
        "framework_id": "FW_RISK",
        "name": "Risk Framework",
        "description": "Credit, market, operational, liquidity and emerging risks.",
        "purpose": "Risk and document risk-section questions.",
        "applicable_sectors": ["generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["risk", "documents", "analyse"],
        "required_evidence": ["RISK_FACTORS", "DOCUMENT_SECTIONS"],
        "required_kpis": [],
        "required_documents": ["annual_report"],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.35},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_CORPORATE_GOVERNANCE": {
        "framework_id": "FW_CORPORATE_GOVERNANCE",
        "name": "Corporate Governance",
        "description": "Board, related-party, capital allocation governance.",
        "purpose": "Governance and management-quality overlays.",
        "applicable_sectors": ["generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["documents", "analyse", "explain"],
        "required_evidence": ["DOCUMENT_SECTIONS", "OWNERSHIP"],
        "required_kpis": [],
        "required_documents": ["annual_report"],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.25},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_NONE": {
        "framework_id": "FW_NONE",
        "name": "No Framework Required",
        "description": "Procedural / meta questions without a valuation framework.",
        "purpose": "Fallback when no analytical framework applies.",
        "applicable_sectors": ["generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["unknown"],
        "required_evidence": [],
        "required_kpis": [],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": ["Should be rare"],
        "confidence_rules": {},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    # Sector-specific operational frameworks (Phase 1 extensions from mapping table)
    "FW_EMBEDDED_VALUE": {
        "framework_id": "FW_EMBEDDED_VALUE",
        "name": "Embedded Value",
        "description": "Insurance EV / VNB economics.",
        "purpose": "Life insurance valuation.",
        "applicable_sectors": ["insurance"],
        "applicable_industries": ["insurance"],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "analyse", "explain"],
        "required_evidence": ["FINANCIAL_METRICS", "DOCUMENT_SECTIONS"],
        "required_kpis": ["EV", "VNB", "NBAP"],
        "required_documents": ["embedded_value_report"],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"sector_match": 0.45},
        "replay_compatibility": True,
        "available_from": "2000-01-01",
    },
    "FW_EV_EBITDAR": {
        "framework_id": "FW_EV_EBITDAR",
        "name": "EV / EBITDAR",
        "description": "Enterprise value to EBITDAR — aviation lease-adjusted.",
        "purpose": "Airlines.",
        "applicable_sectors": ["airlines"],
        "applicable_industries": ["aviation"],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "analyse", "compare"],
        "required_evidence": ["FINANCIAL_METRICS"],
        "required_kpis": ["EBITDAR", "leases"],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"sector_match": 0.4},
        "replay_compatibility": True,
        "available_from": "2000-01-01",
    },
    "FW_HEALTHCARE_OPS": {
        "framework_id": "FW_HEALTHCARE_OPS",
        "name": "Healthcare Operations (Occupancy / ARPOB)",
        "description": "Hospital operating KPIs: occupancy, ARPOB, ALOS.",
        "purpose": "Hospital economics alongside EV/EBITDA.",
        "applicable_sectors": ["hospitals"],
        "applicable_industries": ["healthcare"],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "analyse", "explain", "industry"],
        "required_evidence": ["FINANCIAL_METRICS", "ALTERNATIVE_DATA"],
        "required_kpis": ["occupancy", "ARPOB", "ALOS"],
        "required_documents": ["investor_presentation"],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"sector_match": 0.4},
        "replay_compatibility": True,
        "available_from": "2005-01-01",
    },
    "FW_AVIATION_OPS": {
        "framework_id": "FW_AVIATION_OPS",
        "name": "Aviation Operations (Load Factor / ASK / RPK)",
        "description": "Airline traffic and yield KPIs.",
        "purpose": "Airline operating analysis.",
        "applicable_sectors": ["airlines"],
        "applicable_industries": ["aviation"],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "analyse", "industry", "explain"],
        "required_evidence": ["FINANCIAL_METRICS", "ALTERNATIVE_DATA"],
        "required_kpis": ["load_factor", "ASK", "RPK", "yield"],
        "required_documents": ["investor_presentation"],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"sector_match": 0.4},
        "replay_compatibility": True,
        "available_from": "2000-01-01",
    },
    "FW_CEMENT_CAPACITY": {
        "framework_id": "FW_CEMENT_CAPACITY",
        "name": "Cement Capacity / Utilisation",
        "description": "Capacity, utilisation, pricing and regional balance.",
        "purpose": "Cement industry / valuation context.",
        "applicable_sectors": ["cement"],
        "applicable_industries": ["cement"],
        "applicable_companies": [],
        "applicable_question_types": ["industry", "valuation", "analyse", "explain"],
        "required_evidence": ["FINANCIAL_METRICS", "ALTERNATIVE_DATA"],
        "required_kpis": ["capacity", "utilisation", "realisations"],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"sector_match": 0.4},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_COMMODITY_CYCLE": {
        "framework_id": "FW_COMMODITY_CYCLE",
        "name": "Commodity Cycle",
        "description": "Cycle position, spreads, and cost curve for commodity producers.",
        "purpose": "Steel and other commodity industries.",
        "applicable_sectors": ["steel"],
        "applicable_industries": ["metals"],
        "applicable_companies": [],
        "applicable_question_types": ["industry", "valuation", "macro", "analyse"],
        "required_evidence": ["MACRO_INDICATORS", "FINANCIAL_METRICS"],
        "required_kpis": ["spreads", "utilisation"],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"sector_match": 0.35},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_RAB": {
        "framework_id": "FW_RAB",
        "name": "Regulated Asset Base",
        "description": "Regulated utilities valued on RAB / allowed returns.",
        "purpose": "Utilities.",
        "applicable_sectors": ["utilities"],
        "applicable_industries": ["power", "utilities"],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "analyse", "government"],
        "required_evidence": ["FINANCIAL_METRICS", "GOVERNMENT_POLICIES"],
        "required_kpis": ["RAB", "allowed_ROE"],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"sector_match": 0.45},
        "replay_compatibility": True,
        "available_from": "1995-01-01",
    },
    "FW_TELECOM_SUBSCRIBER": {
        "framework_id": "FW_TELECOM_SUBSCRIBER",
        "name": "Telecom Subscriber Metrics",
        "description": "ARPU, subscribers, churn alongside EV/EBITDA.",
        "purpose": "Telecom operating economics.",
        "applicable_sectors": ["telecom"],
        "applicable_industries": ["telecom"],
        "applicable_companies": [],
        "applicable_question_types": ["valuation", "analyse", "industry"],
        "required_evidence": ["FINANCIAL_METRICS", "ALTERNATIVE_DATA"],
        "required_kpis": ["ARPU", "subscribers", "churn"],
        "required_documents": ["investor_presentation"],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"sector_match": 0.35},
        "replay_compatibility": True,
        "available_from": "2000-01-01",
    },
    "FW_POLICY": {
        "framework_id": "FW_POLICY",
        "name": "Policy Framework",
        "description": "Trace government / regulator actions to sector outcomes.",
        "purpose": "Government and policy questions.",
        "applicable_sectors": ["generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["government", "macro", "crossdomain"],
        "required_evidence": ["GOVERNMENT_POLICIES", "MACRO_INDICATORS"],
        "required_kpis": [],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.45},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
    "FW_FRAMEWORK_EXPLANATION": {
        "framework_id": "FW_FRAMEWORK_EXPLANATION",
        "name": "Framework Explanation",
        "description": "Explain why a valuation / analytical framework applies or fails.",
        "purpose": "Education / Explain questions about methodology.",
        "applicable_sectors": ["generic"],
        "applicable_industries": [],
        "applicable_companies": [],
        "applicable_question_types": ["explain", "education"],
        "required_evidence": ["ACCOUNTING_NOTES", "FINANCIAL_METRICS", "DOCUMENT_SECTIONS"],
        "required_kpis": [],
        "required_documents": [],
        "forbidden_domains": [],
        "known_limitations": [],
        "confidence_rules": {"question_match": 0.4},
        "replay_compatibility": True,
        "available_from": "1990-01-01",
    },
}


def get_framework(framework_id: str) -> dict[str, Any] | None:
    row = _FW.get(framework_id)
    return dict(row) if row else None


def list_frameworks() -> list[dict[str, Any]]:
    return [dict(v) for v in _FW.values()]


def framework_ids() -> list[str]:
    return list(_FW.keys())


def registry_index() -> dict[str, dict[str, Any]]:
    return {k: dict(v) for k, v in _FW.items()}
