"""Per-analyst institutional mandates — domain, inputs, outputs, never-discuss."""

from __future__ import annotations

from typing import Any

from analyst_router.schema import ANALYST_REGISTRY

# Title-case keys matching ANALYST_REGISTRY
MANDATES: dict[str, dict[str, Any]] = {
    "Business": {
        "role": "Business",
        "primary_questions": [
            "Is this a business we would like to own?",
            "Does a durable competitive advantage exist?",
        ],
        "secondary_questions": [
            "Is the moat strengthening or weakening?",
            "What is the capital cycle and customer quality?",
        ],
        "mandatory_inputs": ["Company Analysis", "Company Dossier", "Filings"],
        "optional_inputs": ["Peer Intelligence", "Sector Intelligence"],
        "output_contract": ["Business Opinion", "Moat Assessment", "Growth Quality"],
        "dependencies": [],
        "maximum_scope": "Business model, moat, competition, pricing, capital cycle, growth, customers",
        "allowed": [
            "Business model",
            "Moat",
            "Competition",
            "Pricing",
            "Capital cycle",
            "Growth",
            "Customers",
        ],
        "never": ["PE", "DCF", "Interest rates", "Portfolio"],
        "voting_rights": True,
    },
    "Financial": {
        "role": "Financial",
        "primary_questions": [
            "Do the financial statements support the investment thesis?",
            "Is capital allocation value-creating?",
        ],
        "secondary_questions": [
            "Is earnings quality high?",
            "Is cash conversion sustainable?",
        ],
        "mandatory_inputs": ["Financial statements", "Cash flow", "Balance sheet"],
        "optional_inputs": ["Accounting flags", "Filings"],
        "output_contract": ["Financial Opinion", "ROIC/ROE View", "Cash Conversion"],
        "dependencies": [],
        "maximum_scope": "Cash flow, balance sheet, returns, margins, working capital, capital allocation",
        "allowed": [
            "Cash flow",
            "Balance sheet",
            "ROIC",
            "ROE",
            "Margins",
            "Working capital",
            "Capital allocation",
        ],
        "never": ["Brand", "Macro", "Valuation"],
        "voting_rights": True,
    },
    "Valuation": {
        "role": "Valuation",
        "primary_questions": [
            "Does current valuation already discount expected business quality?",
            "Where is the margin of safety?",
        ],
        "secondary_questions": [
            "What is priced in?",
            "Which assumptions matter most?",
        ],
        "mandatory_inputs": ["Price", "Multiples", "Business Opinion", "Financial Opinion"],
        "optional_inputs": ["Peer multiples", "Historical multiples"],
        "output_contract": ["Valuation Opinion", "Embedded Expectations", "Margin of Safety"],
        "dependencies": ["Business", "Financial"],
        "maximum_scope": "DCF, relative valuation, EV, PE, PB, embedded expectations, margin of safety",
        "allowed": [
            "DCF",
            "Relative valuation",
            "EV",
            "PE",
            "PB",
            "Embedded expectations",
            "Margin of safety",
        ],
        "never": ["Brand", "Moat", "Accounting fraud"],
        "voting_rights": True,
    },
    "Risk": {
        "role": "Risk",
        "primary_questions": [
            "What can permanently impair capital?",
            "Which risks are underpriced?",
        ],
        "secondary_questions": ["What are the stress scenarios?", "What mitigants exist?"],
        "mandatory_inputs": ["Financial Opinion", "Macro context"],
        "optional_inputs": ["Market data", "News"],
        "output_contract": ["Risk Opinion", "Stress Map", "Mitigants"],
        "dependencies": ["Financial"],
        "maximum_scope": "Downside, stress, idiosyncratic and market risks",
        "allowed": ["Downside", "Stress tests", "Tail risk", "Drawdown", "Mitigants"],
        "never": ["Buy recommendation", "Position sizing as sole conclusion"],
        "voting_rights": True,
    },
    "Sector": {
        "role": "Sector",
        "primary_questions": ["Is the sector structurally attractive?", "Where does the company sit vs peers?"],
        "secondary_questions": ["Cycle position?", "Competitive intensity?"],
        "mandatory_inputs": ["Sector Intelligence", "Peer set"],
        "optional_inputs": ["Macro"],
        "output_contract": ["Sector Opinion", "Peer Positioning"],
        "dependencies": [],
        "maximum_scope": "Sector attractiveness, industry structure, peer context",
        "allowed": ["Sector outlook", "Industry structure", "Peer set", "Cycle"],
        "never": ["Company DCF", "Portfolio construction"],
        "voting_rights": True,
    },
    "Macro": {
        "role": "Macro",
        "primary_questions": ["What macro impulses matter for this decision?"],
        "secondary_questions": ["Rates, inflation, liquidity, FX, policy transmission?"],
        "mandatory_inputs": ["Macro series", "Policy context"],
        "optional_inputs": ["Commodity prices", "FX"],
        "output_contract": ["Macro Opinion", "Transmission Channels"],
        "dependencies": [],
        "maximum_scope": "Inflation, rates, GDP, liquidity, oil, currency, policy",
        "allowed": ["Inflation", "Rates", "GDP", "Liquidity", "Oil", "Currency", "Policy"],
        "never": ["DCF", "Business model"],
        "voting_rights": True,
    },
    "Management": {
        "role": "Management",
        "primary_questions": ["Is management capable and aligned?"],
        "secondary_questions": ["Capital allocation track record?", "Governance red flags?"],
        "mandatory_inputs": ["Filings", "Transcripts"],
        "optional_inputs": ["Ownership"],
        "output_contract": ["Management Opinion"],
        "dependencies": [],
        "maximum_scope": "Leadership quality, capital allocation behaviour, credibility",
        "allowed": ["CEO/leadership", "Execution", "Capital allocation behaviour"],
        "never": ["PE multiples", "Portfolio sizing"],
        "voting_rights": False,
    },
    "Ownership": {
        "role": "Ownership",
        "primary_questions": ["Does ownership structure support minority investors?"],
        "secondary_questions": ["Promoter / FII / DII shifts?"],
        "mandatory_inputs": ["Shareholding pattern"],
        "optional_inputs": ["Governance filings"],
        "output_contract": ["Ownership Opinion"],
        "dependencies": [],
        "maximum_scope": "Shareholding, promoter pledges, institutional ownership",
        "allowed": ["Promoter holding", "FII/DII", "Pledges"],
        "never": ["Business moat", "DCF"],
        "voting_rights": False,
    },
    "Accounting": {
        "role": "Accounting",
        "primary_questions": ["Are reported earnings trustworthy?"],
        "secondary_questions": ["Forensic flags?", "Revenue recognition risk?"],
        "mandatory_inputs": ["Financial statements", "Notes"],
        "optional_inputs": ["Auditor changes"],
        "output_contract": ["Accounting Opinion", "Quality Flags"],
        "dependencies": ["Financial"],
        "maximum_scope": "Earnings quality, forensic accounting, audit flags",
        "allowed": ["Earnings quality", "Forensic flags", "Audit"],
        "never": ["Brand", "Macro policy"],
        "voting_rights": False,
    },
    "Portfolio": {
        "role": "Portfolio",
        "primary_questions": ["How does this fit the portfolio mandate?"],
        "secondary_questions": ["Sizing, concentration, correlation, factor exposure?"],
        "mandatory_inputs": ["Risk Opinion", "Valuation Opinion"],
        "optional_inputs": ["Existing holdings"],
        "output_contract": ["Portfolio Fit", "Sizing Guidance"],
        "dependencies": ["Risk", "Valuation"],
        "maximum_scope": "Diversification, sizing, concentration, risk budget, correlation, factors",
        "allowed": [
            "Diversification",
            "Sizing",
            "Concentration",
            "Risk Budget",
            "Correlation",
            "Factor Exposure",
        ],
        "never": ["Company valuation"],
        "voting_rights": True,
    },
    "Forecast": {
        "role": "Forecast",
        "primary_questions": ["What is the base-case path for key drivers?"],
        "secondary_questions": ["Sensitivities?", "Risks to the forecast?"],
        "mandatory_inputs": ["Business Opinion", "Financial Opinion", "Macro Opinion"],
        "optional_inputs": ["Guidance", "Consensus"],
        "output_contract": ["Forecast Opinion", "Scenario Paths"],
        "dependencies": ["Business", "Financial", "Macro"],
        "maximum_scope": "Forward paths for earnings, growth, and key drivers",
        "allowed": ["Base/bull/bear paths", "Driver forecasts", "Sensitivities"],
        "never": ["Final buy/sell without committee"],
        "voting_rights": True,
    },
    "Market": {
        "role": "Market",
        "primary_questions": ["What is the market regime telling us?"],
        "secondary_questions": ["Liquidity, momentum, technical context?"],
        "mandatory_inputs": ["Price/volume", "Index context"],
        "optional_inputs": ["Derivatives"],
        "output_contract": ["Market Opinion"],
        "dependencies": [],
        "maximum_scope": "Tape, liquidity, technical regime",
        "allowed": ["Momentum", "Liquidity", "Technical regime"],
        "never": ["Intrinsic value", "Moat"],
        "voting_rights": False,
    },
    "News": {
        "role": "News",
        "primary_questions": ["What material news changes the thesis?"],
        "secondary_questions": ["Is the market reaction proportional?"],
        "mandatory_inputs": ["Headlines", "Filings events"],
        "optional_inputs": ["Social/wire"],
        "output_contract": ["News Impact Opinion"],
        "dependencies": [],
        "maximum_scope": "Material news and event impact",
        "allowed": ["Headline impact", "Event reaction"],
        "never": ["Full DCF rebuild"],
        "voting_rights": False,
    },
    "Academy": {
        "role": "Academy",
        "primary_questions": ["What concept must the user understand?"],
        "secondary_questions": ["How is it applied in practice?"],
        "mandatory_inputs": ["Academy corpus"],
        "optional_inputs": ["Worked examples"],
        "output_contract": ["Educational Guide"],
        "dependencies": [],
        "maximum_scope": "Definitions, frameworks, teaching",
        "allowed": ["Explain", "Teach", "Define", "Worked examples"],
        "never": ["Buy/sell recommendation", "Portfolio sizing"],
        "voting_rights": False,
    },
    "Committee": {
        "role": "Committee",
        "primary_questions": ["What is the institutional synthesis?"],
        "secondary_questions": ["Where do analysts disagree?"],
        "mandatory_inputs": ["All participating analyst opinions"],
        "optional_inputs": [],
        "output_contract": ["Committee View", "Disagreement Matrix"],
        "dependencies": ["Business", "Financial", "Valuation", "Risk"],
        "maximum_scope": "Synthesis and recommendation framing",
        "allowed": ["Synthesis", "Recommendation status", "Disagreement"],
        "never": ["Original primary research outside synthesis"],
        "voting_rights": True,
    },
    "CIO": {
        "role": "CIO",
        "primary_questions": ["What decision do we take?"],
        "secondary_questions": ["Under what conditions would we reverse?"],
        "mandatory_inputs": ["Committee View"],
        "optional_inputs": ["Portfolio Fit"],
        "output_contract": ["CIO Decision", "Executive Summary"],
        "dependencies": ["Committee"],
        "maximum_scope": "Final institutional decision framing",
        "allowed": ["Decision", "Executive summary", "Conditions"],
        "never": ["Raw data dump"],
        "voting_rights": True,
    },
}


def get_mandate(analyst: str) -> dict[str, Any] | None:
    return MANDATES.get(analyst)


def all_mandates() -> dict[str, dict[str, Any]]:
    return {k: MANDATES[k] for k in ANALYST_REGISTRY if k in MANDATES}


def never_topics(analyst: str) -> list[str]:
    m = MANDATES.get(analyst) or {}
    return list(m.get("never") or [])
