"""Institutional glossary (FKB-01)."""

from __future__ import annotations

from typing import Any


def _g(id_: str, term: str, definition: str, *, related: list[str] | None = None) -> dict[str, Any]:
    return {
        "id": id_,
        "term": term,
        "definition": definition,
        "related_terms": related or [],
        "performs_analysis": False,
    }


GLOSSARY: dict[str, dict[str, Any]] = {
    "operating_leverage": _g(
        "operating_leverage",
        "Operating Leverage",
        "The sensitivity of operating profit to changes in revenue, arising from fixed operating costs. "
        "When revenue rises faster than operating costs, margins expand.",
        related=["operating_margin", "revenue"],
    ),
    "working_capital": _g(
        "working_capital",
        "Working Capital",
        "Capital tied in short-term operating assets and liabilities (receivables, inventory, payables). "
        "Changes in working capital bridge accounting profit and operating cash flow.",
        related=["receivables", "inventory", "payables", "cash_conversion"],
    ),
    "liquidity": _g(
        "liquidity",
        "Liquidity",
        "Ability to meet near-term obligations using cash and liquid assets.",
        related=["cash", "current_ratio", "quick_ratio"],
    ),
    "solvency": _g(
        "solvency",
        "Solvency",
        "Ability to meet long-term obligations and remain a going concern under leverage and interest burdens.",
        related=["total_debt", "interest_coverage", "debt_to_ebitda"],
    ),
    "capital_allocation": _g(
        "capital_allocation",
        "Capital Allocation",
        "Management choices on deploying capital: capex, M&A, dividends, buybacks, debt repayment, and cash retention.",
        related=["capex", "dividends", "share_buybacks", "total_debt"],
    ),
    "financial_flexibility": _g(
        "financial_flexibility",
        "Financial Flexibility",
        "Capacity to absorb shocks and fund opportunities without distress — liquidity, unused leverage capacity, and FCF.",
        related=["cash", "net_debt", "free_cash_flow"],
    ),
    "cash_conversion": _g(
        "cash_conversion",
        "Cash Conversion",
        "Extent to which accounting profit is realised as operating or free cash flow.",
        related=["pat", "operating_cash_flow", "free_cash_flow", "fcf_conversion"],
    ),
    "margin_expansion": _g(
        "margin_expansion",
        "Margin Expansion",
        "An increase in profitability margins (gross, operating, EBITDA, or net) over a comparable period.",
        related=["gross_margin", "operating_margin", "ebitda_margin"],
    ),
    "margin_compression": _g(
        "margin_compression",
        "Margin Compression",
        "A decrease in profitability margins over a comparable period.",
        related=["gross_margin", "operating_margin"],
    ),
    "organic_growth": _g(
        "organic_growth",
        "Organic Growth",
        "Growth generated by the existing business, excluding acquisitions and often currency effects.",
        related=["revenue"],
    ),
    "return_on_capital": _g(
        "return_on_capital",
        "Return on Capital",
        "Profitability relative to capital invested (ROE, ROCE, ROIC and related measures).",
        related=["roe", "roce", "roic"],
    ),
    "economic_moat": _g(
        "economic_moat",
        "Economic Moat",
        "Durable competitive advantage that protects returns on capital over time. Not inferred from a single ratio.",
        related=["roic", "gross_margin"],
    ),
    "asset_intensity": _g(
        "asset_intensity",
        "Asset Intensity",
        "Amount of assets required to generate a unit of revenue; inverse of asset turnover.",
        related=["asset_turnover", "total_assets"],
    ),
    "recurring_revenue": _g(
        "recurring_revenue",
        "Recurring Revenue",
        "Revenue expected to continue from ongoing customer relationships (subscriptions, retainers, annuities).",
        related=["revenue"],
    ),
    "one_off_item": _g(
        "one_off_item",
        "One-off Item",
        "A non-recurring gain or loss that should be identified when interpreting earnings trends.",
        related=["pat", "ebit"],
    ),
}


def all_glossary() -> list[dict[str, Any]]:
    return [GLOSSARY[k] for k in sorted(GLOSSARY)]


def get_glossary(key: str) -> dict[str, Any] | None:
    k = key.strip().lower().replace(" ", "_").replace("-", "_")
    if k not in GLOSSARY and any(c.isupper() for c in key):
        import re

        k = re.sub(r"(?<!^)(?=[A-Z])", "_", key).lower()
    aliases = {"operatingleverage": "operating_leverage", "wc": "working_capital"}
    k = aliases.get(k, k)
    row = GLOSSARY.get(k)
    return dict(row) if row else None
