"""Module 3 — Valuation Concepts."""

from __future__ import annotations

from financial_concepts.schema import ConceptCard

M = "valuation"

VALUATION_CONCEPTS: dict[str, ConceptCard] = {
    "equity_value": ConceptCard(
        "equity_value", M, "Equity Value",
        "The value of a company's equity claim alone — what Enterprise Value becomes after backing out net debt and other non-equity claims.",
        formula="Equity Value = Enterprise Value − Net Debt − Minority Interest − Preferred Equity",
        business_meaning="Equity Value (per share, it is the share price) is what public-market investors actually trade; Enterprise Value is the analytical construct used to compare operating businesses.",
        interpretation="Equity Value can rise even as Enterprise Value stays flat if net debt is paid down — deleveraging alone transfers value from lenders to shareholders.",
        related_concepts=("enterprise_value", "market_capitalization", "net_debt"),
    ),
    "ev_vs_market_cap": ConceptCard(
        "ev_vs_market_cap", M, "EV vs. Market Cap",
        "The relationship between Enterprise Value and Market Capitalization: EV = Market Cap + Net Debt (+ minority interest/preferred).",
        business_meaning="EV is always larger than Market Cap when a company carries net debt, and can be smaller than Market Cap when the company holds net cash exceeding its debt.",
        interpretation="A company can have a growing Market Cap while EV grows even faster if it's funding growth (or buybacks) with debt — EV captures the full picture Market Cap alone misses.",
        common_mistakes="Using EV and Market Cap interchangeably in valuation multiples — EV/EBITDA and P/E are not directly comparable because their numerators sit at different levels of the capital structure.",
        related_concepts=("enterprise_value", "market_capitalization", "equity_value"),
    ),
    "ev_ebitda": ConceptCard(
        "ev_ebitda", M, "EV/EBITDA",
        "A capital-structure-neutral valuation multiple comparing a company's total operating value to its pre-interest, pre-tax, pre-depreciation earnings.",
        formula="EV/EBITDA = Enterprise Value / EBITDA",
        business_meaning="Because both EV (numerator) and EBITDA (denominator) sit above the effects of financing and depreciation policy, this multiple lets you compare companies with very different leverage and capex/depreciation profiles.",
        interpretation="A lower EV/EBITDA than peers can signal undervaluation — or can signal genuinely lower quality/growth/returns that deserve a discount; always check which explanation fits.",
        industry_exceptions="Not meaningful for banks and financial institutions, where debt is raw material (deposits) rather than a financing choice — see 'why banks use P/B'.",
        related_concepts=("enterprise_value", "ev_sales", "p_e"),
    ),
    "ev_sales": ConceptCard(
        "ev_sales", M, "EV/Sales (EV/Revenue)",
        "A valuation multiple comparing Enterprise Value to revenue, used when earnings or EBITDA are negative or not yet meaningful.",
        formula="EV/Sales = Enterprise Value / Revenue",
        business_meaning="Common for early-stage, high-growth, or currently loss-making companies where profitability multiples cannot be computed.",
        interpretation="EV/Sales says nothing about margin or capital efficiency on its own — a high EV/Sales can be justified by a path to very high eventual margins, or can be a bubble valuation; it must be paired with a margin/growth view.",
        common_mistakes="Comparing EV/Sales across companies with structurally different margin profiles (e.g. a software company vs. a low-margin distributor) without adjusting for that difference.",
        related_concepts=("ev_ebitda", "enterprise_value"),
    ),
    "p_e": ConceptCard(
        "p_e", M, "P/E Ratio (Price-to-Earnings)",
        "The most widely used equity valuation multiple: share price divided by earnings per share (or Market Cap divided by Net Income).",
        formula="P/E = Share Price / Earnings Per Share = Market Cap / Net Income",
        business_meaning="Represents how many years of current earnings an investor is paying for — implicitly a bet on the durability and growth of those earnings.",
        interpretation="A high P/E can reflect high expected growth, high earnings quality, or overvaluation; a low P/E can reflect value, or a genuine risk the market is pricing in (cyclicality, declining moat, leverage).",
        common_mistakes="Comparing P/E across companies with very different capital structures or one-off/non-recurring items distorting reported EPS — always check for normalized/adjusted earnings.",
        related_concepts=("peg", "ev_ebitda", "p_b"),
    ),
    "peg": ConceptCard(
        "peg", M, "PEG Ratio",
        "The P/E ratio divided by the expected earnings growth rate, used to judge whether a high P/E is justified by growth.",
        formula="PEG = P/E Ratio / Expected EPS Growth Rate (%)",
        business_meaning="A stock trading at 30x earnings growing at 30% a year (PEG = 1.0) may be more reasonably valued than one trading at 15x earnings growing at 5% (PEG = 3.0).",
        interpretation="PEG below 1.0 is traditionally viewed as attractive, but the ratio is highly sensitive to the growth estimate used and to how sustainable that growth actually is.",
        common_mistakes="Using a single year's growth spike (e.g. post-recession rebound) rather than a normalized multi-year growth rate in the denominator.",
        related_concepts=("p_e",),
    ),
    "p_b": ConceptCard(
        "p_b", M, "P/B Ratio (Price-to-Book)",
        "A valuation multiple comparing share price (or Market Cap) to a company's book value of equity.",
        formula="P/B = Market Cap / Book Value of Equity = Share Price / Book Value Per Share",
        business_meaning="Most meaningful for asset-heavy or financial businesses where book value closely tracks the real economic value of the balance sheet (loans, securities, real estate).",
        interpretation="P/B should be read alongside ROE: a company earning ROE above its cost of equity deserves to trade above 1x book (it is creating value on top of the capital already invested), and vice versa.",
        industry_exceptions="Less meaningful for asset-light businesses (software, brands) where most economic value comes from intangible assets never recognised on the balance sheet.",
        related_concepts=("why_banks_use_pb", "book_value", "tangible_book", "roe_decomposition"),
    ),
    "why_banks_use_pb": ConceptCard(
        "why_banks_use_pb", M, "Why Banks Trade on P/B (Not EV/EBITDA)",
        "Banks are valued on Price-to-Book rather than EV/EBITDA because their core 'raw material' — deposits and borrowings — is debt, not a financing choice layered on top of an operating business.",
        business_meaning="A bank's balance sheet (loans, securities, deposits) IS the business; interest income and interest expense are operating revenue and operating cost, not financing items sitting below an operating line.",
        interpretation="EBITDA is meaningless for banks (interest expense is their core cost of goods sold, not a financing charge to be added back), and Enterprise Value double-counts debt that is actually the bank's product. Book value, adjusted for asset quality (NPAs), is the cleanest anchor — and P/B versus ROE captures whether the bank earns above its cost of equity.",
        common_mistakes="Applying EV/EBITDA to a bank, insurer, or other financial institution — this is a textbook valuation error because 'debt' for a bank is its operating input, not a capital-structure choice.",
        related_concepts=("p_b", "book_value", "roe_decomposition", "nim", "gnpa"),
    ),
    "dividend_yield": ConceptCard(
        "dividend_yield", M, "Dividend Yield",
        "The annual dividend per share expressed as a percentage of the current share price.",
        formula="Dividend Yield = Annual Dividend Per Share / Share Price",
        business_meaning="Represents the cash-income component of total shareholder return, separate from capital appreciation.",
        interpretation="A very high dividend yield can signal either a genuinely attractive income stock or a distressed one where the market expects a dividend cut (price has fallen faster than the dividend has been cut) — always check payout ratio and coverage.",
        related_concepts=("dividend_coverage", "payout_ratio", "dividend_sustainability", "fcf_yield"),
    ),
    "fcf_yield": ConceptCard(
        "fcf_yield", M, "Free Cash Flow Yield",
        "Free Cash Flow expressed as a percentage of Market Capitalization (or Enterprise Value), showing how much real cash-generating power an investor is buying per dollar of price paid.",
        formula="FCF Yield = Free Cash Flow / Market Capitalization (equity FCF yield) or Free Cash Flow / Enterprise Value (unlevered FCF yield)",
        business_meaning="Unlike the Earnings Yield (inverse of P/E), FCF Yield reflects actual cash generation after capex and working-capital needs — harder to manipulate with accounting choices than reported earnings.",
        interpretation="FCF Yield can exceed Earnings Yield when a company has large non-cash charges (depreciation, amortization) relative to actual maintenance capex needs, or when working capital is releasing cash — meaning true cash generation outpaces accounting profit.",
        common_mistakes="Comparing FCF Yield across companies at very different points in their capex cycle without normalizing for one-off growth investment.",
        related_concepts=("free_cash_flow", "p_e", "earnings_yield", "cash_conversion"),
    ),
    "earnings_yield": ConceptCard(
        "earnings_yield", M, "Earnings Yield",
        "The inverse of the P/E ratio, expressing earnings as a percentage of price — directly comparable to bond yields.",
        formula="Earnings Yield = Earnings Per Share / Share Price = 1 / (P/E Ratio)",
        business_meaning="Lets investors compare the 'yield' of equities directly against the risk-free rate or corporate bond yields when judging relative attractiveness.",
        interpretation="An earnings yield well below the risk-free rate implies the market expects substantial future earnings growth to justify the premium.",
        related_concepts=("p_e", "fcf_yield", "risk_free_rate"),
    ),
    "sotp": ConceptCard(
        "sotp", M, "Sum-of-the-Parts (SOTP) Valuation",
        "A valuation method that values each of a diversified company's business segments separately (using the most appropriate method/multiple for each) and adds them together.",
        business_meaning="A single blended multiple can mis-value a conglomerate with segments of very different quality, growth, and risk — SOTP avoids averaging away that structure.",
        interpretation="A large gap between a company's SOTP value and its actual market value ('conglomerate discount') is often cited as an activist-investor or breakup catalyst thesis.",
        common_mistakes="Failing to deduct holding-company costs, minority interests, or intercompany eliminations when summing the parts.",
        related_concepts=("ev_ebitda", "enterprise_value"),
    ),
    "dcf": ConceptCard(
        "dcf", M, "DCF (Discounted Cash Flow) Valuation",
        "A valuation method that estimates intrinsic value as the present value of all future free cash flows a business is expected to generate, discounted at its cost of capital.",
        formula="Enterprise Value = Σ [FCF_t / (1 + WACC)^t] + Terminal Value / (1 + WACC)^n",
        business_meaning="The most theoretically rigorous valuation approach because it is built directly from cash generation and the required return on capital, not a market-price comparison.",
        interpretation="DCF output is only as good as its assumptions — small changes to growth, margin, or discount-rate assumptions can swing the answer dramatically, which is why it is typically triangulated against comparable-company multiples.",
        common_mistakes="Treating a DCF's precise output number as more certain than the assumptions feeding it — the value of a DCF is often more in the sensitivity analysis than the single point estimate.",
        related_concepts=("terminal_value", "wacc", "terminal_growth", "exit_multiple"),
    ),
    "comparable_company_analysis": ConceptCard(
        "comparable_company_analysis", M, "Comparable Company Analysis (Comps)",
        "A valuation method that values a company by applying the trading multiples of similar, publicly-listed peers to its own financial metrics.",
        business_meaning="Anchors valuation to what the market is actually paying for similar businesses today, rather than a theoretical model of future cash flows.",
        interpretation="Comps are only as good as the peer set chosen — comparing across companies with different growth, margin, or risk profiles without adjustment can mislead badly.",
        related_concepts=("ev_ebitda", "p_e", "precedent_transactions"),
    ),
    "precedent_transactions": ConceptCard(
        "precedent_transactions", M, "Precedent Transactions Analysis",
        "A valuation method that derives multiples from actual historical M&A deals for similar companies, rather than public trading prices.",
        business_meaning="Precedent transaction multiples typically embed a control premium — the extra amount an acquirer pays to gain full control versus buying shares in the open market.",
        interpretation="Precedent transaction values are usually higher than comparable-company trading multiples precisely because of that control premium and expected synergies.",
        related_concepts=("comparable_company_analysis", "control_premium", "acquisition_returns"),
    ),
    "control_premium": ConceptCard(
        "control_premium", M, "Control Premium",
        "The extra amount an acquirer pays above the current market price to gain a controlling stake and the ability to direct company strategy.",
        business_meaning="Reflects the value of synergies, strategic control, and the ability to change management/capital allocation that a passive minority shareholder cannot access.",
        interpretation="A large control premium paid without a credible synergy case is a red flag for potential overpayment/value destruction for the acquirer's shareholders.",
        related_concepts=("precedent_transactions", "acquisition_returns", "minority_discount"),
    ),
    "minority_discount": ConceptCard(
        "minority_discount", M, "Minority (Discount for Lack of Control)",
        "The reduction in per-share value applied to a non-controlling equity stake, reflecting its inability to direct company strategy or force liquidity events.",
        business_meaning="The mirror image of the control premium — public market trading prices typically reflect this minority, non-control basis.",
        related_concepts=("control_premium", "liquidity_discount"),
    ),
    "liquidity_discount": ConceptCard(
        "liquidity_discount", M, "Liquidity Discount (Discount for Lack of Marketability)",
        "A reduction in value applied to an asset or stake that cannot be easily bought or sold, reflecting the cost and risk of illiquidity.",
        business_meaning="Private companies, restricted shares, and small-float stocks all typically warrant a liquidity discount versus an otherwise identical, freely-tradable public security.",
        related_concepts=("minority_discount", "control_premium"),
    ),
}
