"""Module 1 — Corporate Finance Concepts."""

from __future__ import annotations

from financial_concepts.schema import ConceptCard

M = "corporate_finance"

CORPORATE_FINANCE_CONCEPTS: dict[str, ConceptCard] = {
    "enterprise_value": ConceptCard(
        "enterprise_value", M, "Enterprise Value (EV)",
        "The total value of a company's core operating business, belonging to both debt and equity holders — what it would cost to buy the whole company and pay off its debt.",
        formula="EV = Market Capitalization + Total Debt + Minority Interest + Preferred Equity − Cash & Equivalents",
        business_meaning="EV is capital-structure-neutral: it lets you compare a highly-levered company with an unlevered one on the same operating-value basis, which Market Cap alone cannot do.",
        interpretation="A rising EV with flat Market Cap usually means debt is increasing; EV below Market Cap (net cash exceeding debt) means the market is valuing operations below the cash pile.",
        common_mistakes="Confusing EV with Market Cap, or forgetting to net out cash — cash is not part of the operating business being valued.",
        related_concepts=("market_capitalization", "net_debt", "equity_value", "ev_ebitda"),
    ),
    "market_capitalization": ConceptCard(
        "market_capitalization", M, "Market Capitalization",
        "The total market value of a company's outstanding equity shares.",
        formula="Market Cap = Share Price × Total Shares Outstanding",
        business_meaning="Represents what the market is currently paying for the equity claim only — it says nothing about the debt or cash sitting inside the business.",
        interpretation="Market Cap can rise purely from share-count changes (buybacks reduce it at a constant price × fewer shares) as well as from price moves.",
        common_mistakes="Treating Market Cap as 'the value of the company' — it ignores the capital structure entirely.",
        related_concepts=("enterprise_value", "equity_value", "share_buyback"),
    ),
    "net_debt": ConceptCard(
        "net_debt", M, "Net Debt",
        "Total interest-bearing debt minus cash and cash equivalents.",
        formula="Net Debt = Total Debt (short + long term) − Cash & Equivalents",
        business_meaning="Measures the company's true leverage after accounting for the cash cushion it could use to pay debt down immediately.",
        interpretation="Negative net debt ('net cash') signals a fortress balance sheet; rising net debt alongside flat EBITDA signals deteriorating credit quality.",
        common_mistakes="Excluding operating leases or off-balance-sheet debt-like obligations from the calculation.",
        related_concepts=("enterprise_value", "capital_structure", "interest_coverage"),
    ),
    "capital_structure": ConceptCard(
        "capital_structure", M, "Capital Structure",
        "The mix of debt and equity a company uses to finance its assets and operations.",
        formula="Capital Structure = Debt / (Debt + Equity), i.e. the leverage mix",
        business_meaning="Debt is cheaper (tax-deductible interest, fixed claim) but riskier (must be repaid regardless of performance); equity is more expensive but flexible.",
        interpretation="An optimal capital structure balances the tax shield of debt against the rising cost of financial distress as leverage increases.",
        common_mistakes="Assuming more debt is always better because it is 'cheaper' — ignoring the increased risk of financial distress and reduced flexibility.",
        related_concepts=("cost_of_debt", "cost_of_equity", "wacc", "net_debt"),
    ),
    "cost_of_debt": ConceptCard(
        "cost_of_debt", M, "Cost of Debt",
        "The effective interest rate a company pays on its borrowings, after the tax shield from deductible interest.",
        formula="After-tax Cost of Debt = Pre-tax Interest Rate × (1 − Tax Rate)",
        business_meaning="Because interest is tax-deductible, debt's true cost to the company is lower than the stated coupon rate.",
        interpretation="A rising cost of debt (wider credit spreads) signals the market perceives higher default risk.",
        common_mistakes="Using the pre-tax borrowing rate directly in a WACC calculation without applying the tax shield.",
        related_concepts=("wacc", "credit_ratings", "interest_coverage", "capital_structure"),
    ),
    "cost_of_equity": ConceptCard(
        "cost_of_equity", M, "Cost of Equity",
        "The return shareholders require for bearing the risk of owning the company's stock, typically estimated via the Capital Asset Pricing Model (CAPM).",
        formula="Cost of Equity = Risk-Free Rate + Beta × Equity Risk Premium",
        business_meaning="Unlike debt, equity has no contractual coupon — its 'cost' is an opportunity cost: what investors could earn elsewhere for similar risk.",
        interpretation="Higher beta (more volatile relative to the market) or a wider risk premium (more macro uncertainty) both raise the cost of equity and, all else equal, lower valuations.",
        common_mistakes="Treating cost of equity as directly observable like a bond yield — it is always an estimate built from assumptions (beta, risk-free rate, risk premium).",
        related_concepts=("beta", "equity_risk_premium", "wacc"),
    ),
    "wacc": ConceptCard(
        "wacc", M, "Weighted Average Cost of Capital (WACC)",
        "The blended required return on a company's capital, weighting the after-tax cost of debt and the cost of equity by their share of the capital structure.",
        formula="WACC = (E/V) × Cost of Equity + (D/V) × Cost of Debt × (1 − Tax Rate), where V = D + E",
        business_meaning="WACC is the discount rate used to value the whole enterprise (both debt and equity claims) and the hurdle rate a project must clear to create value.",
        interpretation="When ROIC exceeds WACC, the company is creating economic value; when ROIC is below WACC, growth actually destroys value even if accounting profit is positive.",
        common_mistakes="Using book-value weights instead of market-value weights for debt and equity, or applying a single WACC across businesses with very different risk profiles.",
        related_concepts=("cost_of_debt", "cost_of_equity", "roic", "economic_profit", "terminal_value"),
    ),
    "beta": ConceptCard(
        "beta", M, "Beta",
        "A measure of a stock's volatility relative to the overall market — how much the stock tends to move for a given move in the market index.",
        formula="Beta = Covariance(Stock Return, Market Return) / Variance(Market Return)",
        business_meaning="Beta of 1.0 means the stock moves with the market; above 1.0 means it amplifies market moves (more cyclical/leveraged businesses); below 1.0 means it dampens them (defensive businesses).",
        interpretation="Beta rises with operating leverage and financial leverage — a company can raise its own beta simply by taking on more debt (levered vs. unlevered beta).",
        common_mistakes="Treating beta as a fixed, permanent property of a company rather than something that changes with its business mix and leverage.",
        related_concepts=("cost_of_equity", "unlevered_beta", "levered_beta", "systematic_risk"),
    ),
    "unlevered_beta": ConceptCard(
        "unlevered_beta", M, "Unlevered (Asset) Beta",
        "A company's beta stripped of the effect of financial leverage — the volatility of the underlying business alone.",
        formula="Unlevered Beta = Levered Beta / [1 + (1 − Tax Rate) × (Debt/Equity)]",
        business_meaning="Lets analysts compare the operating risk of companies with very different capital structures on a like-for-like basis, and re-lever a peer's beta to a target's capital structure.",
        interpretation="Two companies in the same industry with similar operations should have similar unlevered betas even if their levered betas differ sharply due to debt.",
        related_concepts=("beta", "levered_beta", "capital_structure"),
    ),
    "levered_beta": ConceptCard(
        "levered_beta", M, "Levered (Equity) Beta",
        "A company's observed market beta, which already reflects the amplifying effect of its financial leverage.",
        formula="Levered Beta = Unlevered Beta × [1 + (1 − Tax Rate) × (Debt/Equity)]",
        business_meaning="This is the beta actually used in the CAPM cost-of-equity formula, since equity holders bear the leverage risk directly.",
        interpretation="Adding debt to a company's capital structure mechanically raises its levered beta and therefore its cost of equity, even if the underlying business risk is unchanged.",
        related_concepts=("beta", "unlevered_beta", "cost_of_equity"),
    ),
    "equity_risk_premium": ConceptCard(
        "equity_risk_premium", M, "Equity Risk Premium (ERP)",
        "The extra return investors demand for holding stocks over a risk-free asset like a government bond.",
        formula="Equity Risk Premium = Expected Market Return − Risk-Free Rate",
        business_meaning="Compensates equity investors for bearing the higher, more uncertain risk of stock ownership versus a guaranteed government payout.",
        interpretation="ERP widens during periods of macro stress or uncertainty (investors demand more compensation for risk) and narrows in calm, low-volatility markets.",
        common_mistakes="Using a single global ERP for all markets — emerging markets typically carry a higher country-specific risk premium on top of the base ERP.",
        related_concepts=("cost_of_equity", "risk_free_rate", "beta"),
    ),
    "risk_free_rate": ConceptCard(
        "risk_free_rate", M, "Risk-Free Rate",
        "The theoretical return on an investment with zero default risk, typically proxied by a long-term government bond yield in the relevant currency.",
        business_meaning="Serves as the baseline against which every other required return (cost of equity, cost of debt, hurdle rates) is built up.",
        interpretation="Rising risk-free rates mechanically raise the cost of capital across the economy and compress valuation multiples, all else equal.",
        related_concepts=("cost_of_equity", "equity_risk_premium", "wacc", "nominal_rates"),
    ),
    "terminal_value": ConceptCard(
        "terminal_value", M, "Terminal Value",
        "The value of all cash flows a business is expected to generate beyond an explicit forecast period, capturing the vast majority of a DCF valuation.",
        formula="Terminal Value (Gordon Growth) = Final Year Cash Flow × (1 + g) / (WACC − g)",
        business_meaning="Because most businesses are expected to operate indefinitely, a finite 5-10 year forecast alone captures only a fraction of true value — terminal value fills in 'everything after'.",
        interpretation="Terminal value is highly sensitive to the assumed long-run growth rate (g) and discount rate; small changes to either can swing total valuation dramatically.",
        common_mistakes="Assuming a terminal growth rate above the long-run GDP/inflation growth rate, which implies the company eventually becomes larger than the entire economy.",
        related_concepts=("dcf", "wacc", "terminal_growth", "exit_multiple"),
    ),
    "terminal_growth": ConceptCard(
        "terminal_growth", M, "Terminal Growth Rate",
        "The perpetual growth rate assumed for cash flows beyond the explicit forecast period in a DCF's Gordon Growth terminal value.",
        business_meaning="Should be conservative and sustainable forever — typically anchored near long-run nominal GDP growth or inflation, never near the company's current high-growth rate.",
        interpretation="A terminal growth rate set too high relative to WACC can make the terminal value mathematically explode or even go negative when g approaches WACC.",
        related_concepts=("terminal_value", "dcf", "wacc"),
    ),
    "exit_multiple": ConceptCard(
        "exit_multiple", M, "Exit Multiple",
        "An alternative to Gordon Growth terminal value: applying a market-observed multiple (e.g. EV/EBITDA) to the final forecast year's metric to estimate terminal value.",
        formula="Terminal Value = Final Year EBITDA × Assumed Exit Multiple",
        business_meaning="Anchors the DCF's terminal value to real market pricing of comparable businesses rather than a purely theoretical growth-perpetuity formula.",
        interpretation="Cross-checking the implied terminal growth rate from an exit-multiple approach against the Gordon Growth approach is a standard DCF sanity check.",
        related_concepts=("terminal_value", "ev_ebitda", "dcf"),
    ),
    "nopat": ConceptCard(
        "nopat", M, "NOPAT (Net Operating Profit After Tax)",
        "Operating profit (EBIT) as if the company had no debt, taxed at the effective rate — the pure operating profit available to all capital providers.",
        formula="NOPAT = EBIT × (1 − Effective Tax Rate)",
        business_meaning="Strips out the effect of financing decisions (interest expense) so operating performance can be compared across companies with different capital structures.",
        interpretation="NOPAT is the numerator used in ROIC and Economic Profit calculations — it represents the true operating return generated for all capital invested, before financing costs.",
        common_mistakes="Confusing NOPAT with Net Income — NOPAT deliberately excludes interest expense, while Net Income includes it.",
        related_concepts=("roic", "economic_profit", "invested_capital"),
    ),
    "economic_profit": ConceptCard(
        "economic_profit", M, "Economic Profit",
        "The value a business creates above and beyond the cost of the capital it employs — profit is not 'real' economic value creation until it clears the capital charge.",
        formula="Economic Profit = NOPAT − (WACC × Invested Capital) = Invested Capital × (ROIC − WACC)",
        business_meaning="A company can be profitable on an accounting basis (positive Net Income) while destroying economic value, if its ROIC is below its WACC.",
        interpretation="Positive and growing economic profit is the clearest single signal of genuine value creation; a company can grow NOPAT while economic profit shrinks if it grows capital faster than returns.",
        common_mistakes="Equating accounting profit (Net Income, EBITDA) with value creation without checking it against the capital charge.",
        related_concepts=("nopat", "wacc", "roic", "residual_income", "eva"),
    ),
    "residual_income": ConceptCard(
        "residual_income", M, "Residual Income",
        "The equity-level analogue of Economic Profit: net income remaining after charging for the cost of equity capital employed.",
        formula="Residual Income = Net Income − (Cost of Equity × Book Value of Equity)",
        business_meaning="Recognises that equity capital is not free — a company must earn more than shareholders' required return just to justify the equity invested.",
        interpretation="Used as a valuation approach (Residual Income Model) where equity value = book value of equity + present value of future residual income.",
        related_concepts=("economic_profit", "cost_of_equity", "eva", "nopat"),
    ),
    "eva": ConceptCard(
        "eva", M, "EVA (Economic Value Added)",
        "A trademarked, standardized implementation of Economic Profit developed by Stern Stewart & Co., with specific accounting adjustments (capitalizing R&D, operating leases, etc.).",
        formula="EVA = NOPAT − (WACC × Invested Capital), with standardized adjustments to both NOPAT and Invested Capital",
        business_meaning="Designed to reduce accounting distortions (e.g. expensing R&D immediately understates invested capital) so the value-creation signal is cleaner across companies.",
        interpretation="Conceptually identical to Economic Profit; the specific adjustments matter mainly for cross-company comparability in R&D- or lease-heavy industries.",
        common_mistakes="Treating EVA as fundamentally different from Economic Profit — the core formula is the same; EVA is a specific, branded set of adjustments to it.",
        related_concepts=("economic_profit", "nopat", "invested_capital", "wacc"),
    ),
    "invested_capital": ConceptCard(
        "invested_capital", M, "Invested Capital",
        "The total capital — both debt and equity — that has been put to work in a company's operating business.",
        formula="Invested Capital = Total Debt + Total Equity − Cash & Equivalents (or equivalently, Net Working Capital + Net Fixed Assets)",
        business_meaning="The denominator for ROIC — measures how much capital shareholders and lenders have committed to generate the company's operating profit.",
        interpretation="A company can grow NOPAT while ROIC falls if invested capital grows even faster — capital efficiency, not just absolute profit growth, is what matters.",
        common_mistakes="Using Total Assets instead of Invested Capital — Total Assets includes non-interest-bearing current liabilities (like payables) that are not 'invested' capital.",
        related_concepts=("roic", "nopat", "capital_employed", "economic_profit"),
    ),
    "capital_employed": ConceptCard(
        "capital_employed", M, "Capital Employed",
        "The total long-term capital used to generate a company's returns — typically Total Assets minus Current Liabilities, or equivalently Equity plus Non-Current (Long-Term) Liabilities.",
        formula="Capital Employed = Total Assets − Current Liabilities",
        business_meaning="Used as the denominator for ROCE (Return on Capital Employed), a widely used capital-efficiency ratio, especially outside the US.",
        interpretation="Very close conceptually to Invested Capital but calculated slightly differently — ROCE and ROIC are often near each other in practice but not identical.",
        related_concepts=("invested_capital", "roic"),
    ),
    "incremental_roic": ConceptCard(
        "incremental_roic", M, "Incremental ROIC",
        "The return generated on the newest, marginal dollar of capital reinvested into the business — not the average return on all capital already deployed.",
        formula="Incremental ROIC = Change in NOPAT / Change in Invested Capital (period over period)",
        business_meaning="A company's average ROIC can look attractive purely from a legacy, highly profitable core business, while every new dollar of growth capex earns far less — incremental ROIC exposes this.",
        interpretation="If incremental ROIC is well below the company's WACC, continued reinvestment is destroying value even though the historical/average ROIC still looks healthy.",
        common_mistakes="Relying only on average/trailing ROIC to judge whether a company's growth investments are creating value.",
        related_concepts=("roic", "economic_profit", "reinvestment_rate", "growth_capex"),
    ),
    "cash_conversion_cycle": ConceptCard(
        "cash_conversion_cycle", M, "Cash Conversion Cycle (CCC)",
        "The number of days it takes a company to convert its investments in inventory and other resources into cash flow from sales.",
        formula="CCC = Days Inventory Outstanding + Days Sales Outstanding − Days Payable Outstanding",
        business_meaning="A shorter (or negative) cycle means the company is funded by its suppliers and customers rather than needing its own working capital — a structural cash advantage.",
        interpretation="A lengthening CCC over time signals working-capital strain even if revenue and profit both look healthy — cash is getting tied up for longer.",
        industry_exceptions="Retailers and quick-service businesses can run negative CCCs (they collect cash from customers before paying suppliers), which is a significant funding advantage.",
        related_concepts=("inventory_days", "receivable_days", "payable_days", "working_capital"),
    ),
    "working_capital": ConceptCard(
        "working_capital", M, "Working Capital",
        "The capital tied up in day-to-day operations: current assets (receivables, inventory) minus current liabilities (payables).",
        formula="Working Capital = Current Assets − Current Liabilities (Net Working Capital typically excludes cash and short-term debt)",
        business_meaning="Determines how much cash is locked up funding operations versus available for investment, debt repayment, or shareholder returns.",
        interpretation="A company can be profitable on the Income Statement yet run into a cash crunch if working capital keeps expanding faster than profit.",
        related_concepts=("cash_conversion_cycle", "working_capital_absorption", "working_capital_release"),
    ),
    "maintenance_capex": ConceptCard(
        "maintenance_capex", M, "Maintenance Capex",
        "Capital expenditure required simply to keep existing assets operating at their current capacity — replacing worn-out equipment, not expanding the business.",
        business_meaning="Represents the 'true cost of staying in business' — cash flow after only maintenance capex (not total capex) better approximates sustainable owner earnings.",
        interpretation="A company reporting strong free cash flow while under-spending on maintenance capex may be borrowing performance from the future via a deteriorating asset base.",
        common_mistakes="Assuming Depreciation & Amortization is always a good proxy for maintenance capex — in inflationary or growing-asset-base environments the two can diverge significantly.",
        related_concepts=("growth_capex", "owner_earnings", "free_cash_flow", "capex_intensity"),
    ),
    "growth_capex": ConceptCard(
        "growth_capex", M, "Growth Capex",
        "Capital expenditure aimed at expanding capacity, entering new markets, or launching new products — investment beyond what is needed to sustain current operations.",
        business_meaning="Whether growth capex creates value depends entirely on the incremental ROIC it earns relative to the company's WACC.",
        interpretation="High growth capex alongside declining incremental ROIC is a red flag for capital discipline, even if reported revenue growth looks strong.",
        related_concepts=("maintenance_capex", "incremental_roic", "reinvestment_rate", "capex_intensity"),
    ),
    "npv": ConceptCard(
        "npv", M, "Net Present Value (NPV)",
        "The sum of all a project's future cash flows, discounted back to today's value at the company's required rate of return, minus the initial investment.",
        formula="NPV = Σ [Cash Flow_t / (1 + r)^t] − Initial Investment",
        business_meaning="A positive NPV project is expected to create value in excess of its cost of capital; a negative NPV project destroys value even if it is 'profitable' in a simple accounting sense.",
        interpretation="NPV is the theoretically correct capital-budgeting decision rule because it directly measures value creation, unlike payback period or simple accounting return metrics.",
        related_concepts=("irr", "hurdle_rate", "wacc", "economic_profit"),
    ),
    "irr": ConceptCard(
        "irr", M, "Internal Rate of Return (IRR)",
        "The discount rate at which a project's or investment's Net Present Value equals exactly zero.",
        business_meaning="Represents the annualized return the investment is expected to generate — compared against the hurdle rate to decide whether to proceed.",
        interpretation="A project should be accepted if IRR exceeds the hurdle rate (typically WACC); IRR can give misleading rankings versus NPV when comparing mutually exclusive projects of different sizes.",
        common_mistakes="Using IRR alone to rank projects of very different scale — a small project can have a higher IRR but create far less absolute value than a larger one.",
        related_concepts=("npv", "hurdle_rate", "wacc"),
    ),
    "hurdle_rate": ConceptCard(
        "hurdle_rate", M, "Hurdle Rate",
        "The minimum acceptable rate of return a company requires before committing capital to a project or investment.",
        business_meaning="Typically set at or above WACC, sometimes with a risk premium added for riskier projects — it is the bar new investment must clear to be worth pursuing.",
        interpretation="Setting the hurdle rate too low leads to over-investment in value-destroying projects; too high causes the company to pass on genuinely value-creating opportunities.",
        related_concepts=("wacc", "npv", "irr", "incremental_roic"),
    ),
}
