"""Alternative Data Registry — Phase 1 high-signal datasets."""

from __future__ import annotations

from typing import Any

from knowledge_factory.alternative_data_intelligence.schema import (
    IADI_VERSION,
    PHASE_1_DATASETS,
    PHASE_1_DOMAINS,
    PHASE_2_EXTENSIBLE_DATASETS,
)

DATASET_REGISTRY: dict[str, dict[str, Any]] = {
    "upi_transactions": {
        "name": "UPI Transaction Volumes",
        "provider": "NPCI",
        "description": "Unified Payments Interface transaction count — digital consumer activity proxy.",
        "domain": "payments",
        "frequency": "monthly",
        "coverage": "india_national",
        "unit": "million_transactions",
        "company_links": ["HDFCBANK", "ICICIBANK", "SBIN", "PAYTM", "BAJFINANCE"],
        "industry_links": ["private_banks", "psu_banks", "nbfc", "retail", "consumer_internet"],
        "sector_links": ["banks", "financial_services", "retail"],
        "macro_links": ["consumption", "liquidity"],
        "government_links": ["RBI", "NPCI"],
        "relationship_hints": ["upi", "digital_payments", "retail"],
        "source_priority": "npci",
        "confidence": 0.92,
    },
    "electricity_demand": {
        "name": "All-India Electricity Demand",
        "provider": "Grid India / POSOCO",
        "description": "System electricity demand — industrial and broader economic activity proxy.",
        "domain": "energy",
        "frequency": "monthly",
        "coverage": "india_national",
        "unit": "bu_or_index",
        "company_links": ["NTPC", "POWERGRID", "SIEMENS", "ABB", "LT"],
        "industry_links": ["power_generation", "capital_goods", "engineering", "aluminium", "cement"],
        "sector_links": ["power", "industrials"],
        "macro_links": ["gdp", "industrial_activity"],
        "government_links": ["Ministry of Power"],
        "relationship_hints": ["electricity", "power_demand"],
        "source_priority": "posoco_grid_india",
        "confidence": 0.9,
    },
    "iip_manufacturing": {
        "name": "IIP Manufacturing",
        "provider": "MOSPI",
        "description": "Index of Industrial Production — manufacturing (public government series; PMI licensing deferred).",
        "domain": "manufacturing",
        "frequency": "monthly",
        "coverage": "india_national",
        "unit": "index",
        "company_links": ["TATASTEEL", "JSWSTEEL", "ULTRACEMCO", "SIEMENS", "LT"],
        "industry_links": ["steel", "cement", "capital_goods", "passenger_vehicles", "specialty_chem"],
        "sector_links": ["industrials", "materials"],
        "macro_links": ["gdp", "industrial_activity"],
        "government_links": ["MOSPI"],
        "relationship_hints": ["manufacturing", "iip"],
        "source_priority": "mospi",
        "confidence": 0.9,
        "notes": "Phase 1 uses MOSPI IIP rather than licensed S&P PMI.",
    },
    "railway_freight": {
        "name": "Railway Freight Loading",
        "provider": "Indian Railways",
        "description": "Freight loading volumes — bulk logistics, coal, steel, cement activity.",
        "domain": "transport",
        "frequency": "monthly",
        "coverage": "india_national",
        "unit": "mt_or_index",
        "company_links": ["COALINDIA", "TATASTEEL", "JSWSTEEL", "CONCOR", "LT"],
        "industry_links": ["logistics", "steel", "cement", "power_generation"],
        "sector_links": ["logistics", "materials", "energy"],
        "macro_links": ["gdp", "industrial_activity"],
        "government_links": ["Indian Railways", "Ministry of Railways"],
        "relationship_hints": ["rail_freight", "logistics"],
        "source_priority": "indian_railways",
        "confidence": 0.88,
    },
    "port_cargo": {
        "name": "Major Port Cargo Throughput",
        "provider": "Ministry of Ports / IPA",
        "description": "Major port cargo volumes — trade and logistics activity.",
        "domain": "transport",
        "frequency": "monthly",
        "coverage": "india_major_ports",
        "unit": "mt_or_index",
        "company_links": ["ADANIPORTS", "CONCOR", "GESHIP"],
        "industry_links": ["logistics", "shipping", "trade"],
        "sector_links": ["logistics", "industrials"],
        "macro_links": ["trade", "exports", "imports"],
        "government_links": ["Ministry of Commerce", "Ministry of Ports"],
        "relationship_hints": ["port_cargo", "trade_policy"],
        "source_priority": "ministry_ports",
        "confidence": 0.88,
    },
    "vehicle_registrations": {
        "name": "Vehicle Registrations (VAHAN aggregates)",
        "provider": "VAHAN / MoRTH",
        "description": "Aggregated vehicle registration activity — auto demand leading indicator.",
        "domain": "consumer",
        "frequency": "monthly",
        "coverage": "india_national",
        "unit": "units_or_index",
        "company_links": ["MARUTI", "M&M", "TATAMOTORS", "BAJAJ-AUTO", "EICHERMOT"],
        "industry_links": ["passenger_vehicles", "two_wheelers", "commercial_vehicles"],
        "sector_links": ["auto"],
        "macro_links": ["consumption", "credit"],
        "government_links": ["MoRTH"],
        "relationship_hints": ["vehicle_sales", "auto_demand"],
        "source_priority": "vahan_morth",
        "confidence": 0.85,
    },
    "air_passengers_domestic": {
        "name": "Domestic Air Passengers",
        "provider": "DGCA",
        "description": "Domestic air passenger traffic — travel and higher-income consumer mobility.",
        "domain": "consumer",
        "frequency": "monthly",
        "coverage": "india_domestic",
        "unit": "million_passengers",
        "company_links": ["INDIGO", "INDHOTEL", "IRCTC"],
        "industry_links": ["airlines", "hotels", "tourism"],
        "sector_links": ["consumer_discretionary", "travel"],
        "macro_links": ["consumption"],
        "government_links": ["DGCA", "Ministry of Civil Aviation"],
        "relationship_hints": ["air_travel", "oil_sensitivity"],
        "source_priority": "dgca",
        "confidence": 0.9,
    },
    "bank_credit_growth": {
        "name": "Scheduled Bank Credit Growth",
        "provider": "RBI",
        "description": "Bank credit growth — credit cycle and financing conditions.",
        "domain": "banking",
        "frequency": "monthly",
        "coverage": "india_scheduled_banks",
        "unit": "yoy_percent",
        "company_links": ["HDFCBANK", "ICICIBANK", "SBIN", "KOTAKBANK", "BAJFINANCE"],
        "industry_links": ["private_banks", "psu_banks", "nbfc", "housing_finance"],
        "sector_links": ["banks", "financial_services"],
        "macro_links": ["credit", "liquidity", "repo_rate"],
        "government_links": ["RBI"],
        "relationship_hints": ["credit_dependency", "interest_rate_sensitivity"],
        "source_priority": "rbi",
        "confidence": 0.92,
    },
    "rainfall_monsoon": {
        "name": "All-India Rainfall / Monsoon Progress",
        "provider": "IMD",
        "description": "Rainfall vs LPA — agriculture, rural demand, and reservoir outlook.",
        "domain": "agriculture",
        "frequency": "monthly",
        "coverage": "india_national",
        "unit": "percent_of_lpa",
        "company_links": ["RALLIS", "COROMANDEL", "M&M", "BRITANNIA"],
        "industry_links": ["fertilisers", "agrochemicals", "tractors", "fmcg", "sugar"],
        "sector_links": ["agriculture", "fmcg"],
        "macro_links": ["rural_demand", "inflation"],
        "government_links": ["IMD", "Ministry of Agriculture"],
        "relationship_hints": ["monsoon", "agriculture"],
        "source_priority": "imd",
        "confidence": 0.9,
    },
    "gst_collections": {
        "name": "GST Gross Collections",
        "provider": "GSTN / MoF published aggregates",
        "description": "Published GST collection aggregates — formal economy and consumption proxy.",
        "domain": "trade",
        "frequency": "monthly",
        "coverage": "india_national",
        "unit": "inr_crore_or_index",
        "company_links": ["HINDUNILVR", "RELIANCE", "TITAN", "DMART"],
        "industry_links": ["fmcg", "retail", "passenger_vehicles", "consumer_durables"],
        "sector_links": ["consumer", "retail"],
        "macro_links": ["consumption", "government_spending"],
        "government_links": ["GST_COUNCIL", "MOF"],
        "relationship_hints": ["gst", "consumption"],
        "source_priority": "gstn_mof",
        "confidence": 0.9,
    },
}


def registry_snapshot() -> dict[str, Any]:
    return {
        "version": IADI_VERSION,
        "delivery_phase": "phase_1_high_signal",
        "phase_1_datasets": list(PHASE_1_DATASETS),
        "phase_1_domains": list(PHASE_1_DOMAINS),
        "phase_2_extensible": list(PHASE_2_EXTENSIBLE_DATASETS),
        "registry": {k: dict(v) for k, v in DATASET_REGISTRY.items()},
        "n_phase_1": len(PHASE_1_DATASETS),
        "data_source_priority": [
            "npci",
            "rbi",
            "mospi",
            "ministry_of_power",
            "posoco_grid_india",
            "indian_railways",
            "ministry_of_commerce",
            "gstn_published",
            "dgca",
            "ministry_of_agriculture",
            "imd",
            "government_open_data",
        ],
        "notes": "Phase 1 only — expand after ingestion/validation/replay proven.",
    }
