"""Institutional Knowledge Graph (IKG) V1 — schema constants."""

from __future__ import annotations

IKG_VERSION = "1.0.0"
PROGRAMME = "AGIB_INSTITUTIONAL_KNOWLEDGE_GRAPH"
PROGRAMME_SHORT = "IKG"
ARCHITECTURE_STATUS = "v1.0.1 LOCKED"
PRIMARY_QUESTION = "What is connected?"

PIPELINE = [
    "Official Filings",
    "FIL",
    "FDI",
    "MII",
    "ACI",
    "EIL",
    "PIL",
    "CIG",
    "INSTITUTIONAL KNOWLEDGE GRAPH",
    "Institutional Analysts",
    "Investment Committee",
    "Portfolio Intelligence",
    "Forecast Intelligence",
    "CIO",
    "Research Writer",
    "ACS",
    "IRS",
    "Production",
]

NODE_TYPES = (
    "company",
    "person",
    "director",
    "founder",
    "product",
    "brand",
    "customer",
    "supplier",
    "country",
    "industry",
    "sector",
    "technology",
    "patent",
    "currency",
    "commodity",
    "interest_rate",
    "inflation",
    "government",
    "central_bank",
    "regulator",
    "exchange",
    "competitor",
    "partner",
    "acquisition",
    "subsidiary",
    "index",
    "etf",
    "portfolio_holding",
    "research_report",
    "filing",
    "committee_decision",
    "analyst_opinion",
    "thesis",
    "event",
)

EDGE_TYPES = (
    "owns",
    "supplies",
    "competes_with",
    "customer_of",
    "partner_of",
    "regulated_by",
    "depends_on",
    "exports_to",
    "imports_from",
    "acquired",
    "merged",
    "invests_in",
    "shares_director",
    "shares_customer",
    "shares_supplier",
    "affected_by",
    "drives",
    "subsidiary_of",
    "board_of",
    "ceo_of",
    "produces",
    "listed_on",
    "member_of",
    "thesis_of",
    "decided_on",
    # Phase 3 IKI soft expansion (in-process framework judgement graph)
    "REQUIRES",
    "SUPPORTED_BY",
    "CONFLICTS_WITH",
    "APPLIES_TO",
    "INVALIDATED_BY",
    "COMPETES_WITH",
    "ALTERNATIVE_TO",
)

NO_REDESIGN = (
    "engine",
    "ui",
    "provider",
    "filing_intelligence",
    "filing_diff",
    "management_intelligence",
    "accounting_intelligence",
    "evidence_intelligence",
    "peer_intelligence",
    "causal_intelligence",
    "forecast_intelligence",
    "portfolio_intelligence",
    "institutional_analysts",
    "investment_committee",
    "cio",
    "research_writer",
    "certification",
    "regression",
    "institutional_stack",
)
