"""Sector DNA — how industries behave (institutional identity, not statistics)."""

from __future__ import annotations

from typing import Any

from knowledge_factory.sector_intelligence.schema import SECTOR_UNIVERSE

# Sensitivity: -2 (strong negative) … +2 (strong positive)
_DNA: dict[str, dict[str, Any]] = {
    "it_services": {
        "display_name": "IT Services",
        "business_model": "Asset-light, export-oriented, human-capital intensive services",
        "capital_intensity": "low",
        "operating_leverage": "moderate_high",
        "asset_intensity": "low",
        "margin_profile": "high_teens_to_mid_twenties_ebit",
        "growth_drivers": ["digital_transformation", "ai_adoption", "large_deal_pipeline", "cloud_migration"],
        "valuation_drivers": ["earnings_growth", "margin_stability", "deal_tcv", "usd_inr"],
        "economic_sensitivity": 1,
        "interest_rate_sensitivity": 0,
        "inflation_sensitivity": -1,
        "fx_sensitivity": 2,  # USD revenue / INR cost
        "commodity_sensitivity": 0,
        "labour_sensitivity": 2,
        "regulatory_sensitivity": 0,
        "technology_disruption_risk": "moderate",
        "competitive_structure": "oligopoly_global_plus_midcap_challengers",
        "industry_maturity": "mature_growth",
        "historical_characteristics": [
            "Rerates ahead of earnings acceleration in tech spending cycles",
            "Sensitive to US recession expectations",
            "Outperforms during global IT budget expansion",
        ],
        "common_accounting_risks": ["revenue_recognition_milestones", "capitalised_costs", "forex_translation"],
        "preferred_frameworks": ["pe", "ev_ebitda", "dcf_stable"],
        "alternative_frameworks": ["peg", "ev_sales_growth"],
        "forbidden_frameworks": ["book_value_primary"],
        "preferred_mental_models": ["franchise_quality", "operating_leverage", "client_concentration"],
    },
    "banks": {
        "display_name": "Banks",
        "business_model": "Spread business — deposit franchise funding loans; capital is the constraint",
        "capital_intensity": "high_regulatory_capital",
        "operating_leverage": "moderate",
        "asset_intensity": "high",
        "margin_profile": "nim_driven",
        "growth_drivers": ["credit_growth", "deposit_franchise", "fee_income", "asset_quality"],
        "valuation_drivers": ["roe", "pb", "nim", "slippages", "capital_adequacy"],
        "economic_sensitivity": 2,
        "interest_rate_sensitivity": 2,
        "inflation_sensitivity": 1,
        "fx_sensitivity": 0,
        "commodity_sensitivity": 0,
        "labour_sensitivity": 0,
        "regulatory_sensitivity": 2,
        "technology_disruption_risk": "moderate",
        "competitive_structure": "regulated_oligopoly",
        "industry_maturity": "mature",
        "historical_characteristics": [
            "PB tracks ROE through credit cycles",
            "Asset-quality shocks dominate drawdowns",
            "Rate hiking cycles reprice NIMs with lag",
        ],
        "common_accounting_risks": ["npa_recognition", "provisioning", "restructuring_optics"],
        "preferred_frameworks": ["residual_income", "pb", "roe"],
        "alternative_frameworks": ["justified_pb", "dividend_discount"],
        "forbidden_frameworks": ["traditional_dcf", "ev_ebitda"],
        "preferred_mental_models": ["franchise_value", "credit_cycle", "capital_as_scarce_resource"],
    },
    "nbfc": {
        "display_name": "NBFC",
        "business_model": "Wholesale/retail credit without full deposit franchise; liability-sensitive",
        "capital_intensity": "high",
        "operating_leverage": "high",
        "asset_intensity": "high",
        "margin_profile": "spread_minus_credit_cost",
        "growth_drivers": ["aum_growth", "funding_access", "credit_cost", "product_mix"],
        "valuation_drivers": ["roe", "pb", "growth", "asset_quality"],
        "economic_sensitivity": 2,
        "interest_rate_sensitivity": 2,
        "inflation_sensitivity": 1,
        "fx_sensitivity": 0,
        "commodity_sensitivity": 0,
        "labour_sensitivity": 0,
        "regulatory_sensitivity": 2,
        "technology_disruption_risk": "moderate",
        "competitive_structure": "fragmented_to_consolidating",
        "industry_maturity": "growth",
        "historical_characteristics": ["Funding shocks amplify drawdowns", "Rate cuts support spreads and volumes"],
        "common_accounting_risks": ["stage2_3_migration", "borrowing_rollover"],
        "preferred_frameworks": ["pb", "roe", "residual_income"],
        "alternative_frameworks": ["pe_growth"],
        "forbidden_frameworks": ["traditional_dcf", "ev_ebitda"],
        "preferred_mental_models": ["liability_franchise", "credit_cycle"],
    },
    "insurance": {
        "display_name": "Insurance",
        "business_model": "Long-duration liabilities + float; VNB / embedded value economics",
        "capital_intensity": "high",
        "operating_leverage": "moderate",
        "asset_intensity": "high",
        "margin_profile": "vnb_margin_driven",
        "growth_drivers": ["ape_growth", "persistency", "protection_mix", "distribution"],
        "valuation_drivers": ["iev_multiple", "vnb", "roe", "persistency"],
        "economic_sensitivity": 1,
        "interest_rate_sensitivity": 1,
        "inflation_sensitivity": 0,
        "fx_sensitivity": 0,
        "commodity_sensitivity": 0,
        "labour_sensitivity": 0,
        "regulatory_sensitivity": 2,
        "technology_disruption_risk": "moderate",
        "competitive_structure": "regulated_oligopoly",
        "industry_maturity": "growth",
        "historical_characteristics": ["Rates affect float and duration matching"],
        "common_accounting_risks": ["assumption_changes", "persistency_shock"],
        "preferred_frameworks": ["embedded_value", "pb", "roe"],
        "alternative_frameworks": ["pe"],
        "forbidden_frameworks": ["traditional_dcf_primary", "ev_ebitda"],
        "preferred_mental_models": ["float", "duration", "distribution_moat"],
    },
    "pharma": {
        "display_name": "Pharma",
        "business_model": "IP + manufacturing complex; US generics / India formulations / API mix",
        "capital_intensity": "moderate",
        "operating_leverage": "high",
        "asset_intensity": "moderate",
        "margin_profile": "mid_to_high_teens_ebitda_variable",
        "growth_drivers": ["us_launches", "india_branded", "api", "biosimilars"],
        "valuation_drivers": ["pipeline", "margins", "fda_compliance", "fx"],
        "economic_sensitivity": 0,
        "interest_rate_sensitivity": 0,
        "inflation_sensitivity": -1,
        "fx_sensitivity": 1,
        "commodity_sensitivity": 0,
        "labour_sensitivity": 1,
        "regulatory_sensitivity": 2,
        "technology_disruption_risk": "moderate",
        "competitive_structure": "fragmented_global",
        "industry_maturity": "mature_growth",
        "historical_characteristics": ["FDA actions create binary drawdowns", "Defensive in domestic cycles"],
        "common_accounting_risks": ["r_and_d_capitalisation", "inventory", "related_party"],
        "preferred_frameworks": ["pe", "ev_ebitda", "dcf"],
        "alternative_frameworks": ["ev_sales_pipeline"],
        "forbidden_frameworks": [],
        "preferred_mental_models": ["regulatory_optionality", "pipeline_option_value"],
    },
    "healthcare": {
        "display_name": "Healthcare",
        "business_model": "Hospital / diagnostics networks; capacity + ARPOB economics",
        "capital_intensity": "high",
        "operating_leverage": "high",
        "asset_intensity": "high",
        "margin_profile": "improving_with_occupancy",
        "growth_drivers": ["bed_adds", "occupancy", "case_mix", "diagnostics"],
        "valuation_drivers": ["ev_ebitda", "occupancy", "arpoeb"],
        "economic_sensitivity": 0,
        "interest_rate_sensitivity": -1,
        "inflation_sensitivity": -1,
        "fx_sensitivity": 0,
        "commodity_sensitivity": 0,
        "labour_sensitivity": 2,
        "regulatory_sensitivity": 1,
        "technology_disruption_risk": "low_moderate",
        "competitive_structure": "regional_networks",
        "industry_maturity": "growth",
        "historical_characteristics": ["Defensive demand; capex cycles matter"],
        "common_accounting_risks": ["related_party_doctor", "capex_capitalisation"],
        "preferred_frameworks": ["ev_ebitda", "dcf", "pe"],
        "alternative_frameworks": ["ev_bed"],
        "forbidden_frameworks": ["book_value_primary"],
        "preferred_mental_models": ["unit_economics", "network_density"],
    },
    "auto": {
        "display_name": "Auto",
        "business_model": "Cyclical manufacturing + brand; volume and mix driven",
        "capital_intensity": "high",
        "operating_leverage": "very_high",
        "asset_intensity": "high",
        "margin_profile": "cyclical_mid_single_to_teens",
        "growth_drivers": ["volume", "premiumisation", "exports", "ev_transition"],
        "valuation_drivers": ["volume_cycle", "margins", "ev_capex", "commodity_costs"],
        "economic_sensitivity": 2,
        "interest_rate_sensitivity": -2,  # financing demand
        "inflation_sensitivity": -1,
        "fx_sensitivity": 1,
        "commodity_sensitivity": 2,
        "labour_sensitivity": 1,
        "regulatory_sensitivity": 1,
        "technology_disruption_risk": "high",
        "competitive_structure": "oligopoly",
        "industry_maturity": "mature_cyclical",
        "historical_characteristics": ["Rate cuts unlock volumes", "Commodity spikes compress margins"],
        "common_accounting_risks": ["warranty", "dealer_incentives", "capex"],
        "preferred_frameworks": ["ev_ebitda", "pe", "dcf_cycle_normalised"],
        "alternative_frameworks": ["ev_sales"],
        "forbidden_frameworks": [],
        "preferred_mental_models": ["operating_leverage", "replacement_cycle"],
    },
    "fmcg": {
        "display_name": "FMCG",
        "business_model": "Brand + distribution moat; volume and pricing balance",
        "capital_intensity": "low_moderate",
        "operating_leverage": "moderate",
        "asset_intensity": "low",
        "margin_profile": "stable_high",
        "growth_drivers": ["rural_recovery", "premiumisation", "pricing", "distribution"],
        "valuation_drivers": ["volume_growth", "gross_margin", "brand_strength"],
        "economic_sensitivity": 0,
        "interest_rate_sensitivity": 0,
        "inflation_sensitivity": -1,  # input costs
        "fx_sensitivity": 0,
        "commodity_sensitivity": 1,
        "labour_sensitivity": 0,
        "regulatory_sensitivity": 1,
        "technology_disruption_risk": "low",
        "competitive_structure": "brand_oligopoly",
        "industry_maturity": "mature",
        "historical_characteristics": ["Defensive; rerates on volume recovery", "Inflation squeezes then pricing catches up"],
        "common_accounting_risks": ["trade_spends", "promotions"],
        "preferred_frameworks": ["pe", "ev_ebitda", "dcf"],
        "alternative_frameworks": ["ev_sales"],
        "forbidden_frameworks": [],
        "preferred_mental_models": ["brand_moat", "pricing_power"],
    },
    "utilities": {
        "display_name": "Utilities",
        "business_model": "Regulated / contracted cash flows; asset-heavy",
        "capital_intensity": "very_high",
        "operating_leverage": "moderate",
        "asset_intensity": "very_high",
        "margin_profile": "regulated_stable",
        "growth_drivers": ["capacity_adds", "regulated_returns", "renewables"],
        "valuation_drivers": ["dcf", "dividend", "regulated_roe"],
        "economic_sensitivity": 0,
        "interest_rate_sensitivity": -2,
        "inflation_sensitivity": 0,
        "fx_sensitivity": 0,
        "commodity_sensitivity": 1,
        "labour_sensitivity": 0,
        "regulatory_sensitivity": 2,
        "technology_disruption_risk": "moderate",
        "competitive_structure": "regulated",
        "industry_maturity": "mature",
        "historical_characteristics": ["Bond-proxy behaviour; rate cuts support valuations"],
        "common_accounting_risks": ["regulatory_assets", "capex_capitalisation"],
        "preferred_frameworks": ["dcf", "dividend_discount", "ev_ebitda"],
        "alternative_frameworks": ["pb_regulated"],
        "forbidden_frameworks": ["growth_saas_multiples"],
        "preferred_mental_models": ["regulated_return", "duration"],
    },
    "oil_gas": {
        "display_name": "Oil & Gas",
        "business_model": "Upstream / refining / marketing — commodity + crack spread economics",
        "capital_intensity": "very_high",
        "operating_leverage": "very_high",
        "asset_intensity": "very_high",
        "margin_profile": "commodity_cyclical",
        "growth_drivers": ["oil_price", "cracks", "volumes", "petchem"],
        "valuation_drivers": ["oil", "ev_ebitda", "normalised_earnings"],
        "economic_sensitivity": 1,
        "interest_rate_sensitivity": 0,
        "inflation_sensitivity": 1,
        "fx_sensitivity": 1,
        "commodity_sensitivity": 2,
        "labour_sensitivity": 0,
        "regulatory_sensitivity": 2,
        "technology_disruption_risk": "moderate_high",
        "competitive_structure": "oligopoly_psu_private",
        "industry_maturity": "mature_cyclical",
        "historical_characteristics": ["Oil shocks dominate", "Marketing under-recoveries in India"],
        "common_accounting_risks": ["inventory_gains", "subsidy_receivables"],
        "preferred_frameworks": ["ev_ebitda", "pe_normalised", "dcf_midcycle"],
        "alternative_frameworks": ["ev_reserves"],
        "forbidden_frameworks": [],
        "preferred_mental_models": ["commodity_cycle", "midcycle_earnings"],
    },
    "metals": {
        "display_name": "Metals",
        "business_model": "Commodity producers; price × volume minus costs",
        "capital_intensity": "very_high",
        "operating_leverage": "extreme",
        "asset_intensity": "very_high",
        "margin_profile": "highly_cyclical",
        "growth_drivers": ["metal_prices", "china_demand", "volumes"],
        "valuation_drivers": ["ev_ebitda", "midcycle", "net_debt"],
        "economic_sensitivity": 2,
        "interest_rate_sensitivity": -1,
        "inflation_sensitivity": 1,
        "fx_sensitivity": 1,
        "commodity_sensitivity": 2,
        "labour_sensitivity": 1,
        "regulatory_sensitivity": 1,
        "technology_disruption_risk": "low",
        "competitive_structure": "global_commodity",
        "industry_maturity": "mature_cyclical",
        "historical_characteristics": ["Deep drawdowns at cycle peaks", "Balance sheet quality separates survivors"],
        "common_accounting_risks": ["inventory", "impairment", "leverage"],
        "preferred_frameworks": ["ev_ebitda", "pb", "midcycle_dcf"],
        "alternative_frameworks": ["ev_capacity"],
        "forbidden_frameworks": ["peak_earnings_pe"],
        "preferred_mental_models": ["commodity_cycle", "cost_curve"],
    },
    "industrials": {
        "display_name": "Industrials / Capital Goods",
        "business_model": "Order-book / project / product industrial compounds",
        "capital_intensity": "moderate_high",
        "operating_leverage": "high",
        "asset_intensity": "moderate",
        "margin_profile": "improving_with_mix",
        "growth_drivers": ["capex_cycle", "order_inflow", "government_infra", "exports"],
        "valuation_drivers": ["order_book", "margins", "ev_ebitda"],
        "economic_sensitivity": 2,
        "interest_rate_sensitivity": -1,
        "inflation_sensitivity": -1,
        "fx_sensitivity": 1,
        "commodity_sensitivity": 1,
        "labour_sensitivity": 1,
        "regulatory_sensitivity": 1,
        "technology_disruption_risk": "moderate",
        "competitive_structure": "specialist_oligopoly",
        "industry_maturity": "cyclical_growth",
        "historical_characteristics": ["Leads private capex recovery", "Order book visibility matters"],
        "common_accounting_risks": ["percentage_completion", "working_capital"],
        "preferred_frameworks": ["ev_ebitda", "dcf", "pe"],
        "alternative_frameworks": ["ev_orderbook"],
        "forbidden_frameworks": [],
        "preferred_mental_models": ["capex_cycle", "order_book_quality"],
    },
}

# Template filler for remaining universe sectors
_TEMPLATE = {
    "capital_intensity": "moderate",
    "operating_leverage": "moderate",
    "asset_intensity": "moderate",
    "margin_profile": "sector_typical",
    "growth_drivers": ["demand", "pricing", "mix"],
    "valuation_drivers": ["earnings", "margins", "growth"],
    "economic_sensitivity": 1,
    "interest_rate_sensitivity": 0,
    "inflation_sensitivity": 0,
    "fx_sensitivity": 0,
    "commodity_sensitivity": 0,
    "labour_sensitivity": 0,
    "regulatory_sensitivity": 1,
    "technology_disruption_risk": "moderate",
    "competitive_structure": "fragmented_to_oligopoly",
    "industry_maturity": "mature",
    "historical_characteristics": ["Cyclical with sector-specific shocks"],
    "common_accounting_risks": ["working_capital", "impairment"],
    "preferred_frameworks": ["ev_ebitda", "pe", "dcf"],
    "alternative_frameworks": ["pb"],
    "forbidden_frameworks": [],
    "preferred_mental_models": ["mean_reversion", "competitive_advantage"],
}

_EXTRAS: dict[str, dict[str, Any]] = {
    "auto_ancillary": {
        "display_name": "Auto Ancillary",
        "business_model": "OEM-tied component manufacturing; content-per-vehicle + exports",
        "preferred_frameworks": ["ev_ebitda", "pe", "dcf"],
        "forbidden_frameworks": [],
        "interest_rate_sensitivity": -1,
        "commodity_sensitivity": 1,
        "economic_sensitivity": 2,
    },
    "capital_goods": {
        "display_name": "Capital Goods",
        "business_model": "Long-cycle equipment and project systems tied to capex",
        "preferred_frameworks": ["ev_ebitda", "dcf", "pe"],
        "interest_rate_sensitivity": -1,
        "economic_sensitivity": 2,
    },
    "infrastructure": {
        "display_name": "Infrastructure",
        "business_model": "Asset ownership / EPC with concession or annuity cash flows",
        "preferred_frameworks": ["dcf", "ev_ebitda", "dividend_discount"],
        "interest_rate_sensitivity": -2,
    },
    "real_estate": {
        "display_name": "Real Estate",
        "business_model": "Development / rental; inventory and pre-sales economics",
        "preferred_frameworks": ["nav", "pe", "dcf"],
        "forbidden_frameworks": ["ev_ebitda_primary_developers"],
        "interest_rate_sensitivity": -2,
        "economic_sensitivity": 2,
    },
    "mining": {
        "display_name": "Mining",
        "business_model": "Resource extraction; volume × realisation minus stripping costs",
        "preferred_frameworks": ["ev_ebitda", "pb", "midcycle_dcf"],
        "forbidden_frameworks": ["peak_earnings_pe"],
        "commodity_sensitivity": 2,
    },
    "power": {
        "display_name": "Power",
        "business_model": "Generation / transmission with PPAs or merchant exposure",
        "preferred_frameworks": ["dcf", "ev_ebitda", "dividend_discount"],
        "interest_rate_sensitivity": -2,
    },
    "telecom": {
        "display_name": "Telecom",
        "business_model": "Network utility; ARPU × subs minus spectrum/capex",
        "preferred_frameworks": ["ev_ebitda", "dcf", "pe"],
        "forbidden_frameworks": ["book_value_primary"],
        "regulatory_sensitivity": 2,
        "capital_intensity": "very_high",
    },
    "consumer": {
        "display_name": "Consumer Discretionary",
        "business_model": "Discretionary brands and experiences",
        "preferred_frameworks": ["pe", "ev_ebitda", "dcf"],
        "interest_rate_sensitivity": -1,
        "economic_sensitivity": 2,
    },
    "retail": {
        "display_name": "Retail",
        "business_model": "Store / online throughput; SSSG and margins",
        "preferred_frameworks": ["pe", "ev_ebitda", "ev_sales"],
        "interest_rate_sensitivity": -1,
        "economic_sensitivity": 2,
    },
    "chemicals": {
        "display_name": "Chemicals",
        "business_model": "Specialty / commodity chemical manufacturing",
        "preferred_frameworks": ["ev_ebitda", "pe", "dcf"],
        "commodity_sensitivity": 2,
    },
    "cement": {
        "display_name": "Cement",
        "business_model": "Regional oligopoly; volume × realisation minus power/fuel",
        "preferred_frameworks": ["ev_ebitda", "pe", "replacement_cost"],
        "commodity_sensitivity": 1,
        "economic_sensitivity": 2,
        "interest_rate_sensitivity": -1,
    },
    "textiles": {
        "display_name": "Textiles",
        "business_model": "Fibre-to-garment; export and domestic mix",
        "preferred_frameworks": ["pe", "ev_ebitda"],
        "fx_sensitivity": 1,
    },
    "logistics": {
        "display_name": "Logistics",
        "business_model": "Transport / aviation / supply-chain networks",
        "preferred_frameworks": ["ev_ebitda", "pe", "dcf"],
        "economic_sensitivity": 2,
        "oil_sensitivity_note": "fuel_cost_critical",
        "commodity_sensitivity": 1,
    },
    "media": {
        "display_name": "Media",
        "business_model": "Attention / subscription / advertising",
        "preferred_frameworks": ["ev_sales", "pe", "dcf"],
        "forbidden_frameworks": ["book_value_primary"],
    },
    "internet": {
        "display_name": "Internet / Consumer Internet",
        "business_model": "Platform / marketplace; growth and unit economics first",
        "preferred_frameworks": ["ev_sales", "revenue_multiple", "growth"],
        "alternative_frameworks": ["rule_of_40"],
        "forbidden_frameworks": ["book_value_primary", "traditional_graham"],
        "industry_maturity": "growth",
        "technology_disruption_risk": "high",
    },
}


def sector_dna(sector: str) -> dict[str, Any]:
    from knowledge_factory.sector_intelligence.schema import canonicalize

    key = canonicalize(sector) or sector
    if key in _DNA:
        base = dict(_DNA[key])
    else:
        extra = _EXTRAS.get(key, {})
        base = {**_TEMPLATE, **extra}
        base.setdefault("display_name", key.replace("_", " ").title())
        base.setdefault("business_model", f"{base['display_name']} institutional business model")
    base["sector"] = key
    # Completeness score
    required = (
        "business_model",
        "preferred_frameworks",
        "forbidden_frameworks",  # may be empty list (= none forbidden)
        "growth_drivers",
        "valuation_drivers",
        "interest_rate_sensitivity",
        "inflation_sensitivity",
    )
    ok = 0
    for r in required:
        val = base.get(r)
        if val is None:
            continue
        if isinstance(val, list) and r != "forbidden_frameworks" and not val:
            continue
        ok += 1
    base["dna_completeness"] = round(100.0 * ok / len(required), 2)
    return base


def all_sector_dna() -> dict[str, dict[str, Any]]:
    return {s: sector_dna(s) for s in SECTOR_UNIVERSE}
