"""Research Golden 25 — permanent fixed regression suite for Research Intelligence.

Never changes. Covers annual reports, earnings calls, management, guidance,
events, and cross-document synthesis. Engine-only (pre-KUL).
"""

from __future__ import annotations

from typing import Any, Dict, List

from ask_product_test.research_intelligence_acceptance_v1 import evaluate_ri_case

RESEARCH_GOLDEN_25: List[Dict[str, Any]] = [
    # Annual reports (5)
    {
        "id": "RG25-AR01",
        "section": "annual_reports",
        "category": "Annual Reports",
        "prompt": "Explain Reliance's business segments from the annual report.",
        "entity": "reliance",
        "must_any": ["segment", "retail", "digital", "o2c", "annual"],
        "expect_modules": ["annual_report"],
        "fields_any": ["summary", "annual_report"],
    },
    {
        "id": "RG25-AR02",
        "section": "annual_reports",
        "category": "Annual Reports",
        "prompt": "How does TCS describe its business model?",
        "entity": "tcs",
        "must_any": ["business", "strategy", "service", "client"],
        "expect_modules": ["annual_report"],
        "fields_any": ["summary", "annual_report"],
    },
    {
        "id": "RG25-AR03",
        "section": "annual_reports",
        "category": "Annual Reports",
        "prompt": "What strategic priorities did Infosys discuss in annual reports?",
        "entity": "infosys",
        "must_any": ["strategy", "priority", "theme"],
        "expect_modules": ["annual_report"],
        "fields_any": ["summary"],
    },
    {
        "id": "RG25-AR04",
        "section": "annual_reports",
        "category": "Annual Reports",
        "prompt": "What risks did HDFC Bank highlight in the annual report?",
        "entity": "hdfc_bank",
        "must_any": ["risk", "credit", "bank", "annual"],
        "expect_modules": ["annual_report"],
        "fields_any": ["summary"],
    },
    {
        "id": "RG25-AR05",
        "section": "annual_reports",
        "category": "Annual Reports",
        "prompt": "Explain Asian Paints' capital allocation priorities from annual reports.",
        "entity": "asian_paints",
        "must_any": ["capital", "allocat", "annual"],
        "expect_modules": ["annual_report"],
        "fields_any": ["summary"],
    },
    # Earnings calls (5)
    {
        "id": "RG25-TX01",
        "section": "transcripts",
        "category": "Earnings Calls",
        "prompt": "Structure management commentary from Reliance's latest earnings transcript.",
        "entity": "reliance",
        "must_any": ["management", "commentary", "transcript"],
        "expect_modules": ["transcript"],
        "fields_any": ["summary", "transcript"],
    },
    {
        "id": "RG25-TX02",
        "section": "transcripts",
        "category": "Earnings Calls",
        "prompt": "What demand commentary appears in TCS earnings calls?",
        "entity": "tcs",
        "must_any": ["demand", "commentary"],
        "expect_modules": ["transcript"],
        "fields_any": ["summary"],
    },
    {
        "id": "RG25-TX03",
        "section": "transcripts",
        "category": "Earnings Calls",
        "prompt": "Explain margin commentary in Infosys transcripts.",
        "entity": "infosys",
        "must_any": ["margin", "commentary"],
        "expect_modules": ["transcript"],
        "fields_any": ["summary"],
    },
    {
        "id": "RG25-TX04",
        "section": "transcripts",
        "category": "Earnings Calls",
        "prompt": "What analyst Q&A themes appear for HDFC Bank?",
        "entity": "hdfc_bank",
        "must_any": ["analyst", "question"],
        "expect_modules": ["transcript"],
        "fields_any": ["summary"],
    },
    {
        "id": "RG25-TX05",
        "section": "transcripts",
        "category": "Earnings Calls",
        "prompt": "Track pricing commentary across Asian Paints earnings transcripts.",
        "entity": "asian_paints",
        "must_any": ["pricing", "commentary"],
        "expect_modules": ["transcript"],
        "fields_any": ["summary"],
    },
    # Management (4)
    {
        "id": "RG25-MG01",
        "section": "management",
        "category": "Management",
        "prompt": "Explain CEO / management philosophy for Reliance.",
        "entity": "reliance",
        "must_any": ["ceo", "philosophy", "management"],
        "expect_modules": ["management"],
        "fields_any": ["summary", "management"],
    },
    {
        "id": "RG25-MG02",
        "section": "management",
        "category": "Management",
        "prompt": "How consistent is management communication for TCS?",
        "entity": "tcs",
        "must_any": ["consistency", "communication", "management"],
        "expect_modules": ["management"],
        "fields_any": ["summary"],
    },
    {
        "id": "RG25-MG03",
        "section": "management",
        "category": "Management",
        "prompt": "Assess capital allocation discipline of Infosys management.",
        "entity": "infosys",
        "must_any": ["capital", "allocat", "management"],
        "expect_modules": ["management"],
        "fields_any": ["summary"],
    },
    {
        "id": "RG25-MG04",
        "section": "management",
        "category": "Management",
        "prompt": "Track leadership changes for HDFC Bank.",
        "entity": "hdfc_bank",
        "must_any": ["leadership", "management"],
        "expect_modules": ["management"],
        "fields_any": ["summary"],
    },
    # Guidance (4)
    {
        "id": "RG25-GD01",
        "section": "guidance",
        "category": "Guidance",
        "prompt": "Explain revenue guidance history for TCS.",
        "entity": "tcs",
        "must_any": ["revenue", "guidance"],
        "expect_modules": ["guidance"],
        "fields_any": ["summary", "guidance"],
    },
    {
        "id": "RG25-GD02",
        "section": "guidance",
        "category": "Guidance",
        "prompt": "Explain margin guidance for Infosys.",
        "entity": "infosys",
        "must_any": ["margin", "guidance"],
        "expect_modules": ["guidance"],
        "fields_any": ["summary"],
    },
    {
        "id": "RG25-GD03",
        "section": "guidance",
        "category": "Guidance",
        "prompt": "How has management guidance evolved for HDFC Bank?",
        "entity": "hdfc_bank",
        "must_any": ["guidance", "previous", "evol"],
        "expect_modules": ["guidance"],
        "fields_any": ["summary"],
    },
    {
        "id": "RG25-GD04",
        "section": "guidance",
        "category": "Guidance",
        "prompt": "Compare Asian Paints guidance versus previous, consensus, and actual framing.",
        "entity": "asian_paints",
        "must_any": ["guidance", "previous", "consensus"],
        "expect_modules": ["guidance"],
        "fields_any": ["summary"],
    },
    # Events (3)
    {
        "id": "RG25-EV01",
        "section": "events",
        "category": "Events",
        "prompt": "Explain acquisition / major corporate events for Reliance.",
        "entity": "reliance",
        "must_any": ["acquisition", "event"],
        "expect_modules": ["events"],
        "fields_any": ["summary", "events"],
    },
    {
        "id": "RG25-EV02",
        "section": "events",
        "category": "Events",
        "prompt": "What buyback or dividend events are structured for TCS?",
        "entity": "tcs",
        "must_any": ["event", "buyback", "dividend", "capital", "structured"],
        "expect_modules": ["events"],
        "fields_any": ["summary"],
    },
    {
        "id": "RG25-EV03",
        "section": "events",
        "category": "Events",
        "prompt": "Explain management-change events for HDFC Bank.",
        "entity": "hdfc_bank",
        "must_any": ["management", "change", "event"],
        "expect_modules": ["events"],
        "fields_any": ["summary"],
    },
    # Cross-document / deep (4)
    {
        "id": "RG25-XD01",
        "section": "cross_document",
        "category": "Cross-Document",
        "prompt": "Connect annual reports, transcripts, and presentations for Reliance.",
        "entity": "reliance",
        "must_any": ["annual", "transcript", "document"],
        "expect_modules": ["cross_document"],
        "fields_any": ["summary", "cross_document"],
    },
    {
        "id": "RG25-XD02",
        "section": "cross_document",
        "category": "Cross-Document",
        "prompt": "Compare FY23/FY24 annual report chain with earnings transcripts for TCS.",
        "entity": "tcs",
        "must_any": ["annual", "transcript", "document"],
        "expect_modules": ["cross_document"],
        "fields_any": ["summary"],
    },
    {
        "id": "RG25-DR01",
        "section": "deep_research",
        "category": "Cross-Document",
        "prompt": "Summarize five years of strategy for Infosys.",
        "entity": "infosys",
        "must_any": ["strategy", "evolution", "five", "5"],
        "expect_modules": ["deep_research"],
        "fields_any": ["summary", "deep_research"],
    },
    {
        "id": "RG25-DR02",
        "section": "deep_research",
        "category": "Cross-Document",
        "prompt": "Explain capital allocation evolution for Asian Paints.",
        "entity": "asian_paints",
        "must_any": ["capital", "allocat", "evolution"],
        "expect_modules": ["deep_research"],
        "fields_any": ["summary"],
    },
]

assert len(RESEARCH_GOLDEN_25) == 25, len(RESEARCH_GOLDEN_25)


def evaluate_golden_case(case: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
    row = evaluate_ri_case(
        {
            **case,
            "policy_refuse": False,
            "fields_any": case.get("fields_any") or ["summary"],
        },
        payload,
    )
    row["suite"] = "Research Golden 25"
    return row
