"""Company analytical playbooks (12)."""

from __future__ import annotations

from institutional_playbooks.registry.models import playbook

PLAYBOOKS = [
    playbook(
        "PB_COMPANY_QUALITY",
        name="Company Quality Assessment",
        category="company",
        question_types=["Analyse", "Explain", "Assess"],
        cues=["quality", "high quality", "business quality", "franchise quality"],
        frameworks=["FW_ROIC", "FW_ROE", "FW_MOAT"],
        checklist=[
            "Economic moat durability",
            "Pricing power evidence",
            "ROIC vs WACC spread",
            "Reinvestment runway",
            "Cash conversion quality",
            "Balance sheet resilience",
            "Earnings quality",
            "Governance / related parties",
            "Capital allocation track record",
            "Competitive intensity",
        ],
        procedure=[
            "Franchise quality",
            "Returns on capital",
            "Reinvestment needs",
            "Cash conversion",
            "Balance sheet",
            "Governance",
            "Conclusion on quality tier",
        ],
        evidence_required=["financials", "annual_report", "peer_metrics", "governance"],
        knowledge_objects=["KO_COMPANY_PROFILE", "KO_RETURN_METRICS", "KO_GOVERNANCE"],
        common_mistakes=[
            "Equating growth with quality",
            "Ignoring cash conversion when ROE looks high",
            "Skipping related-party / governance red flags",
        ],
        output_structure=["Quality thesis", "Supporting checklist", "Risks to quality", "Confidence"],
        priority=70,
    ),
    playbook(
        "PB_COMPANY_MOAT",
        name="Economic Moat Analysis",
        category="company",
        question_types=["Explain", "Analyse"],
        cues=["moat", "competitive advantage", "pricing power", "switching costs", "network effects"],
        frameworks=["FW_MOAT", "FW_ROIC", "FW_PEER_COMPARISON"],
        checklist=[
            "Moat type identification",
            "Evidence of pricing power",
            "Customer switching costs",
            "Cost advantage durability",
            "Network / scale effects",
            "Threats to moat erosion",
            "ROIC sustainability",
            "Peer relative advantage",
        ],
        procedure=[
            "Identify claimed moat",
            "Test with operating evidence",
            "Map erosion risks",
            "Link to returns",
            "Peer check",
            "Conclusion",
        ],
        evidence_required=["operating_metrics", "pricing", "peer_comparison", "management_commentary"],
        knowledge_objects=["KO_MOAT", "KO_PEER_SET"],
        common_mistakes=["Labeling brand as moat without pricing evidence", "Ignoring industry disruption"],
        output_structure=["Moat thesis", "Evidence", "Erosion risks", "Conclusion"],
        priority=65,
    ),
    playbook(
        "PB_COMPANY_CAPITAL_ALLOCATION",
        name="Capital Allocation Review",
        category="company",
        question_types=["Analyse", "Explain", "Assess"],
        cues=["capital allocation", "buyback", "dividend", "m&a", "capex", "reinvestment"],
        frameworks=["FW_ROIC", "FW_CAPITAL_ALLOCATION", "FW_DCF"],
        checklist=[
            "Organic reinvestment returns",
            "Capex discipline",
            "M&A track record",
            "Dividend sustainability",
            "Buyback timing quality",
            "Balance sheet capacity",
            "Opportunity cost of cash",
            "Governance of capital decisions",
        ],
        procedure=[
            "Map uses of cash",
            "Score historical returns on each use",
            "Assess current capacity",
            "Judge alignment with ROIC opportunity set",
            "Conclusion",
        ],
        evidence_required=["cash_flow", "capex", "mna_history", "dividends"],
        knowledge_objects=["KO_CASH_FLOW", "KO_CAPITAL_HISTORY"],
        common_mistakes=["Praising buybacks while leverage rises unsustainably"],
        output_structure=["Allocation map", "Return evidence", "Risks", "IC implication"],
        priority=60,
    ),
    playbook(
        "PB_COMPANY_EARNINGS_QUALITY",
        name="Earnings Quality Checklist",
        category="company",
        question_types=["Analyse", "Assess", "Explain"],
        cues=["earnings quality", "cash earnings", "accruals", "one-off", "adjusted ebitda"],
        frameworks=["FW_EARNINGS_QUALITY", "FW_CASH_FLOW", "FW_ACCOUNTING"],
        checklist=[
            "Cash vs accrual gap",
            "One-offs / exceptional items",
            "Revenue recognition aggressiveness",
            "Working capital swings",
            "Provision adequacy",
            "Related-party earnings influence",
            "Auditor emphasis / qualifications",
            "Adjusted metric integrity",
        ],
        procedure=[
            "Reconcile profit to cash",
            "Strip adjustments",
            "Inspect notes & auditor",
            "Flag quality issues",
            "Conclusion",
        ],
        evidence_required=["cash_flow", "notes", "auditor", "earnings_release"],
        knowledge_objects=["KO_EARNINGS", "KO_NOTES"],
        common_mistakes=["Taking management adjusted EBITDA at face value"],
        output_structure=["Quality score", "Red flags", "Adjusted view", "Confidence"],
        priority=68,
    ),
    playbook(
        "PB_COMPANY_MANAGEMENT_GOVERNANCE",
        name="Management & Governance Review",
        category="company",
        question_types=["Analyse", "Assess"],
        cues=["management", "governance", "promoter", "related party", "remuneration", "board"],
        frameworks=["FW_GOVERNANCE", "FW_CAPITAL_ALLOCATION"],
        checklist=[
            "Promoter / ownership alignment",
            "Board independence",
            "Related-party transactions",
            "Remuneration vs performance",
            "Capital allocation integrity",
            "Disclosure quality",
            "Regulatory / legal overhang",
            "Succession risk",
        ],
        procedure=[
            "Ownership map",
            "Related-party scan",
            "Remuneration vs value created",
            "Disclosure quality",
            "Conclusion on agency risk",
        ],
        evidence_required=["annual_report", "related_party", "remuneration", "filings"],
        knowledge_objects=["KO_GOVERNANCE", "KO_RELATED_PARTY"],
        common_mistakes=["Ignoring related-party complexity in conglomerates"],
        output_structure=["Governance thesis", "Agency risks", "Mitigants", "IC implication"],
        priority=62,
    ),
    playbook(
        "PB_COMPANY_COMPETITIVE_POSITION",
        name="Competitive Position Assessment",
        category="company",
        question_types=["Compare", "Analyse", "Explain"],
        cues=["competitive position", "market share", "vs peers", "positioning", "rival"],
        frameworks=["FW_PEER_COMPARISON", "FW_MOAT", "FW_INDUSTRY_STRUCTURE"],
        checklist=[
            "Market share trend",
            "Relative margins",
            "Relative growth",
            "Cost position",
            "Product / service differentiation",
            "Customer concentration",
            "Capacity / utilization",
            "Competitive responses",
        ],
        procedure=[
            "Define peer set",
            "Compare operating metrics",
            "Locate cost/differentiation position",
            "Assess share momentum",
            "Conclusion",
        ],
        evidence_required=["peer_metrics", "industry_data", "company_ops"],
        knowledge_objects=["KO_PEER_SET", "KO_INDUSTRY"],
        common_mistakes=["Using wrong peer set", "Ignoring capacity cycles"],
        output_structure=["Position map", "Relative strengths", "Threats", "Conclusion"],
        priority=58,
    ),
    playbook(
        "PB_COMPANY_GROWTH_DURABILITY",
        name="Growth Durability Analysis",
        category="company",
        question_types=["Analyse", "Forecast", "Explain"],
        cues=["growth", "durable growth", "runway", "addressable market", "volume growth"],
        frameworks=["FW_DCF", "FW_ROIC", "FW_INDUSTRY_STRUCTURE"],
        checklist=[
            "TAM / SAM runway",
            "Volume vs price mix",
            "Unit economics at scale",
            "Reinvestment required for growth",
            "Competitive intensity at higher share",
            "Cyclicality overlay",
            "Management guidance credibility",
            "Historical growth quality",
        ],
        procedure=[
            "Decompose growth drivers",
            "Test durability of each driver",
            "Link to reinvestment",
            "Stress competitive response",
            "Conclusion",
        ],
        evidence_required=["segment_data", "guidance", "industry_growth", "capex"],
        knowledge_objects=["KO_GROWTH", "KO_SEGMENTS"],
        common_mistakes=["Extrapolating past growth without runway check"],
        output_structure=["Growth thesis", "Durability risks", "Implications for valuation"],
        priority=55,
    ),
    playbook(
        "PB_COMPANY_BALANCE_SHEET_STRENGTH",
        name="Balance Sheet Strength",
        category="company",
        question_types=["Analyse", "Assess", "Risk"],
        cues=["balance sheet", "leverage", "debt", "liquidity", "solvency", "net cash"],
        frameworks=["FW_BALANCE_SHEET", "FW_CREDIT", "FW_CASH_FLOW"],
        checklist=[
            "Gross / net leverage",
            "Maturity profile",
            "Interest coverage",
            "Liquidity buffer",
            "Contingent liabilities",
            "Off-balance-sheet items",
            "Asset quality (if financial)",
            "Refinancing risk",
        ],
        procedure=[
            "Map debt stack",
            "Assess coverage & liquidity",
            "Scan contingencies",
            "Stress scenario",
            "Conclusion",
        ],
        evidence_required=["balance_sheet", "notes", "cash_flow", "ratings"],
        knowledge_objects=["KO_BALANCE_SHEET", "KO_DEBT"],
        common_mistakes=["Looking only at net debt / EBITDA without maturity risk"],
        output_structure=["Solvency view", "Liquidity view", "Stress risks", "Conclusion"],
        priority=60,
    ),
    playbook(
        "PB_COMPANY_CASH_CONVERSION",
        name="Cash Conversion Analysis",
        category="company",
        question_types=["Analyse", "Assess"],
        cues=["cash conversion", "fcf", "working capital", "cash flow quality"],
        frameworks=["FW_CASH_FLOW", "FW_EARNINGS_QUALITY", "FW_ROIC"],
        checklist=[
            "CFO / PAT conversion",
            "FCF after maintenance capex",
            "Working capital intensity",
            "Capex vs growth needs",
            "Seasonality of cash",
            "One-time cash items",
            "Peer cash conversion",
        ],
        procedure=[
            "Bridge earnings to cash",
            "Separate maintenance vs growth capex",
            "Assess WC drag",
            "Peer compare",
            "Conclusion",
        ],
        evidence_required=["cash_flow", "working_capital", "capex"],
        knowledge_objects=["KO_CASH_FLOW"],
        common_mistakes=["Calling a company FCF generative while growth capex is mandatory"],
        output_structure=["Conversion score", "WC risks", "FCF durability", "Conclusion"],
        priority=57,
    ),
    playbook(
        "PB_COMPANY_SEGMENT_ANALYSIS",
        name="Segment Deep Dive",
        category="company",
        question_types=["Analyse", "Explain", "Compare"],
        cues=["segment", "business mix", "division", "subsidiary contribution"],
        frameworks=["FW_SOTP", "FW_PEER_COMPARISON", "FW_ROIC"],
        checklist=[
            "Segment revenue / profit mix",
            "Segment ROCE differentials",
            "Growth by segment",
            "Capital intensity by segment",
            "Inter-segment transfers",
            "Disclosure quality",
            "Strategic importance vs profitability",
        ],
        procedure=[
            "Map segment mix",
            "Score each segment economically",
            "Identify value / value-destroying units",
            "Implications for SOTP / strategy",
            "Conclusion",
        ],
        evidence_required=["segment_reporting", "annual_report", "notes"],
        knowledge_objects=["KO_SEGMENTS"],
        common_mistakes=["Valuing conglomerate on blended multiple only"],
        output_structure=["Segment map", "Economic ranking", "SOTP implication", "Conclusion"],
        priority=54,
    ),
    playbook(
        "PB_COMPANY_RESULTS_REACTION",
        name="Why Stock Moved After Results",
        category="company",
        question_types=["Explain", "Analyse", "Event"],
        cues=[
            "stock fell",
            "stock fall",
            "stock rose",
            "stock drop",
            "after results",
            "after good results",
            "after earnings",
            "good results",
            "beat",
            "miss",
            "selloff",
            "why did the stock",
        ],
        frameworks=["FW_EARNINGS_REACTION", "FW_HISTORICAL_VALUATION", "FW_PEER_COMPARISON"],
        checklist=[
            "Headline results vs consensus",
            "Expectation miss on key line items",
            "Guidance change",
            "Valuation already rich / cheap",
            "Positioning / crowded trade",
            "Profit booking / technicals",
            "Margin trajectory",
            "Cash flow confirmation",
            "Management commentary tone",
            "Macro overlay",
            "Sector tape",
            "Liquidity / flows",
        ],
        procedure=[
            "Results",
            "Expectation miss?",
            "Guidance?",
            "Valuation already rich?",
            "Positioning?",
            "Profit booking?",
            "Margins?",
            "Cash flow?",
            "Management commentary?",
            "Macro?",
            "Sector?",
            "Liquidity?",
            "Conclusion",
        ],
        evidence_required=[
            "earnings_release",
            "consensus",
            "guidance",
            "price_action",
            "peer_moves",
            "macro",
        ],
        knowledge_objects=["KO_EARNINGS", "KO_PRICE_ACTION", "KO_GUIDANCE"],
        common_mistakes=[
            "Assuming good results must mean stock up",
            "Ignoring starting valuation and positioning",
            "Skipping guidance and margin quality",
        ],
        output_structure=[
            "Price reaction thesis",
            "Checklist findings",
            "Primary drivers ranked",
            "What would change the view",
        ],
        priority=95,
    ),
    playbook(
        "PB_COMPANY_TURNAROUND",
        name="Turnaround / Recovery Assessment",
        category="company",
        question_types=["Analyse", "Assess"],
        cues=["turnaround", "recovery", "restructuring", "revival", "inflection"],
        frameworks=["FW_BALANCE_SHEET", "FW_EARNINGS_QUALITY", "FW_ROIC"],
        checklist=[
            "Root cause of underperformance",
            "Balance sheet runway",
            "Operating inflection evidence",
            "Management credibility",
            "Industry tailwind / headwind",
            "Dilution / restructuring risk",
            "Early leading indicators",
            "Valuation asymmetry",
        ],
        procedure=[
            "Diagnose failure mode",
            "Check survival runway",
            "Identify inflection evidence",
            "Score probability of success",
            "Conclusion",
        ],
        evidence_required=["financials", "management_actions", "industry", "capital_raise"],
        knowledge_objects=["KO_TURNAROUND", "KO_BALANCE_SHEET"],
        common_mistakes=["Calling turnaround on narrative alone without cash runway"],
        output_structure=["Diagnosis", "Inflection evidence", "Risks", "Asymmetry"],
        priority=52,
    ),
]
