"""Document review analytical playbooks (5)."""

from __future__ import annotations

from institutional_playbooks.registry.models import playbook

PLAYBOOKS = [
    playbook(
        "PB_DOC_ANNUAL_REPORT",
        name="Annual Report Review",
        category="documents",
        question_types=["Analyse", "Explain", "Document"],
        cues=[
            "annual report",
            "audited annual report",
            "read the annual report",
            "how to analyse annual",
            "sections of an annual",
            "md&a",
            "yearbook",
            "ar review",
            "investor presentation",
            "inconsistencies between",
        ],
        frameworks=["FW_ACCOUNTING", "FW_GOVERNANCE", "FW_EARNINGS_QUALITY", "FW_CAPITAL_ALLOCATION"],
        checklist=[
            "MD&A",
            "Risk Factors",
            "Auditor opinion / emphasis",
            "Notes to accounts",
            "Related party transactions",
            "Capital allocation",
            "Contingent liabilities",
            "Segment reporting",
            "Remuneration",
            "Governance",
        ],
        procedure=[
            "MDA",
            "Risk Factors",
            "Auditor",
            "Notes",
            "Related Party",
            "Capital Allocation",
            "Contingent Liabilities",
            "Segment Reporting",
            "Remuneration",
            "Governance",
            "Conclusion",
        ],
        evidence_required=[
            "annual_report",
            "auditor_report",
            "notes",
            "related_party",
            "segments",
            "remuneration",
        ],
        knowledge_objects=["KO_ANNUAL_REPORT", "KO_NOTES", "KO_GOVERNANCE"],
        common_mistakes=[
            "Reading only the glossy MD&A",
            "Skipping notes, contingencies, and related parties",
            "Ignoring auditor emphasis of matter",
        ],
        output_structure=[
            "Document checklist completed",
            "Red flags",
            "Quality of disclosure",
            "Investment implications",
        ],
        priority=97,
    ),
    playbook(
        "PB_DOC_EARNINGS_CALL",
        name="Earnings Call / Transcript Review",
        category="documents",
        question_types=["Analyse", "Explain", "Document", "Event"],
        cues=["earnings call", "conference call", "transcript", "management commentary", "q&a"],
        frameworks=["FW_EARNINGS_REACTION", "FW_EARNINGS_QUALITY"],
        checklist=[
            "Guidance language",
            "Margin commentary",
            "Demand commentary",
            "Capital allocation comments",
            "Tone vs prior quarter",
            "Q&A evasions",
            "Contradiction vs reported numbers",
            "What management avoided",
        ],
        procedure=[
            "Prepared remarks",
            "Guidance",
            "Q&A stress points",
            "Consistency with numbers",
            "Conclusion",
        ],
        evidence_required=["transcript", "earnings_release", "prior_guidance"],
        knowledge_objects=["KO_TRANSCRIPT", "KO_GUIDANCE"],
        common_mistakes=["Taking prepared remarks as complete without Q&A"],
        output_structure=["Tone", "Guidance delta", "Open questions", "Implications"],
        priority=82,
    ),
    playbook(
        "PB_DOC_FILING_NOTES",
        name="Filing Notes Deep Dive",
        category="documents",
        question_types=["Analyse", "Document", "Accounting"],
        cues=["notes to accounts", "accounting notes", "filing notes", "footnote"],
        frameworks=["FW_ACCOUNTING", "FW_EARNINGS_QUALITY"],
        checklist=[
            "Revenue recognition note",
            "Impairment / provisions",
            "Leases",
            "Taxes / deferred tax",
            "Related parties",
            "Contingencies",
            "Fair value hierarchy",
            "Changes in estimates",
        ],
        procedure=[
            "Scan material notes",
            "Flag aggressive policies",
            "Link to earnings quality",
            "Conclusion",
        ],
        evidence_required=["notes", "policies", "auditor"],
        knowledge_objects=["KO_NOTES"],
        common_mistakes=["Ignoring estimate changes that flattered earnings"],
        output_structure=["Material notes", "Quality flags", "Conclusion"],
        priority=76,
    ),
    playbook(
        "PB_DOC_AUDITOR_OPINION",
        name="Auditor Opinion Protocol",
        category="documents",
        question_types=["Analyse", "Document", "Risk"],
        cues=["auditor", "audit opinion", "emphasis of matter", "qualified opinion", "key audit"],
        frameworks=["FW_ACCOUNTING", "FW_GOVERNANCE", "FW_EARNINGS_QUALITY"],
        checklist=[
            "Opinion type",
            "Key audit matters",
            "Emphasis of matter",
            "Going concern language",
            "Internal control comments",
            "Auditor change history",
            "Implication for confidence",
        ],
        procedure=[
            "Opinion class",
            "KAMs",
            "Going concern",
            "Confidence impact",
            "Conclusion",
        ],
        evidence_required=["auditor_report", "kams", "prior_opinions"],
        knowledge_objects=["KO_AUDITOR"],
        common_mistakes=["Treating clean opinion as proof of high earnings quality"],
        output_structure=["Opinion", "KAMs", "Confidence adjustment"],
        priority=74,
    ),
    playbook(
        "PB_DOC_RELATED_PARTY_REVIEW",
        name="Related Party Transaction Review",
        category="documents",
        question_types=["Analyse", "Document", "Governance"],
        cues=["related party", "rpt", "promoter transaction", "group company"],
        frameworks=["FW_GOVERNANCE", "FW_ACCOUNTING", "FW_EARNINGS_QUALITY"],
        checklist=[
            "Parties identified",
            "Nature of transactions",
            "Pricing arm's length evidence",
            "Scale vs profits / assets",
            "Guarantees / pledges",
            "Board / audit committee oversight",
            "Recurring vs one-off",
        ],
        procedure=[
            "Map parties",
            "Quantify flows",
            "Test arm's length",
            "Agency risk",
            "Conclusion",
        ],
        evidence_required=["related_party_note", "governance", "guarantees"],
        knowledge_objects=["KO_RELATED_PARTY"],
        common_mistakes=["Ignoring guarantees and pledges outside P&L"],
        output_structure=["RPT map", "Agency score", "Implication"],
        priority=73,
    ),
]
