"""Government / policy analytical playbooks (5)."""

from __future__ import annotations

from institutional_playbooks.registry.models import playbook

PLAYBOOKS = [
    playbook(
        "PB_GOV_POLICY_CHANGE",
        name="Policy Change Impact",
        category="government",
        question_types=["Explain", "Analyse", "Event", "Government"],
        cues=["policy change", "new policy", "government announced", "reform", "policy impact"],
        frameworks=["FW_GOVERNMENT_POLICY", "FW_INDUSTRY_STRUCTURE"],
        checklist=[
            "Policy text / intent",
            "Direct beneficiaries",
            "Direct losers",
            "Implementation lag",
            "Fiscal cost",
            "Second-order effects",
            "Market already priced?",
        ],
        procedure=[
            "Parse policy",
            "Map winners / losers",
            "Lags & implementation",
            "Pricing check",
            "Conclusion",
        ],
        evidence_required=["policy_document", "fiscal", "sector_exposure", "price_action"],
        knowledge_objects=["KO_POLICY"],
        common_mistakes=["Trading the headline without implementation lag"],
        output_structure=["Policy summary", "Impact map", "Pricing", "Confidence"],
        priority=75,
    ),
    playbook(
        "PB_GOV_REGULATION_IMPACT",
        name="Regulatory Impact Assessment",
        category="government",
        question_types=["Explain", "Analyse", "Government"],
        cues=["regulation", "regulatory", "sebi", "rbi circular", "compliance cost"],
        frameworks=["FW_GOVERNMENT_POLICY", "FW_INDUSTRY_STRUCTURE", "FW_GOVERNANCE"],
        checklist=[
            "Regulatory body & instrument",
            "Scope of entities affected",
            "Compliance / capital cost",
            "Competitive redistribution",
            "Timeline",
            "Enforcement credibility",
        ],
        procedure=[
            "Identify rule",
            "Cost / constraint",
            "Competitive effects",
            "Timeline",
            "Conclusion",
        ],
        evidence_required=["circular", "compliance_cost", "sector_structure"],
        knowledge_objects=["KO_REGULATION"],
        common_mistakes=["Ignoring competitive redistribution from regulation"],
        output_structure=["Rule", "Cost", "Winners/losers", "Conclusion"],
        priority=70,
    ),
    playbook(
        "PB_GOV_BUDGET_FISCAL",
        name="Union Budget / Fiscal Read",
        category="government",
        question_types=["Explain", "Analyse", "Government"],
        cues=["budget", "union budget", "fiscal deficit", "capex push", "tax change", "gst collections", "gst"],
        frameworks=["FW_GOVERNMENT_POLICY", "FW_MACRO_TRANSMISSION"],
        checklist=[
            "Deficit / glide path",
            "Capex vs revenue spend",
            "Tax / duty changes",
            "Sector allocations",
            "Bond market implication",
            "Equity sector map",
        ],
        procedure=[
            "Fiscal arithmetic",
            "Composition of spend",
            "Tax measures",
            "Market channels",
            "Conclusion",
        ],
        evidence_required=["budget_docs", "deficit", "tax_schedule", "yields"],
        knowledge_objects=["KO_BUDGET"],
        common_mistakes=["Focusing only on sector schemes, ignoring deficit path"],
        output_structure=["Fiscal scorecard", "Sector map", "Market implication"],
        priority=72,
    ),
    playbook(
        "PB_GOV_RBI_MONETARY",
        name="RBI Monetary Policy Read",
        category="government",
        question_types=["Explain", "Analyse", "Government", "Macro"],
        cues=["rbi policy", "mpc", "monetary policy", "stance", "liquidity guidance"],
        frameworks=["FW_MACRO_TRANSMISSION", "FW_GOVERNMENT_POLICY", "FW_PB"],
        checklist=[
            "Rate decision",
            "Stance / guidance",
            "Inflation vs growth balance",
            "Liquidity tools",
            "Banking channel",
            "Equity / bond reaction logic",
        ],
        procedure=[
            "Decision",
            "Guidance",
            "Macro balance",
            "Transmission",
            "Conclusion",
        ],
        evidence_required=["mpc_statement", "inflation", "growth", "liquidity"],
        knowledge_objects=["KO_RBI"],
        common_mistakes=["Trading only the rate, ignoring stance and liquidity"],
        output_structure=["Decision", "Guidance", "Transmission", "Implications"],
        priority=78,
    ),
    playbook(
        "PB_GOV_SECTOR_POLICY",
        name="Sector-Specific Policy Lens",
        category="government",
        question_types=["Explain", "Analyse", "Government"],
        cues=["plis", "production linked", "import duty", "import duties", "subsidy", "sector policy", "doubles import"],
        frameworks=["FW_GOVERNMENT_POLICY", "FW_INDUSTRY_STRUCTURE", "FW_MOAT"],
        checklist=[
            "Instrument type (PLI/duty/subsidy)",
            "Eligibility & duration",
            "Incumbent vs new entrant effects",
            "Capex inducement quality",
            "Fiscal durability",
            "Global trade response risk",
        ],
        procedure=[
            "Instrument",
            "Incentive economics",
            "Industry structure change",
            "Durability",
            "Conclusion",
        ],
        evidence_required=["policy_scheme", "eligibility", "capex_plans", "trade"],
        knowledge_objects=["KO_SECTOR_POLICY"],
        common_mistakes=["Assuming subsidies permanently raise ROIC"],
        output_structure=["Scheme economics", "Structure change", "Durability"],
        priority=66,
    ),
]
