"""Industry analytical playbooks (8)."""

from __future__ import annotations

from institutional_playbooks.registry.models import playbook

PLAYBOOKS = [
    playbook(
        "PB_IND_BANKING_STRUCTURE",
        name="Banking Industry Structure",
        category="industry",
        question_types=["Explain", "Analyse", "Industry"],
        cues=["banking industry", "bank sector", "credit cycle", "systemic banks"],
        frameworks=["FW_INDUSTRY_STRUCTURE", "FW_MACRO_TRANSMISSION", "FW_PB"],
        sectors=["banks"],
        checklist=[
            "Credit growth cycle",
            "Deposit franchise trends",
            "NIM industry drivers",
            "Asset quality cycle",
            "Capital regime",
            "Competitive intensity (PSU vs private)",
            "Regulatory overlay",
            "Transmission from RBI policy",
        ],
        procedure=[
            "Cycle position",
            "Franchise economics",
            "Asset quality",
            "Regulation",
            "Winners / losers",
            "Conclusion",
        ],
        evidence_required=["industry_credit", "nim", "npa", "rbi", "peers"],
        knowledge_objects=["KO_BANKING_INDUSTRY"],
        common_mistakes=["Analysing one bank without cycle / franchise context"],
        output_structure=["Industry map", "Cycle call", "Stock implications"],
        priority=74,
    ),
    playbook(
        "PB_IND_IT_SERVICES",
        name="IT Services Industry Playbook",
        category="industry",
        question_types=["Explain", "Analyse", "Industry"],
        cues=["it services", "software services", "deal wins", "utilization", "digital services"],
        frameworks=["FW_INDUSTRY_STRUCTURE", "FW_EV_EBITDA", "FW_DCF"],
        sectors=["it_services"],
        checklist=[
            "Demand environment (US/EU)",
            "Deal TCV / pipeline",
            "Pricing / wage inflation",
            "Utilization & attrition",
            "Vertical mix",
            "Currency impact",
            "Competitive intensity",
            "Valuation vs growth",
        ],
        procedure=[
            "Demand",
            "Supply / talent",
            "Margins",
            "Growth quality",
            "Valuation implication",
            "Conclusion",
        ],
        evidence_required=["deal_wins", "utilization", "margins", "fx", "peers"],
        knowledge_objects=["KO_IT_INDUSTRY"],
        common_mistakes=["Ignoring wage and utilization when reading revenue growth"],
        output_structure=["Demand thesis", "Margin bridge", "Valuation"],
        priority=70,
    ),
    playbook(
        "PB_IND_HOSPITALS",
        name="Hospitals / Healthcare Ops",
        category="industry",
        question_types=["Explain", "Analyse", "Industry"],
        cues=["hospital", "healthcare", "arpo", "occupancy", "beds", "payor mix"],
        frameworks=["FW_HEALTHCARE_OPS", "FW_EV_EBITDA", "FW_INDUSTRY_STRUCTURE"],
        sectors=["hospitals"],
        checklist=[
            "Occupancy / ALOS",
            "ARPOB / case mix",
            "Payor mix",
            "Doctor engagement model",
            "Capex / bed expansion",
            "Regulatory risk",
            "Peer ops comparison",
            "Appropriate valuation framework",
        ],
        procedure=[
            "Ops metrics",
            "Unit economics",
            "Expansion plan",
            "Regulation",
            "Valuation framework",
            "Conclusion",
        ],
        evidence_required=["ops_metrics", "payor", "capex", "peers"],
        knowledge_objects=["KO_HOSPITAL_OPS"],
        common_mistakes=["Valuing hospitals like pharma manufacturers"],
        output_structure=["Ops scorecard", "Unit economics", "Valuation fit"],
        priority=72,
    ),
    playbook(
        "PB_IND_AIRLINES",
        name="Airlines Operating Playbook",
        category="industry",
        question_types=["Explain", "Analyse", "Industry"],
        cues=["airline", "aviation", "ask", "rask", "load factor", "atf", "indigo"],
        frameworks=["FW_AVIATION_OPS", "FW_INDUSTRY_STRUCTURE", "FW_BALANCE_SHEET"],
        sectors=["airlines"],
        checklist=[
            "ASK / RASK",
            "Load factor",
            "Fuel / ATF sensitivity",
            "Yield management",
            "Fleet plan & leases",
            "Balance sheet / leverage",
            "Competitive capacity",
            "Cyclical / exogenous shocks",
        ],
        procedure=[
            "Traffic & yield",
            "Cost stack",
            "Fleet & leverage",
            "Competition",
            "Conclusion",
        ],
        evidence_required=["traffic", "yield", "fuel", "fleet", "debt"],
        knowledge_objects=["KO_AIRLINE_OPS"],
        common_mistakes=["Ignoring fuel and capacity cycles in airline earnings"],
        output_structure=["Ops bridge", "Sensitivity", "Balance sheet risk"],
        priority=71,
    ),
    playbook(
        "PB_IND_CONSUMER_STAPLES",
        name="Consumer Staples Industry",
        category="industry",
        question_types=["Explain", "Analyse", "Industry"],
        cues=["fmcg", "staples", "volume growth", "rural demand", "brand strength"],
        frameworks=["FW_INDUSTRY_STRUCTURE", "FW_MOAT", "FW_DCF"],
        sectors=["consumer_staples"],
        checklist=[
            "Volume vs value growth",
            "Rural / urban split",
            "Gross margin / RM inflation",
            "Brand / distribution moat",
            "Competitive intensity",
            "Pricing power evidence",
            "Working capital",
            "Premiumization trend",
        ],
        procedure=[
            "Demand split",
            "Margin bridge",
            "Moat test",
            "Competitive map",
            "Conclusion",
        ],
        evidence_required=["volumes", "margins", "rm_costs", "distribution"],
        knowledge_objects=["KO_FMCG"],
        common_mistakes=["Reading value growth as volume strength"],
        output_structure=["Demand quality", "Margin durability", "Moat"],
        priority=64,
    ),
    playbook(
        "PB_IND_CEMENT_CYCLICAL",
        name="Cement / Materials Cycle",
        category="industry",
        question_types=["Explain", "Analyse", "Industry"],
        cues=["cement", "capacity addition", "utilization", "pricing power cement", "infra demand"],
        frameworks=["FW_INDUSTRY_STRUCTURE", "FW_EV_EBITDA", "FW_CYCLE"],
        sectors=["cement"],
        checklist=[
            "Demand (housing / infra)",
            "Capacity additions",
            "Utilization",
            "Regional pricing",
            "Cost curve (power/fuel/freight)",
            "Balance sheets in cycle",
            "Peak / trough earnings risk",
        ],
        procedure=[
            "Demand",
            "Supply / capacity",
            "Pricing",
            "Cost curve",
            "Cycle position",
            "Conclusion",
        ],
        evidence_required=["capacity", "utilization", "pricing", "costs"],
        knowledge_objects=["KO_CEMENT"],
        common_mistakes=["Capitalizing peak-cycle earnings as mid-cycle"],
        output_structure=["Cycle map", "Cost position", "Valuation caution"],
        priority=63,
    ),
    playbook(
        "PB_IND_NBFC",
        name="NBFC Credit Franchise Playbook",
        category="industry",
        question_types=["Explain", "Analyse", "Industry"],
        cues=["nbfc", "aumi", "cost of funds", "asset quality nbfc", "liability franchise"],
        frameworks=["FW_PB", "FW_ROE", "FW_CREDIT"],
        sectors=["nbfc"],
        checklist=[
            "Liability franchise / CoF",
            "Asset mix risk",
            "Asset quality / stage 2-3",
            "Capital adequacy",
            "Growth vs underwriting",
            "ALM gaps",
            "Regulatory changes",
            "Peer ROE–P/B",
        ],
        procedure=[
            "Funding",
            "Assets",
            "Quality",
            "Capital",
            "Valuation",
            "Conclusion",
        ],
        evidence_required=["cof", "aum", "asset_quality", "capital", "alm"],
        knowledge_objects=["KO_NBFC"],
        common_mistakes=["Treating all NBFCs like banks without CoF/ALM check"],
        output_structure=["Franchise quality", "Risk stack", "ROE–P/B"],
        priority=68,
    ),
    playbook(
        "PB_IND_COMPETITIVE_INTENSITY",
        name="Industry Competitive Intensity",
        category="industry",
        question_types=["Explain", "Analyse", "Industry"],
        cues=["competitive intensity", "porter", "industry structure", "barriers to entry", "pricing war"],
        frameworks=["FW_INDUSTRY_STRUCTURE", "FW_MOAT", "FW_PEER_COMPARISON"],
        checklist=[
            "Number / power of rivals",
            "Barriers to entry",
            "Buyer power",
            "Supplier power",
            "Substitution threat",
            "Pricing behavior",
            "Capacity race",
            "Regulatory barriers",
        ],
        procedure=[
            "Structure map",
            "Profit pool pressure",
            "Implications for incumbents",
            "Conclusion",
        ],
        evidence_required=["industry_structure", "pricing", "capacity", "regulation"],
        knowledge_objects=["KO_INDUSTRY"],
        common_mistakes=["Calling industry attractive without profit-pool evidence"],
        output_structure=["Structure", "Intensity score", "Stock implications"],
        priority=60,
    ),
]
