"""Investment committee thought-process playbooks (4)."""

from __future__ import annotations

from institutional_playbooks.registry.models import playbook

PLAYBOOKS = [
    playbook(
        "PB_IC_INITIATE_COVERAGE",
        name="IC Initiate / Fresh Coverage",
        category="investment_committee",
        question_types=["Analyse", "Assess", "IC", "Recommend"],
        cues=[
            "initiate coverage",
            "initiate research",
            "research coverage",
            "newly listed",
            "should we buy",
            "new position",
            "fresh look",
            "investment case",
            "before recommending that an analyst",
            "investment committee",
            "evidence package",
            "before anyone begins valuation",
            "presenting",
        ],
        frameworks=["FW_DCF", "FW_PEER_COMPARISON", "FW_MOAT", "FW_GOVERNANCE"],
        checklist=[
            "Business quality",
            "Industry structure",
            "Financial strength",
            "Earnings quality",
            "Valuation",
            "Variant perception",
            "Key risks",
            "Position sizing premise",
            "Kill criteria",
            "Evidence completeness",
        ],
        procedure=[
            "Quality",
            "Industry",
            "Financials",
            "Valuation",
            "Variant view",
            "Risks",
            "Sizing / kill criteria",
            "IC recommendation",
        ],
        evidence_required=["full_dossier", "valuation", "risks", "peers"],
        knowledge_objects=["KO_IC_MEMO"],
        common_mistakes=["Recommending without kill criteria or variant perception"],
        output_structure=["Thesis", "Variant", "Risks", "Action", "Confidence"],
        priority=88,
    ),
    playbook(
        "PB_IC_POSITION_SIZING",
        name="IC Position Sizing Protocol",
        category="investment_committee",
        question_types=["Assess", "IC", "Portfolio"],
        cues=["position size", "sizing", "how large", "portfolio weight", "conviction"],
        frameworks=["FW_PORTFOLIO", "FW_BALANCE_SHEET", "FW_PEER_COMPARISON"],
        checklist=[
            "Conviction level",
            "Downside asymmetry",
            "Liquidity",
            "Correlation / factor exposure",
            "Balance sheet tail risk",
            "Evidence completeness",
            "Governance risk haircut",
            "Max loss tolerance",
        ],
        procedure=[
            "Conviction",
            "Downside",
            "Portfolio fit",
            "Haircuts",
            "Size band",
            "Conclusion",
        ],
        evidence_required=["risk", "liquidity", "portfolio_factors", "thesis"],
        knowledge_objects=["KO_SIZING"],
        common_mistakes=["Sizing from upside alone"],
        output_structure=["Size band", "Haircuts applied", "Review triggers"],
        priority=80,
    ),
    playbook(
        "PB_IC_THESIS_CHALLENGE",
        name="IC Thesis Challenge / Red Team",
        category="investment_committee",
        question_types=["Assess", "IC", "Challenge"],
        cues=["challenge the thesis", "what could go wrong", "red team", "bear case", "disconfirm"],
        frameworks=["FW_RISK", "FW_EARNINGS_QUALITY", "FW_GOVERNANCE"],
        checklist=[
            "Primary thesis claims",
            "Disconfirming evidence",
            "Accounting / quality attack",
            "Industry structure attack",
            "Management / governance attack",
            "Valuation already prices the good news?",
            "Forced update triggers",
        ],
        procedure=[
            "State thesis crisply",
            "Attack each pillar",
            "Rank fatal risks",
            "Update or kill",
            "Conclusion",
        ],
        evidence_required=["thesis", "counter_evidence", "risks"],
        knowledge_objects=["KO_RED_TEAM"],
        common_mistakes=["Steelmanning the bull case only"],
        output_structure=["Attacks", "Survivability", "Update decision"],
        priority=86,
    ),
    playbook(
        "PB_IC_SELL_OR_HOLD",
        name="IC Sell / Hold / Trim Decision",
        category="investment_committee",
        question_types=["Assess", "IC", "Recommend"],
        cues=["should we sell", "trim", "hold or sell", "exit", "thesis broken"],
        frameworks=["FW_PEER_COMPARISON", "FW_HISTORICAL_VALUATION", "FW_PORTFOLIO"],
        checklist=[
            "Original thesis intact?",
            "Fundamentals deteriorated?",
            "Valuation stretched vs thesis?",
            "Opportunity cost / better ideas",
            "Position size vs risk",
            "Tax / friction",
            "Partial trim vs full exit",
        ],
        procedure=[
            "Thesis check",
            "Fundamentals check",
            "Valuation check",
            "Opportunity cost",
            "Action (hold / trim / sell)",
            "Conclusion",
        ],
        evidence_required=["thesis_log", "fundamentals", "valuation", "portfolio"],
        knowledge_objects=["KO_EXIT"],
        common_mistakes=["Anchoring to purchase price instead of forward thesis"],
        output_structure=["Thesis status", "Action", "Triggers for revisit"],
        priority=84,
    ),
]
