"""Macro analytical playbooks (8)."""

from __future__ import annotations

from institutional_playbooks.registry.models import playbook

PLAYBOOKS = [
    playbook(
        "PB_MACRO_RATE_TRANSMISSION",
        name="Interest Rate Transmission",
        category="macro",
        question_types=["Explain", "Analyse", "Macro"],
        cues=["interest rate", "repo", "rbi hike", "rate cut", "transmission", "cost of equity"],
        frameworks=["FW_MACRO_TRANSMISSION", "FW_PB", "FW_DCF"],
        checklist=[
            "Policy rate impulse",
            "Banking NIM / CoF channel",
            "Credit demand response",
            "Equity discount-rate channel",
            "Sector winners / losers",
            "Currency / flows overlay",
            "Lag structure",
        ],
        procedure=[
            "Policy impulse",
            "Credit channel",
            "Valuation channel",
            "Sector map",
            "Conclusion",
        ],
        evidence_required=["policy_rate", "nim", "credit_growth", "equity_multiples"],
        knowledge_objects=["KO_RATES", "KO_TRANSMISSION"],
        common_mistakes=["Assuming instantaneous and uniform transmission"],
        output_structure=["Channels", "Lags", "Portfolio implications"],
        priority=80,
    ),
    playbook(
        "PB_MACRO_INFLATION_IMPACT",
        name="Inflation Impact Playbook",
        category="macro",
        question_types=["Explain", "Analyse", "Macro"],
        cues=["inflation", "cpi", "wpi", "input cost", "pricing power inflation"],
        frameworks=["FW_MACRO_TRANSMISSION", "FW_MOAT", "FW_INDUSTRY_STRUCTURE"],
        checklist=[
            "Inflation type (demand vs cost-push)",
            "Pass-through ability by sector",
            "Margin squeeze risk",
            "Real income / demand impact",
            "Policy response risk",
            "Nominal growth vs real growth",
        ],
        procedure=[
            "Diagnose inflation",
            "Map pass-through",
            "Policy risk",
            "Sector implications",
            "Conclusion",
        ],
        evidence_required=["cpi", "input_costs", "margins", "policy"],
        knowledge_objects=["KO_INFLATION"],
        common_mistakes=["Treating all inflation as equally bad for equities"],
        output_structure=["Inflation type", "Pass-through map", "Implications"],
        priority=70,
    ),
    playbook(
        "PB_MACRO_CURRENCY_FX",
        name="Currency / FX Impact",
        category="macro",
        question_types=["Explain", "Analyse", "Macro"],
        cues=["rupee", "fx", "currency", "dollar", "translation", "hedging"],
        frameworks=["FW_MACRO_TRANSMISSION", "FW_CASH_FLOW"],
        checklist=[
            "Direction of FX move",
            "Exporters vs importers",
            "Translation vs transaction",
            "Hedging disclosure",
            "Debt FX mismatch",
            "Macro cause of move",
        ],
        procedure=[
            "FX impulse",
            "Winners / losers",
            "Balance-sheet FX risk",
            "Conclusion",
        ],
        evidence_required=["fx", "export_mix", "import_intensity", "hedges"],
        knowledge_objects=["KO_FX"],
        common_mistakes=["Ignoring translation vs transaction distinction"],
        output_structure=["FX channel", "Sector map", "Risks"],
        priority=65,
    ),
    playbook(
        "PB_MACRO_LIQUIDITY_CREDIT",
        name="Liquidity & Credit Conditions",
        category="macro",
        question_types=["Explain", "Analyse", "Macro"],
        cues=["liquidity", "credit conditions", "tightening", "systemic liquidity", "funding stress"],
        frameworks=["FW_MACRO_TRANSMISSION", "FW_CREDIT", "FW_BALANCE_SHEET"],
        checklist=[
            "System liquidity indicators",
            "Credit growth vs deposits",
            "Spreads / risk appetite",
            "NBFC / bank funding stress",
            "Equity market liquidity",
            "Vulnerable sectors",
        ],
        procedure=[
            "Liquidity state",
            "Credit channel",
            "Stress points",
            "Market implications",
            "Conclusion",
        ],
        evidence_required=["liquidity", "credit", "spreads", "funding"],
        knowledge_objects=["KO_LIQUIDITY"],
        common_mistakes=["Equating policy rate alone with liquidity conditions"],
        output_structure=["Liquidity map", "Credit stress", "Implications"],
        priority=68,
    ),
    playbook(
        "PB_MACRO_GROWTH_CYCLE",
        name="Growth Cycle Positioning",
        category="macro",
        question_types=["Explain", "Analyse", "Macro"],
        cues=["gdp", "growth cycle", "slowdown", "recovery", "mid-cycle", "late cycle"],
        frameworks=["FW_MACRO_TRANSMISSION", "FW_CYCLE", "FW_INDUSTRY_STRUCTURE"],
        checklist=[
            "Cycle stage evidence",
            "Leading indicators",
            "Consumption vs investment",
            "Corporate earnings cycle",
            "Sector rotation implications",
            "Policy support / drag",
        ],
        procedure=[
            "Stage the cycle",
            "Leading indicators",
            "Earnings implication",
            "Sector map",
            "Conclusion",
        ],
        evidence_required=["gdp", "pmi", "capex", "consumption", "earnings"],
        knowledge_objects=["KO_GROWTH_CYCLE"],
        common_mistakes=["Calling late-cycle without leading-indicator confirmation"],
        output_structure=["Cycle stage", "Evidence", "Portfolio tilt"],
        priority=66,
    ),
    playbook(
        "PB_MACRO_COMMODITY_SHOCK",
        name="Commodity Shock Transmission",
        category="macro",
        question_types=["Explain", "Analyse", "Macro", "Event"],
        cues=["oil shock", "commodity", "crude", "metal prices", "input shock"],
        frameworks=["FW_MACRO_TRANSMISSION", "FW_INDUSTRY_STRUCTURE"],
        checklist=[
            "Commodity impulse",
            "Import bill / CAD channel",
            "Inflation channel",
            "Sector cost pass-through",
            "Fiscal subsidy risk",
            "Equity winners / losers",
        ],
        procedure=[
            "Shock size",
            "Macro channels",
            "Sector map",
            "Second-order policy risk",
            "Conclusion",
        ],
        evidence_required=["commodity_prices", "cad", "margins", "fiscal"],
        knowledge_objects=["KO_COMMODITY"],
        common_mistakes=["Stopping at direct cost impact without CAD/fiscal channel"],
        output_structure=["Shock", "Channels", "Sector implications"],
        priority=64,
    ),
    playbook(
        "PB_MACRO_FISCAL_MONETARY",
        name="Fiscal–Monetary Mix",
        category="macro",
        question_types=["Explain", "Analyse", "Macro"],
        cues=["fiscal", "deficit", "monetary policy mix", "crowding out", "policy mix"],
        frameworks=["FW_MACRO_TRANSMISSION", "FW_GOVERNMENT_POLICY"],
        checklist=[
            "Fiscal impulse size",
            "Deficit / debt path",
            "Monetary stance alignment",
            "Crowding-out risk",
            "Bond yields",
            "Equity risk premium implication",
        ],
        procedure=[
            "Fiscal stance",
            "Monetary stance",
            "Mix consistency",
            "Market channels",
            "Conclusion",
        ],
        evidence_required=["budget", "deficit", "policy_rate", "yields"],
        knowledge_objects=["KO_FISCAL", "KO_MONETARY"],
        common_mistakes=["Analysing fiscal without monetary offset"],
        output_structure=["Mix diagnosis", "Yield path", "Equity implication"],
        priority=62,
    ),
    playbook(
        "PB_MACRO_GLOBAL_SPILLOVER",
        name="Global Spillover Playbook",
        category="macro",
        question_types=["Explain", "Analyse", "Macro"],
        cues=["fed", "global", "spillover", "risk-off", "fii", "us recession"],
        frameworks=["FW_MACRO_TRANSMISSION", "FW_LIQUIDITY"],
        checklist=[
            "External impulse source",
            "Capital flow channel",
            "FX channel",
            "Trade / earnings channel",
            "Domestic cushion / vulnerability",
            "Sector beta to global risk",
        ],
        procedure=[
            "External shock",
            "Transmission channels",
            "Domestic buffers",
            "Portfolio implication",
            "Conclusion",
        ],
        evidence_required=["global_macro", "fii", "fx", "exports"],
        knowledge_objects=["KO_GLOBAL"],
        common_mistakes=["Assuming India is insulated without checking flow/FX channels"],
        output_structure=["Impulse", "Channels", "Domestic buffers", "Implications"],
        priority=61,
    ),
]
