"""Valuation analytical playbooks (8)."""

from __future__ import annotations

from institutional_playbooks.registry.models import playbook

PLAYBOOKS = [
    playbook(
        "PB_VAL_PREMIUM_MULTIPLE",
        name="Premium Valuation",
        category="valuation",
        question_types=["Explain", "Analyse", "Compare"],
        cues=[
            "premium multiple",
            "premium valuation",
            "deserves a premium",
            "expensive stock",
            "why premium",
            "trades at a premium",
            "rich valuation",
            "overvalued",
            "twice the valuation",
            "identical revenue growth",
        ],
        frameworks=["FW_DCF", "FW_HISTORICAL_VALUATION", "FW_ROIC", "FW_PEER_COMPARISON"],
        checklist=[
            "Economic moat",
            "Pricing power",
            "ROIC",
            "Reinvestment runway",
            "Capital allocation",
            "Cash conversion",
            "Governance",
            "Balance sheet",
            "Earnings quality",
            "Historical premium",
            "Peer premium",
            "Macro support",
        ],
        procedure=[
            "Establish current premium vs history and peers",
            "Test quality drivers (moat, ROIC, cash)",
            "Test durability of growth / reinvestment",
            "Check governance and earnings quality",
            "Macro / sector support",
            "Conclude whether premium is earned or fragile",
        ],
        evidence_required=[
            "multiples_history",
            "peer_multiples",
            "roic",
            "cash_flow",
            "governance",
            "macro",
        ],
        knowledge_objects=["KO_VALUATION", "KO_RETURN_METRICS", "KO_PEER_SET"],
        common_mistakes=[
            "Calling a stock expensive without quality checklist",
            "Ignoring historical premium persistence",
            "Using wrong peer set for premium comparison",
        ],
        output_structure=[
            "Premium diagnosis",
            "Quality checklist",
            "Fragility risks",
            "Conclusion on deservedness",
        ],
        priority=96,
    ),
    playbook(
        "PB_VAL_BANK_PB_RI",
        name="Bank Valuation (P/B · Residual Income)",
        category="valuation",
        question_types=["Explain", "Analyse", "Value"],
        cues=[
            "bank valuation",
            "price to book",
            "p/b",
            "residual income",
            "banks valued",
            "hdfc bank",
            "why banks use",
        ],
        frameworks=["FW_PB", "FW_RESIDUAL_INCOME", "FW_ROE", "FW_MACRO_TRANSMISSION"],
        sectors=["banks", "nbfc", "insurance"],
        checklist=[
            "Book value quality",
            "ROE vs cost of equity",
            "Residual income bridge",
            "NPA / asset quality",
            "Provisioning coverage",
            "CASA franchise",
            "NIM trajectory",
            "Capital adequacy",
            "Historical P/B",
            "Peer P/B / ROE",
            "Macro / rate transmission",
        ],
        procedure=[
            "Book value",
            "ROE",
            "Cost of equity",
            "Residual income",
            "NPA",
            "Provisioning",
            "CASA",
            "NIM",
            "Capital adequacy",
            "Historical P/B",
            "Peers",
            "Conclusion",
        ],
        evidence_required=[
            "bank_financials",
            "asset_quality",
            "nim",
            "casa",
            "capital",
            "peer_banks",
            "rates",
        ],
        knowledge_objects=["KO_BANK_METRICS", "KO_VALUATION", "KO_ASSET_QUALITY"],
        common_mistakes=[
            "Using EV/EBITDA for banks",
            "Stopping at 'banks use P/B' without ROE–COE–RI chain",
            "Ignoring NPA / provisioning when reading P/B",
        ],
        output_structure=[
            "Why P/B + RI",
            "Operating checklist",
            "Multiple vs fundamentals",
            "Conclusion",
        ],
        priority=98,
    ),
    playbook(
        "PB_VAL_DCF_STANDARD",
        name="Standard DCF Procedure",
        category="valuation",
        question_types=["Value", "Analyse", "Explain"],
        cues=["dcf", "discounted cash flow", "intrinsic value", "wacc", "terminal value"],
        frameworks=["FW_DCF", "FW_ROIC", "FW_CASH_FLOW"],
        checklist=[
            "Revenue drivers",
            "Margin path",
            "Reinvestment / FCFF",
            "WACC assumptions",
            "Terminal growth sanity",
            "Scenario / sensitivity",
            "Cross-check vs multiples",
            "Key value drivers ranked",
        ],
        procedure=[
            "Forecast drivers",
            "Build FCFF",
            "Discount at WACC",
            "Terminal value check",
            "Sensitivity",
            "Cross-check",
            "Conclusion",
        ],
        evidence_required=["financials", "guidance", "capex", "cost_of_capital"],
        knowledge_objects=["KO_DCF_INPUTS", "KO_CASH_FLOW"],
        common_mistakes=["Terminal growth ≥ nominal GDP without justification"],
        output_structure=["Base case value", "Sensitivities", "Cross-checks", "Confidence"],
        priority=70,
    ),
    playbook(
        "PB_VAL_PEER_COMPARISON",
        name="Peer Multiple Comparison Protocol",
        category="valuation",
        question_types=["Compare", "Analyse", "Explain"],
        cues=["peer comparison", "relative valuation", "vs peers", "cheaper than peers", "multiple vs"],
        frameworks=["FW_PEER_COMPARISON", "FW_HISTORICAL_VALUATION"],
        checklist=[
            "Correct peer set",
            "Same multiple definition",
            "Growth differentials",
            "Return differentials",
            "Risk / leverage differentials",
            "Accounting comparability",
            "Cycle position alignment",
            "Premium / discount justified?",
        ],
        procedure=[
            "Define peer set",
            "Align metrics",
            "Compare growth / returns / risk",
            "Explain premium or discount",
            "Conclusion",
        ],
        evidence_required=["peer_multiples", "peer_fundamentals", "accounting_notes"],
        knowledge_objects=["KO_PEER_SET", "KO_VALUATION"],
        common_mistakes=["Comparing banks to IT on EV/EBITDA", "Ignoring cycle mismatch"],
        output_structure=["Peer table logic", "Justified gap", "Risks to relative call"],
        priority=75,
    ),
    playbook(
        "PB_VAL_HISTORICAL_MULTIPLES",
        name="Historical Valuation Context",
        category="valuation",
        question_types=["Explain", "Analyse", "Replay"],
        cues=["historical valuation", "vs history", "trading range", "decade average", "mean reversion"],
        frameworks=["FW_HISTORICAL_VALUATION", "FW_PEER_COMPARISON"],
        checklist=[
            "Current multiple vs own history",
            "Regime shifts in fundamentals",
            "Interest-rate regime overlay",
            "Growth / ROIC then vs now",
            "Accounting changes",
            "Mean-reversion validity",
        ],
        procedure=[
            "Locate current vs history",
            "Test if fundamentals regime changed",
            "Macro overlay",
            "Conclude re-rating vs de-rating case",
        ],
        evidence_required=["multiples_history", "roic_history", "macro_history"],
        knowledge_objects=["KO_VALUATION_HISTORY"],
        common_mistakes=["Blind mean-reversion without regime check"],
        output_structure=["Historical context", "Regime test", "Implication"],
        priority=72,
    ),
    playbook(
        "PB_VAL_SOTP_CONGLOMERATE",
        name="SOTP Conglomerate Valuation",
        category="valuation",
        question_types=["Value", "Analyse", "Explain"],
        cues=["sotp", "sum of the parts", "conglomerate", "holding company", "stub"],
        frameworks=["FW_SOTP", "FW_PEER_COMPARISON", "FW_DCF"],
        sectors=["conglomerates", "generic"],
        checklist=[
            "Segment identification",
            "Appropriate multiple per segment",
            "Listed subsidiary marks",
            "Holdco discount rationale",
            "Net debt / cash allocation",
            "Intercompany adjustments",
            "Disclosure gaps",
        ],
        procedure=[
            "Map parts",
            "Value each part",
            "Adjust for holdco items",
            "Apply holdco discount explicitly",
            "Conclusion",
        ],
        evidence_required=["segment_reporting", "listed_subs", "net_debt", "notes"],
        knowledge_objects=["KO_SOTP", "KO_SEGMENTS"],
        common_mistakes=["Using single blended multiple for conglomerates"],
        output_structure=["Parts table", "Holdco bridge", "Discount rationale", "Conclusion"],
        priority=80,
    ),
    playbook(
        "PB_VAL_CHEAP_OR_VALUE_TRAP",
        name="Cheap vs Value Trap Protocol",
        category="valuation",
        question_types=["Analyse", "Assess", "Explain"],
        cues=["cheap", "value trap", "undervalued", "low multiple", "why cheap"],
        frameworks=["FW_HISTORICAL_VALUATION", "FW_EARNINGS_QUALITY", "FW_BALANCE_SHEET"],
        checklist=[
            "Multiple vs history / peers",
            "Earnings quality",
            "Balance sheet stress",
            "Industry structural decline?",
            "Governance / capital allocation",
            "Catalyst path",
            "Downside asymmetry",
            "Why the market may be right",
        ],
        procedure=[
            "Confirm cheapness",
            "Test value-trap hypotheses",
            "Identify required catalyst",
            "Asymmetry",
            "Conclusion",
        ],
        evidence_required=["multiples", "quality", "balance_sheet", "industry"],
        knowledge_objects=["KO_VALUATION", "KO_RISKS"],
        common_mistakes=["Buying low multiples without trap checklist"],
        output_structure=["Cheapness proof", "Trap tests", "Catalyst", "Conclusion"],
        priority=78,
    ),
    playbook(
        "PB_VAL_EV_EBITDA_OPS",
        name="EV/EBITDA Operating Valuation",
        category="valuation",
        question_types=["Value", "Explain", "Compare"],
        cues=["ev/ebitda", "enterprise value", "operating multiple"],
        frameworks=["FW_EV_EBITDA", "FW_PEER_COMPARISON", "FW_DCF"],
        checklist=[
            "Confirm sector appropriateness (not banks/insurance)",
            "Normalize EBITDA",
            "Net debt bridge",
            "Lease / pension adjustments",
            "Growth & margin vs peers",
            "Capex intensity overlay",
            "Cross-check vs DCF / FCF yield",
        ],
        procedure=[
            "Validate framework fit",
            "Normalize EV and EBITDA",
            "Peer / history compare",
            "Cross-check",
            "Conclusion",
        ],
        evidence_required=["ebitda", "net_debt", "leases", "peers"],
        knowledge_objects=["KO_VALUATION", "KO_OPS"],
        common_mistakes=["Applying EV/EBITDA to banks", "Ignoring lease-adjusted EV"],
        output_structure=["Framework fit", "Normalized multiple", "Cross-check", "Conclusion"],
        priority=66,
    ),
]
