"""HVIE Universe Completion Programme — constants and status vocabularies."""

from __future__ import annotations

PROGRAMME_CODE = "hvie_universe_completion"
PROGRAMME_VERSION = "8.3B"

# Queue plane (resumable bootstrap)
QUEUE_PENDING = "PENDING"
QUEUE_RUNNING = "RUNNING"
QUEUE_COMPLETED = "COMPLETED"
QUEUE_RETRY = "RETRY"
QUEUE_SKIPPED = "SKIPPED"
QUEUE_FAILED = "FAILED"

QUEUE_STATUSES = (
    QUEUE_PENDING,
    QUEUE_RUNNING,
    QUEUE_COMPLETED,
    QUEUE_RETRY,
    QUEUE_SKIPPED,
    QUEUE_FAILED,
)

# Eligibility / lifecycle plane
LIFE_NOT_STARTED = "NOT_STARTED"
LIFE_READY = "READY"
LIFE_WAITING_PRICE = "WAITING_PRICE_HISTORY"
LIFE_WAITING_STATEMENTS = "WAITING_STATEMENTS"
LIFE_WAITING_CA = "WAITING_CORPORATE_ACTIONS"
LIFE_WAITING_SHARE_COUNT = "WAITING_SHARE_COUNT"
LIFE_RUNNING = "RUNNING"
LIFE_FAILED = "FAILED"
LIFE_COMPLETE = "COMPLETE"

LIFECYCLES = (
    LIFE_NOT_STARTED,
    LIFE_READY,
    LIFE_WAITING_PRICE,
    LIFE_WAITING_STATEMENTS,
    LIFE_WAITING_CA,
    LIFE_WAITING_SHARE_COUNT,
    LIFE_RUNNING,
    LIFE_FAILED,
    LIFE_COMPLETE,
)

# Pipeline stages (Phase 3)
STAGE_CLASSIFY = "classify"
STAGE_PRICES = "prices"
STAGE_STATEMENTS = "statements"
STAGE_CA = "corporate_actions"
STAGE_RECONSTRUCT = "reconstruct"
STAGE_STATISTICS = "statistics"
STAGE_PERCENTILE = "percentile"
STAGE_BANDS = "bands"
STAGE_REGIME = "regime"
STAGE_RESEARCH = "research"
STAGE_COMPLETE = "complete"

PIPELINE_STAGES = (
    STAGE_CLASSIFY,
    STAGE_PRICES,
    STAGE_STATEMENTS,
    STAGE_CA,
    STAGE_RECONSTRUCT,
    STAGE_STATISTICS,
    STAGE_PERCENTILE,
    STAGE_BANDS,
    STAGE_REGIME,
    STAGE_RESEARCH,
    STAGE_COMPLETE,
)

# Retry
MAX_ATTEMPTS = 8
BASE_BACKOFF_SECONDS = 300  # 5 minutes
MAX_BACKOFF_SECONDS = 86_400  # 24 hours

# Eligibility floors
MIN_PRICE_OBS = 5
MIN_STATEMENT_OBS = 1
MIN_HISTORY_OBS_FOR_COMPLETE = 12
