"""Phase 2–3 — canonical institutional sector frameworks."""

from __future__ import annotations

from sif.schema import SIF_VERSION, SectorFramework


_DEFAULT_EVIDENCE = [
    "latest_annual_report",
    "latest_quarterly_results",
    "latest_investor_presentation",
    "recent_earnings_call",
    "material_announcements",
    "financial_statements",
    "valuation_metrics",
    "sector_benchmarks",
]


def _fw(**kwargs) -> SectorFramework:
    kwargs.setdefault("version", SIF_VERSION)
    kwargs.setdefault("evidence_required", list(_DEFAULT_EVIDENCE))
    return SectorFramework(**kwargs)


FRAMEWORKS: dict[str, SectorFramework] = {
    "banks": _fw(
        sector_id="banks",
        name="Banking",
        aliases=["bank", "private banks", "psu banks"],
        business_model_focus=["loan_mix", "deposit_mix", "casa_ratio", "fee_income", "treasury_income"],
        required_kpis=[
            "nim", "casa", "credit_cost", "gnpa", "nnpa", "provision_coverage",
            "cet1", "capital_adequacy", "lcr", "cost_of_funds", "yield_on_advances",
            "roa", "roe", "pb", "fee_income", "treasury_income",
        ],
        priority_metrics=["nim", "casa", "credit_cost", "gnpa", "nnpa", "cet1", "roe", "pb", "deposit_franchise"],
        accounting_focus=["earnings_quality", "net_interest_margin", "provisions", "npa_recognition", "interest_income"],
        corporate_finance_focus=["roe", "cost_of_equity", "capital_allocation", "optimal_capital_structure", "wacc"],
        academy_concept_priority=[
            "roe", "cost_of_equity", "equity_risk_premium", "country_risk_premium",
            "earnings_quality", "financial_leverage", "optimal_capital_structure",
            "capital_allocation", "monetary_policy", "credit", "wacc",
        ],
        valuation_methodology=["residual_income", "justified_pb", "pb", "excess_return"],
        preferred_multiples=["P/B", "P/E"],
        forecast_drivers=["loan_growth", "nim_trajectory", "credit_cost", "casa_mix", "fee_income", "rate_cycle"],
        risk_factors=["asset_quality", "concentration", "interest_rate_risk", "liquidity_risk", "regulatory_capital", "deposit_franchise_erosion"],
        industry_mental_models=["deposit_franchise_is_moat", "credit_cost_dominates_cycle", "roe_vs_coe_drives_pb", "banks_are_leverage_businesses"],
        decision_framework=[
            "Underwrite deposit franchise (CASA) before loan growth narratives",
            "Stress NIM and credit cost through the rate/credit cycle before changing weights",
            "Buy only when ROE sustainably exceeds cost of equity with CET1 headroom and improving asset quality",
            "Prefer P/B vs ROE–COE spread; avoid generic DCF-as-primary for banks",
        ],
        common_mistakes=[
            "Using manufacturing WACC/DCF as primary bank valuation",
            "Ignoring credit cost and NPA while focusing on loan growth",
            "Treating treasury gains as core earnings",
            "Prioritising generic liquidity/diversification concepts over NIM/CASA/GNPA",
        ],
        monitoring_signals=["nim", "casa", "gnpa", "nnpa", "credit_cost", "cet1", "deposit_growth", "pcr"],
        iie_focus=["credit_cycle", "deposit_franchise", "capital_strength", "digital_moat", "management_quality", "regulatory_risk"],
        suppress_generic_concepts=["risk_and_diversification", "liquidity", "monetary_system", "gains_from_trade", "elasticity"],
    ),
    "nbfc": _fw(
        sector_id="nbfc",
        name="NBFC / HFC",
        required_kpis=["nim", "aumm_growth", "disbursements", "stage3", "credit_cost", "leverage", "liquidity", "roe", "pb"],
        priority_metrics=["nim", "stage3", "credit_cost", "leverage", "liability_mix", "roe"],
        accounting_focus=["earnings_quality", "provisions", "ecl", "interest_income"],
        corporate_finance_focus=["roe", "cost_of_equity", "financial_leverage", "capital_allocation"],
        academy_concept_priority=["roe", "cost_of_equity", "financial_leverage", "earnings_quality", "credit", "wacc"],
        valuation_methodology=["justified_pb", "pb", "excess_return"],
        preferred_multiples=["P/B", "P/E"],
        forecast_drivers=["disbursement_growth", "spreads", "credit_cost", "funding_cost"],
        risk_factors=["almmismatch", "wholesale_funding", "asset_quality", "regulatory"],
        industry_mental_models=["liability_franchise_matters", "cycle_is_credit_cost"],
        decision_framework=["Underwrite liability mix and stage-3 before growth", "Size to funding stress resilience"],
        common_mistakes=["Bank-like CASA assumptions for wholesale-funded NBFCs"],
        monitoring_signals=["stage3", "credit_cost", "nim", "leverage", "cpcb"],
        iie_focus=["credit_cycle", "funding_franchise", "underwriting_quality"],
        suppress_generic_concepts=["risk_and_diversification", "monetary_system"],
    ),
    "insurance": _fw(
        sector_id="insurance",
        name="Insurance",
        required_kpis=["vnb", "vnb_margin", "embedded_value", "ape", "persistenc", "solvency", "combined_ratio", "roe"],
        priority_metrics=["vnb_margin", "embedded_value", "persistenc", "solvency"],
        accounting_focus=["earnings_quality", "provisions", "revenue_recognition"],
        corporate_finance_focus=["cost_of_equity", "capital_allocation", "roe"],
        academy_concept_priority=["cost_of_equity", "roe", "earnings_quality", "present_value", "wacc"],
        valuation_methodology=["embedded_value", "appraisal_value", "pb"],
        preferred_multiples=["P/EV", "P/B"],
        forecast_drivers=["ape_growth", "vnb_margin", "persistenc", "investment_yield"],
        risk_factors=["persistenc_shock", "claims", "regulatory", "market_risk"],
        industry_mental_models=["vnb_quality_over_ape_growth", "solvency_constrains_growth"],
        decision_framework=["Prefer VNB margin quality and persistency over APE optics"],
        common_mistakes=["Valuing insurers like banks on P/B alone without EV"],
        monitoring_signals=["vnb_margin", "persistenc", "solvency", "ape"],
        iie_focus=["distribution_moat", "product_mix", "capital_strength"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "it_services": _fw(
        sector_id="it_services",
        name="IT Services",
        business_model_focus=["deal_wins", "pipeline", "utilisation", "attrition", "pricing", "offshore_mix", "digital_revenue", "genai_exposure"],
        required_kpis=[
            "deal_wins", "pipeline", "utilisation", "attrition", "pricing", "offshore_mix",
            "ebit_margin", "cash_conversion", "order_book", "digital_revenue", "genai_exposure", "roic", "fcf",
        ],
        priority_metrics=["deal_wins", "utilisation", "attrition", "ebit_margin", "cash_conversion", "digital_revenue", "genai_exposure"],
        accounting_focus=["revenue_recognition", "deferred_revenue", "operating_cash_flow", "free_cash_flow", "earnings_quality", "working_capital"],
        corporate_finance_focus=["roic", "roic_wacc_spread", "capital_allocation", "wacc", "share_buybacks", "incremental_roic"],
        academy_concept_priority=[
            "free_cash_flow", "operating_cash_flow", "earnings_quality", "roic", "roic_wacc_spread",
            "wacc", "working_capital", "revenue_recognition", "capital_allocation", "exchange_rates",
        ],
        valuation_methodology=["dcf_fcff", "pe", "ev_ebitda"],
        preferred_multiples=["P/E", "EV/EBITDA"],
        forecast_drivers=["deal_wins", "pricing", "utilisation", "attrition", "usd_inr", "vertical_demand", "genai"],
        risk_factors=["client_concentration", "pricing_pressure", "attrition", "visa", "fx", "ai_disruption"],
        industry_mental_models=["talent_is_the_factory", "deal_wins_lead_revenue", "fx_is_not_operating_alpha"],
        decision_framework=[
            "Lead with large deal TCV/pipeline and utilisation before multiple expansion stories",
            "Require cash conversion confirmation of earnings",
            "Haircut if attrition spikes or pricing turns negative even if revenue grows",
        ],
        common_mistakes=["Ignoring attrition/utilisation", "Treating INR depreciation as structural quality"],
        monitoring_signals=["attrition", "utilisation", "deal_wins", "ebit_margin", "fcf_cfo"],
        iie_focus=["competitive_moat", "switching_costs", "vertical_mix", "genai_positioning", "management_quality"],
        suppress_generic_concepts=["risk_and_diversification", "monetary_system", "gdp"],
    ),
    "software": _fw(
        sector_id="software",
        name="Software / SaaS",
        required_kpis=["arr", "nr", "logo_churn", "ndr", "ltv_cac", "rule_of_40", "gross_margin", "fcf"],
        priority_metrics=["arr_growth", "ndr", "rule_of_40", "fcf_margin"],
        accounting_focus=["deferred_revenue", "revenue_recognition", "free_cash_flow", "share_based_compensation"],
        corporate_finance_focus=["roic", "wacc", "capital_allocation", "incremental_roic"],
        academy_concept_priority=["deferred_revenue", "revenue_recognition", "free_cash_flow", "roic", "wacc"],
        valuation_methodology=["ev_sales", "dcf_fcff", "rule_of_40"],
        preferred_multiples=["EV/Sales", "EV/ARR"],
        forecast_drivers=["arr_growth", "ndr", "sales_efficiency"],
        risk_factors=["churn", "competition", "multiple_compression"],
        industry_mental_models=["retention_beats_logo_growth", "cash_over_adjusted_ebitda"],
        decision_framework=["Prefer durable NDR and path to FCF over vanity ARR"],
        common_mistakes=["Valuing unprofitable growth without cash discipline"],
        monitoring_signals=["ndr", "arr_growth", "fcf", "sbc"],
        iie_focus=["product_moat", "switching_costs", "unit_economics"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "telecom": _fw(
        sector_id="telecom",
        name="Telecom",
        required_kpis=["arpu", "subscribers", "churn", "capex_intensity", "net_debt_ebitda", "spectrum", "ebitda_margin", "fcf"],
        priority_metrics=["arpu", "capex", "leverage", "fcf"],
        accounting_focus=["leases", "depreciation", "free_cash_flow", "impairment"],
        corporate_finance_focus=["wacc", "optimal_capital_structure", "roic", "capital_allocation"],
        academy_concept_priority=["free_cash_flow", "wacc", "leases", "financial_leverage", "roic"],
        valuation_methodology=["dcf_fcff", "ev_ebitda"],
        preferred_multiples=["EV/EBITDA"],
        forecast_drivers=["arpu", "subscriber_adds", "capex_cycle", "competitive_intensity"],
        risk_factors=["spectrum_cost", "price_wars", "leverage", "regulation"],
        industry_mental_models=["scale_and_spectrum_are_moats", "capex_never_ends"],
        decision_framework=["Underwrite FCF after spectrum/capex before leverage stories"],
        common_mistakes=["Ignoring spectrum liabilities"],
        monitoring_signals=["arpu", "net_debt_ebitda", "capex", "churn"],
        iie_focus=["spectrum_position", "competitive_intensity", "balance_sheet"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "fmcg": _fw(
        sector_id="fmcg",
        name="FMCG / Consumer Staples / Branded Consumer",
        required_kpis=[
            "volume_growth", "pricing", "rural_demand", "urban_demand", "gross_margin",
            "distribution", "brand_strength", "market_share", "working_capital", "cash_conversion", "roic",
        ],
        priority_metrics=["volume_growth", "gross_margin", "rural_demand", "market_share", "cash_conversion", "roic"],
        accounting_focus=["revenue_recognition", "working_capital", "gross_profit", "earnings_quality", "free_cash_flow"],
        corporate_finance_focus=["roic", "roic_wacc_spread", "capital_allocation", "brand_reinvestment", "wacc"],
        academy_concept_priority=[
            "working_capital", "free_cash_flow", "roic", "roic_wacc_spread", "earnings_quality",
            "revenue_recognition", "inflation", "capital_allocation",
        ],
        valuation_methodology=["dcf_fcff", "pe", "ev_ebitda"],
        preferred_multiples=["P/E", "EV/EBITDA"],
        forecast_drivers=["volume", "pricing", "rural_recovery", "gross_margin", "ad_spend"],
        risk_factors=["commodity_costs", "rural_slowdown", "competition", "channel_shift"],
        industry_mental_models=["volume_is_truth", "brand_moat_shows_in_gross_margin", "distribution_is_capital"],
        decision_framework=[
            "Separate volume vs price/mix before calling growth high-quality",
            "Require cash conversion and ROIC vs WACC on brand reinvestment",
        ],
        common_mistakes=["Paying premium multiples for price-led growth without volume"],
        monitoring_signals=["volume_growth", "gross_margin", "rural", "working_capital"],
        iie_focus=["brand_moat", "distribution", "category_growth", "management_quality"],
        suppress_generic_concepts=["risk_and_diversification", "monetary_system", "liquidity"],
    ),
    "retail": _fw(
        sector_id="retail",
        name="Retail",
        required_kpis=["sss", "footfall", "ticket_size", "gross_margin", "inventory_days", "store_adds", "roce", "fcf"],
        priority_metrics=["sss", "inventory_days", "gross_margin", "roce"],
        accounting_focus=["inventory", "working_capital", "leases", "revenue_recognition", "free_cash_flow"],
        corporate_finance_focus=["roic", "wacc", "capital_allocation", "leases"],
        academy_concept_priority=["working_capital", "inventory", "leases", "roic", "free_cash_flow"],
        valuation_methodology=["dcf_fcff", "ev_ebitda", "pe"],
        preferred_multiples=["EV/EBITDA", "P/E"],
        forecast_drivers=["sss", "store_expansion", "mix", "inventory"],
        risk_factors=["inventory_glut", "rent", "competition", "discretionary_demand"],
        industry_mental_models=["sss_before_store_adds", "inventory_kills_fcf"],
        decision_framework=["Prefer SSS and inventory discipline over square-footage optics"],
        common_mistakes=["Ignoring lease-adjusted leverage"],
        monitoring_signals=["sss", "inventory_days", "gross_margin"],
        iie_focus=["format_moat", "supply_chain", "location_strategy"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "pharma": _fw(
        sector_id="pharma",
        name="Pharmaceuticals",
        required_kpis=["us_revenue", "anda_pipeline", "usfda_status", "gross_margin", "r_and_d", "working_capital", "roic", "fcf"],
        priority_metrics=["usfda", "anda", "gross_margin", "roic", "fcf"],
        accounting_focus=["revenue_recognition", "working_capital", "r_and_d", "earnings_quality", "free_cash_flow"],
        corporate_finance_focus=["roic", "capital_allocation", "wacc", "acquisition_quality"],
        academy_concept_priority=["roic", "free_cash_flow", "working_capital", "earnings_quality", "acquisition_quality", "wacc"],
        valuation_methodology=["dcf_fcff", "pe", "ev_ebitda"],
        preferred_multiples=["P/E", "EV/EBITDA"],
        forecast_drivers=["us_launches", "price_erosion", "india_branded", "api"],
        risk_factors=["usfda", "price_erosion", "litigation", "fx"],
        industry_mental_models=["compliance_is_existential", "pipeline_beats_spot_earnings"],
        decision_framework=["Haircut for FDA/compliance risk before multiple expansion"],
        common_mistakes=["Extrapolating one-off launch profits"],
        monitoring_signals=["usfda", "gross_margin", "working_capital", "fcf"],
        iie_focus=["pipeline_quality", "compliance", "geography_mix"],
        suppress_generic_concepts=["risk_and_diversification", "monetary_system"],
    ),
    "healthcare": _fw(
        sector_id="healthcare",
        name="Healthcare",
        required_kpis=["occupancy", "arpo", "payer_mix", "ebitda_margin", "capex", "roce"],
        priority_metrics=["occupancy", "arpo", "payer_mix", "roce"],
        accounting_focus=["revenue_recognition", "depreciation", "working_capital"],
        corporate_finance_focus=["roic", "capital_allocation", "wacc"],
        academy_concept_priority=["roic", "capital_allocation", "wacc", "free_cash_flow"],
        valuation_methodology=["dcf_fcff", "ev_ebitda"],
        preferred_multiples=["EV/EBITDA"],
        forecast_drivers=["bed_adds", "arpo", "specialty_mix"],
        risk_factors=["regulation", "talent", "payer_pressure"],
        industry_mental_models=["case_mix_drives_arpo"],
        decision_framework=["Underwrite utilisation and payer mix before expansion"],
        common_mistakes=["Ignoring gestation on new hospitals"],
        monitoring_signals=["occupancy", "arpo", "ebitda_margin"],
        iie_focus=["network_density", "specialty_strength"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "hospitals": _fw(
        sector_id="hospitals",
        name="Hospitals",
        required_kpis=["occupancy", "arpo", "alps", "payer_mix", "ebitda_margin", "bed_adds", "roce"],
        priority_metrics=["occupancy", "arpo", "payer_mix", "roce"],
        accounting_focus=["revenue_recognition", "depreciation", "working_capital"],
        corporate_finance_focus=["roic", "capital_allocation", "wacc"],
        academy_concept_priority=["roic", "capital_allocation", "free_cash_flow", "wacc"],
        valuation_methodology=["dcf_fcff", "ev_ebitda"],
        preferred_multiples=["EV/EBITDA"],
        forecast_drivers=["occupancy", "arpo", "new_beds"],
        risk_factors=["doctor_attrition", "regulation", "capex_overrun"],
        industry_mental_models=["mature_cluster_roce_matters"],
        decision_framework=["Prefer cluster maturity economics over vanity bed counts"],
        common_mistakes=["Capitalising growth without ROCE path"],
        monitoring_signals=["occupancy", "arpo", "roce"],
        iie_focus=["cluster_strategy", "specialty_mix", "brand"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "power": _fw(
        sector_id="power",
        name="Power Generation",
        required_kpis=["plf", "paf", "merchant_exposure", "receivables", "regulated_equity", "leverage", "fcf"],
        priority_metrics=["plf", "receivables", "regulated_return", "leverage"],
        accounting_focus=["depreciation", "receivables", "impairment", "free_cash_flow"],
        corporate_finance_focus=["wacc", "optimal_capital_structure", "roic", "capital_allocation"],
        academy_concept_priority=["wacc", "free_cash_flow", "working_capital", "financial_leverage", "roic"],
        valuation_methodology=["dcf_fcff", "regulated_equity"],
        preferred_multiples=["P/B", "EV/EBITDA"],
        forecast_drivers=["demand", "fuel", "tariffs", "receivables"],
        risk_factors=["discom_receivables", "fuel", "merchant_prices", "regulation"],
        industry_mental_models=["receivables_are_the_hidden_leverage"],
        decision_framework=["Stress discom receivables and merchant mix before growth"],
        common_mistakes=["Ignoring working-capital traps at IPPs"],
        monitoring_signals=["receivables", "plf", "leverage"],
        iie_focus=["fuel_security", "offtake", "balance_sheet"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "utilities": _fw(
        sector_id="utilities",
        name="Utilities / Transmission & Distribution",
        required_kpis=["regulated_equity", "roe_allowed", "capex_pipeline", "incentive_income", "leverage", "fcf"],
        priority_metrics=["regulated_equity_growth", "allowed_roe", "capex_execution"],
        accounting_focus=["depreciation", "regulated_assets", "free_cash_flow"],
        corporate_finance_focus=["wacc", "cost_of_equity", "capital_allocation", "optimal_capital_structure"],
        academy_concept_priority=["wacc", "cost_of_equity", "present_value", "free_cash_flow", "capital_allocation"],
        valuation_methodology=["dcf_fcff", "regulated_dcf", "pb"],
        preferred_multiples=["P/B", "EV/EBITDA"],
        forecast_drivers=["capex_pipeline", "capitalisation", "incentives"],
        risk_factors=["regulatory_lag", "execution", "interest_rates"],
        industry_mental_models=["rate_base_growth_is_value", "wacc_matters_acutely"],
        decision_framework=["Primary valuation is DCF/regulated equity — not software multiples"],
        common_mistakes=["Applying growth-tech multiples to regulated utilities"],
        monitoring_signals=["capex", "capitalisation", "allowed_roe"],
        iie_focus=["regulatory_stability", "execution", "balance_sheet"],
        suppress_generic_concepts=["risk_and_diversification", "deferred_revenue"],
    ),
    "renewables": _fw(
        sector_id="renewables",
        name="Renewables",
        required_kpis=["capacity_mw", "cuf", "tariff", "ppa_quality", "leverage", "bid_pipeline", "fcf"],
        priority_metrics=["cuf", "ppa_quality", "leverage", "bid_irrs"],
        accounting_focus=["depreciation", "impairment", "free_cash_flow", "leases"],
        corporate_finance_focus=["wacc", "npv", "capital_allocation", "financial_leverage"],
        academy_concept_priority=["wacc", "npv", "free_cash_flow", "financial_leverage", "present_value"],
        valuation_methodology=["dcf_fcff", "ev_ebitda"],
        preferred_multiples=["EV/EBITDA", "EV/MW"],
        forecast_drivers=["capacity_adds", "tariffs", "cuf", "module_costs"],
        risk_factors=["bid_aggression", "execution", "offtaker", "interest_rates"],
        industry_mental_models=["ppa_quality_over_mw_optics"],
        decision_framework=["Underwrite IRR vs WACC on contracted cash flows"],
        common_mistakes=["Paying for pipeline MW without PPA economics"],
        monitoring_signals=["cuf", "leverage", "bid_pipeline"],
        iie_focus=["offtake_quality", "cost_curve", "balance_sheet"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "oil_gas": _fw(
        sector_id="oil_gas",
        name="Oil & Gas",
        required_kpis=["grm", "throughput", "realisations", "upstream_volume", "marketing_margin", "working_capital", "fcf", "leverage"],
        priority_metrics=["grm", "upstream_volume", "fcf", "leverage"],
        accounting_focus=["inventory", "working_capital", "depreciation", "exceptional_items", "free_cash_flow"],
        corporate_finance_focus=["roic", "capital_allocation", "wacc", "debt_repayment"],
        academy_concept_priority=["free_cash_flow", "working_capital", "roic", "capital_allocation", "wacc", "exceptional_items"],
        valuation_methodology=["dcf_fcff", "ev_ebitda", "sotp"],
        preferred_multiples=["EV/EBITDA", "P/B"],
        forecast_drivers=["crude", "cracks", "volumes", "marketing"],
        risk_factors=["commodity", "policy", "inventory_losses", "capex"],
        industry_mental_models=["cycle_position_dominates", "grm_is_not_structural_moat"],
        decision_framework=["Separate upstream/refining/marketing; use mid-cycle assumptions"],
        common_mistakes=["Peak-cycle multiple on refining earnings"],
        monitoring_signals=["grm", "inventory", "fcf", "net_debt"],
        iie_focus=["integration", "cycle_position", "capital_discipline"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "metals": _fw(
        sector_id="metals",
        name="Metals",
        required_kpis=["realisation", "cost_curve", "volume", "spread", "working_capital", "leverage", "roic"],
        priority_metrics=["spread", "cost_curve", "leverage", "roic"],
        accounting_focus=["inventory", "working_capital", "depreciation", "impairment", "free_cash_flow"],
        corporate_finance_focus=["roic", "capital_allocation", "wacc", "debt_repayment"],
        academy_concept_priority=["roic", "working_capital", "free_cash_flow", "wacc", "capital_allocation"],
        valuation_methodology=["ev_ebitda", "replacement_cost", "dcf_midcycle"],
        preferred_multiples=["EV/EBITDA", "P/B"],
        forecast_drivers=["prices", "costs", "china", "volumes"],
        risk_factors=["commodity", "china_exports", "leverage", "working_capital"],
        industry_mental_models=["cost_curve_position_is_moat", "mid_cycle_not_spot"],
        decision_framework=["Value on mid-cycle spreads and net debt"],
        common_mistakes=["Spot-price DCF without cycle normalisation"],
        monitoring_signals=["spread", "net_debt", "inventory"],
        iie_focus=["cost_curve", "cycle", "balance_sheet"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "steel": _fw(
        sector_id="steel",
        name="Steel",
        business_model_focus=["capacity", "utilisation", "realisation", "iron_ore", "coal", "chinese_exports", "spread"],
        required_kpis=[
            "capacity", "utilisation", "realisation", "iron_ore", "coking_coal", "chinese_exports",
            "spread", "working_capital", "roic", "leverage", "fcf",
        ],
        priority_metrics=["spread", "utilisation", "working_capital", "roic", "leverage", "cycle_position"],
        accounting_focus=["inventory", "working_capital", "depreciation", "impairment", "free_cash_flow", "earnings_quality"],
        corporate_finance_focus=["roic", "roic_wacc_spread", "capital_allocation", "wacc", "debt_repayment", "optimal_capital_structure"],
        academy_concept_priority=[
            "roic", "roic_wacc_spread", "working_capital", "inventory", "free_cash_flow",
            "wacc", "capital_allocation", "business_cycle", "earnings_quality",
        ],
        valuation_methodology=["ev_ebitda_midcycle", "replacement_cost", "dcf_fcff"],
        preferred_multiples=["EV/EBITDA", "P/B"],
        forecast_drivers=["spreads", "utilisation", "raw_material", "china", "domestic_demand"],
        risk_factors=["china_exports", "coking_coal", "leverage", "working_capital_swings", "protectionism"],
        industry_mental_models=["spread_is_the_business", "cycle_position_first", "capacity_discipline"],
        decision_framework=[
            "Locate cycle position before extrapolating EBITDA",
            "Prefer FCF and deleveraging over peak ROIC narratives",
            "Working capital swings can erase reported profits",
        ],
        common_mistakes=["Peak-spread multiples", "Ignoring China export shocks"],
        monitoring_signals=["hcr_spreads", "utilisation", "net_debt", "inventory_days"],
        iie_focus=["cost_curve", "capacity", "cycle_position", "balance_sheet"],
        suppress_generic_concepts=["risk_and_diversification", "monetary_system", "deferred_revenue"],
    ),
    "mining": _fw(
        sector_id="mining",
        name="Mining",
        required_kpis=["production", "realisation", "cash_cost", "stripping", "volume", "fcf", "royalty"],
        priority_metrics=["cash_cost", "volume", "fcf"],
        accounting_focus=["depreciation", "impairment", "provisions", "free_cash_flow"],
        corporate_finance_focus=["capital_allocation", "roic", "wacc", "dividend_policy"],
        academy_concept_priority=["free_cash_flow", "roic", "capital_allocation", "wacc"],
        valuation_methodology=["dcf_fcff", "ev_ebitda"],
        preferred_multiples=["EV/EBITDA"],
        forecast_drivers=["volumes", "prices", "costs"],
        risk_factors=["commodity", "policy", "esg", "volume_miss"],
        industry_mental_models=["volume_and_cash_cost"],
        decision_framework=["Prefer FCF yield through the cycle"],
        common_mistakes=["Ignoring royalty/policy shocks"],
        monitoring_signals=["production", "cash_cost", "fcf"],
        iie_focus=["resource_quality", "policy", "cost"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "cement": _fw(
        sector_id="cement",
        name="Cement",
        business_model_focus=["capacity", "capacity_utilisation", "realisation", "fuel_cost", "freight", "regional_demand"],
        required_kpis=[
            "capacity", "capacity_utilisation", "realisation", "fuel_cost", "freight",
            "regional_demand", "government_capex", "housing_demand", "ebitda_per_tonne", "expansion_pipeline", "roic",
        ],
        priority_metrics=["ebitda_per_tonne", "utilisation", "realisation", "fuel_cost", "regional_demand", "roic"],
        accounting_focus=["depreciation", "working_capital", "free_cash_flow", "earnings_quality", "inventory"],
        corporate_finance_focus=["roic", "roic_wacc_spread", "capital_allocation", "wacc", "organic_reinvestment"],
        academy_concept_priority=[
            "roic", "roic_wacc_spread", "incremental_roic", "wacc", "free_cash_flow",
            "working_capital", "capital_allocation", "business_cycle", "gdp",
        ],
        valuation_methodology=["ev_ebitda", "replacement_cost", "dcf_fcff"],
        preferred_multiples=["EV/EBITDA", "EV/tonne"],
        forecast_drivers=["utilisation", "pricing", "fuel", "infra_housing_demand", "capacity_adds"],
        risk_factors=["pricing_discipline", "fuel", "freight", "overcapacity", "regional_glut"],
        industry_mental_models=["pricing_is_local", "cost_curve_and_freight", "capacity_discipline"],
        decision_framework=[
            "Lead with regional demand-supply and EBITDA/tonne before national narratives",
            "Test incremental ROIC on expansion pipeline vs WACC",
        ],
        common_mistakes=["National average pricing for regional cement economics"],
        monitoring_signals=["ebitda_per_tonne", "utilisation", "petcoke_coal", "trade_prices"],
        iie_focus=["cost_curve", "capacity", "regional_pricing_power", "cycle"],
        suppress_generic_concepts=["risk_and_diversification", "monetary_system", "deferred_revenue"],
    ),
    "chemicals": _fw(
        sector_id="chemicals",
        name="Chemicals",
        required_kpis=["utilisation", "spreads", "product_mix", "gross_margin", "working_capital", "roic", "capex"],
        priority_metrics=["spreads", "utilisation", "roic", "working_capital"],
        accounting_focus=["inventory", "working_capital", "free_cash_flow", "earnings_quality"],
        corporate_finance_focus=["roic", "capital_allocation", "wacc", "incremental_roic"],
        academy_concept_priority=["roic", "working_capital", "free_cash_flow", "wacc", "capital_allocation"],
        valuation_methodology=["ev_ebitda", "dcf_fcff", "pe"],
        preferred_multiples=["EV/EBITDA", "P/E"],
        forecast_drivers=["spreads", "volumes", "china", "specialty_mix"],
        risk_factors=["commodity_chem_cycle", "china", "environmental"],
        industry_mental_models=["specialty_mix_lifts_roic"],
        decision_framework=["Separate commodity vs specialty economics"],
        common_mistakes=["Peak-spread specialty multiples on commodity buckets"],
        monitoring_signals=["gross_margin", "working_capital", "utilisation"],
        iie_focus=["product_complexity", "customer_stickiness", "cost"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "automobile": _fw(
        sector_id="automobile",
        name="Automobile",
        required_kpis=["volumes", "mix", "realisation", "margins", "inventory", "dealer_stock", "roce", "fcf"],
        priority_metrics=["volumes", "mix", "margins", "inventory", "roce"],
        accounting_focus=["inventory", "working_capital", "revenue_recognition", "free_cash_flow"],
        corporate_finance_focus=["roic", "capital_allocation", "wacc", "working_capital"],
        academy_concept_priority=["working_capital", "inventory", "roic", "free_cash_flow", "wacc", "business_cycle"],
        valuation_methodology=["ev_ebitda", "pe", "dcf_fcff"],
        preferred_multiples=["EV/EBITDA", "P/E"],
        forecast_drivers=["pv_cv_volumes", "mix", "commodity", "financing"],
        risk_factors=["cycle", "regulatory", "competition", "ev_transition"],
        industry_mental_models=["mix_and_cycle", "dealer_inventory_signal"],
        decision_framework=["Read channel inventory before extrapolating wholesale"],
        common_mistakes=["Ignoring CV/PV cycle differences"],
        monitoring_signals=["volumes", "dealer_stock", "margins"],
        iie_focus=["brand", "portfolio", "ev_readiness", "cycle"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "auto_components": _fw(
        sector_id="auto_components",
        name="Auto Components",
        required_kpis=["content_per_vehicle", "utilisation", "oem_concentration", "margins", "working_capital", "roce"],
        priority_metrics=["content_per_vehicle", "oem_mix", "roce", "working_capital"],
        accounting_focus=["working_capital", "inventory", "revenue_recognition", "free_cash_flow"],
        corporate_finance_focus=["roic", "capital_allocation", "wacc"],
        academy_concept_priority=["roic", "working_capital", "free_cash_flow", "wacc"],
        valuation_methodology=["ev_ebitda", "pe"],
        preferred_multiples=["EV/EBITDA", "P/E"],
        forecast_drivers=["oem_volumes", "content_growth", "exports"],
        risk_factors=["oem_concentration", "commodity", "ev_content_shift"],
        industry_mental_models=["content_growth_can_beat_volume"],
        decision_framework=["Map EV content risk/opportunity explicitly"],
        common_mistakes=["ICE-only content assumptions"],
        monitoring_signals=["margins", "working_capital", "order_book"],
        iie_focus=["technology", "oem_relationships", "localisation"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "capital_goods": _fw(
        sector_id="capital_goods",
        name="Capital Goods",
        required_kpis=["order_book", "order_inflow", "execution", "margins", "working_capital", "roce"],
        priority_metrics=["order_book", "inflow", "working_capital", "roce"],
        accounting_focus=["revenue_recognition", "working_capital", "contract_assets", "free_cash_flow"],
        corporate_finance_focus=["roic", "working_capital", "capital_allocation", "wacc"],
        academy_concept_priority=["working_capital", "revenue_recognition", "roic", "free_cash_flow", "wacc"],
        valuation_methodology=["pe", "ev_ebitda", "dcf_fcff"],
        preferred_multiples=["P/E", "EV/EBITDA"],
        forecast_drivers=["order_inflow", "execution", "industrial_capex"],
        risk_factors=["order_deferrals", "working_capital", "execution"],
        industry_mental_models=["order_book_quality", "cash_conversion_on_projects"],
        decision_framework=["Require cash conversion on order-book growth"],
        common_mistakes=["Booking revenue quality from weak advances"],
        monitoring_signals=["order_inflow", "nwc", "margins"],
        iie_focus=["franchise", "execution", "cycle"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "infrastructure": _fw(
        sector_id="infrastructure",
        name="Infrastructure / EPC",
        required_kpis=["order_book", "execution", "ham_bot_mix", "receivables", "leverage", "roce"],
        priority_metrics=["order_book", "receivables", "leverage", "asset_monetisation"],
        accounting_focus=["revenue_recognition", "receivables", "working_capital", "free_cash_flow"],
        corporate_finance_focus=["capital_allocation", "financial_leverage", "wacc", "roic"],
        academy_concept_priority=["working_capital", "financial_leverage", "free_cash_flow", "wacc", "capital_allocation"],
        valuation_methodology=["sotp", "pe", "dcf_fcff"],
        preferred_multiples=["P/B", "P/E"],
        forecast_drivers=["awards", "execution", "funding"],
        risk_factors=["receivables", "funding", "execution", "policy"],
        industry_mental_models=["asset_light_vs_asset_heavy"],
        decision_framework=["Separate EPC profits from annuity/asset ownership"],
        common_mistakes=["Double counting EPC and asset NPV"],
        monitoring_signals=["receivables", "order_book", "net_debt"],
        iie_focus=["execution", "balance_sheet", "policy_pipeline"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "real_estate": _fw(
        sector_id="real_estate",
        name="Real Estate",
        required_kpis=["presales", "collections", "launches", "business_development", "net_debt", "margins"],
        priority_metrics=["presales", "collections", "net_debt", "operating_cash"],
        accounting_focus=["revenue_recognition", "inventory", "working_capital", "free_cash_flow"],
        corporate_finance_focus=["capital_allocation", "financial_leverage", "wacc"],
        academy_concept_priority=["revenue_recognition", "working_capital", "financial_leverage", "free_cash_flow", "wacc"],
        valuation_methodology=["nav", "sotp", "pe"],
        preferred_multiples=["P/NAV", "P/E"],
        forecast_drivers=["presales", "launches", "mortgage_rates", "collections"],
        risk_factors=["funding", "approvals", "inventory", "rate_cycle"],
        industry_mental_models=["collections_not_bookings", "nav_haircuts"],
        decision_framework=["Prefer collections and BD discipline over booking optics"],
        common_mistakes=["Valuing unsold inventory at brochure prices"],
        monitoring_signals=["presales", "collections", "net_debt"],
        iie_focus=["brand", "land_bank_quality", "funding"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "airlines": _fw(
        sector_id="airlines",
        name="Airlines",
        required_kpis=["ask", "rask", "cask", "load_factor", "fuel", "fx", "leverage", "fcf"],
        priority_metrics=["rask_cask_spread", "load_factor", "fuel", "leverage"],
        accounting_focus=["leases", "fuel_hedging", "exceptional_items", "free_cash_flow"],
        corporate_finance_focus=["financial_leverage", "wacc", "capital_allocation"],
        academy_concept_priority=["leases", "financial_leverage", "free_cash_flow", "wacc", "exceptional_items"],
        valuation_methodology=["ev_ebitdar", "dcf_fcff"],
        preferred_multiples=["EV/EBITDAR"],
        forecast_drivers=["ask", "load_factor", "fuel", "fx", "competitive_capacity"],
        risk_factors=["fuel", "fx", "capacity_wars", "leverage"],
        industry_mental_models=["unit_economics_per_ask", "lease_adjusted_leverage"],
        decision_framework=["Always lease-adjust; stress fuel/fx"],
        common_mistakes=["Ignoring off-balance sheet lease leverage"],
        monitoring_signals=["rask", "cask", "load_factor", "net_debt"],
        iie_focus=["network", "cost", "balance_sheet"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "shipping": _fw(
        sector_id="shipping",
        name="Shipping",
        required_kpis=["tce", "fleet_utilisation", "asset_values", "leverage", "fcf"],
        priority_metrics=["tce", "asset_values", "leverage"],
        accounting_focus=["depreciation", "impairment", "free_cash_flow"],
        corporate_finance_focus=["capital_allocation", "financial_leverage", "wacc"],
        academy_concept_priority=["free_cash_flow", "financial_leverage", "capital_allocation", "business_cycle"],
        valuation_methodology=["nav", "ev_ebitda"],
        preferred_multiples=["P/NAV", "EV/EBITDA"],
        forecast_drivers=["freight_rates", "fleet_supply", "oil_trade"],
        risk_factors=["rate_volatility", "asset_value_swings"],
        industry_mental_models=["asset_values_mean_revert"],
        decision_framework=["Link TCE to replacement/nav cycle"],
        common_mistakes=["Peak TCE multiples"],
        monitoring_signals=["tce", "asset_values", "net_debt"],
        iie_focus=["fleet_age", "segment_exposure"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "logistics": _fw(
        sector_id="logistics",
        name="Logistics",
        required_kpis=["volume", "realisation", "network_density", "margins", "asset_turns", "roce"],
        priority_metrics=["volume", "margins", "roce", "network"],
        accounting_focus=["revenue_recognition", "working_capital", "leases", "free_cash_flow"],
        corporate_finance_focus=["roic", "capital_allocation", "wacc"],
        academy_concept_priority=["roic", "working_capital", "free_cash_flow", "wacc"],
        valuation_methodology=["ev_ebitda", "pe", "dcf_fcff"],
        preferred_multiples=["EV/EBITDA", "P/E"],
        forecast_drivers=["volumes", "pricing", "network_expansion"],
        risk_factors=["fuel", "competition", "client_concentration"],
        industry_mental_models=["density_creates_moat"],
        decision_framework=["Prefer network density economics over vanity GMV"],
        common_mistakes=["Confusing volume growth with ROCE"],
        monitoring_signals=["margins", "volume", "roce"],
        iie_focus=["network", "integration", "pricing_power"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "defence": _fw(
        sector_id="defence",
        name="Defence",
        required_kpis=["order_book", "execution", "indigenisation", "margins", "working_capital", "roce"],
        priority_metrics=["order_book", "execution", "indigenisation", "roce"],
        accounting_focus=["revenue_recognition", "working_capital", "contract_assets", "free_cash_flow"],
        corporate_finance_focus=["roic", "capital_allocation", "wacc"],
        academy_concept_priority=["revenue_recognition", "working_capital", "roic", "free_cash_flow"],
        valuation_methodology=["pe", "ev_ebitda", "dcf_fcff"],
        preferred_multiples=["P/E", "EV/EBITDA"],
        forecast_drivers=["orders", "execution", "defence_budget"],
        risk_factors=["execution", "offset", "working_capital", "policy"],
        industry_mental_models=["order_book_visibility", "working_capital_drag"],
        decision_framework=["Require execution/cash proof on large orders"],
        common_mistakes=["Capitalising order-book hype without margins"],
        monitoring_signals=["order_inflow", "nwc", "margins"],
        iie_focus=["technology", "indigenisation", "customer_concentration"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "media": _fw(
        sector_id="media",
        name="Media",
        required_kpis=["ad_growth", "subscription", "viewership", "margins", "content_cost", "fcf"],
        priority_metrics=["ad_growth", "subscription", "content_cost", "fcf"],
        accounting_focus=["revenue_recognition", "content_capitalisation", "free_cash_flow", "impairment"],
        corporate_finance_focus=["capital_allocation", "roic", "wacc"],
        academy_concept_priority=["free_cash_flow", "revenue_recognition", "capital_allocation", "wacc"],
        valuation_methodology=["ev_ebitda", "pe", "dcf_fcff"],
        preferred_multiples=["EV/EBITDA", "P/E"],
        forecast_drivers=["ad_cycle", "subscription", "content"],
        risk_factors=["ad_cycle", "cord_cutting", "content_inflation"],
        industry_mental_models=["ad_cyclicality", "content_roi"],
        decision_framework=["Separate cyclical ad from structural subscription"],
        common_mistakes=["Peak-ad multiples"],
        monitoring_signals=["ad_growth", "subscription", "content_cost"],
        iie_focus=["brand", "distribution", "content_slate"],
        suppress_generic_concepts=["risk_and_diversification"],
    ),
    "consumer_internet": _fw(
        sector_id="consumer_internet",
        name="Consumer Internet",
        required_kpis=["gmv", "take_rate", "contribution_margin", "users", "cohort_retention", "cash_burn", "rule_of_40"],
        priority_metrics=["take_rate", "contribution_margin", "retention", "path_to_fcf"],
        accounting_focus=["revenue_recognition", "deferred_revenue", "share_based_compensation", "free_cash_flow"],
        corporate_finance_focus=["capital_allocation", "wacc", "incremental_roic"],
        academy_concept_priority=["revenue_recognition", "deferred_revenue", "free_cash_flow", "wacc", "earnings_quality"],
        valuation_methodology=["ev_sales", "ev_gmv", "dcf_fcff"],
        preferred_multiples=["EV/Sales", "EV/GMV"],
        forecast_drivers=["users", "take_rate", "contribution", "competition"],
        risk_factors=["unit_economics", "competition", "regulation", "dilution"],
        industry_mental_models=["contribution_before_gmv", "retention_is_moat"],
        decision_framework=["No Buy without credible path to FCF and stable take-rate"],
        common_mistakes=["GMV vanity without contribution margins"],
        monitoring_signals=["contribution_margin", "take_rate", "burn", "retention"],
        iie_focus=["network_effects", "unit_economics", "competition"],
        suppress_generic_concepts=["risk_and_diversification", "nim"],
    ),
    "conglomerates": _fw(
        sector_id="conglomerates",
        name="Conglomerates",
        required_kpis=["segment_ebitda", "holding_company_discount", "capex", "net_debt", "capital_allocation", "roic_by_segment"],
        priority_metrics=["sotp_components", "capital_allocation", "holding_discount", "net_debt"],
        accounting_focus=["segment_reporting", "related_party", "exceptional_items", "free_cash_flow", "earnings_quality"],
        corporate_finance_focus=["capital_allocation", "roic_wacc_spread", "acquisition_quality", "share_buybacks", "wacc"],
        academy_concept_priority=[
            "capital_allocation", "roic_wacc_spread", "acquisition_quality", "free_cash_flow",
            "wacc", "earnings_quality", "share_buybacks", "value_creation",
        ],
        valuation_methodology=["sotp", "dcf_fcff", "ev_ebitda"],
        preferred_multiples=["SOTP", "EV/EBITDA"],
        forecast_drivers=["segment_cycles", "capex", "energy_retail_telecom_mix"],
        risk_factors=["complexity", "related_party", "capex_overload", "governance"],
        industry_mental_models=["sotp_with_haircuts", "capital_allocation_is_the_product"],
        decision_framework=[
            "Value segments with their own sector frameworks then apply holding discount",
            "Judge management as capital allocator across verticals",
        ],
        common_mistakes=["Single-multiple on blended conglomerate earnings"],
        monitoring_signals=["segment_ebitda", "capex", "net_debt", "related_party"],
        iie_focus=["capital_allocation", "governance", "segment_moats"],
        suppress_generic_concepts=["risk_and_diversification", "monetary_system"],
    ),
}


def get_framework(sector_id: str | None) -> SectorFramework | None:
    if not sector_id:
        return None
    return FRAMEWORKS.get(sector_id)


def list_frameworks() -> list[dict]:
    return [fw.to_dict() for fw in FRAMEWORKS.values()]
