"""Living accounting profiles — evidence-backed institutional memory (V1 seed).

Numbers and labels are tied to FIL corpus / disclosed metrics where available.
No accounting opinion without an evidence hook.
"""

from __future__ import annotations

from typing import Any

from accounting_intelligence.schema import AccountingObservation, ForensicInputs, PolicyChange

PROFILES: dict[str, dict[str, Any]] = {
    "HDFCBANK": {
        "ticker": "HDFCBANK",
        "company": "HDFC Bank",
        "sector": "banks",
        "latest_period": "Q1FY27",
        "behaviour_prior": ["Conservative and Consistent", "Highly Predictable"],
        "earnings": {
            "recurring_share": 0.96,
            "one_offs": "low",
            "exceptional_items": "nil_disclosed",
            "persistence": "high",
            "core_vs_reported": "aligned",
            "label_prior": "High",
            "notes": "Bank NI / PAT dominated by NII + fees; exceptional items nil in Q1FY27 presentation",
            "evidence_doc": "hdfc_pres_q1fy27",
        },
        "cash": {
            # Banks: cash conversion framed via credit cost / capital generation proxies
            "cfo_vs_ni": "strong_capital_generation",
            "cash_conversion": 0.92,
            "fcf_proxy": "capital_accretive",
            "trend": "stable",
            "notes": "CET1 17.4% / CAR 19.6% supports earnings durability; deposit mix pressure is funding not accrual",
            "evidence_doc": "hdfc_pres_q1fy27",
        },
        "accruals": {
            "accrual_ratio": 0.02,
            "receivable_growth": None,  # N/A bank
            "inventory_growth": None,
            "label_prior": "Healthy",
            "notes": "Credit cost contained; no evidence of aggressive fee accrual in Q1FY27 notes",
            "evidence_doc": "hdfc_pres_q1fy27",
        },
        "revenue": {
            "policy": "interest_and_fee_income_ind_as",
            "policy_change": False,
            "channel_stuffing_risk": "low",
            "early_recognition_risk": "low",
            "notes": "Interest income recognition standard; no material revenue recognition change vs prior notes",
            "evidence_doc": "hdfc_pres_q1fy27",
        },
        "working_capital": {
            # Bank liability franchise as WC analogue
            "dso_trend": "n/a_bank",
            "efficiency": "watch",
            "notes": "CASA 32.3% / time-deposit mix shift — funding efficiency deterioration, not classic WC accruals",
            "evidence_doc": "hdfc_pr_q1fy27",
            "casa": 32.3,
            "nim": 3.26,
        },
        "balance_sheet": {
            "liquidity": "strong",
            "leverage": "regulated_bank",
            "cet1": 17.4,
            "gnpa": 1.17,
            "goodwill_watch": "post_merger_monitoring",
            "contingent": "unchanged_notes",
            "notes": "Capital strong; GNPA 1.17%; goodwill monitoring ongoing post-merger",
            "evidence_doc": "hdfc_pres_q1fy27",
        },
        "policies": [
            PolicyChange(
                "hdfc_p_rev_q1fy27",
                "HDFCBANK",
                "Q1FY27",
                "2026-07-18",
                "revenue_recognition",
                "No material revenue recognition change vs prior quarter notes",
                "non_material",
                "hdfc_pres_q1fy27",
            ).to_dict(),
            PolicyChange(
                "hdfc_p_exceptional_q1fy27",
                "HDFCBANK",
                "Q1FY27",
                "2026-07-18",
                "exceptional_items",
                "Exceptional items nil",
                "non_material",
                "hdfc_pres_q1fy27",
            ).to_dict(),
        ],
        "forensic": ForensicInputs(
            dsri=1.0,
            gmi=1.02,  # NIM compression → mild margin pressure (not manipulation)
            aqi=1.0,
            sgi=1.05,
            depi=1.0,
            sgai=1.0,
            lvgi=1.0,
            tata=0.01,
            f_roa_pos=1,
            f_cfo_pos=1,
            f_roa_up=0,  # RoA under pressure with NIM
            f_accrual_ok=1,
            f_leverage_down=1,
            f_current_up=1,
            f_no_dilution=1,
            f_gross_margin_up=0,
            f_asset_turnover_up=1,
            bank_mode=True,
        ).to_dict(),
        "manipulation_flags": [],
        "observations": [
            AccountingObservation(
                "hdfc_o_pat",
                "HDFCBANK",
                "Q1FY27",
                "2026-07-18",
                "earnings",
                "PAT ₹190.6 bn with exceptional items nil",
                "hdfc_pres_q1fy27",
                2,
                "PAT",
                190.6,
                "₹ bn",
            ).to_dict(),
            AccountingObservation(
                "hdfc_o_cet1",
                "HDFCBANK",
                "Q1FY27",
                "2026-07-18",
                "balance_sheet",
                "CET1 17.4% / CAR 19.6% — capital quality supports reported earnings",
                "hdfc_pres_q1fy27",
                2,
                "CET1",
                17.4,
                "%",
            ).to_dict(),
            AccountingObservation(
                "hdfc_o_nim",
                "HDFCBANK",
                "Q1FY27",
                "2026-07-18",
                "earnings",
                "NIM 3.26% — earnings pressure from funding mix, not accounting policy",
                "hdfc_pr_q1fy27",
                4,
                "NIM",
                3.26,
                "%",
            ).to_dict(),
        ],
        "timeline_seed": [
            {"as_of": "2026-04-20", "period": "Q4FY26", "event": "Prior quarter accounting notes unchanged", "type": "policy"},
            {"as_of": "2026-07-18", "period": "Q1FY27", "event": "Exceptional items nil; revenue recognition unchanged", "type": "policy"},
            {"as_of": "2026-07-18", "period": "Q1FY27", "event": "NIM compression — economic, not accrual-driven", "type": "earnings"},
        ],
    },
    "NESTLEIND": {
        "ticker": "NESTLEIND",
        "company": "Nestlé India",
        "sector": "fmcg",
        "latest_period": "Q1FY27",
        "behaviour_prior": ["Conservative and Consistent", "Highly Predictable"],
        "earnings": {
            "recurring_share": 0.94,
            "one_offs": "low",
            "exceptional_items": "low",
            "persistence": "high",
            "core_vs_reported": "aligned",
            "label_prior": "High",
            "notes": "FMCG operating earnings; sales growth 25.4%, PAT ₹975.1 cr — brand franchise earnings",
            "evidence_doc": "nestle_bse_q1fy27",
        },
        "cash": {
            "cfo_vs_ni": "historically_strong",
            "cash_conversion": 0.88,
            "fcf_proxy": "positive",
            "trend": "stable",
            "notes": "Consumer staple cash conversion typically high; Q1 disclosure focuses on sales/PAT",
            "evidence_doc": "nestle_bse_q1fy27",
        },
        "accruals": {
            "accrual_ratio": 0.04,
            "receivable_growth": 0.06,
            "inventory_growth": 0.08,
            "label_prior": "Healthy",
            "notes": "No channel-stuffing language; growth disclosed as sales-led",
            "evidence_doc": "nestle_bse_q1fy27",
        },
        "revenue": {
            "policy": "ind_as_115_point_in_time",
            "policy_change": False,
            "channel_stuffing_risk": "low",
            "early_recognition_risk": "low",
            "notes": "No disclosed revenue recognition policy change in Q1FY27 filing stub",
            "evidence_doc": "nestle_bse_q1fy27",
        },
        "working_capital": {
            "dso_trend": "stable",
            "efficiency": "stable",
            "notes": "Working capital detail sparse in stub — flag as coverage gap",
            "evidence_doc": "nestle_bse_q1fy27",
            "coverage_gap": True,
        },
        "balance_sheet": {
            "liquidity": "strong",
            "leverage": "low",
            "goodwill_watch": "limited",
            "contingent": "standard",
            "notes": "Balance-sheet granularity limited in Q1 stub",
            "evidence_doc": "nestle_bse_q1fy27",
        },
        "policies": [
            PolicyChange(
                "nestle_p_rev_q1fy27",
                "NESTLEIND",
                "Q1FY27",
                "2026-07-17",
                "revenue_recognition",
                "No material policy change disclosed in Q1FY27 results",
                "non_material",
                "nestle_bse_q1fy27",
            ).to_dict(),
        ],
        "forensic": ForensicInputs(
            dsri=1.02,
            gmi=0.98,
            aqi=1.0,
            sgi=1.25,
            depi=1.0,
            sgai=1.0,
            lvgi=0.98,
            tata=0.03,
            f_roa_pos=1,
            f_cfo_pos=1,
            f_roa_up=1,
            f_accrual_ok=1,
            f_leverage_down=1,
            f_current_up=1,
            f_no_dilution=1,
            f_gross_margin_up=1,
            f_asset_turnover_up=1,
            z_wc_ta=0.25,
            z_re_ta=0.45,
            z_ebit_ta=0.22,
            z_me_tl=8.0,
            z_sales_ta=1.4,
            bank_mode=False,
        ).to_dict(),
        "manipulation_flags": [],
        "observations": [
            AccountingObservation(
                "nestle_o_pat",
                "NESTLEIND",
                "Q1FY27",
                "2026-07-17",
                "earnings",
                "PAT ₹975.1 crore on sales growth 25.4%",
                "nestle_bse_q1fy27",
                2,
                "PAT",
                975.1,
                "₹ cr",
            ).to_dict(),
        ],
        "timeline_seed": [
            {"as_of": "2026-07-17", "period": "Q1FY27", "event": "Sales +25.4% / PAT disclosed; no policy change flagged", "type": "earnings"},
        ],
    },
    "TCS": {
        "ticker": "TCS",
        "company": "Tata Consultancy Services",
        "sector": "it_services",
        "latest_period": "Q1FY27",
        "behaviour_prior": ["Conservative", "Highly Predictable"],
        "earnings": {
            "recurring_share": 0.97,
            "one_offs": "low",
            "exceptional_items": "low",
            "persistence": "high",
            "core_vs_reported": "aligned",
            "label_prior": "High",
            "notes": "Services revenue + operating margins historically cash-backed; V1 profile uses sector priors pending denser FIL",
            "evidence_doc": "tcs_profile_prior",
        },
        "cash": {
            "cfo_vs_ni": "strong",
            "cash_conversion": 0.95,
            "fcf_proxy": "strong",
            "trend": "stable",
            "notes": "IT services typically high cash conversion; coverage pending full cash-flow filing ingest",
            "evidence_doc": "tcs_profile_prior",
        },
        "accruals": {
            "accrual_ratio": 0.03,
            "receivable_growth": 0.05,
            "inventory_growth": None,
            "deferred_revenue": "monitored",
            "label_prior": "Healthy",
            "notes": "Contract assets / deferred revenue are primary IT accrual watchpoints",
            "evidence_doc": "tcs_profile_prior",
        },
        "revenue": {
            "policy": "ind_as_115_over_time",
            "policy_change": False,
            "channel_stuffing_risk": "n/a",
            "early_recognition_risk": "watch_contract_assets",
            "notes": "Over-time recognition; no V1 policy-change evidence yet",
            "evidence_doc": "tcs_profile_prior",
        },
        "working_capital": {
            "dso_trend": "stable",
            "efficiency": "stable",
            "notes": "DSO / unbilled revenue detail pending denser FIL",
            "evidence_doc": "tcs_profile_prior",
            "coverage_gap": True,
        },
        "balance_sheet": {
            "liquidity": "strong",
            "leverage": "net_cash",
            "goodwill_watch": "limited",
            "contingent": "standard",
            "notes": "Net-cash IT franchise balance sheet (sector prior)",
            "evidence_doc": "tcs_profile_prior",
        },
        "policies": [],
        "forensic": ForensicInputs(
            dsri=1.03,
            gmi=1.0,
            aqi=1.0,
            sgi=1.08,
            depi=1.0,
            sgai=1.0,
            lvgi=0.95,
            tata=0.02,
            f_roa_pos=1,
            f_cfo_pos=1,
            f_roa_up=1,
            f_accrual_ok=1,
            f_leverage_down=1,
            f_current_up=1,
            f_no_dilution=1,
            f_gross_margin_up=1,
            f_asset_turnover_up=1,
            z_wc_ta=0.35,
            z_re_ta=0.5,
            z_ebit_ta=0.28,
            z_me_tl=12.0,
            z_sales_ta=1.1,
            bank_mode=False,
        ).to_dict(),
        "manipulation_flags": [],
        "observations": [
            AccountingObservation(
                "tcs_o_prior",
                "TCS",
                "Q1FY27",
                "2026-07-01",
                "earnings",
                "Accounting quality prior: cash-rich IT services model — denser FIL tables pending",
                "tcs_profile_prior",
                1,
            ).to_dict(),
        ],
        "timeline_seed": [
            {"as_of": "2026-07-01", "period": "Q1FY27", "event": "ACI profile seeded — awaiting denser cash-flow / WC filings", "type": "coverage"},
        ],
    },
}


def list_profiles() -> list[str]:
    return sorted(PROFILES.keys())


def profile_for(ticker: str) -> dict[str, Any] | None:
    t = (ticker or "").upper().replace(".NS", "").replace(".BO", "")
    aliases = {"HDFC": "HDFCBANK", "NESTLE": "NESTLEIND", "TATA CONSULTANCY SERVICES": "TCS"}
    t = aliases.get(t, t)
    p = PROFILES.get(t)
    return dict(p) if p else None
