"""Institutional question library — templates by hypothesis theme and investigation layer."""

from __future__ import annotations

from typing import Any

# Each template: question (with {entity}/{peer} placeholders), type, priority, evidence, impact, tree_layer, deps_layers
QuestionTemplate = dict[str, Any]

# Universal layers that every hypothesis must investigate
_UNIVERSAL: list[QuestionTemplate] = [
    {
        "question": "Over the last ten years, what measurable evidence supports the claim that {entity} holds this advantage versus history?",
        "type": "Historical",
        "priority": "Critical",
        "evidence": ["FIL", "Historical series"],
        "impact": 9,
        "tree_layer": "Historical",
        "depends_on_layers": [],
    },
    {
        "question": "How did the same metric behave for {entity} during previous stress or rate-hiking cycles?",
        "type": "Historical",
        "priority": "Important",
        "evidence": ["Historical", "Macro"],
        "impact": 8,
        "tree_layer": "Historical",
        "depends_on_layers": [],
    },
    {
        "question": "Has {entity}'s claimed advantage remained above the peer median versus {peer} over the last decade?",
        "type": "Peer",
        "priority": "Critical",
        "evidence": ["PIL", "FIL"],
        "impact": 10,
        "tree_layer": "Peer",
        "depends_on_layers": ["Historical"],
    },
    {
        "question": "Which peer among {peer} improved the relevant quality metric faster than {entity} over the last five years?",
        "type": "Peer",
        "priority": "Important",
        "evidence": ["PIL"],
        "impact": 8,
        "tree_layer": "Peer",
        "depends_on_layers": ["Historical"],
    },
    {
        "question": "Is the market already pricing this hypothesis for {entity} through current valuation multiples versus history?",
        "type": "Valuation",
        "priority": "Critical",
        "evidence": ["PIL", "Valuation"],
        "impact": 10,
        "tree_layer": "Valuation",
        "depends_on_layers": ["Peer"],
    },
    {
        "question": "What forward earnings or growth path would be required for {entity} to justify today's premium if this hypothesis is only partially true?",
        "type": "Forecast",
        "priority": "Important",
        "evidence": ["Forecast", "Valuation"],
        "impact": 8,
        "tree_layer": "Forecast",
        "depends_on_layers": ["Valuation"],
    },
    {
        "question": "What observable evidence would contradict or falsify this hypothesis for {entity} within the next four quarters?",
        "type": "Contradiction",
        "priority": "Critical",
        "evidence": ["Risk", "FIL"],
        "impact": 10,
        "tree_layer": "Peer",
        "depends_on_layers": ["Historical"],
    },
    {
        "question": "Has management commentary acknowledged risks that would undermine this hypothesis for {entity}?",
        "type": "Contradiction",
        "priority": "Important",
        "evidence": ["FIL", "Transcript"],
        "impact": 8,
        "tree_layer": "Historical",
        "depends_on_layers": [],
    },
    {
        "question": "What would eliminate this advantage for {entity} — regulation, competition, or macro regime shift?",
        "type": "Contradiction",
        "priority": "Critical",
        "evidence": ["Risk", "Macro"],
        "impact": 9,
        "tree_layer": "Forecast",
        "depends_on_layers": ["Valuation"],
    },
    {
        "question": "Does portfolio construction still improve if this hypothesis for {entity} is only half as strong as assumed?",
        "type": "Portfolio",
        "priority": "Supporting",
        "evidence": ["Portfolio", "Risk"],
        "impact": 5,
        "tree_layer": "Forecast",
        "depends_on_layers": ["Valuation"],
    },
]

_BY_THEME: dict[str, list[QuestionTemplate]] = {
    "Business": [
        {
            "question": "Has {entity}'s CASA ratio remained above peer median versus {peer} during the last ten years?",
            "type": "Verification",
            "priority": "Critical",
            "evidence": ["FIL", "PIL"],
            "impact": 10,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
        {
            "question": "Has the funding or franchise advantage of {entity} narrowed versus {peer} over the last three years?",
            "type": "Peer",
            "priority": "Critical",
            "evidence": ["PIL"],
            "impact": 10,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "Has management acknowledged deposit or franchise competition for {entity} in conference calls?",
            "type": "Management",
            "priority": "Important",
            "evidence": ["FIL", "Transcript"],
            "impact": 8,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "How resilient was CASA or deposit mix for {entity} during previous rate hiking cycles?",
            "type": "Historical",
            "priority": "Critical",
            "evidence": ["Historical", "Macro"],
            "impact": 9,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
        {
            "question": "What would eliminate {entity}'s funding advantage relative to {peer}?",
            "type": "Risk",
            "priority": "Critical",
            "evidence": ["Risk", "Macro"],
            "impact": 9,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
        {
            "question": "Which peer improved funding quality faster than {entity} over the last five years?",
            "type": "Peer",
            "priority": "Important",
            "evidence": ["PIL"],
            "impact": 8,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "Is the market already pricing {entity}'s funding advantage in the current valuation premium?",
            "type": "Valuation",
            "priority": "Critical",
            "evidence": ["PIL", "Valuation"],
            "impact": 10,
            "tree_layer": "Valuation",
            "depends_on_layers": ["Peer"],
        },
        {
            "question": "Has cost of funds for {entity} stayed structurally below {peer} on a through-cycle basis?",
            "type": "Financial",
            "priority": "Important",
            "evidence": ["FIL", "PIL"],
            "impact": 8,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "Did branch or digital acquisition productivity for {entity} deteriorate versus {peer} recently?",
            "type": "Business",
            "priority": "Supporting",
            "evidence": ["FIL", "Business"],
            "impact": 5,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "Would a prolonged liquidity squeeze reverse {entity}'s deposit franchise lead within two years?",
            "type": "Contradiction",
            "priority": "Important",
            "evidence": ["Macro", "Risk"],
            "impact": 8,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
    ],
    "Valuation": [
        {
            "question": "What is the current PE percentile for {entity} versus its own ten-year history?",
            "type": "Valuation",
            "priority": "Critical",
            "evidence": ["PIL", "Valuation"],
            "impact": 10,
            "tree_layer": "Valuation",
            "depends_on_layers": ["Peer"],
        },
        {
            "question": "What is the current PB percentile for {entity} versus its own history?",
            "type": "Valuation",
            "priority": "Critical",
            "evidence": ["PIL", "Valuation"],
            "impact": 9,
            "tree_layer": "Valuation",
            "depends_on_layers": ["Peer"],
        },
        {
            "question": "What is the forward PE percentile for {entity} relative to the last decade?",
            "type": "Valuation",
            "priority": "Critical",
            "evidence": ["PIL", "Forecast"],
            "impact": 10,
            "tree_layer": "Valuation",
            "depends_on_layers": ["Peer"],
        },
        {
            "question": "What premium does {entity} trade at versus the broader market index today?",
            "type": "Peer",
            "priority": "Important",
            "evidence": ["PIL"],
            "impact": 8,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "What premium does {entity} trade at versus global tech or sector comps such as Nasdaq Tech where relevant?",
            "type": "Peer",
            "priority": "Supporting",
            "evidence": ["PIL"],
            "impact": 6,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "Is the premium versus {entity}'s own history justified by earnings growth differentials?",
            "type": "Forecast",
            "priority": "Critical",
            "evidence": ["Forecast", "Valuation"],
            "impact": 10,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
        {
            "question": "What happened historically when {entity} valuation reached similar percentile levels?",
            "type": "Historical",
            "priority": "Critical",
            "evidence": ["Historical", "PIL"],
            "impact": 9,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
        {
            "question": "Could mean-reversion alone erase expected returns for {entity} even if fundamentals hold?",
            "type": "Contradiction",
            "priority": "Critical",
            "evidence": ["Valuation", "Risk"],
            "impact": 9,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
        {
            "question": "Has relative valuation versus {peer} compressed or expanded over the last five years?",
            "type": "Historical",
            "priority": "Important",
            "evidence": ["Historical", "PIL"],
            "impact": 7,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
        {
            "question": "Would a growth miss of 200 bps invalidate the current multiple for {entity}?",
            "type": "Contradiction",
            "priority": "Important",
            "evidence": ["Forecast", "Risk"],
            "impact": 8,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
    ],
    "Financial": [
        {
            "question": "Have credit costs for {entity} remained below peer mid-cycle averages versus {peer}?",
            "type": "Verification",
            "priority": "Critical",
            "evidence": ["FIL", "PIL"],
            "impact": 10,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "How did GNPA/NNPA for {entity} behave through the last credit cycle versus history?",
            "type": "Historical",
            "priority": "Critical",
            "evidence": ["Historical", "FIL"],
            "impact": 9,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
        {
            "question": "Is the secured versus unsecured mix for {entity} still structurally safer than {peer}?",
            "type": "Peer",
            "priority": "Important",
            "evidence": ["FIL", "PIL"],
            "impact": 8,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "Would a 50 bps rise in credit costs eliminate the earnings thesis for {entity}?",
            "type": "Contradiction",
            "priority": "Critical",
            "evidence": ["Risk", "Forecast"],
            "impact": 10,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
        {
            "question": "Has cash conversion / ROIC for {entity} stayed superior to {peer} for five or more years?",
            "type": "Financial",
            "priority": "Important",
            "evidence": ["FIL", "PIL"],
            "impact": 8,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "Are accounting choices for {entity} inflating reported quality versus economic cash returns?",
            "type": "Accounting",
            "priority": "Important",
            "evidence": ["Accounting", "FIL"],
            "impact": 7,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
        {
            "question": "Did leverage or liquidity metrics for {entity} deteriorate versus {peer} recently?",
            "type": "Risk",
            "priority": "Important",
            "evidence": ["FIL", "Risk"],
            "impact": 8,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "What historical precedent exists for credit-cost spikes after similar growth phases at {entity}?",
            "type": "Historical",
            "priority": "Supporting",
            "evidence": ["Historical"],
            "impact": 6,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
    ],
    "Competitive": [
        {
            "question": "Is competitive intensity from {peer} narrowing {entity}'s historical advantage in deposits, digital, or loan growth?",
            "type": "Peer",
            "priority": "Critical",
            "evidence": ["PIL", "Business"],
            "impact": 10,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "Has market share for {entity} risen or fallen versus {peer} over five years?",
            "type": "Historical",
            "priority": "Critical",
            "evidence": ["Historical", "PIL"],
            "impact": 9,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
        {
            "question": "Are pricing or fee differentials versus {peer} compressing for {entity}?",
            "type": "Verification",
            "priority": "Important",
            "evidence": ["FIL", "PIL"],
            "impact": 8,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "What evidence would show the competitive gap has already closed for {entity}?",
            "type": "Contradiction",
            "priority": "Critical",
            "evidence": ["PIL", "Risk"],
            "impact": 9,
            "tree_layer": "Valuation",
            "depends_on_layers": ["Peer"],
        },
        {
            "question": "Has management of {entity} changed strategy in response to {peer} encroachment?",
            "type": "Management",
            "priority": "Supporting",
            "evidence": ["Transcript", "FIL"],
            "impact": 5,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
    ],
    "Forecast": [
        {
            "question": "Is consensus growth for {entity} already embedding the optimistic path required by this hypothesis?",
            "type": "Forecast",
            "priority": "Critical",
            "evidence": ["Forecast", "PIL"],
            "impact": 10,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
        {
            "question": "How often did similar growth forecasts for {entity} miss over the last decade?",
            "type": "Historical",
            "priority": "Important",
            "evidence": ["Historical", "Forecast"],
            "impact": 7,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
        {
            "question": "Do peer growth revisions for {peer} lead or lag {entity}?",
            "type": "Peer",
            "priority": "Important",
            "evidence": ["PIL", "Forecast"],
            "impact": 7,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "What macro path would force a downward revision that breaks the thesis for {entity}?",
            "type": "Macro",
            "priority": "Critical",
            "evidence": ["Macro", "Risk"],
            "impact": 9,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
        {
            "question": "Would two consecutive negative revision quarters falsify the growth hypothesis for {entity}?",
            "type": "Contradiction",
            "priority": "Critical",
            "evidence": ["Forecast", "Risk"],
            "impact": 9,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
    ],
    "Macro": [
        {
            "question": "Through which channel — NIM, volumes, or multiples — does the macro path affect {entity} most?",
            "type": "Macro",
            "priority": "Critical",
            "evidence": ["Macro", "FIL"],
            "impact": 10,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
        {
            "question": "How did {entity} perform versus {peer} in the last easing or hiking cycle?",
            "type": "Historical",
            "priority": "Critical",
            "evidence": ["Historical", "PIL"],
            "impact": 9,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
        {
            "question": "Is the macro recovery already priced into {entity} relative to {peer}?",
            "type": "Valuation",
            "priority": "Critical",
            "evidence": ["PIL", "Valuation"],
            "impact": 9,
            "tree_layer": "Valuation",
            "depends_on_layers": ["Peer"],
        },
        {
            "question": "Which peer captures incremental demand faster if the macro thesis is correct?",
            "type": "Peer",
            "priority": "Important",
            "evidence": ["PIL", "Macro"],
            "impact": 7,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "What macro miss would contradict the investment implication for {entity}?",
            "type": "Contradiction",
            "priority": "Critical",
            "evidence": ["Macro", "Risk"],
            "impact": 9,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
    ],
    "Risk": [
        {
            "question": "Which regulatory, funding, or concentration risk could invalidate the thesis for {entity} even if near-term earnings hold?",
            "type": "Risk",
            "priority": "Critical",
            "evidence": ["Risk", "FIL"],
            "impact": 10,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
        {
            "question": "Have similar risk flags appeared historically before drawdowns in {entity}?",
            "type": "Historical",
            "priority": "Important",
            "evidence": ["Historical", "Risk"],
            "impact": 8,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
        {
            "question": "Are peers such as {peer} better capitalised against the same risk factor?",
            "type": "Peer",
            "priority": "Important",
            "evidence": ["PIL", "Risk"],
            "impact": 7,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "Is the market underpricing this risk in {entity}'s current multiple?",
            "type": "Valuation",
            "priority": "Critical",
            "evidence": ["Valuation", "Risk"],
            "impact": 9,
            "tree_layer": "Valuation",
            "depends_on_layers": ["Peer"],
        },
        {
            "question": "What evidence would show the risk is already materialising for {entity}?",
            "type": "Contradiction",
            "priority": "Critical",
            "evidence": ["Risk", "FIL"],
            "impact": 9,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
    ],
    "Industry": [
        {
            "question": "Is sector AI or growth optimism for {entity} supported by observable order books versus narrative alone?",
            "type": "Verification",
            "priority": "Critical",
            "evidence": ["FIL", "Industry"],
            "impact": 9,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "Where does sector valuation for {entity} sit versus its own historical range?",
            "type": "Historical",
            "priority": "Critical",
            "evidence": ["Historical", "PIL"],
            "impact": 10,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
        {
            "question": "How does {entity} premium compare versus {peer} on growth-adjusted multiples?",
            "type": "Peer",
            "priority": "Important",
            "evidence": ["PIL"],
            "impact": 8,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "What prior cycle outcome followed similar sector premiums for {entity}?",
            "type": "Historical",
            "priority": "Important",
            "evidence": ["Historical"],
            "impact": 7,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
        {
            "question": "Would fading order momentum falsify the sector premium thesis for {entity}?",
            "type": "Contradiction",
            "priority": "Critical",
            "evidence": ["Industry", "Risk"],
            "impact": 9,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
    ],
    "Portfolio": [
        {
            "question": "Does adding {entity} diversify existing factor exposure or concentrate the same macro beta?",
            "type": "Portfolio",
            "priority": "Critical",
            "evidence": ["Portfolio", "Risk"],
            "impact": 10,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
        {
            "question": "How correlated has {entity} been with current financials holdings versus {peer} historically?",
            "type": "Historical",
            "priority": "Important",
            "evidence": ["Historical", "Portfolio"],
            "impact": 7,
            "tree_layer": "Historical",
            "depends_on_layers": [],
        },
        {
            "question": "What position size still improves risk-adjusted portfolio quality if the thesis is only partially true?",
            "type": "Portfolio",
            "priority": "Important",
            "evidence": ["Portfolio", "Risk"],
            "impact": 8,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
        {
            "question": "Would replacing {entity} with {peer} raise or lower portfolio drawdown contribution?",
            "type": "Peer",
            "priority": "Supporting",
            "evidence": ["Portfolio", "PIL"],
            "impact": 6,
            "tree_layer": "Peer",
            "depends_on_layers": ["Historical"],
        },
        {
            "question": "What portfolio constraint would force rejection of {entity} despite a strong stock thesis?",
            "type": "Contradiction",
            "priority": "Critical",
            "evidence": ["Portfolio", "Risk"],
            "impact": 9,
            "tree_layer": "Forecast",
            "depends_on_layers": ["Valuation"],
        },
    ],
}


def templates_for_hypothesis_type(hypothesis_type: str) -> list[QuestionTemplate]:
    theme = (hypothesis_type or "Business").strip()
    themed = list(_BY_THEME.get(theme) or [])
    # Fall back: map related types
    if not themed:
        if theme in ("Capital Allocation", "Accounting", "Management"):
            themed = list(_BY_THEME.get("Financial") or [])
        else:
            themed = list(_BY_THEME.get("Business") or [])
    # Merge universal + themed (universal first for tree spine)
    merged = list(_UNIVERSAL) + themed
    return merged


def library_stats() -> dict[str, Any]:
    return {
        "universal_templates": len(_UNIVERSAL),
        "theme_count": len(_BY_THEME),
        "themes": sorted(_BY_THEME.keys()),
        "total_themed_templates": sum(len(v) for v in _BY_THEME.values()),
    }
