# Phase 3.1 Industry DNA — Part 2 (32 industries)

add(
    key="it_services", name="IT Services", aliases=["it", "it services", "technology services", "outsourcing"],
    revenue_drivers=["Client spend", "Deal wins", "Billing rates", "Utilization"],
    margin_drivers=["Utilization", "Pyramid mix", "Offshore leverage", "Pricing"],
    cost_drivers=["Employee cost", "Subcontractors", "Delivery centers", "Sales"],
    value_drivers=["Revenue Growth", "Utilization", "Attrition", "Deal Pipeline", "Offshore Mix"],
    capital_intensity="Asset-light — people and delivery centers",
    working_capital="Receivables and unbilled revenue; low inventory",
    cash_conversion="Strong when DSO controlled and capex light",
    operating_leverage="High — bench and fixed delivery cost vs billable hours",
    pricing_power="Moderate — contracts and skill scarcity offset commoditization",
    competitive_structure="global",
    porter=P("Medium — brand, scale, delivery track record", "Medium — talent markets", "High — large clients", "Medium — captives, automation", "High"),
    concentration="Global oligopoly of large vendors; long tail of niche players",
    regulators=["SEBI", "RBI (FX/repatriation)", "Labour/IT Act"],
    regulatory_risks=["Visa/immigration", "Data localization", "Labour compliance"],
    valuation_methods=["P/E", "EV/EBITDA", "EV/Sales"],
    valuation_why="Earnings and EBITDA reflect utilization-led operating leverage on fee revenue",
    lifecycle="mature", typical_roic="High teens to mid-20s ROIC for quality franchises",
    typical_growth="GDP+ when client tech spend expands; cyclical with US/EU budgets",
    typical_risks=["Client concentration", "Attrition", "FX", "Automation/disruption"],
    risk_weightings={"demand": "High", "execution": "High", "regulatory": "Medium", "refinancing": "Low", "commodity": "Low"},
    macro_sensitivity=["USD/INR", "Global IT spend", "US/EU GDP"],
    customers=["BFSI", "Retail", "Healthcare", "Manufacturing"], suppliers=["Talent", "Cloud vendors", "Subcontractors"],
    adjacent_industries=["software", "data_centers", "banks"], substitutes=["Captives", "Low-cost regions", "GenAI automation"],
    capital_allocation_typical="Dividends and buybacks; modest capex on centers and tools",
    kpis=[
        K("utilization", "Utilization", "Billable / available hours", "Margin lever", "High stable", "Falling", ["EBIT margin"]),
        K("attrition", "Attrition", "Voluntary exits / avg headcount", "Delivery stability", "Low vs peers", "Spiking", ["Utilization", "Pyramid"]),
        K("billing_rate", "Billing Rate", "Revenue per billable hour/FTE", "Pricing power", "Stable/rising", "Compressing", ["Mix"]),
        K("offshore_mix", "Offshore Mix", "Offshore delivery / total", "Cost structure", "High", "Falling", ["Margin"]),
        K("dso", "DSO", "Receivables / daily revenue", "Cash conversion", "Low", "Rising", ["WC"]),
    ],
    why_margins="Utilization and offshore pyramid drive gross margin; SG&A scales with revenue",
    why_roic="Minimal invested capital; returns driven by human capital productivity",
    why_leverage="Low financial leverage; high operating leverage on bench",
    why_working_capital="Receivables cycle with milestone billing; minimal inventory",
    why_valuation="P/E and EV/EBITDA capture earnings power without heavy assets",
    primary_cycle="technology_cycle",
)

add(
    key="software", name="Software", aliases=["saas", "software products", "product software"],
    revenue_drivers=["License/subscription ARR", "Seat expansion", "Upsell/cross-sell", "Renewals"],
    margin_drivers=["Gross margin on software", "R&D efficiency", "CAC payback", "Churn"],
    cost_drivers=["R&D", "Sales & marketing", "Cloud hosting", "Support"],
    value_drivers=["ARR Growth", "Net Retention", "Gross Margin", "Rule of 40", "CAC/LTV"],
    capital_intensity="Asset-light — R&D and GTM are the investment",
    working_capital="Deferred revenue and receivables; negative WC possible in SaaS",
    cash_conversion="Strong at scale when churn low and CAC disciplined",
    operating_leverage="Very high — incremental ARR drops through after R&D base",
    pricing_power="Moderate-High for mission-critical products; weak for commoditized tools",
    competitive_structure="fragmented",
    porter=P("Medium — product, distribution, switching costs", "Low-Medium — cloud, talent", "Medium-High — enterprises", "Medium — open source, build", "High"),
    concentration="Fragmented with category leaders in niches",
    regulators=["SEBI", "MeitY", "DPDP Act"],
    regulatory_risks=["Data privacy", "Export controls", "IP protection"],
    valuation_methods=["EV/Sales", "EV/ARR", "P/E", "DCF"],
    valuation_why="Growth and recurring revenue justify sales multiples before mature earnings",
    lifecycle="growth", typical_roic="High when growth efficient; negative early",
    typical_growth="Double-digit ARR for winners; wide dispersion",
    typical_risks=["Churn", "Competition", "R&D misallocation", "Valuation"],
    risk_weightings={"demand": "High", "execution": "High", "regulatory": "Medium", "market": "High"},
    macro_sensitivity=["Enterprise IT budgets", "Rates (growth multiples)", "USD/INR"],
    customers=["Enterprises", "SMBs", "Government"], suppliers=["Cloud (AWS/Azure)", "Talent", "Open-source ecosystem"],
    adjacent_industries=["it_services", "data_centers", "internet_platforms"], substitutes=["Open source", "In-house build", "IT services"],
    capital_allocation_typical="Reinvest in R&D and S&M; M&A for product expansion",
    kpis=[
        K("arr_growth", "ARR Growth", "Change in annual recurring revenue", "Top-line momentum", "Strong", "Decelerating", ["NRR"]),
        K("nrr", "Net Revenue Retention", "Expansion − churn on cohort", "Land-and-expand", ">100%", "<90%", ["ARR"]),
        K("gross_margin", "Gross Margin", "Gross profit / revenue", "Software economics", "High 70%+", "Compressing", ["Hosting"]),
        K("churn", "Logo/Churn Rate", "Lost customers / base", "Durability", "Low", "Rising", ["NRR"]),
        K("cac_payback", "CAC Payback", "Months to recover CAC", "Unit economics", "Short", "Lengthening", ["LTV"]),
    ],
    why_margins="High gross margin on software; S&M and R&D determine EBIT",
    why_roic="Capital-light; ROIC rises as R&D amortizes over growing ARR",
    why_leverage="Low debt typical; operating leverage on fixed R&D",
    why_working_capital="Deferred revenue can fund growth; receivables on enterprise terms",
    why_valuation="EV/Sales and EV/ARR price recurring growth before profitability",
    primary_cycle="technology_cycle",
)

add(
    key="retail", name="Retail", aliases=["retail", "organised retail", "department stores", "e-commerce retail"],
    revenue_drivers=["Same-store sales", "Store expansion", "Ticket size", "Category mix"],
    margin_drivers=["Gross margin", "Inventory shrink", "Rent/occupancy", "Promotions"],
    cost_drivers=["COGS", "Rent", "Labour", "Logistics", "Marketing"],
    value_drivers=["SSSG", "GMROI", "Inventory Turns", "Store Productivity", "EBITDAR"],
    capital_intensity="Moderate — stores, fixtures, working capital in inventory",
    working_capital="Inventory-heavy; payables offset partially",
    cash_conversion="Moderate — inventory days and rent cycles matter",
    operating_leverage="Moderate — fixed rent and store costs vs revenue",
    pricing_power="Low-Moderate — promotions and competition limit",
    competitive_structure="fragmented",
    porter=P("Medium — real estate, brand, supply chain", "Medium — brands/manufacturers", "High — consumers", "High — e-commerce, D2C", "High"),
    concentration="Fragmented; modern trade consolidating in pockets",
    regulators=["FSSAI", "Legal Metrology", "Consumer Protection", "SEBI"],
    regulatory_risks=["FSSAI compliance", "E-commerce policy", "GST"],
    valuation_methods=["EV/EBITDA", "EV/Sales", "P/E"],
    valuation_why="EBITDA after rent captures store economics; sales for early-stage formats",
    lifecycle="growth", typical_roic="Low to mid-teens for efficient operators",
    typical_growth="SSSG plus new stores; e-commerce faster",
    typical_risks=["Competition", "Inventory obsolescence", "Rent escalation", "Consumer slowdown"],
    risk_weightings={"demand": "High", "execution": "High", "regulatory": "Medium", "refinancing": "Low"},
    macro_sensitivity=["Consumer confidence", "Inflation", "Urban income"],
    customers=["Mass market", "Urban consumers"], suppliers=["FMCG", "Apparel brands", "Private label"],
    adjacent_industries=["fmcg", "logistics", "internet_platforms", "qsr"], substitutes=["E-commerce", "Wholesale", "D2C"],
    capital_allocation_typical="Capex on stores and supply chain; working capital for inventory",
    kpis=[
        K("sssg", "SSSG", "Same-store sales growth", "Organic momentum", "Positive", "Negative", ["Traffic", "Ticket"]),
        K("inventory_days", "Inventory Days", "Inventory / COGS × days", "Working capital", "Low vs category", "Rising", ["GMROI"]),
        K("gmroi", "GMROI", "Gross margin / avg inventory", "Inventory productivity", "High", "Falling", ["Turns"]),
        K("sales_per_sqft", "Sales per Sq Ft", "Revenue / retail area", "Store productivity", "Rising", "Stagnant", ["Rent"]),
        K("ebitdar", "EBITDAR", "EBITDA before rent", "Operating before occupancy", "Stable/expanding", "Compressing", ["Margin"]),
    ],
    why_margins="Merchandise margin minus shrink, promotions, and occupancy",
    why_roic="Returns tied to inventory turns and store productivity vs invested capital",
    why_leverage="Moderate — lease obligations act as quasi-debt",
    why_working_capital="Inventory is the main WC sink; payables provide float",
    why_valuation="EV/EBITDAR and EV/EBITDA normalize rent structures",
    primary_cycle="expansion",
)

add(
    key="fmcg", name="FMCG", aliases=["fmcg", "consumer goods", "cpg", "staples"],
    revenue_drivers=["Volume", "Price/mix", "Distribution reach", "Innovation"],
    margin_drivers=["Gross margin", "A&P efficiency", "Mix premiumization", "Scale"],
    cost_drivers=["Raw materials", "A&P", "Distribution", "Labour"],
    value_drivers=["Volume Growth", "Market Share", "Gross Margin", "Distribution Reach", "Working Capital"],
    capital_intensity="Low-Moderate — plants and brands, asset-light vs heavy industry",
    working_capital="Receivables and inventory; strong brands extend payables",
    cash_conversion="Strong for leaders — negative WC possible",
    operating_leverage="Moderate — fixed brand and plant cost vs volume",
    pricing_power="Moderate — brand equity supports; rural price sensitivity limits",
    competitive_structure="oligopoly",
    porter=P("High — brand, distribution, shelf space", "Medium — agri/commodity inputs", "Medium — modern trade", "Medium — private label", "High"),
    concentration="Oligopoly in most categories with regional players",
    regulators=["FSSAI", "Legal Metrology", "ASCI", "SEBI"],
    regulatory_risks=["Labeling", "Health claims", "Plastic/packaging norms"],
    valuation_methods=["P/E", "EV/EBITDA", "EV/Sales"],
    valuation_why="Stable cash flows and brand franchises support earnings multiples",
    lifecycle="mature", typical_roic="Mid-teens to high-teens for leaders",
    typical_growth="Low to mid-single digit volume; price/mix adds",
    typical_risks=["Input inflation", "Competition", "Rural slowdown", "Regulatory"],
    risk_weightings={"demand": "Medium", "commodity": "High", "execution": "Medium", "regulatory": "Medium"},
    macro_sensitivity=["Rural demand", "Commodity prices", "Monsoon"],
    customers=["Mass consumers", "Modern trade", "Kirana"], suppliers=["Agri commodities", "Packaging", "Toll manufacturers"],
    adjacent_industries=["retail", "agriculture", "qsr"], substitutes=["Private label", "Regional brands", "Unbranded"],
    capital_allocation_typical="Dividends and brand capex; bolt-on M&A",
    kpis=[
        K("volume_growth", "Volume Growth", "Unit volume change", "Organic demand", "Positive", "Negative", ["Market share"]),
        K("market_share", "Market Share", "Category share", "Competitive position", "Stable/gaining", "Losing", ["Volume"]),
        K("gross_margin", "Gross Margin", "Gross profit / revenue", "Pricing and mix", "Stable/expanding", "Compressing", ["Input costs"]),
        K("distribution_reach", "Distribution Reach", "Numeric/outlet coverage", "Go-to-market", "Expanding", "Stagnant", ["Volume"]),
        K("wc_days", "Working Capital Days", "Inventory + AR − AP cycle", "Cash efficiency", "Low/negative", "Rising", ["FCF"]),
    ],
    why_margins="Brand premium over commodity inputs minus A&P",
    why_roic="Asset-light model with strong brands delivers high ROIC",
    why_leverage="Conservative balance sheets typical",
    why_working_capital="Leaders run tight inventory and extend payables",
    why_valuation="P/E for stable earnings; EV/EBITDA for comparability",
    primary_cycle="expansion",
)

add(
    key="consumer_durables", name="Consumer Durables", aliases=["durables", "appliances", "consumer electronics", "white goods"],
    revenue_drivers=["Replacement demand", "Premiumization", "Distribution", "Seasonality"],
    margin_drivers=["Product mix", "Localization", "Raw material costs", "Scale"],
    cost_drivers=["Components", "Manufacturing", "Logistics", "Warranty"],
    value_drivers=["Volume", "ASP", "Market Share", "After-sales", "Localization"],
    capital_intensity="Moderate — plants, tooling, working capital",
    working_capital="Inventory and channel receivables",
    cash_conversion="Moderate — seasonal inventory build",
    operating_leverage="Moderate — plant fixed cost vs volume",
    pricing_power="Moderate — differentiation in premium; weak in mass",
    competitive_structure="oligopoly",
    porter=P("Medium-High — brand, distribution, service", "Medium — component suppliers", "Medium", "Medium — rentals, repair", "High"),
    concentration="Oligopoly in major categories; Chinese imports in electronics",
    regulators=["BIS", "BEE", "Legal Metrology", "SEBI"],
    regulatory_risks=["Energy efficiency norms", "Import duties", "Safety standards"],
    valuation_methods=["P/E", "EV/EBITDA"],
    valuation_why="Cyclical earnings on volume and mix; EBITDA normalizes plant load",
    lifecycle="mature", typical_roic="Low to mid-teens; premium brands higher",
    typical_growth="GDP-linked replacement; premiumization adds mix",
    typical_risks=["Input costs", "Import competition", "Demand cyclicality", "Channel inventory"],
    risk_weightings={"demand": "High", "commodity": "High", "execution": "Medium", "regulatory": "Medium"},
    macro_sensitivity=["Housing", "Consumer credit", "Commodity prices", "Festive demand"],
    customers=["Urban households", "Tier 2/3 upgraders"], suppliers=["Steel", "Copper", "Compressors", "Semiconductors"],
    adjacent_industries=["retail", "auto_components", "capital_goods"], substitutes=["Refurbished", "Shared/rental models", "Delay replacement"],
    capital_allocation_typical="Plant capex and localization; dividends when cycle peaks",
    kpis=[
        K("volume_growth", "Volume Growth", "Unit sales change", "Demand", "Positive", "Negative", ["Share"]),
        K("asp", "ASP", "Average selling price", "Mix/premiumization", "Rising", "Falling", ["Margin"]),
        K("market_share", "Market Share", "Category share", "Competitive position", "Gaining", "Losing", ["Volume"]),
        K("localization", "Localization", "Domestic value add", "Margin and policy", "High", "Low", ["Cost"]),
        K("channel_inventory", "Channel Inventory", "Stock at trade", "Demand health", "Normal", "Elevated", ["Volume"]),
    ],
    why_margins="ASP minus input and manufacturing cost; mix shifts margin",
    why_roic="Plant utilization and localization drive returns on invested capital",
    why_leverage="Moderate debt for working capital and capex",
    why_working_capital="Seasonal inventory and channel financing",
    why_valuation="P/E and EV/EBITDA reflect cyclical earnings power",
    primary_cycle="expansion",
)

add(
    key="automobile", name="Automobile", aliases=["auto", "passenger vehicles", "pv", "two-wheeler", "commercial vehicles"],
    revenue_drivers=["Volume", "Mix", "Exports", "New launches"],
    margin_drivers=["Scale", "Localization", "Raw material costs", "Discounting"],
    cost_drivers=["Steel/aluminium", "Components", "Labour", "R&D", "Marketing"],
    value_drivers=["Volume", "Market Share", "ASP", "Capacity Utilization", "Export Mix"],
    capital_intensity="High — plants, platforms, tooling",
    working_capital="Inventory and dealer receivables",
    cash_conversion="Weak in downturns — inventory builds",
    operating_leverage="High — fixed plant and platform cost",
    pricing_power="Low-Moderate — intense rivalry limits",
    competitive_structure="oligopoly",
    porter=P("High — capital, brand, distribution", "Medium — component oligopolies", "High — buyers", "Medium — used, mobility", "Very High"),
    concentration="Oligopoly in PV; fragmented in two-wheelers",
    regulators=["MoRTH", "BIS", "CAFE norms", "SEBI"],
    regulatory_risks=["Emission/safety norms", "EV policy", "Scrappage"],
    valuation_methods=["P/E", "EV/EBITDA"],
    valuation_why="Cyclical earnings; EBITDA captures operating leverage at normalized volume",
    lifecycle="mature", typical_roic="Low to mid-teens at cycle peak",
    typical_growth="GDP+ in expansions; cyclical downturns",
    typical_risks=["Demand cycles", "Commodity spikes", "EV transition capex", "Discount wars"],
    risk_weightings={"demand": "High", "commodity": "High", "execution": "High", "regulatory": "Medium"},
    macro_sensitivity=["Interest rates", "Fuel prices", "Consumer sentiment", "Rural income"],
    customers=["Retail buyers", "Fleet", "Exports"], suppliers=["Auto components", "Steel", "Tyres"],
    adjacent_industries=["auto_components", "oil_gas", "banks"], substitutes=["Used vehicles", "Shared mobility", "Public transport"],
    capital_allocation_typical="Platform capex and EV investment; dividends at cycle peak",
    kpis=[
        K("volume", "Volume", "Units sold", "Demand", "Growing", "Falling", ["Share"]),
        K("market_share", "Market Share", "Segment share", "Competitive position", "Stable/gaining", "Losing", ["Volume"]),
        K("capacity_util", "Capacity Utilization", "Production / capacity", "Fixed cost absorption", "High", "Low", ["Margin"]),
        K("discounting", "Discounting", "Incentives / ASP", "Pricing pressure", "Low", "High", ["Margin"]),
        K("export_mix", "Export Mix", "Exports / total sales", "Diversification", "Rising", "Falling", ["Volume"]),
    ],
    why_margins="Scale and mix minus commodity and discounting",
    why_roic="High capex and cyclical utilization compress average ROIC",
    why_leverage="Moderate; working capital swings with inventory",
    why_working_capital="Dealer and inventory financing dominate",
    why_valuation="P/E and EV/EBITDA through the cycle",
    primary_cycle="expansion",
)

add(
    key="auto_components", name="Auto Components", aliases=["auto ancillaries", "auto parts", "tier-1 supplier"],
    revenue_drivers=["OEM volumes", "Content per vehicle", "Aftermarket", "Exports"],
    margin_drivers=["Operating leverage", "Localization", "Pass-through of commodities", "Mix"],
    cost_drivers=["Raw materials", "Labour", "Tooling", "R&D"],
    value_drivers=["Revenue per Vehicle", "Market Share", "Export Mix", "Operating Margin", "Customer Diversification"],
    capital_intensity="Moderate-High — plants and tooling tied to platforms",
    working_capital="Receivables from OEMs; inventory for JIT",
    cash_conversion="Moderate — OEM payment terms",
    operating_leverage="High — plant fixed cost vs OEM volume",
    pricing_power="Low-Moderate — OEM bargaining power strong",
    competitive_structure="fragmented",
    porter=P("Medium — technology, OEM approval", "Medium — commodities", "High — OEMs", "Low — limited", "High"),
    concentration="Fragmented with global tier-1s in key systems",
    regulators=["AIS standards", "BIS", "SEBI"],
    regulatory_risks=["Safety/emission content rules", "PLI localization"],
    valuation_methods=["P/E", "EV/EBITDA"],
    valuation_why="EBITDA reflects plant leverage to OEM volumes",
    lifecycle="mature", typical_roic="Mid-teens for specialized suppliers",
    typical_growth="Tracks auto volumes plus content increase",
    typical_risks=["OEM concentration", "Volume cyclicality", "EV content shift", "Commodity"],
    risk_weightings={"demand": "High", "execution": "High", "commodity": "Medium", "regulatory": "Medium"},
    macro_sensitivity=["Auto production", "Commodity prices", "Export markets"],
    customers=["OEMs", "Aftermarket", "Exports"], suppliers=["Steel", "Rubber", "Electronics"],
    adjacent_industries=["automobile", "capital_goods"], substitutes=["In-house OEM parts", "Imports"],
    capital_allocation_typical="Tooling and capacity for new platforms; exports investment",
    kpis=[
        K("content_per_vehicle", "Content per Vehicle", "Revenue / industry units", "Penetration", "Rising", "Flat", ["Volume"]),
        K("oem_mix", "OEM Concentration", "Top customer share", "Risk", "Diversified", "Concentrated", ["Margin"]),
        K("operating_margin", "Operating Margin", "EBIT / revenue", "Efficiency", "Stable", "Compressing", ["Utilization"]),
        K("export_share", "Export Share", "Exports / revenue", "Diversification", "Rising", "Falling", ["Growth"]),
        K("aftermarket_mix", "Aftermarket Mix", "Aftermarket / revenue", "Margin stability", "Higher", "Lower", ["Cyclicality"]),
    ],
    why_margins="Scale on fixed plants minus pass-through commodity lag",
    why_roic="Tooling amortization and utilization drive returns",
    why_leverage="Working capital and modest term debt",
    why_working_capital="OEM receivables and JIT inventory",
    why_valuation="EV/EBITDA for cyclical normalization",
    primary_cycle="expansion",
)

add(
    key="telecom", name="Telecom", aliases=["telecommunications", "mobile", "telco", "wireless"],
    revenue_drivers=["Subscribers", "ARPU", "Data consumption", "Enterprise"],
    margin_drivers=["Spectrum amortization", "Network opex", "ARPU", "Scale"],
    cost_drivers=["Spectrum", "Tower/fiber rent", "Energy", "Handset subsidies"],
    value_drivers=["Subscriber Market Share", "ARPU", "Data Usage", "Churn", "Network Quality"],
    capital_intensity="Very high — spectrum and network capex",
    working_capital="Receivables and deferred revenue; moderate",
    cash_conversion="Weak during heavy 5G capex; improves post-build",
    operating_leverage="High — fixed network cost vs subscribers",
    pricing_power="Low — tariff wars; regulated floor",
    competitive_structure="oligopoly",
    porter=P("Very High — spectrum, capital", "Medium — tower/fiber", "High — consumers", "Medium — OTT/WiFi", "Very High"),
    concentration="Three-player oligopoly post consolidation",
    regulators=["TRAI", "DoT", "SEBI"],
    regulatory_risks=["Tariff regulation", "Spectrum pricing", "AGR dues", "QoS norms"],
    valuation_methods=["EV/EBITDA", "EV/Subscriber", "DCF"],
    valuation_why="Heavy D&A and capex make EBITDA the operational cash proxy",
    lifecycle="mature", typical_roic="Low — spectrum and capex drag",
    typical_growth="Low single-digit revenue; data ARPU uplift",
    typical_risks=["Tariff competition", "Capex overload", "Regulatory", "Technology obsolescence"],
    risk_weightings={"regulatory": "High", "refinancing": "High", "execution": "High", "demand": "Medium"},
    macro_sensitivity=["Spectrum auctions", "Digital adoption", "Interest rates"],
    customers=["Retail mobile", "Enterprise", "Broadband"], suppliers=["Tower cos", "Equipment vendors", "Spectrum"],
    adjacent_industries=["media", "internet_platforms", "data_centers"], substitutes=["OTT messaging", "WiFi", "Satellite"],
    capital_allocation_typical="Network capex and spectrum; limited dividends until leverage falls",
    kpis=[
        K("subscribers", "Subscribers", "Active subscriber base", "Scale", "Growing", "Flat/declining", ["Share"]),
        K("arpu", "ARPU", "Revenue / subscriber / month", "Monetization", "Rising", "Falling", ["Data usage"]),
        K("churn", "Churn", "Disconnects / base", "Retention", "Low", "High", ["ARPU"]),
        K("data_usage", "Data Usage", "GB per user", "Monetization potential", "Rising", "Flat", ["ARPU"]),
        K("leverage", "Net Debt/EBITDA", "Net debt / EBITDA", "Balance sheet", "Falling", "Elevated", ["Capex"]),
    ],
    why_margins="ARPU minus network opex and spectrum amortization",
    why_roic="Spectrum and capex create structurally low ROIC",
    why_leverage="High — funded network and spectrum acquisitions",
    why_working_capital="Receivables minor vs capex burden",
    why_valuation="EV/EBITDA standard for capital-intensive telcos",
    primary_cycle="interest_rate_cycle",
)

add(
    key="hospitals", name="Hospitals", aliases=["healthcare providers", "multi-specialty", "hospital chain"],
    revenue_drivers=["Occupancy", "ARPOB", "Bed expansion", "Payor mix"],
    margin_drivers=["Occupancy", "Case mix", "Doctor costs", "Payor tariffs"],
    cost_drivers=["Medical consumables", "Doctor fees", "Staff", "Rent/capex depreciation"],
    value_drivers=["Occupancy", "ARPOB", "ALOS", "Bed Capacity", "Payor Mix"],
    capital_intensity="High — beds, equipment, real estate",
    working_capital="Receivables from insurers and TPAs",
    cash_conversion="Moderate — insurer payment lags",
    operating_leverage="High — fixed bed and staff cost vs occupancy",
    pricing_power="Moderate — brand and clinical outcomes; payor pressure",
    competitive_structure="fragmented",
    porter=P("High — licenses, doctors, capex", "Medium — consumables, equipment", "Medium — insurers/corporates", "Low — limited", "Medium-High"),
    concentration="Fragmented; chains consolidating in metros",
    regulators=["NABH", "State health departments", "CDSCO", "SEBI"],
    regulatory_risks=["Clinical establishment acts", "Price caps", "Accreditation"],
    valuation_methods=["EV/EBITDA", "EV/Bed", "P/E"],
    valuation_why="EBITDA and per-bed metrics capture operating leverage on bed base",
    lifecycle="growth", typical_roic="Low to mid-teens; greenfield drags early",
    typical_growth="Bed additions plus occupancy/ARPOB uplift",
    typical_risks=["Doctor attrition", "Payor pricing", "Regulatory", "Execution on new units"],
    risk_weightings={"execution": "High", "regulatory": "Medium", "demand": "Medium", "refinancing": "Medium"},
    macro_sensitivity=["Healthcare awareness", "Insurance penetration", "Urbanization"],
    customers=["Cash patients", "Insurance/TPA", "Corporate", "Government schemes"], suppliers=["Pharma", "Devices", "Doctors"],
    adjacent_industries=["diagnostics", "pharma", "insurance"], substitutes=["Government hospitals", "Clinics", "Telemedicine"],
    capital_allocation_typical="Greenfield/brownfield bed capex; moderate dividends",
    kpis=[
        K("occupancy", "Occupancy", "Patient days / available bed days", "Asset utilization", "High", "Low", ["ARPOB"]),
        K("arpob", "ARPOB", "Revenue / occupied bed / day", "Yield per bed", "Rising", "Falling", ["Mix"]),
        K("alos", "ALOS", "Average length of stay", "Throughput vs acuity", "Optimal for mix", "Too high/low", ["Occupancy"]),
        K("bed_capacity", "Bed Capacity", "Operational beds", "Scale", "Growing", "Stagnant", ["Revenue"]),
        K("payor_mix", "Payor Mix", "Insurance vs cash share", "Realization", "Balanced", "Adverse shift", ["ARPOB"]),
    ],
    why_margins="ARPOB minus doctor, consumable, and fixed costs at occupancy",
    why_roic="High capex per bed; mature units earn better returns",
    why_leverage="Moderate debt for hospital builds",
    why_working_capital="Insurer receivables are the main WC item",
    why_valuation="EV/EBITDA and EV/Bed standard for provider chains",
    primary_cycle="expansion",
)

add(
    key="diagnostics", name="Diagnostics", aliases=["pathology", "diagnostic labs", "radiology chains"],
    revenue_drivers=["Test volumes", "Test mix", "Collection centre network", "B2B hospital tie-ups"],
    margin_drivers=["Reagent costs", "Collection efficiency", "Mix (specialty vs routine)", "Scale"],
    cost_drivers=["Reagents/consumables", "Technicians", "Logistics", "Equipment"],
    value_drivers=["Test Volume", "Revenue per Patient", "Collection Centres", "B2B Mix", "Turnaround Time"],
    capital_intensity="Moderate — equipment and lab infrastructure",
    working_capital="Low — quick cash cycles in retail",
    cash_conversion="Strong — retail prepay common",
    operating_leverage="High — lab fixed cost vs test volume",
    pricing_power="Moderate — brand and accuracy; competition in routine tests",
    competitive_structure="fragmented",
    porter=P("Medium — accreditation, network", "Medium — reagent suppliers", "Medium — patients/referrals", "Medium — hospital in-house labs", "High"),
    concentration="Fragmented; national chains gaining share",
    regulators=["NABL", "CDSCO", "State drug controllers", "SEBI"],
    regulatory_risks=["Quality accreditation", "Price transparency", "Data privacy"],
    valuation_methods=["EV/EBITDA", "P/E", "EV/Revenue"],
    valuation_why="Scalable lab model with operating leverage on test volumes",
    lifecycle="growth", typical_roic="Mid-teens to high-teens at scale",
    typical_growth="Double-digit volume; preventive health tailwind",
    typical_risks=["Price competition", "Quality incidents", "Hospital insourcing", "Reagent inflation"],
    risk_weightings={"execution": "Medium", "regulatory": "Medium", "demand": "Medium", "commodity": "Low"},
    macro_sensitivity=["Health awareness", "Insurance", "Preventive care trends"],
    customers=["Walk-in retail", "Hospital referrals", "Corporate wellness"], suppliers=["Reagent OEMs", "Equipment vendors"],
    adjacent_industries=["hospitals", "pharma"], substitutes=["Hospital captive labs", "Point-of-care devices"],
    capital_allocation_typical="Network expansion and automation; high FCF at maturity",
    kpis=[
        K("test_volume", "Test Volume", "Tests processed", "Scale", "Growing", "Flat", ["Revenue"]),
        K("rev_per_patient", "Revenue per Patient", "Revenue / patient visits", "Mix and pricing", "Stable/rising", "Falling", ["Margin"]),
        K("collection_centres", "Collection Centres", "Patient access points", "Network reach", "Expanding", "Stagnant", ["Volume"]),
        K("b2b_mix", "B2B Mix", "Hospital/corporate / total", "Channel mix", "Balanced", "Over-reliant", ["Margin"]),
        K("tat", "Turnaround Time", "Report delivery speed", "Customer satisfaction", "Fast", "Slow", ["Volume"]),
    ],
    why_margins="Test revenue minus reagents and lab fixed costs at volume",
    why_roic="Asset-light vs hospitals; scale improves ROIC",
    why_leverage="Low — mostly working capital funded",
    why_working_capital="Minimal — retail cash and quick cycles",
    why_valuation="EV/EBITDA captures lab operating leverage",
    primary_cycle="expansion",
)

add(
    key="pharma", name="Pharma", aliases=["pharmaceuticals", "formulations", "generics", "api"],
    revenue_drivers=["Volume", "New launches", "US/EU exports", "Chronic portfolio"],
    margin_drivers=["Product mix", "API vs formulations", "Regulatory approvals", "Pricing"],
    cost_drivers=["API/raw materials", "R&D", "Regulatory", "Manufacturing"],
    value_drivers=["Revenue Growth", "Gross Margin", "ANDA/DMF Pipeline", "US Exposure", "R&D Productivity"],
    capital_intensity="Moderate — plants and R&D; less than heavy industry",
    working_capital="Inventory and receivables; US channel stocking",
    cash_conversion="Moderate — inventory and receivable cycles",
    operating_leverage="Moderate — plant and R&D fixed cost",
    pricing_power="Low in generics; moderate in complex/specialty",
    competitive_structure="fragmented",
    porter=P("High — approvals, compliance, scale", "Medium — API suppliers", "High — payers/channels", "Medium — biosimilars, alternatives", "High"),
    concentration="Fragmented domestically; consolidated in US generics",
    regulators=["CDSCO", "US FDA", "EMA", "SEBI"],
    regulatory_risks=["Warning letters", "Price control (NPPA)", "Data integrity"],
    valuation_methods=["P/E", "EV/EBITDA", "EV/Sales"],
    valuation_why="Earnings reflect pipeline and regulatory quality; sales for R&D-heavy",
    lifecycle="mature", typical_roic="Mid-teens for quality operators",
    typical_growth="Mid-single to low-double digit; US cycles volatile",
    typical_risks=["Regulatory", "US pricing erosion", "API dependence", "Litigation"],
    risk_weightings={"regulatory": "High", "execution": "High", "demand": "Medium", "commodity": "Medium"},
    macro_sensitivity=["US healthcare policy", "Currency", "API import dependence"],
    customers=["Domestic trade", "US/EU generics", "Hospital tenders"], suppliers=["API/china imports", "Excipients", "CMOs"],
    adjacent_industries=["diagnostics", "hospitals", "chemicals"], substitutes=["Alternate molecules", "Biosimilars", "Ayurveda"],
    capital_allocation_typical="R&D and US filings; plant compliance capex",
    kpis=[
        K("anda_pipeline", "ANDA/DMF Pipeline", "Pending approvals", "Future revenue", "Rich pipeline", "Thin", ["US revenue"]),
        K("us_revenue_mix", "US Revenue Mix", "US / total revenue", "Exposure", "Balanced", "Over-concentrated", ["Risk"]),
        K("gross_margin", "Gross Margin", "Gross profit / revenue", "Mix and pricing", "Stable", "Compressing", ["API costs"]),
        K("r_and_d_intensity", "R&D Intensity", "R&D / revenue", "Innovation investment", "Adequate", "Under-investing", ["Pipeline"]),
        K("regulatory_actions", "Regulatory Actions", "FDA observations/warnings", "Compliance risk", "Clean", "Elevated", ["US supply"]),
    ],
    why_margins="Formulation pricing minus API and compliance cost",
    why_roic="Plant utilization and US mix drive returns",
    why_leverage="Conservative; working capital is main funding need",
    why_working_capital="US stocking and API inventory",
    why_valuation="P/E with regulatory quality discount/premium",
    primary_cycle="expansion",
)

add(
    key="chemicals", name="Chemicals", aliases=["specialty chemicals", "petrochemicals", "agrochemicals"],
    revenue_drivers=["Volume", "Realizations", "Capacity additions", "Export demand"],
    margin_drivers=["Spread over feedstock", "Capacity utilization", "Product mix", "Integration"],
    cost_drivers=["Feedstock (naphtha, gas)", "Energy", "Catalysts", "Environmental compliance"],
    value_drivers=["Volume", "Realization", "Capacity Utilization", "Integration", "Export Mix"],
    capital_intensity="High — crackers, reactors, continuous process plants",
    working_capital="Inventory and receivables; commodity cycles swell inventory",
    cash_conversion="Cyclical — weak at peak inventory build",
    operating_leverage="Very high — fixed plant cost vs utilization",
    pricing_power="Low in commodities; higher in specialty/niche",
    competitive_structure="oligopoly",
    porter=P("High — capital, technology, environmental", "Medium-High — feedstock/linkages", "Medium — downstream", "Medium — substitutes", "High"),
    concentration="Oligopoly in bulk; fragmented in specialty",
    regulators=["MoEFCC", "PCB", "DGS&D", "SEBI"],
    regulatory_risks=["Environmental norms", "Carbon/regulatory capex", "Import duties"],
    valuation_methods=["EV/EBITDA", "Replacement Cost", "P/E"],
    valuation_why="Cyclical EBITDA and asset replacement value matter at trough/peak",
    lifecycle="mature", typical_roic="Cyclical — low at peak capex, high at utilization peaks",
    typical_growth="GDP+ with capex cycles; China/global demand linked",
    typical_risks=["Feedstock volatility", "China supply", "Environmental capex", "Cycle timing"],
    risk_weightings={"commodity": "High", "regulatory": "High", "demand": "Medium", "execution": "Medium"},
    macro_sensitivity=["Oil/gas prices", "Global demand", "INR/USD", "China exports"],
    customers=["Automotive", "Agri", "Pharma", "Paints", "Exports"], suppliers=["Crude/LNG", "Catalysts", "Technology licensors"],
    adjacent_industries=["pharma", "oil_gas", "agriculture", "fmcg"], substitutes=["Imports", "Alternate chemistries"],
    capital_allocation_typical="Capex at cycle trough; dividends at peak cash generation",
    kpis=[
        K("realization", "Realization", "Price per unit", "Cycle position", "Favorable spread", "Compressing", ["Margin"]),
        K("capacity_util", "Capacity Utilization", "Output / capacity", "Fixed cost leverage", "High", "Low", ["EBITDA"]),
        K("spread", "Product Spread", "Product − feedstock", "Core economics", "Wide", "Narrow", ["Realization"]),
        K("export_mix", "Export Mix", "Exports / revenue", "Demand diversification", "Balanced", "Domestic-only", ["Growth"]),
        K("integration", "Integration", "Backward/forward link", "Margin stability", "Integrated", "Standalone", ["Spread"]),
    ],
    why_margins="Product realization minus feedstock and energy at utilization",
    why_roic="Heavily cyclical with capex and spread timing",
    why_leverage="Moderate-High through cycle peaks",
    why_working_capital="Inventory inflates in upcycles",
    why_valuation="EV/EBITDA through cycle; replacement cost at trough",
    primary_cycle="commodity_cycle",
)

add(
    key="cement", name="Cement", aliases=["cement", "building materials"],
    revenue_drivers=["Volume", "Realizations", "Regional demand"],
    margin_drivers=["Power/fuel cost", "Lead distance", "Capacity utilization", "Mix (trade vs institutional)"],
    cost_drivers=["Limestone", "Power/fuel", "Freight", "Royalty"],
    value_drivers=["Volume", "Realization", "Cost per Tonne", "Market Share", "Lead Distance"],
    capital_intensity="High — kilns and quarries",
    working_capital="Low-Moderate — receivables seasonal",
    cash_conversion="Strong at utilization; weak in downturns",
    operating_leverage="Very high — kiln fixed cost vs tonnes",
    pricing_power="Regional — logistics create local oligopolies",
    competitive_structure="oligopoly",
    porter=P("High — limestone, capital, logistics", "Medium — power, fuel", "Medium — builders/trade", "Low — substitutes limited", "High regionally"),
    concentration="Regional oligopolies; national players",
    regulators=["MoEFCC", "Mines department", "SEBI"],
    regulatory_risks=["Mining leases", "Carbon/emission norms", "Anti-trust scrutiny"],
    valuation_methods=["EV/EBITDA", "EV/Tonne", "Replacement Cost"],
    valuation_why="EBITDA per tonne and clinker capacity are standard cyclical metrics",
    lifecycle="mature", typical_roic="Cyclical mid-teens at peak utilization",
    typical_growth="Tracks housing and infrastructure cement demand",
    typical_risks=["Overcapacity regionally", "Power/fuel spikes", "Monsoon seasonality", "Demand slowdown"],
    risk_weightings={"commodity": "High", "demand": "High", "regulatory": "Medium", "execution": "Medium"},
    macro_sensitivity=["Housing", "Infrastructure spend", "Power/coal prices", "Monsoon"],
    customers=["Trade/dealers", "Real estate", "Infrastructure"], suppliers=["Coal/pet coke", "Power", "Limestone"],
    adjacent_industries=["infrastructure", "real_estate", "capital_goods"], substitutes=["Blended materials", "Imports (coastal)"],
    capital_allocation_typical="Kiln debottlenecking and logistics; dividends in upcycles",
    kpis=[
        K("volume", "Volume", "Tonnes sold", "Demand capture", "Growing", "Falling", ["Share"]),
        K("realization", "Realization", "Revenue / tonne", "Pricing", "Stable/rising", "Falling", ["Margin"]),
        K("cost_per_tonne", "Cost per Tonne", "Operating cost / tonne", "Efficiency", "Falling", "Rising", ["Fuel"]),
        K("lead_distance", "Lead Distance", "Avg delivery radius", "Freight advantage", "Short", "Lengthening", ["Realization"]),
        K("capacity_util", "Capacity Utilization", "Production / capacity", "Fixed cost leverage", "High", "Low", ["EBITDA"]),
    ],
    why_margins="Realization minus fuel, power, and freight per tonne",
    why_roic="Utilization and lead distance determine returns on kiln assets",
    why_leverage="Moderate — cyclical debt paydown in booms",
    why_working_capital="Seasonal receivables; low inventory vs heavy industry",
    why_valuation="EV/EBITDA and EV/Tonne through the construction cycle",
    primary_cycle="housing_cycle",
)

add(
    key="power", name="Power Generation", aliases=["power", "generation", "thermal power", "IPP"],
    revenue_drivers=["Plant load factor", "Tariff/realizations", "Merchant sales", "Capacity"],
    margin_drivers=["Fuel cost pass-through", "PLF", "Fixed charge recovery", "Auxiliary consumption"],
    cost_drivers=["Coal/gas", "Transportation", "O&M", "Interest"],
    value_drivers=["PLF", "Tariff", "Fuel Cost", "PPA Coverage", "Merchant Exposure"],
    capital_intensity="Very high — boilers, turbines, fuel linkages",
    working_capital="Receivables from discoms; fuel inventory",
    cash_conversion="Weak when discom payments delay",
    operating_leverage="High — fixed generation cost vs PLF",
    pricing_power="Low — regulated/competitive bidding tariffs",
    competitive_structure="oligopoly",
    porter=P("Very High — capital, fuel linkages, PPAs", "Medium-High — coal suppliers", "High — discoms", "Medium — renewables", "Medium"),
    concentration="Oligopoly among large IPPs and state gencos",
    regulators=["CEA", "CERC/SERC", "MoP", "SEBI"],
    regulatory_risks=["Tariff revision delays", "Coal allocation", "Environmental norms", "Discom health"],
    valuation_methods=["EV/EBITDA", "DCF", "P/E"],
    valuation_why="Regulated/competitive returns on generation assets; DCF on contracted cash flows",
    lifecycle="mature", typical_roic="Low to mid-single digits — capital intensive",
    typical_growth="Capacity adds slow; PLF and merchant drive earnings",
    typical_risks=["Discom receivables", "Coal availability", "PLF decline", "Renewable cannibalization"],
    risk_weightings={"regulatory": "High", "refinancing": "High", "commodity": "High", "demand": "Medium"},
    macro_sensitivity=["Coal prices", "Industrial demand", "Discom reforms", "Interest rates"],
    customers=["State discoms", "Open access", "Merchant market"], suppliers=["Coal India", "Railways", "Equipment OEMs"],
    adjacent_industries=["utilities", "renewables", "coal mining"], substitutes=["Renewables", "Captive generation", "Imports"],
    capital_allocation_typical="Maintenance capex; limited greenfield thermal; debt paydown",
    kpis=[
        K("plf", "PLF", "Plant load factor", "Asset utilization", "High", "Low", ["Tariff"]),
        K("tariff", "Tariff", "Revenue / unit sold", "Realization", "Stable", "Compressing", ["Margin"]),
        K("fuel_cost", "Fuel Cost", "Fuel / unit generated", "Margin driver", "Controlled", "Spiking", ["PLF"]),
        K("ppa_coverage", "PPA Coverage", "Contracted / capacity", "Revenue visibility", "High", "Low", ["Merchant"]),
        K("discom_receivable_days", "Discom Receivable Days", "Outstanding from discoms", "Cash risk", "Low", "Elevated", ["FCF"]),
    ],
    why_margins="Tariff minus fuel and fixed O&M at PLF",
    why_roic="Heavy generation assets earn regulated returns — structurally modest ROIC",
    why_leverage="High — project finance model",
    why_working_capital="Discom receivables and coal inventory",
    why_valuation="EV/EBITDA and DCF on contracted generation cash flows",
    primary_cycle="interest_rate_cycle",
)

add(
    key="renewables", name="Renewables", aliases=["renewable energy", "solar", "wind", "green power"],
    revenue_drivers=["Capacity additions", "CUF/PLF", "Tariff (auction)", "Merchant/real-time market"],
    margin_drivers=["Resource intensity (CUF)", "Module/turbine costs", "O&M", "Interest rates"],
    cost_drivers=["Modules/turbines", "Land", "Transmission", "O&M"],
    value_drivers=["Capacity", "CUF", "Tariff", "Bid Competitiveness", "Portfolio Age"],
    capital_intensity="High upfront — panels, turbines; low ongoing opex",
    working_capital="Moderate — receivables from SECI/discoms",
    cash_conversion="Moderate — subsidy/settlement lags possible",
    operating_leverage="High — fixed asset base vs generation",
    pricing_power="Low — reverse auction tariffs declining",
    competitive_structure="fragmented",
    porter=P("Medium — land, connectivity, bidding", "Medium — OEMs", "High — offtakers", "Medium — thermal/hydro", "High"),
    concentration="Fragmented developers; OEMs consolidated globally",
    regulators=["MNRE", "SECI", "CERC/SERC", "SEBI"],
    regulatory_risks=["Tariff renegotiation", "Connectivity delays", "ALMM/DCR policy", "Land acquisition"],
    valuation_methods=["DCF", "EV/EBITDA", "Yield Co"],
    valuation_why="Long-duration contracted cash flows suit DCF and yield metrics",
    lifecycle="growth", typical_roic="Mid-single to low-teens depending on leverage and tariff",
    typical_growth="Strong — policy-driven capacity additions",
    typical_risks=["Tariff compression", "Curtailment", "Equipment costs", "Offtaker risk"],
    risk_weightings={"regulatory": "High", "execution": "High", "refinancing": "Medium", "commodity": "Low"},
    macro_sensitivity=["Interest rates", "Module prices", "Policy targets", "Discom health"],
    customers=["SECI", "Discoms", "Corporate PPAs"], suppliers=["Module/turbine OEMs", "EPC contractors", "Land"],
    adjacent_industries=["power", "utilities", "infrastructure"], substitutes=["Thermal", "Hydro", "Nuclear"],
    capital_allocation_typical="Reinvest in new bids; portfolio rotation to yield vehicles",
    kpis=[
        K("capacity", "Installed Capacity", "MW operational", "Scale", "Growing", "Stagnant", ["Generation"]),
        K("cuf", "CUF/PLF", "Actual / potential generation", "Resource capture", "High vs P90", "Underperforming", ["Revenue"]),
        K("tariff", "Bid Tariff", "Contracted tariff", "Return profile", "Above cost of capital", "Race to bottom", ["ROIC"]),
        K("curtailment", "Curtailment", "Lost generation / potential", "Grid/offtaker risk", "Low", "High", ["CUF"]),
        K("portfolio_age", "Portfolio Age", "Weighted avg asset life", "Refurbishment risk", "Young fleet", "Aging", ["O&M"]),
    ],
    why_margins="Tariff times generation minus low opex — front-loaded capex",
    why_roic="Returns set at bid; leverage and CUF determine equity ROIC",
    why_leverage="High project finance at asset level",
    why_working_capital="Receivables from offtakers; minimal fuel inventory",
    why_valuation="DCF and yield on long-term contracted assets",
    primary_cycle="interest_rate_cycle",
)

add(
    key="utilities", name="Utilities", aliases=["discom", "transmission", "distribution", "regulated utilities"],
    revenue_drivers=["Regulated asset base growth", "Allowed returns", "AT&C loss reduction", "Tariff orders"],
    margin_drivers=["AT&C losses", "Regulated ROE", "Opex efficiency", "Subsidy timeliness"],
    cost_drivers=["Power purchase", "Distribution opex", "Interest", "Employee cost"],
    value_drivers=["AT&C Losses", "Collection Efficiency", "Regulated ROE", "RAB Growth", "Subsidy Recovery"],
    capital_intensity="High — wires, substations, metering infrastructure",
    working_capital="Large receivables and subsidy dues from government",
    cash_conversion="Weak — discom losses and subsidy delays",
    operating_leverage="Moderate — regulated cost pass-through limits",
    pricing_power="None — tariff set by regulator on cost-plus basis",
    competitive_structure="government",
    porter=P("Very High — license, natural monopoly", "Medium — power suppliers", "Medium — consumers", "Low — captive/open access limited", "Low intra-state"),
    concentration="State monopolies for distribution; central transmission oligopoly",
    regulators=["CERC/SERC", "CEA", "MoP", "State governments"],
    regulatory_risks=["Tariff delay", "Subsidy non-payment", "Loss reduction targets", "Privatization policy"],
    valuation_methods=["DCF", "Regulated ROE", "Yield", "RAB multiples"],
    valuation_why="Regulated returns on RAB suit DCF and dividend yield frameworks",
    lifecycle="mature", typical_roic="Regulated mid-single to low-double digit ROE",
    typical_growth="RAB capex and loss reduction; not volume-led",
    typical_risks=["Political interference", "Subsidy arrears", "AT&C losses", "Tariff lag"],
    risk_weightings={"regulatory": "High", "refinancing": "High", "demand": "Low", "execution": "Medium"},
    macro_sensitivity=["Policy reforms", "Interest rates", "Power purchase costs", "Election cycles"],
    customers=["Residential", "Industrial", "Agricultural"], suppliers=["Gencos", "Transmission", "Equipment"],
    adjacent_industries=["power", "renewables", "infrastructure"], substitutes=["Captive/open access", "Rooftop solar"],
    capital_allocation_typical="Mandatory RAB capex; dividends when discom finances stabilize",
    kpis=[
        K("atc_losses", "AT&C Losses", "Aggregate technical and commercial losses", "Efficiency", "Falling", "Rising", ["Subsidy"]),
        K("collection_efficiency", "Collection Efficiency", "Collections / billing", "Cash conversion", "High", "Low", ["Receivables"]),
        K("regulated_roe", "Regulated ROE", "Allowed return on equity", "Earnings anchor", "Stable", "Compressed", ["RAB"]),
        K("rab_growth", "RAB Growth", "Regulated asset base change", "Earnings growth", "Positive", "Stagnant", ["Capex"]),
        K("subsidy_recovery", "Subsidy Recovery", "Timeliness of govt subsidy", "Liquidity", "Timely", "Delayed", ["Cash"]),
    ],
    why_margins="Allowed revenue minus pass-through costs — margin is regulatory not competitive",
    why_roic="Returns capped at regulated ROE on RAB",
    why_leverage="High — RAB financed with debt within regulatory norms",
    why_working_capital="Subsidy and consumer receivables dominate",
    why_valuation="DCF/Yield on regulated cash flows, not competitive EBITDA multiples",
    primary_cycle="interest_rate_cycle",
)

add(
    key="oil_gas", name="Oil & Gas", aliases=["oil and gas", "upstream", "refining", "OMC", "E&P"],
    revenue_drivers=["Crude throughput/volumes", "Crack spreads/refining margins", "Gas realizations", "Retail fuel volumes"],
    margin_drivers=["GRM/crack spreads", "Exploration success", "Opex per barrel", "Marketing margins"],
    cost_drivers=["Crude import cost", "Exploration", "Energy", "Subsidy under-recovery (legacy)"],
    value_drivers=["GRM", "Production", "Reserve Replacement", "Refining Complexity", "Marketing Volume"],
    capital_intensity="Very high — refineries, E&P blocks, retail network",
    working_capital="Large — crude inventory and receivables",
    cash_conversion="Cyclical with crude inventory and crack spreads",
    operating_leverage="High — refinery fixed cost vs throughput",
    pricing_power="Low upstream globally; marketing regulated in India",
    competitive_structure="oligopoly",
    porter=P("Very High — blocks, capital, licenses", "Medium — crude suppliers (global)", "Medium — consumers/industry", "Medium — renewables/EV", "Medium"),
    concentration="OMC oligopoly in refining/marketing; ONGC/OIL in upstream",
    regulators=["MoPNG", "PNGRB", "PPAC", "SEBI"],
    regulatory_risks=["Pricing/freight policy", "Windfall taxes", "Exploration licensing", "Biofuel blending mandates"],
    valuation_methods=["EV/EBITDA", "EV/BOE", "Sum-of-parts", "Replacement Cost"],
    valuation_why="Upstream EV/BOE and refining EV/EBITDA capture cyclical asset earnings",
    lifecycle="mature", typical_roic="Cyclical — double-digit at favorable cracks/production",
    typical_growth="Volume linked to GDP/energy demand; upstream depends on reserves",
    typical_risks=["Crude price volatility", "GRM cycles", "Geopolitics", "Energy transition"],
    risk_weightings={"commodity": "High", "regulatory": "High", "refinancing": "Medium", "demand": "Medium"},
    macro_sensitivity=["Crude prices", "Global cracks", "INR/USD", "Geopolitics"],
    customers=["Transport", "Industry", "Aviation", "Exports"], suppliers=["Middle East crude", "Services", "Technology"],
    adjacent_industries=["chemicals", "airlines", "logistics"], substitutes=["Renewables", "EVs", "Biofuels"],
    capital_allocation_typical="Refinery upgrades and E&P; dividends at strong cracks",
    kpis=[
        K("grm", "GRM", "Gross refining margin per barrel", "Refining profitability", "Strong vs history", "Weak", ["Throughput"]),
        K("throughput", "Refining Throughput", "Crude processed", "Utilization", "High", "Low", ["GRM"]),
        K("production", "Upstream Production", "BOE/day", "Volume growth", "Growing", "Declining", ["Reserves"]),
        K("reserve_replacement", "Reserve Replacement", "Additions / production", "Sustainability", ">100%", "<100%", ["Production"]),
        K("marketing_volume", "Marketing Volume", "Fuel sales volume", "Downstream scale", "Growing", "Flat", ["Margin"]),
    ],
    why_margins="GRM and realizations minus opex — upstream is commodity minus lifting cost",
    why_roic="Asset-heavy; returns swing with commodity and crack cycles",
    why_leverage="Moderate-High for refineries and E&P",
    why_working_capital="Crude inventory drives WC swings",
    why_valuation="EV/EBITDA and EV/BOE through commodity cycle",
    primary_cycle="commodity_cycle",
)

add(
    key="metals", name="Metals", aliases=["steel", "aluminium", "copper", "metal producers"],
    revenue_drivers=["Volume", "LME/domestic realizations", "Mix (value-added)", "Exports"],
    margin_drivers=["Spread over raw materials", "Capacity utilization", "Energy cost", "Integration"],
    cost_drivers=["Iron ore/coking coal", "Alumina/power", "Freight", "Carbon compliance"],
    value_drivers=["Volume", "Realization", "Cost per Tonne", "Integration", "Net Debt/EBITDA"],
    capital_intensity="Very high — blast furnaces, smelters",
    working_capital="Inventory and receivables swell in upcycles",
    cash_conversion="Highly cyclical",
    operating_leverage="Very high — furnace fixed cost",
    pricing_power="Low — LME/global pricing for commodities",
    competitive_structure="oligopoly",
    porter=P("Very High — capital, ore linkages", "Medium-High — ore/energy", "Medium — autos/infra", "Medium — substitutes", "High"),
    concentration="Oligopoly nationally; global pricing",
    regulators=["MoM", "MoEFCC", "SEBI"],
    regulatory_risks=["Mining leases", "Carbon border adjustments", "Import duties"],
    valuation_methods=["EV/EBITDA", "P/E", "Replacement Cost"],
    valuation_why="Cyclical EBITDA and asset value at trough/peak",
    lifecycle="mature", typical_roic="Highly cyclical — low at peaks, high at trough utilization",
    typical_growth="Tracks infra/auto demand globally",
    typical_risks=["China demand", "Raw material spikes", "Overcapacity", "Carbon costs"],
    risk_weightings={"commodity": "High", "demand": "High", "regulatory": "Medium", "refinancing": "Medium"},
    macro_sensitivity=["China steel/aluminium", "Infrastructure", "Energy costs", "Global growth"],
    customers=["Automotive", "Construction", "Engineering exports"], suppliers=["Iron ore", "Coal", "Power"],
    adjacent_industries=["mining", "automobile", "infrastructure", "capital_goods"], substitutes=["Scrap/recycling", "Imports", "Plastics/composites"],
    capital_allocation_typical="Delever at peaks; capex at trough if returns justify",
    kpis=[
        K("realization", "Realization", "Revenue / tonne", "Cycle indicator", "Favorable", "Weak", ["Spread"]),
        K("cost_per_tonne", "Cost per Tonne", "Operating cost / tonne", "Efficiency", "Low vs peers", "Rising", ["Margin"]),
        K("capacity_util", "Capacity Utilization", "Output / capacity", "Leverage", "High", "Low", ["EBITDA"]),
        K("integration", "Integration", "Captive ore/energy", "Margin stability", "Integrated", "Merchant", ["Cost"]),
        K("net_debt_ebitda", "Net Debt/EBITDA", "Leverage vs earnings", "Balance sheet", "Low", "Elevated", ["Cycle"]),
    ],
    why_margins="Global/local realization minus raw material and energy per tonne",
    why_roic="Cyclical with spread and utilization — average ROIC moderate",
    why_leverage="High at cycle peaks — delever in booms critical",
    why_working_capital="Inventory cycles with price and volume",
    why_valuation="EV/EBITDA through cycle; replacement cost at bottom",
    primary_cycle="commodity_cycle",
)

add(
    key="mining", name="Mining", aliases=["minerals", "iron ore", "coal mining", "extractives"],
    revenue_drivers=["Volume dispatched", "Realizations", "Grade", "Contract renewals"],
    margin_drivers=["Strip ratio/operating cost", "Realizations", "Logistics/rail", "Royalty"],
    cost_drivers=["Diesel", "Explosives", "Labour", "Royalty", "Reclamation"],
    value_drivers=["Volume", "Cash Cost per Tonne", "Reserve Life", "Logistics Access", "Realization"],
    capital_intensity="High — equipment and development; lower than processing",
    working_capital="Low-Moderate — receivables",
    cash_conversion="Strong at favorable realizations and low capex",
    operating_leverage="High — fixed mine cost vs tonnes",
    pricing_power="Low — commodity pricing",
    competitive_structure="oligopoly",
    porter=P("Very High — leases, environmental", "Low — equipment", "Medium — steel/power", "Low", "Medium regionally"),
    concentration="Oligopoly in iron ore/coal; state PSUs dominant",
    regulators=["MoM", "MoEFCC", "IBM", "SEBI"],
    regulatory_risks=["Lease auctions", "Forest clearance", "MMDR amendments", "Export duties"],
    valuation_methods=["EV/EBITDA", "EV/Tonne", "NAV of reserves"],
    valuation_why="Reserve NAV and EBITDA per tonne capture asset value",
    lifecycle="mature", typical_roic="High at favorable prices; cyclical",
    typical_growth="Volume tied to downstream demand and lease capacity",
    typical_risks=["Regulatory/lease", "Logistics bottlenecks", "Commodity prices", "Environmental"],
    risk_weightings={"regulatory": "High", "commodity": "High", "demand": "Medium", "execution": "Medium"},
    macro_sensitivity=["Steel/power demand", "Global ore/coal prices", "Monsoon (dispatch)", "Policy"],
    customers=["Steel mills", "Power plants", "Exports"], suppliers=["Equipment", "Contract mining services"],
    adjacent_industries=["metals", "power", "infrastructure"], substitutes=["Imports", "Scrap (steel)"],
    capital_allocation_typical="Lease acquisition and equipment; dividends in high price environments",
    kpis=[
        K("volume", "Dispatch Volume", "Tonnes sold", "Output", "On target", "Shortfall", ["Revenue"]),
        K("cash_cost", "Cash Cost", "Operating cost / tonne", "Margin lever", "Low", "Rising", ["Realization"]),
        K("reserve_life", "Reserve Life", "Years of reserves", "Longevity", "Long", "Short", ["Capex"]),
        K("realization", "Realization", "Revenue / tonne", "Commodity cycle", "Strong", "Weak", ["EBITDA"]),
        K("logistics_cost", "Logistics Cost", "Freight/rail / tonne", "Netback", "Controlled", "Spiking", ["Realization"]),
    ],
    why_margins="Realization minus cash cost and logistics",
    why_roic="Low reinvestment needs can yield high ROIC at peak prices",
    why_leverage="Moderate — cyclical",
    why_working_capital="Minimal vs processors",
    why_valuation="EV/EBITDA and reserve NAV",
    primary_cycle="commodity_cycle",
)

add(
    key="capital_goods", name="Capital Goods", aliases=["industrial machinery", "engineering", "heavy engineering"],
    revenue_drivers=["Order inflow", "Execution", "Exports", "Aftermarket/services"],
    margin_drivers=["Order mix", "Execution efficiency", "Raw material pass-through", "Services mix"],
    cost_drivers=["Steel/components", "Labour", "Project execution", "R&D"],
    value_drivers=["Order Book", "Order Inflow", "EBIT Margin", "Execution", "Export Mix"],
    capital_intensity="Moderate — plants and project working capital",
    working_capital="High — customer advances offset WIP and receivables",
    cash_conversion="Lumpy — milestone billing and project delays",
    operating_leverage="Moderate — fixed engineering capacity vs orders",
    pricing_power="Moderate in specialized equipment; weak in commoditized",
    competitive_structure="fragmented",
    porter=P("Medium-High — technology, track record", "Medium — components", "Medium-High — PSUs/private", "Medium — imports", "High"),
    concentration="Fragmented with leaders in niches (defence, power equipment)",
    regulators=["DPIIT", "BIS", "Defence procurement", "SEBI"],
    regulatory_risks=["Tender norms", "Localization", "Payment delays from PSUs"],
    valuation_methods=["P/E", "EV/EBITDA", "Order book multiples"],
    valuation_why="Order book visibility and execution quality drive earnings",
    lifecycle="mature", typical_roic="Low to mid-teens — project WC drags",
    typical_growth="Capex cycle linked — infra and private capex",
    typical_risks=["Order deferrals", "Execution overruns", "Raw material spikes", "Customer concentration"],
    risk_weightings={"demand": "High", "execution": "High", "commodity": "Medium", "refinancing": "Low"},
    macro_sensitivity=["Infra capex", "Private capex", "Global trade", "Commodity prices"],
    customers=["Power", "Defence", "Process industries", "Exports"], suppliers=["Steel", "Electronics", "Sub-vendors"],
    adjacent_industries=["infrastructure", "power", "renewables"], substitutes=["Imports", "Chinese equipment"],
    capital_allocation_typical="Working capital for order book; selective capex",
    kpis=[
        K("order_inflow", "Order Inflow", "New orders in period", "Demand momentum", "Strong", "Weak", ["Order book"]),
        K("order_book", "Order Book", "Unexecuted orders", "Revenue visibility", "Growing", "Shrinking", ["Execution"]),
        K("book_to_bill", "Book-to-Bill", "Orders / revenue", "Pipeline health", ">1", "<1", ["Growth"]),
        K("execution_margin", "Execution Margin", "Project EBIT margin", "Delivery quality", "On target", "Overruns", ["Profitability"]),
        K("export_mix", "Export Mix", "Exports / revenue", "Diversification", "Rising", "Falling", ["Margin"]),
    ],
    why_margins="Fixed-price project margins vs material and execution cost",
    why_roic="Working capital intensive — ROIC sensitive to billing cycles",
    why_leverage="Moderate for WC lines",
    why_working_capital="WIP and receivables dominate — advances critical",
    why_valuation="P/E and order book multiples reflect cyclical visibility",
    primary_cycle="expansion",
)

add(
    key="infrastructure", name="Infrastructure", aliases=["epc", "construction", "roads", "highways"],
    revenue_drivers=["Project awards", "Execution", "HAM/BOT/TOT mix", "Order book"],
    margin_drivers=["Bid discipline", "Execution cost", "Claim recovery", "Mix (EPC vs annuity)"],
    cost_drivers=["Materials", "Subcontractors", "Finance cost", "Land/acquisition"],
    value_drivers=["Order Book", "Bid Pipeline", "Execution Margin", "Annuity Assets", "Claim Recovery"],
    capital_intensity="High — HAM/BOT equity and EPC working capital",
    working_capital="Very high — retention, WIP, receivables",
    cash_conversion="Weak during rapid growth; improves on annuities",
    operating_leverage="Moderate — overhead vs project revenue",
    pricing_power="Low — competitive bidding",
    competitive_structure="fragmented",
    porter=P("Medium — track record, capital", "Medium — materials/labour", "High — NHAI/state", "Low", "Very High"),
    concentration="Fragmented EPC; consolidated in large road developers",
    regulators=["NHAI", "MoRTH", "State PWD", "SEBI"],
    regulatory_risks=["Land acquisition", "Bid norms", "Claim/settlement delays", "Environmental"],
    valuation_methods=["P/E", "EV/EBITDA", "SOTP (EPC + annuity)"],
    valuation_why="SOTP separates lumpy EPC from annuity road assets",
    lifecycle="growth", typical_roic="Mid-single to low-teens depending on bid discipline",
    typical_growth="Policy-led road and rail capex",
    typical_risks=["Aggressive bidding", "Execution delays", "Working capital strain", "Claim disputes"],
    risk_weightings={"execution": "High", "refinancing": "High", "regulatory": "Medium", "demand": "Medium"},
    macro_sensitivity=["Govt capex", "Bond yields (annuity)", "Material costs", "Election cycles"],
    customers=["NHAI", "State agencies", "Railways", "Urban bodies"], suppliers=["Cement", "Steel", "Subcontractors"],
    adjacent_industries=["cement", "capital_goods", "real_estate", "logistics"], substitutes=["Foreign EPC", "PPP models"],
    capital_allocation_typical="Equity in HAM/BOT; WC for EPC; monetize annuities via InvITs",
    kpis=[
        K("order_book", "Order Book", "Unexecuted EPC/HAM value", "Visibility", "Strong", "Depleting", ["Revenue"]),
        K("bid_pipeline", "Bid Pipeline", "Projects bidding", "Growth optionality", "Healthy", "Thin", ["Order book"]),
        K("execution_margin", "Execution Margin", "Project-level margin", "Bid discipline", "On plan", "Erosion", ["Claims"]),
        K("ham_annuity_mix", "HAM/Annuity Mix", "Annuity projects / total", "Cash stability", "Balanced", "EPC-heavy", ["FCF"]),
        K("claim_recovery", "Claim Recovery", "Claims settled / filed", "Cash release", "Timely", "Stuck", ["WC"]),
    ],
    why_margins="Bid margin minus execution slippage and claims",
    why_roic="Equity in annuities earns better ROIC than pure EPC WC",
    why_leverage="High — project debt on HAM/BOT",
    why_working_capital="Core constraint — retention and slow pay",
    why_valuation="SOTP: EPC earnings plus annuity DCF",
    primary_cycle="expansion",
)

add(
    key="real_estate", name="Real Estate", aliases=["realty", "residential", "commercial real estate", "developers"],
    revenue_drivers=["Launch volumes", "Sales velocity", "Price per sq ft", "Commercial leasing"],
    margin_drivers=["Land cost", "Construction cost", "Sales pace", "Product mix"],
    cost_drivers=["Land", "Construction", "Interest", "Marketing"],
    value_drivers=["Pre-sales", "Sales Velocity", "Unsold Inventory", "Net Debt", "Launch Pipeline"],
    capital_intensity="High — land bank and project development",
    working_capital="Inventory (WIP) and customer advances",
    cash_conversion="Weak until possession — RERA milestone billing helps",
    operating_leverage="High — interest and overhead vs sales",
    pricing_power="Moderate locally — location and brand matter",
    competitive_structure="fragmented",
    porter=P("High — land, RERA, capital", "Medium — contractors/materials", "Medium — homebuyers", "Low — rent vs buy varies", "High locally"),
    concentration="Fragmented; branded developers gaining in top cities",
    regulators=["RERA", "Local development authorities", "SEBI", "GST council"],
    regulatory_risks=["RERA compliance", "Approval delays", "Input tax credit", "Affordable housing norms"],
    valuation_methods=["NAV", "P/E", "EV/EBITDA", "Residual land value"],
    valuation_why="NAV on completed and WIP inventory minus net debt is standard",
    lifecycle="cyclical", typical_roic="Volatile — high in upcycles, negative in downturns",
    typical_growth="Launch and sales cycle driven",
    typical_risks=["Leverage", "Slow sales", "Approval delays", "Input cost inflation"],
    risk_weightings={"refinancing": "High", "demand": "High", "regulatory": "Medium", "execution": "High"},
    macro_sensitivity=["Interest rates", "Housing credit", "Urban employment", "Black swan liquidity"],
    customers=["Residential buyers", "Commercial tenants", "Retail"], suppliers=["Contractors", "Cement/steel", "Land sellers"],
    adjacent_industries=["cement", "infrastructure", "banks", "nbfc"], substitutes=["Rental housing", "REIT stock", "Delay purchase"],
    capital_allocation_typical="Land acquisition and construction; delever via sales",
    kpis=[
        K("presales", "Pre-sales", "Booking value in period", "Demand", "Strong", "Weak", ["Collections"]),
        K("sales_velocity", "Sales Velocity", "Units sold / launched", "Inventory clearance", "High", "Low", ["Inventory"]),
        K("unsold_inventory", "Unsold Inventory", "Months of stock", "Risk", "Low months", "High months", ["Price"]),
        K("net_debt", "Net Debt", "Debt − cash", "Balance sheet", "Falling", "Rising", ["NAV"]),
        K("collections", "Collections", "Cash collected / due", "Liquidity", "On track", "Lag", ["Presales"]),
    ],
    why_margins="Selling price minus land and construction — recognized on completion/possession",
    why_roic="Land timing and leverage dominate — cyclical ROIC",
    why_leverage="Historically high; RERA and cycles forcing discipline",
    why_working_capital="WIP inventory until sales and possession",
    why_valuation="NAV on project inventory is primary; P/E when earnings stable",
    primary_cycle="housing_cycle",
)

add(
    key="airlines", name="Airlines", aliases=["aviation", "air transport", "carrier"],
    revenue_drivers=["ASK capacity", "Load factor", "Yield/RASK", "Ancillary"],
    margin_drivers=["Load factor", "Yield", "Fuel cost", "Fleet utilization"],
    cost_drivers=["ATF", "Leases", "Airport charges", "Labour", "MRO"],
    value_drivers=["Load Factor", "Yield", "RASK", "CASK", "Fleet Size"],
    capital_intensity="High — aircraft leases and deposits",
    working_capital="Ticket receivables and advance bookings",
    cash_conversion="Weak — high opex and lease burden",
    operating_leverage="Very high — fixed fleet cost vs passengers",
    pricing_power="Low — intense price competition",
    competitive_structure="oligopoly",
    porter=P("Very High — slots, capital, licenses", "High — Boeing/Airbus, airports", "High — passengers", "Medium — rail/video conf", "Very High"),
    concentration="Oligopoly domestically post consolidation",
    regulators=["DGCA", "MoCA", "AAI", "SEBI"],
    regulatory_risks=["Fare regulation (legacy)", "Safety audits", "Route rights", "ATF taxation"],
    valuation_methods=["EV/EBITDAR", "P/E", "EV/ASK"],
    valuation_why="EBITDAR before aircraft rent is standard aviation metric",
    lifecycle="mature", typical_roic="Low to negative — structurally challenging",
    typical_growth="GDP+ passenger traffic; capacity-led",
    typical_risks=["Fuel spikes", "Fare wars", "Lease obligations", "Safety incidents"],
    risk_weightings={"commodity": "High", "demand": "High", "execution": "High", "refinancing": "Medium"},
    macro_sensitivity=["ATF prices", "Consumer travel", "FX (lease/ATF)", "Competition"],
    customers=["Leisure", "Business", "VFR traffic"], suppliers=["Airframe OEMs", "Airports", "ATF suppliers"],
    adjacent_industries=["hotels", "logistics"], substitutes=["Rail", "Video conferencing", "Surface transport"],
    capital_allocation_typical="Fleet leases dominate; minimal dividends",
    kpis=[
        K("load_factor", "Load Factor", "RPK / ASK", "Capacity fill", "High", "Low", ["RASK"]),
        K("yield", "Yield", "Passenger revenue / RPK", "Pricing", "Stable", "Falling", ["RASK"]),
        K("rask", "RASK", "Revenue / ASK", "Unit revenue", "Rising", "Falling", ["Load factor", "Yield"]),
        K("cask", "CASK", "Cost / ASK", "Unit cost", "Controlled", "Rising", ["ATF"]),
        K("ask_growth", "ASK Growth", "Capacity growth", "Supply", "Disciplined", "Overcapacity", ["Load factor"]),
    ],
    why_margins="RASK minus CASK — thin at best",
    why_roic="Lease-heavy model yields poor ROIC industry-wide",
    why_leverage="High operating and financial leverage on fleet",
    why_working_capital="Advance ticket sales help; receivables minor",
    why_valuation="EV/EBITDAR normalizes lease structures",
    primary_cycle="expansion",
)

add(
    key="logistics", name="Logistics", aliases=["3pl", "supply chain", "freight", "express"],
    revenue_drivers=["Shipment volumes", "Network density", "Contract wins", "Mix (express vs freight)"],
    margin_drivers=["Asset utilization", "Route density", "Fuel surcharge", "Automation"],
    cost_drivers=["Fuel", "Labour/drivers", "Fleet/warehousing", "Technology"],
    value_drivers=["Volume Growth", "Asset Turn", "Operating Margin", "Network Reach", "Customer Retention"],
    capital_intensity="Moderate — warehouses and fleet (asset-heavy players)",
    working_capital="Receivables from corporate clients",
    cash_conversion="Moderate — capex for network expansion",
    operating_leverage="Moderate-High — network fixed cost vs volume",
    pricing_power="Low-Moderate — contracts and service quality",
    competitive_structure="fragmented",
    porter=P("Medium — network, technology", "Medium — fuel, vehicles", "Medium-High — large shippers", "Medium — in-house logistics", "High"),
    concentration="Fragmented; express segment consolidating",
    regulators=["MoRTH", "GST", "SEBI"],
    regulatory_risks=["E-way bill/GST", "Driver regulations", "Cross-border"],
    valuation_methods=["EV/EBITDA", "P/E", "EV/Sales"],
    valuation_why="EBITDA captures network scale; asset-light models differ",
    lifecycle="growth", typical_roic="Low to mid-teens depending on asset intensity",
    typical_growth="E-commerce and manufacturing double-digit",
    typical_risks=["Fuel", "Competition", "Working capital", "Execution on integration"],
    risk_weightings={"execution": "High", "demand": "Medium", "commodity": "Medium", "refinancing": "Low"},
    macro_sensitivity=["E-commerce", "Manufacturing", "Fuel prices", "Trade"],
    customers=["E-commerce", "FMCG", "Auto", "Pharma"], suppliers=["Fuel", "Vehicle OEMs", "Warehouse landlords"],
    adjacent_industries=["retail", "internet_platforms", "shipping", "infrastructure"], substitutes=["In-house fleet", "Rail freight", "Hyperlocal"],
    capital_allocation_typical="Network capex and M&A; asset-light players return cash",
    kpis=[
        K("volume_growth", "Volume Growth", "Shipment/tonnage growth", "Demand", "Strong", "Weak", ["Revenue"]),
        K("asset_turn", "Asset Turn", "Revenue / net fixed assets", "Efficiency", "High", "Low", ["ROIC"]),
        K("operating_margin", "Operating Margin", "EBIT / revenue", "Scale benefits", "Expanding", "Compressing", ["Fuel"]),
        K("network_reach", "Network Reach", "Pin codes/hubs covered", "Moat", "Expanding", "Stagnant", ["Volume"]),
        K("customer_retention", "Customer Retention", "Repeat contract share", "Stickiness", "High", "Low", ["Margin"]),
    ],
    why_margins="Density and utilization minus fuel and labour",
    why_roic="Asset turns determine ROIC — asset-light higher",
    why_leverage="Moderate for fleet and warehouses",
    why_working_capital="Corporate receivables; minimal inventory",
    why_valuation="EV/EBITDA for comparability across models",
    primary_cycle="expansion",
)

add(
    key="shipping", name="Shipping", aliases=["maritime", "shipping lines", "ports", "containers"],
    revenue_drivers=["Freight rates", "Fleet utilization", "Trade volumes", "Charter rates"],
    margin_drivers=["Spot vs contract mix", "Bunker costs", "Fleet utilization", "Route mix"],
    cost_drivers=["Bunker fuel", "Crew", "Maintenance", "Port charges", "Leases"],
    value_drivers=["TCE/Daily Earnings", "Utilization", "Fleet Age", "Debt/EBITDA", "Order book"],
    capital_intensity="Very high — vessels",
    working_capital="Low-Moderate — receivables",
    cash_conversion="Highly cyclical with freight rates",
    operating_leverage="Very high — fixed vessel cost vs utilization",
    pricing_power="None globally — spot market sets rates",
    competitive_structure="global",
    porter=P("High — capital, expertise", "Medium — yards, bunkers", "Medium — charterers", "Medium — air/rail", "High globally"),
    concentration="Global oligopolies in container; fragmented in bulk",
    regulators=["DG Shipping", "IMO", "Port authorities", "SEBI"],
    regulatory_risks=["Environmental (IMO 2020/2050)", "Safety", "Flag state rules"],
    valuation_methods=["P/E", "EV/EBITDA", "NAV (fleet)", "TCE multiples"],
    valuation_why="NAV on fleet plus cyclical EBITDA at current rates",
    lifecycle="cyclical", typical_roic="Highly cyclical — double-digit at rate peaks",
    typical_growth="Trade volume linked — volatile",
    typical_risks=["Rate collapse", "Bunker spikes", "Geopolitics", "Overordering vessels"],
    risk_weightings={"commodity": "High", "demand": "High", "refinancing": "Medium", "regulatory": "Medium"},
    macro_sensitivity=["Global trade", "Baltic indices", "Bunker prices", "China exports"],
    customers=["Exporters/importers", "Charterers", "Commodity traders"], suppliers=["Shipyards", "Bunker suppliers", "Crew agencies"],
    adjacent_industries=["logistics", "oil_gas", "metals"], substitutes=["Air freight", "Rail", "Pipeline"],
    capital_allocation_typical="Buy vessels at trough; sell/charter at peaks; delever in booms",
    kpis=[
        K("tce", "TCE", "Time charter equivalent earnings", "Rate capture", "Strong", "Weak", ["Utilization"]),
        K("utilization", "Fleet Utilization", "Days employed / available", "Asset use", "High", "Low", ["TCE"]),
        K("bunker_cost", "Bunker Cost", "Fuel / day or voyage", "Margin", "Controlled", "Spiking", ["TCE"]),
        K("fleet_age", "Fleet Age", "Average vessel age", "Capex/refit need", "Young", "Aging", ["Opex"]),
        K("order_book", "Order Book", "Vessels on order / fleet", "Future supply", "Disciplined", "Over-ordered", ["Rates"]),
    ],
    why_margins="TCE minus bunker and opex — purely cyclical",
    why_roic="Vessel acquisition timing drives ROIC",
    why_leverage="High at cycle peaks",
    why_working_capital="Minimal vs asset base",
    why_valuation="NAV plus cyclical P/E at normalized rates",
    primary_cycle="commodity_cycle",
)

add(
    key="hotels", name="Hotels", aliases=["hospitality", "lodging", "resorts"],
    revenue_drivers=["Occupancy", "ADR", "RevPAR", "Room and F&B mix"],
    margin_drivers=["Occupancy", "ADR", "Fixed cost leverage", "F&B margin"],
    cost_drivers=["Staff", "Utilities", "Franchise fees", "Maintenance", "Lease/rent"],
    value_drivers=["RevPAR", "Occupancy", "ADR", "Pipeline", "GOP Margin"],
    capital_intensity="High — property, fit-out, pre-opening",
    working_capital="Low — guest receivables minimal",
    cash_conversion="Moderate — seasonal; weak in ramp-up",
    operating_leverage="Very high — fixed property cost vs occupancy",
    pricing_power="Moderate — location and brand; competitive in metros",
    competitive_structure="fragmented",
    porter=P("High — location, capital, brand", "Medium — OTAs, staff", "High — leisure/corporate", "Medium — Airbnb, homestays", "High"),
    concentration="Fragmented; chains in upscale/midscale",
    regulators=["State tourism", "FSSAI", "Fire safety", "SEBI"],
    regulatory_risks=["Liquor licensing", "Safety", "Tourism policy"],
    valuation_methods=["EV/EBITDA", "EV/Key", "RevPAR multiples"],
    valuation_why="RevPAR and per-key EBITDA capture operating leverage on rooms",
    lifecycle="growth", typical_roic="Low to mid-teens at stabilized occupancy",
    typical_growth="Room additions plus RevPAR recovery",
    typical_risks=["Overbuilding", "OTA commission", "Seasonality", "Execution on new hotels"],
    risk_weightings={"demand": "High", "execution": "High", "refinancing": "Medium", "regulatory": "Low"},
    macro_sensitivity=["Business travel", "Tourism", "GDP", "Events/MICE"],
    customers=["Leisure", "Corporate", "MICE", "Inbound tourism"], suppliers=["OTAs", "Staff", "F&B vendors"],
    adjacent_industries=["airlines", "media", "internet_platforms"], substitutes=["Airbnb", "Serviced apartments", "Video meetings"],
    capital_allocation_typical="New property capex; asset-light management contracts where possible",
    kpis=[
        K("occupancy", "Occupancy", "Rooms sold / available", "Utilization", "High", "Low", ["RevPAR"]),
        K("adr", "ADR", "Average daily rate", "Pricing", "Rising", "Falling", ["RevPAR"]),
        K("revpar", "RevPAR", "Revenue per available room", "Combined metric", "Growing", "Declining", ["Occupancy", "ADR"]),
        K("gop_margin", "GOP Margin", "Gross operating profit / revenue", "Operating efficiency", "Healthy", "Thin", ["Fixed costs"]),
        K("pipeline_keys", "Pipeline Keys", "Rooms under development", "Growth", "Disciplined", "Overextended", ["RevPAR"]),
    ],
    why_margins="RevPAR minus variable opex and fixed property costs",
    why_roic="High capex per key; stabilized assets earn acceptable returns",
    why_leverage="Moderate-High on owned properties",
    why_working_capital="Minimal — guest prepay common",
    why_valuation="EV/EBITDA and EV/Key standard for hospitality",
    primary_cycle="expansion",
)

add(
    key="media", name="Media", aliases=["entertainment", "broadcasting", "ott", "publishing"],
    revenue_drivers=["Advertising", "Subscriptions", "Content licensing", "Box office"],
    margin_drivers=["Content amortization", "Ad yields", "Subscription ARPU", "Mix"],
    cost_drivers=["Content creation", "Talent", "Marketing", "Distribution"],
    value_drivers=["Viewership/MAU", "Ad Revenue", "Subscription Growth", "Content ROI", "ARPU"],
    capital_intensity="Moderate — content is intangible capex",
    working_capital="Receivables from advertisers; content advances",
    cash_conversion="Lumpy — content spend upfront",
    operating_leverage="High — hit content drives disproportionate returns",
    pricing_power="Moderate for differentiated IP; weak for generic content",
    competitive_structure="oligopoly",
    porter=P("Medium-High — content, distribution", "Medium — talent", "Medium — advertisers/viewers", "High — digital/social", "Very High"),
    concentration="Oligopoly in TV/distribution; fragmented in digital",
    regulators=["MIB", "TRAI", "CBFC", "SEBI"],
    regulatory_risks=["Content regulation", "Tariff orders (TV)", "Digital media rules"],
    valuation_methods=["EV/EBITDA", "EV/Sales", "P/E", "SOTP"],
    valuation_why="SOTP for content library, distribution, and digital separately",
    lifecycle="growth", typical_roic="Volatile — hits drive spikes",
    typical_growth="Digital faster than linear TV",
    typical_risks=["Content flops", "Ad cyclicality", "Regulatory", "Platform competition"],
    risk_weightings={"demand": "High", "execution": "High", "regulatory": "Medium", "market": "Medium"},
    macro_sensitivity=["Ad spend", "Consumer leisure", "Digital adoption"],
    customers=["Advertisers", "Subscribers", "Platforms"], suppliers=["Talent", "Production", "Sports rights"],
    adjacent_industries=["telecom", "internet_platforms", "hotels"], substitutes=["Social media", "User-generated content", "Gaming"],
    capital_allocation_typical="Content investment; M&A for IP and platforms",
    kpis=[
        K("viewership", "Viewership/MAU", "Audience reach", "Monetization base", "Growing", "Declining", ["Ad revenue"]),
        K("ad_revenue", "Ad Revenue", "Advertising income", "Cyclical revenue", "Strong", "Weak", ["Viewership"]),
        K("subscribers", "Subscribers", "Paid subscriber base", "Recurring revenue", "Growing", "Churning", ["ARPU"]),
        K("arpu", "ARPU", "Revenue / subscriber", "Monetization", "Rising", "Falling", ["Subs"]),
        K("content_roi", "Content ROI", "Revenue / content spend", "Investment efficiency", "High on hits", "Poor", ["Margin"]),
    ],
    why_margins="Ad/sub revenue minus content amortization and marketing",
    why_roic="Content hits create lumpy ROIC",
    why_leverage="Moderate for content-heavy balance sheets",
    why_working_capital="Content advances and ad receivables",
    why_valuation="SOTP and EV/EBITDA with content library value",
    primary_cycle="expansion",
)

add(
    key="education", name="Education", aliases=["edtech", "k12", "higher education", "training"],
    revenue_drivers=["Enrollments", "Course fees", "Capacity utilization", "Digital subscriptions"],
    margin_drivers=["Seat fill", "Teacher cost per student", "Marketing CAC", "Mix (online/offline)"],
    cost_drivers=["Faculty", "Campus/rent", "Marketing", "Technology"],
    value_drivers=["Enrollments", "Revenue per Student", "Capacity Utilization", "Placement Outcomes", "Retention"],
    capital_intensity="Moderate — campuses and tech platform",
    working_capital="Fee receivables; advance fee collections",
    cash_conversion="Moderate — seasonal admissions",
    operating_leverage="High — fixed campus cost vs seats filled",
    pricing_power="Moderate — brand and outcomes; regulated caps in some segments",
    competitive_structure="fragmented",
    porter=P("Medium — accreditation, brand", "Medium — faculty", "Medium-High — students", "High — free online content", "High"),
    concentration="Fragmented; branded chains in K-12 and test prep",
    regulators=["UGC", "AICTE", "NCERT", "State education boards", "SEBI"],
    regulatory_risks=["Fee regulation", "Accreditation", "Online degree norms"],
    valuation_methods=["P/E", "EV/EBITDA", "EV/Student"],
    valuation_why="Earnings and per-student metrics for enrollment businesses",
    lifecycle="growth", typical_roic="Mid-teens for established institutions",
    typical_growth="Demographic and aspiration-led; edtech cyclical",
    typical_risks=["Regulation", "CAC inflation", "Outcomes reputation", "Seasonality"],
    risk_weightings={"regulatory": "High", "execution": "High", "demand": "Medium", "market": "Medium"},
    macro_sensitivity=["Employment outcomes", "Disposable income", "Policy on foreign/edtech"],
    customers=["Students", "Parents", "Corporates (B2B)"], suppliers=["Faculty", "Content", "Technology"],
    adjacent_industries=["internet_platforms", "media", "software"], substitutes=["Free MOOCs", "Government schools", "Self-study"],
    capital_allocation_typical="Campus expansion and digital platform; moderate dividends",
    kpis=[
        K("enrollments", "Enrollments", "Student count", "Scale", "Growing", "Declining", ["Revenue"]),
        K("rev_per_student", "Revenue per Student", "Fees / student", "Pricing", "Stable/rising", "Falling", ["Margin"]),
        K("capacity_util", "Capacity Utilization", "Seats filled / capacity", "Fixed cost leverage", "High", "Low", ["Margin"]),
        K("retention", "Retention", "Students continuing", "Quality signal", "High", "Low", ["Brand"]),
        K("placement_rate", "Placement Rate", "Placed / eligible graduates", "Outcomes (HE)", "Strong", "Weak", ["Enrollments"]),
    ],
    why_margins="Fees minus faculty and campus costs at utilization",
    why_roic="Campus utilization drives returns on property and brand investment",
    why_leverage="Low to moderate",
    why_working_capital="Fee collections often upfront per term",
    why_valuation="P/E and EV/EBITDA for stable enrollment franchises",
    primary_cycle="expansion",
)

add(
    key="agriculture", name="Agriculture", aliases=["agri", "agribusiness", "farming inputs"],
    revenue_drivers=["Volume", "Crop prices", "Monsoon", "Export demand"],
    margin_drivers=["Yield", "Input costs", "MSP/support prices", "Processing margin"],
    cost_drivers=["Seeds", "Fertilizers", "Labour", "Irrigation", "Logistics"],
    value_drivers=["Volume", "Realization", "Yield", "Market Share", "Distribution"],
    capital_intensity="Low at farmgate; moderate in processing",
    working_capital="Seasonal inventory and receivables",
    cash_conversion="Seasonal — weak post-harvest gluts",
    operating_leverage="Low at farm level; moderate in processing",
    pricing_power="Low — commodity pricing; brand in inputs",
    competitive_structure="fragmented",
    porter=P("Medium in inputs — R&D, distribution", "Medium — raw agri", "Medium — farmers/trade", "Medium — substitutes", "High in inputs"),
    concentration="Fragmented farming; oligopoly in seeds/fertilizers",
    regulators=["MoAFW", "FCI", "State APMCs", "SEBI"],
    regulatory_risks=["MSP changes", "Export bans", "GM norms", "APMC reforms"],
    valuation_methods=["P/E", "EV/EBITDA", "EV/Tonne"],
    valuation_why="Processing and input companies valued on earnings; commodity on tonnage",
    lifecycle="mature", typical_roic="Mid-teens for branded input players",
    typical_growth="Volume tied to monsoon and crop acreage",
    typical_risks=["Weather", "Policy", "Price volatility", "Inventory"],
    risk_weightings={"commodity": "High", "regulatory": "High", "demand": "Medium", "execution": "Medium"},
    macro_sensitivity=["Monsoon", "Global agri prices", "MSP", "Export policy"],
    customers=["Farmers", "Traders", "Food processors"], suppliers=["Agrochemical API", "Retailers", "Contract farmers"],
    adjacent_industries=["fmcg", "chemicals", "logistics"], substitutes=["Imports", "Alternate crops"],
    capital_allocation_typical="Distribution and R&D in inputs; processing capex",
    kpis=[
        K("volume", "Volume", "Tonnes/units sold", "Demand", "Growing", "Weak", ["Revenue"]),
        K("realization", "Realization", "Price per unit", "Commodity cycle", "Favorable", "Weak", ["Margin"]),
        K("market_share", "Market Share", "Category share (inputs)", "Competitive position", "Stable/gaining", "Losing", ["Volume"]),
        K("yield", "Crop Yield", "Output per hectare (proxy)", "Farm productivity", "Strong monsoon", "Stress", ["Volume"]),
        K("distribution_reach", "Distribution Reach", "Dealer/retail coverage", "Go-to-market", "Expanding", "Stagnant", ["Share"]),
    ],
    why_margins="Realization minus input and logistics; processing adds value",
    why_roic="Branded inputs earn better ROIC than commodity trading",
    why_leverage="Conservative in agri inputs",
    why_working_capital="Seasonal — peaks around kharif/rabi",
    why_valuation="P/E for branded agri; EV/Tonne for commodity",
    primary_cycle="commodity_cycle",
)

add(
    key="qsr", name="QSR", aliases=["quick service restaurants", "fast food", "food chains"],
    revenue_drivers=["Same-store sales", "Unit growth", "Delivery mix", "Ticket size"],
    margin_drivers=["Food cost", "Occupancy cost", "Labour", "Delivery commission"],
    cost_drivers=["Food ingredients", "Rent", "Labour", "Marketing", "Aggregator fees"],
    value_drivers=["SSSG", "Unit Economics", "Store Count", "Food Cost %", "Delivery Mix"],
    capital_intensity="Moderate — franchisee or company-owned stores",
    working_capital="Low — quick inventory turns",
    cash_conversion="Strong in franchise models",
    operating_leverage="Moderate — store fixed cost vs SSSG",
    pricing_power="Moderate — brand supports; value segment sensitive",
    competitive_structure="oligopoly",
    porter=P("Medium — brand, location, supply chain", "Medium — food suppliers", "High — consumers", "High — home cooking, delivery-only", "High"),
    concentration="Global chains plus strong domestic brands",
    regulators=["FSSAI", "Local municipal", "SEBI"],
    regulatory_risks=["Food safety", "Labelling", "Delivery regulation"],
    valuation_methods=["EV/EBITDA", "P/E", "EV/Unit"],
    valuation_why="Per-unit EBITDA and SSSG drive chain valuations",
    lifecycle="growth", typical_roic="Mid-teens for mature franchise systems",
    typical_growth="Unit expansion plus mid-single SSSG",
    typical_risks=["Food inflation", "Rent", "Competition", "Delivery economics"],
    risk_weightings={"demand": "High", "execution": "Medium", "commodity": "Medium", "regulatory": "Low"},
    macro_sensitivity=["Urban consumption", "Food inflation", "Delivery adoption"],
    customers=["Urban youth", "Families", "Office clusters"], suppliers=["Dairy", "Poultry", "Beverage", "Packaging"],
    adjacent_industries=["retail", "internet_platforms", "agriculture"], substitutes=["Home delivery cloud kitchens", "Street food", "Cook at home"],
    capital_allocation_typical="New stores and supply chain; franchisee-funded expansion",
    kpis=[
        K("sssg", "SSSG", "Same-store sales growth", "Organic health", "Positive", "Negative", ["Traffic", "Ticket"]),
        K("food_cost", "Food Cost %", "Food cost / sales", "Margin lever", "Controlled", "Rising", ["Margin"]),
        K("store_count", "Store Count", "Operating units", "Scale", "Growing", "Stagnant", ["Revenue"]),
        K("unit_economics", "Unit EBITDA", "Store-level EBITDA", "Expansion viability", "Positive", "Negative", ["SSSG"]),
        K("delivery_mix", "Delivery Mix", "Delivery / total sales", "Channel economics", "Balanced", "Commission-heavy", ["Margin"]),
    ],
    why_margins="Ticket minus food and occupancy at store level",
    why_roic="Franchise models improve ROIC vs company-owned",
    why_leverage="Low to moderate",
    why_working_capital="Minimal inventory — daily fresh in many formats",
    why_valuation="EV/EBITDA and EV/Unit for rollout stories",
    primary_cycle="expansion",
)

add(
    key="internet_platforms", name="Internet Platforms", aliases=["platform", "marketplace", "e-commerce", "digital platforms"],
    revenue_drivers=["GMV/transaction volume", "Take rate", "Advertising", "Subscriptions"],
    margin_drivers=["Take rate", "Unit economics", "Marketing efficiency", "Scale"],
    cost_drivers=["Customer acquisition", "Logistics subsidies", "Technology", "Incentives"],
    value_drivers=["GMV", "Take Rate", "MAU", "Contribution Margin", "Net Retention"],
    capital_intensity="Asset-light — technology and working capital for marketplace",
    working_capital="Payables to sellers; receivables from customers",
    cash_conversion="Weak during growth — cash burn for acquisition",
    operating_leverage="Very high at scale — fixed tech cost vs GMV",
    pricing_power="Moderate — network effects; competition on subsidies",
    competitive_structure="platform",
    porter=P("High — network effects, scale", "Medium — sellers/merchants", "High — users", "Medium — offline retail", "Very High"),
    concentration="Winner-take-most in categories; few national platforms",
    regulators=["MeitY", "DPIIT", "CCI", "RBI (payments)", "SEBI"],
    regulatory_risks=["E-commerce FDI rules", "Data localization", "Antitrust", "Fintech norms"],
    valuation_methods=["EV/Sales", "EV/GMV", "P/E (at scale)"],
    valuation_why="GMV and take-rate at scale; earnings secondary during growth",
    lifecycle="growth", typical_roic="Negative to low early; improves at scale",
    typical_growth="Very high when category penetration low",
    typical_risks=["Burn rate", "Regulation", "Competition", "Unit economics"],
    risk_weightings={"execution": "High", "regulatory": "High", "demand": "High", "refinancing": "Medium"},
    macro_sensitivity=["Consumer spending", "Funding markets", "Digital penetration"],
    customers=["Consumers", "Merchants", "Advertisers"], suppliers=["Logistics", "Cloud", "Payment rails"],
    adjacent_industries=["retail", "logistics", "software", "media"], substitutes=["Offline retail", "Brand D2C sites", "Social commerce"],
    capital_allocation_typical="Reinvest in growth and subsidies; M&A for category expansion",
    kpis=[
        K("gmv", "GMV", "Gross merchandise value", "Platform scale", "Growing", "Decelerating", ["Revenue"]),
        K("take_rate", "Take Rate", "Revenue / GMV", "Monetization", "Stable/rising", "Compressing", ["Margin"]),
        K("mau", "MAU", "Monthly active users", "Engagement", "Growing", "Flat", ["GMV"]),
        K("contribution_margin", "Contribution Margin", "Unit profit before fixed", "Path to profit", "Positive", "Negative", ["Take rate"]),
        K("cac", "CAC", "Cost to acquire customer", "Growth efficiency", "Falling", "Spiking", ["LTV"]),
    ],
    why_margins="Take rate minus variable logistics and incentives",
    why_roic="Capital-light but often negative until scale",
    why_leverage="Equity-funded growth typical",
    why_working_capital="Marketplace float can be favorable",
    why_valuation="EV/GMV and EV/Sales until profitable at scale",
    primary_cycle="technology_cycle",
)

add(
    key="data_centers", name="Data Centers", aliases=["colocation", "dc", "hyperscale", "cloud infrastructure"],
    revenue_drivers=["Power capacity sold", "Colocation contracts", "Interconnect", "Hyperscale leases"],
    margin_drivers=["Utilization", "Power cost", "PUE efficiency", "Contract escalators"],
    cost_drivers=["Power", "Land/build", "Cooling", "Security", "Fiber"],
    value_drivers=["Utilization", "Contracted Capacity", "PUE", "Churn", "Revenue per kW"],
    capital_intensity="Very high — land, shell, power, cooling",
    working_capital="Low — long-term contracts",
    cash_conversion="Moderate — heavy upfront capex, stable inflows",
    operating_leverage="High — fixed facility cost vs utilization",
    pricing_power="Moderate-High — location and power access moats",
    competitive_structure="oligopoly",
    porter=P("High — land, power, connectivity", "Medium — power utilities", "Medium-High — hyperscalers", "Medium — cloud/on-prem", "Medium"),
    concentration="Oligopoly in tier-1 cities; growing with cloud demand",
    regulators=["MeitY", "State power/discoms", "SEBI"],
    regulatory_risks=["Data localization", "Power tariffs", "Building codes"],
    valuation_methods=["EV/EBITDA", "DCF", "Cap rate on NOI"],
    valuation_why="Long-term contracted cash flows suit DCF and cap rates",
    lifecycle="growth", typical_roic="Mid-single to low-teens unlevered",
    typical_growth="Strong — cloud and AI workload demand",
    typical_risks=["Power availability", "Customer concentration", "Capex overbuild", "Technology shift"],
    risk_weightings={"execution": "High", "refinancing": "Medium", "regulatory": "Medium", "demand": "Medium"},
    macro_sensitivity=["Cloud capex", "Power costs", "Interest rates", "Data sovereignty policy"],
    customers=["Hyperscalers", "Enterprises", "Cloud providers"], suppliers=["Power utilities", "Equipment OEMs", "Fiber providers"],
    adjacent_industries=["telecom", "software", "it_services", "power"], substitutes=["On-premise", "Public cloud regions abroad"],
    capital_allocation_typical="Build-out capex; REIT/InvIT monetization at stabilization",
    kpis=[
        K("utilization", "Utilization", "Sold capacity / built", "Revenue ramp", "High", "Low", ["Revenue"]),
        K("pue", "PUE", "Total power / IT power", "Efficiency", "Low (efficient)", "High", ["Opex"]),
        K("contracted_capacity", "Contracted Capacity", "Pre-leased / built MW", "Visibility", "High pre-lease", "Spec build", ["Churn"]),
        K("churn", "Churn", "Lost capacity / base", "Retention", "Low", "High", ["Utilization"]),
        K("rev_per_kw", "Revenue per kW", "Revenue / sold kW", "Pricing", "Stable/rising", "Falling", ["Contracts"]),
    ],
    why_margins="Contracted revenue minus power and opex at utilization",
    why_roic="Heavy capex yields moderate unlevered returns; leverage improves equity ROIC",
    why_leverage="Project finance common on stabilized assets",
    why_working_capital="Minimal — long-term contracts",
    why_valuation="DCF and EV/EBITDA on contracted utility-like cash flows",
    primary_cycle="technology_cycle",
)
