"""Canonical seed catalogs for KF1 — companies, sectors, themes, macro.

Nifty-oriented liquid universe for V1 (expandable toward Nifty 500).
"""

from __future__ import annotations

COMPANIES: list[dict[str, str]] = [
    # IT
    {"ticker": "TCS", "name": "Tata Consultancy Services", "sector": "IT Services", "industry": "IT Services"},
    {"ticker": "INFY", "name": "Infosys", "sector": "IT Services", "industry": "IT Services"},
    {"ticker": "HCLTECH", "name": "HCLTech", "sector": "IT Services", "industry": "IT Services"},
    {"ticker": "WIPRO", "name": "Wipro", "sector": "IT Services", "industry": "IT Services"},
    {"ticker": "LTIM", "name": "LTIMindtree", "sector": "IT Services", "industry": "IT Services"},
    {"ticker": "TECHM", "name": "Tech Mahindra", "sector": "IT Services", "industry": "IT Services"},
    {"ticker": "PERSISTENT", "name": "Persistent Systems", "sector": "IT Services", "industry": "IT Services"},
    {"ticker": "COFORGE", "name": "Coforge", "sector": "IT Services", "industry": "IT Services"},
    {"ticker": "MPHASIS", "name": "Mphasis", "sector": "IT Services", "industry": "IT Services"},
    {"ticker": "LTTS", "name": "L&T Technology Services", "sector": "IT Services", "industry": "Engineering Services"},
    # Banks / Financials
    {"ticker": "HDFCBANK", "name": "HDFC Bank", "sector": "Banking", "industry": "Private Bank"},
    {"ticker": "ICICIBANK", "name": "ICICI Bank", "sector": "Banking", "industry": "Private Bank"},
    {"ticker": "SBIN", "name": "State Bank of India", "sector": "Banking", "industry": "PSU Bank"},
    {"ticker": "AXISBANK", "name": "Axis Bank", "sector": "Banking", "industry": "Private Bank"},
    {"ticker": "KOTAKBANK", "name": "Kotak Mahindra Bank", "sector": "Banking", "industry": "Private Bank"},
    {"ticker": "BAJFINANCE", "name": "Bajaj Finance", "sector": "Financial Services", "industry": "NBFC"},
    {"ticker": "BAJAJFINSV", "name": "Bajaj Finserv", "sector": "Financial Services", "industry": "Financial Conglomerate"},
    # Energy / Conglomerate
    {"ticker": "RELIANCE", "name": "Reliance Industries", "sector": "Energy", "industry": "Oil & Gas / Conglomerate"},
    {"ticker": "ONGC", "name": "Oil and Natural Gas Corporation", "sector": "Energy", "industry": "Oil & Gas"},
    {"ticker": "NTPC", "name": "NTPC", "sector": "Power", "industry": "Power Generation"},
    {"ticker": "POWERGRID", "name": "Power Grid Corporation", "sector": "Power", "industry": "Power Transmission"},
    # FMCG / Staples
    {"ticker": "HINDUNILVR", "name": "Hindustan Unilever", "sector": "FMCG", "industry": "Personal Care"},
    {"ticker": "ITC", "name": "ITC", "sector": "FMCG", "industry": "Diversified FMCG"},
    {"ticker": "NESTLEIND", "name": "Nestle India", "sector": "FMCG", "industry": "Food"},
    {"ticker": "BRITANNIA", "name": "Britannia Industries", "sector": "FMCG", "industry": "Food"},
    # Auto
    {"ticker": "MARUTI", "name": "Maruti Suzuki", "sector": "Auto", "industry": "Passenger Vehicles"},
    {"ticker": "TATAMOTORS", "name": "Tata Motors", "sector": "Auto", "industry": "Auto OEM"},
    {"ticker": "M&M", "name": "Mahindra & Mahindra", "sector": "Auto", "industry": "Auto OEM"},
    {"ticker": "BAJAJ-AUTO", "name": "Bajaj Auto", "sector": "Auto", "industry": "Two Wheelers"},
    {"ticker": "EICHERMOT", "name": "Eicher Motors", "sector": "Auto", "industry": "Two Wheelers / CV"},
    # Pharma
    {"ticker": "SUNPHARMA", "name": "Sun Pharmaceutical", "sector": "Pharma", "industry": "Pharmaceuticals"},
    {"ticker": "DRREDDY", "name": "Dr. Reddy's Laboratories", "sector": "Pharma", "industry": "Pharmaceuticals"},
    {"ticker": "CIPLA", "name": "Cipla", "sector": "Pharma", "industry": "Pharmaceuticals"},
    {"ticker": "DIVISLAB", "name": "Divi's Laboratories", "sector": "Pharma", "industry": "API / Pharma"},
    # Telecom / Infra / Cap goods
    {"ticker": "BHARTIARTL", "name": "Bharti Airtel", "sector": "Telecom", "industry": "Telecom Services"},
    {"ticker": "LT", "name": "Larsen & Toubro", "sector": "Capital Goods", "industry": "Engineering & Construction"},
    {"ticker": "SIEMENS", "name": "Siemens India", "sector": "Capital Goods", "industry": "Industrial"},
    {"ticker": "ABB", "name": "ABB India", "sector": "Capital Goods", "industry": "Industrial"},
    # Metals / Materials / Cement / Chemicals
    {"ticker": "TATASTEEL", "name": "Tata Steel", "sector": "Metals", "industry": "Steel"},
    {"ticker": "JSWSTEEL", "name": "JSW Steel", "sector": "Metals", "industry": "Steel"},
    {"ticker": "HINDALCO", "name": "Hindalco Industries", "sector": "Metals", "industry": "Aluminium"},
    {"ticker": "ULTRACEMCO", "name": "UltraTech Cement", "sector": "Capital Goods", "industry": "Cement"},
    {"ticker": "PIDILITIND", "name": "Pidilite Industries", "sector": "Chemicals", "industry": "Specialty Chemicals"},
    # Realty / Retail / Defence
    {"ticker": "DLF", "name": "DLF", "sector": "Real Estate", "industry": "Real Estate"},
    {"ticker": "DMART", "name": "Avenue Supermarts", "sector": "Retail", "industry": "Retail"},
    {"ticker": "BEL", "name": "Bharat Electronics", "sector": "Defence", "industry": "Defence Electronics"},
    {"ticker": "HAL", "name": "Hindustan Aeronautics", "sector": "Defence", "industry": "Aerospace & Defence"},
]

SECTORS: list[dict] = [
    {
        "sector_id": "banking",
        "label": "Banking",
        "definition": "Indian commercial banking — private and public sector banks.",
        "growth_drivers": ["Credit growth", "Deposit franchise", "Fee income"],
        "demand_drivers": ["Retail loans", "Corporate capex", "Working capital"],
        "key_metrics": ["NIM", "NPA", "RoA", "CASA", "Credit growth"],
        "major_tickers": ["HDFCBANK", "ICICIBANK", "SBIN", "AXISBANK", "KOTAKBANK"],
        "valuation_framework": "P/B vs RoA / growth; premium for liability franchise quality.",
        "risks": ["Asset quality cycles", "NIM compression", "Regulatory capital"],
        "catalysts": ["Rate cycle turns", "Credit reacceleration", "Fee income recovery"],
    },
    {
        "sector_id": "it_services",
        "label": "IT Services",
        "definition": "Indian IT / software services and global capability centres.",
        "growth_drivers": ["Discretionary IT spend", "Cloud / digital", "Large deals"],
        "demand_drivers": ["BFSI / manufacturing verticals", "Cost optimisation programmes", "GenAI projects"],
        "key_metrics": ["Revenue growth QoQ/YoY", "EBIT margin", "Utilisation", "Attrition", "Deal TCV"],
        "major_tickers": ["TCS", "INFY", "HCLTECH", "WIPRO", "LTIM", "TECHM"],
        "valuation_framework": "P/E vs growth and margin durability; relative to US peers.",
        "risks": ["US/Europe budget freezes", "Pricing pressure", "AI productivity disruption"],
        "catalysts": ["Guidance upgrades", "Large-deal wins", "GenAI monetisation"],
    },
    {
        "sector_id": "fmcg",
        "label": "FMCG",
        "definition": "Fast-moving consumer goods — staples, personal care, food.",
        "growth_drivers": ["Rural recovery", "Premiumisation", "Distribution reach"],
        "demand_drivers": ["Volume growth", "Pricing", "Mix upgrade"],
        "key_metrics": ["Volume growth", "Gross margin", "A&P", "Distribution"],
        "major_tickers": ["HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA"],
        "valuation_framework": "P/E premium for brand moat and consistent compounding.",
        "risks": ["Input cost inflation", "Rural slowdown", "Competitive intensity"],
        "catalysts": ["Rural demand rebound", "Gross margin expansion"],
    },
    {
        "sector_id": "pharma",
        "label": "Pharma",
        "definition": "Indian pharmaceuticals — formulations, API, specialty.",
        "growth_drivers": ["US generics", "Domestic formulations", "Specialty pipeline"],
        "demand_drivers": ["US approvals", "India chronic care", "Exports"],
        "key_metrics": ["US sales", "Gross margin", "R&D", "ANDA pipeline"],
        "major_tickers": ["SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB"],
        "valuation_framework": "P/E vs US specialty mix and pipeline quality.",
        "risks": ["FDA observations", "Price erosion", "API concentration"],
        "catalysts": ["Complex generic launches", "India growth acceleration"],
    },
    {
        "sector_id": "auto",
        "label": "Auto",
        "definition": "Indian automobiles — PV, CV, two-wheelers, EV transition.",
        "growth_drivers": ["PV demand", "CV cycle", "EV adoption", "Exports"],
        "demand_drivers": ["Interest rates", "Replacement demand", "Rural income"],
        "key_metrics": ["Wholesale volumes", "ASP", "Margin", "EV mix"],
        "major_tickers": ["MARUTI", "TATAMOTORS", "M&M", "BAJAJ-AUTO", "EICHERMOT"],
        "valuation_framework": "EV/EBITDA and P/E vs cycle position and EV optionality.",
        "risks": ["Commodity costs", "Demand slowdown", "EV disruption"],
        "catalysts": ["Festive demand", "New model launches", "EV scaling"],
    },
    {
        "sector_id": "capital_goods",
        "label": "Capital Goods",
        "definition": "Engineering, construction, industrial and capital equipment.",
        "growth_drivers": ["Domestic capex", "Infra spend", "Exports"],
        "demand_drivers": ["Order inflows", "Government infra", "Private capex"],
        "key_metrics": ["Order book", "Execution", "Working capital", "Margin"],
        "major_tickers": ["LT", "SIEMENS", "ABB", "ULTRACEMCO"],
        "valuation_framework": "Order book visibility and RoCE vs cycle.",
        "risks": ["Execution delays", "Working capital spikes"],
        "catalysts": ["Large order wins", "Capex upcycle continuation"],
    },
    {
        "sector_id": "power",
        "label": "Power",
        "definition": "Power generation, transmission and related utilities.",
        "growth_drivers": ["Capacity addition", "Renewables", "Transmission capex"],
        "demand_drivers": ["Electricity demand", "Industrial activity"],
        "key_metrics": ["PLF", "Regulated equity", "Capex", "Receivables"],
        "major_tickers": ["NTPC", "POWERGRID"],
        "valuation_framework": "P/B for regulated utilities; growth for renewables.",
        "risks": ["Fuel costs", "Receivables", "Regulatory changes"],
        "catalysts": ["Renewable awards", "Transmission bids"],
    },
    {
        "sector_id": "defence",
        "label": "Defence",
        "definition": "Indian defence manufacturing and electronics.",
        "growth_drivers": ["Indigenisation", "Order pipeline", "Exports"],
        "demand_drivers": ["MoD orders", "Export clearances"],
        "key_metrics": ["Order book", "Execution", "Margins"],
        "major_tickers": ["BEL", "HAL"],
        "valuation_framework": "Order book / sales and strategic premium.",
        "risks": ["Order timing", "Execution", "Geopolitics"],
        "catalysts": ["Large defence contracts", "Export wins"],
    },
    {
        "sector_id": "real_estate",
        "label": "Real Estate",
        "definition": "Residential and commercial real estate developers.",
        "growth_drivers": ["Housing demand", "Launches", "Pre-sales"],
        "demand_drivers": ["Affordability", "Rates", "Urbanisation"],
        "key_metrics": ["Pre-sales", "Collections", "Net debt", "Inventory"],
        "major_tickers": ["DLF"],
        "valuation_framework": "NAV discount/premium and pre-sales growth.",
        "risks": ["Rates", "Inventory", "Regulatory approvals"],
        "catalysts": ["Strong launch pipeline", "Rate easing"],
    },
    {
        "sector_id": "chemicals",
        "label": "Chemicals",
        "definition": "Specialty and commodity chemicals.",
        "growth_drivers": ["Import substitution", "Exports", "Specialty mix"],
        "demand_drivers": ["Global demand", "Domestic industrial activity"],
        "key_metrics": ["Gross margin", "Capacity utilisation", "Exports"],
        "major_tickers": ["PIDILITIND"],
        "valuation_framework": "Specialty premium vs commodity cycle.",
        "risks": ["China competition", "Raw material volatility"],
        "catalysts": ["Capacity commissioning", "Mix upgrade"],
    },
    {
        "sector_id": "metals",
        "label": "Metals",
        "definition": "Steel, aluminium and related metals.",
        "growth_drivers": ["Infra demand", "Exports", "Realisations"],
        "demand_drivers": ["Construction", "Auto", "Global steel prices"],
        "key_metrics": ["Realisations", "Spreads", "Volume", "Net debt"],
        "major_tickers": ["TATASTEEL", "JSWSTEEL", "HINDALCO"],
        "valuation_framework": "EV/EBITDA through cycle; balance sheet quality.",
        "risks": ["Commodity prices", "China supply", "Coking coal"],
        "catalysts": ["Price recovery", "Volume growth"],
    },
    {
        "sector_id": "retail",
        "label": "Retail",
        "definition": "Organised retail and consumer discretionary retail formats.",
        "growth_drivers": ["Store expansion", "Same-store growth", "Private label"],
        "demand_drivers": ["Urban consumption", "Value retail"],
        "key_metrics": ["SSS", "Store adds", "Gross margin", "Inventory turns"],
        "major_tickers": ["DMART"],
        "valuation_framework": "P/E / EV/EBITDA vs growth runway.",
        "risks": ["Competition", "Execution of store adds"],
        "catalysts": ["SSS recovery", "Margin expansion"],
    },
    {
        "sector_id": "telecom",
        "label": "Telecom",
        "definition": "Telecom services and digital connectivity.",
        "growth_drivers": ["ARPU", "Subscriber mix", "Data usage"],
        "demand_drivers": ["Smartphone penetration", "Enterprise connectivity"],
        "key_metrics": ["ARPU", "Subscribers", "Capex", "Net debt"],
        "major_tickers": ["BHARTIARTL"],
        "valuation_framework": "EV/EBITDA and FCF yield post-capex cycle.",
        "risks": ["Tariff wars", "Spectrum costs", "Leverage"],
        "catalysts": ["Tariff hikes", "FCF inflection"],
    },
    {
        "sector_id": "financial_services",
        "label": "Financial Services",
        "definition": "NBFCs, insurance and diversified financials.",
        "growth_drivers": ["AUM growth", "Credit demand", "Insurance penetration"],
        "demand_drivers": ["Retail credit", "Capital markets activity"],
        "key_metrics": ["AUM growth", "NIM/spreads", "Asset quality", "RoE"],
        "major_tickers": ["BAJFINANCE", "BAJAJFINSV"],
        "valuation_framework": "P/B vs RoE and growth sustainability.",
        "risks": ["Funding costs", "Asset quality", "Regulation"],
        "catalysts": ["Growth reacceleration", "Cost of funds easing"],
    },
    {
        "sector_id": "energy",
        "label": "Energy",
        "definition": "Oil, gas and integrated energy conglomerates.",
        "growth_drivers": ["Refining margins", "Downstream", "Energy transition"],
        "demand_drivers": ["Oil prices", "Domestic fuel demand"],
        "key_metrics": ["GRM", "Throughput", "Net debt", "Segment EBIT"],
        "major_tickers": ["RELIANCE", "ONGC"],
        "valuation_framework": "SOTP for conglomerates; EV/EBITDA for upstream/refining.",
        "risks": ["Commodity prices", "Regulatory fuel pricing"],
        "catalysts": ["Margin recovery", "New energy projects"],
    },
]

THEMES: list[dict] = [
    {
        "theme_id": "artificial_intelligence",
        "label": "Artificial Intelligence",
        "definition": "AI / GenAI adoption across software, services and infrastructure.",
        "investment_thesis": "AI spend shifts from experimentation to production workloads.",
        "companies": ["TCS", "INFY", "HCLTECH", "PERSISTENT", "COFORGE"],
        "countries": ["India", "United States"],
        "beneficiaries": ["IT services with GenAI delivery", "Cloud / data platforms"],
        "risks": ["Monetisation lag", "Pricing pressure from productivity gains"],
        "catalysts": ["Large GenAI deals", "Margin-accretive AI mix"],
        "macro_drivers": ["US tech spend", "Enterprise digital budgets"],
        "related_sectors": ["it_services"],
    },
    {
        "theme_id": "ev",
        "label": "Electric Vehicles",
        "definition": "EV transition across two-wheelers, PV and supply chain.",
        "investment_thesis": "Policy support and cost curves drive multi-year EV adoption.",
        "companies": ["TATAMOTORS", "M&M", "EICHERMOT"],
        "countries": ["India"],
        "beneficiaries": ["EV OEMs", "Battery / component suppliers"],
        "risks": ["Subsidy changes", "Charging infra", "Competition"],
        "catalysts": ["New EV launches", "Local battery capacity"],
        "macro_drivers": ["Oil prices", "Policy incentives"],
        "related_sectors": ["auto"],
    },
    {
        "theme_id": "renewables",
        "label": "Renewables",
        "definition": "Renewable power generation, transmission and green energy.",
        "investment_thesis": "India's energy transition supports multi-year renewables capex.",
        "companies": ["NTPC", "POWERGRID", "RELIANCE"],
        "countries": ["India"],
        "beneficiaries": ["Renewable developers", "Transmission"],
        "risks": ["Tariff pressure", "Execution", "Grid constraints"],
        "catalysts": ["Auction wins", "Policy support"],
        "macro_drivers": ["Energy security", "Climate commitments"],
        "related_sectors": ["power", "energy"],
    },
    {
        "theme_id": "railways",
        "label": "Railways",
        "definition": "Railway modernisation, rolling stock and related capex.",
        "investment_thesis": "Sustained government railway capex supports industrial suppliers.",
        "companies": ["LT", "BEL"],
        "countries": ["India"],
        "beneficiaries": ["Cap goods", "Defence / electronics suppliers"],
        "risks": ["Order timing", "Budget allocation"],
        "catalysts": ["Large railway tenders"],
        "macro_drivers": ["Fiscal capex"],
        "related_sectors": ["capital_goods", "defence"],
    },
    {
        "theme_id": "manufacturing",
        "label": "Manufacturing",
        "definition": "India manufacturing / PLI-linked industrial expansion.",
        "investment_thesis": "China+1 and PLI support domestic manufacturing scale-up.",
        "companies": ["LT", "SIEMENS", "ABB", "RELIANCE"],
        "countries": ["India"],
        "beneficiaries": ["Cap goods", "Specialty chemicals", "Electronics"],
        "risks": ["Global demand", "Execution"],
        "catalysts": ["PLI offtake", "Private capex"],
        "macro_drivers": ["GDP", "Capex cycle"],
        "related_sectors": ["capital_goods", "chemicals"],
    },
    {
        "theme_id": "semiconductors",
        "label": "Semiconductors",
        "definition": "Semiconductor design, packaging and India ecosystem buildout.",
        "investment_thesis": "Strategic semiconductor investments create long-dated optionality.",
        "companies": ["RELIANCE"],
        "countries": ["India", "United States"],
        "beneficiaries": ["Electronics manufacturing", "Design services"],
        "risks": ["Capex intensity", "Technology risk", "Long gestation"],
        "catalysts": ["Policy awards", "JV announcements"],
        "macro_drivers": ["Geopolitics", "Tech export controls"],
        "related_sectors": ["capital_goods"],
    },
    {
        "theme_id": "china_plus_one",
        "label": "China Plus One",
        "definition": "Supply-chain diversification away from China concentration.",
        "investment_thesis": "Global firms diversify manufacturing and sourcing into India.",
        "companies": ["PIDILITIND", "LT", "DIVISLAB"],
        "countries": ["India"],
        "beneficiaries": ["Chemicals", "Pharma API", "Manufacturing"],
        "risks": ["China price competition", "Execution delays"],
        "catalysts": ["FDI / capacity announcements"],
        "macro_drivers": ["Trade policy", "Geopolitics"],
        "related_sectors": ["chemicals", "pharma", "manufacturing"],
    },
    {
        "theme_id": "defence_theme",
        "label": "Defence Indigenisation",
        "definition": "Domestic defence manufacturing and electronics indigenisation.",
        "investment_thesis": "Multi-year order cycle from Atmanirbhar defence policy.",
        "companies": ["BEL", "HAL"],
        "countries": ["India"],
        "beneficiaries": ["Defence OEMs", "Electronics"],
        "risks": ["Order lumpiness", "Geopolitics"],
        "catalysts": ["MoD contracts", "Export clearances"],
        "macro_drivers": ["Geopolitics", "Fiscal defence spend"],
        "related_sectors": ["defence"],
    },
    {
        "theme_id": "data_centres",
        "label": "Data Centres",
        "definition": "Data centre capacity, power and digital infrastructure.",
        "investment_thesis": "AI and cloud demand drive Indian data-centre capacity growth.",
        "companies": ["RELIANCE", "POWERGRID", "NTPC"],
        "countries": ["India"],
        "beneficiaries": ["Power", "Infra", "Telecom adjacency"],
        "risks": ["Power availability", "Capex intensity"],
        "catalysts": ["Capacity announcements", "Hyperscaler demand"],
        "macro_drivers": ["Digital adoption", "AI spend"],
        "related_sectors": ["power", "telecom", "energy"],
    },
    {
        "theme_id": "digital_payments",
        "label": "Digital Payments",
        "definition": "UPI / digital payments rails and fintech enablement.",
        "investment_thesis": "India's digital payment rails deepen financial inclusion and fee pools.",
        "companies": ["HDFCBANK", "ICICIBANK", "SBIN"],
        "countries": ["India"],
        "beneficiaries": ["Banks", "Payment ecosystems"],
        "risks": ["Fee compression", "Regulation"],
        "catalysts": ["Transaction growth", "New payment products"],
        "macro_drivers": ["Consumption", "Digital adoption"],
        "related_sectors": ["banking", "financial_services"],
    },
]

MACROS: list[dict] = [
    {
        "macro_id": "inflation",
        "label": "Inflation",
        "definition": "General price level changes (CPI / WPI).",
        "why_investors_care": "Drives real rates, margins, and policy response.",
        "affected_sectors": ["fmcg", "banking", "auto", "metals"],
        "leading_indicators": ["Commodity prices", "Food prices", "Core CPI"],
        "lagging_indicators": ["Wage inflation", "Services inflation"],
        "historical_episodes": ["2022 global inflation shock", "India food inflation spikes"],
    },
    {
        "macro_id": "interest_rates",
        "label": "Interest Rates",
        "definition": "Policy and market interest rates (RBI repo, bond yields).",
        "why_investors_care": "Affects valuations, credit demand, NIMs and housing.",
        "affected_sectors": ["banking", "financial_services", "real_estate", "auto"],
        "leading_indicators": ["Inflation prints", "RBI commentary", "Liquidity"],
        "lagging_indicators": ["Credit growth", "Housing demand"],
        "historical_episodes": ["COVID rate cut cycle", "2022–24 tightening"],
    },
    {
        "macro_id": "gdp",
        "label": "GDP",
        "definition": "Economic growth — GDP / GVA trajectory.",
        "why_investors_care": "Sets the earnings cycle for cyclicals and financials.",
        "affected_sectors": ["capital_goods", "auto", "metals", "banking"],
        "leading_indicators": ["PMI", "GST collections", "Credit growth"],
        "lagging_indicators": ["Unemployment", "Capacity utilisation"],
        "historical_episodes": ["COVID collapse / rebound", "Capex-led growth phases"],
    },
    {
        "macro_id": "fiscal_policy",
        "label": "Fiscal Policy",
        "definition": "Government spending, deficits and taxation.",
        "why_investors_care": "Directly drives infra / defence / railway demand.",
        "affected_sectors": ["capital_goods", "defence", "power", "railways"],
        "leading_indicators": ["Budget announcements", "Capex run-rate"],
        "lagging_indicators": ["Deficit outcomes"],
        "historical_episodes": ["Infra-heavy Union Budgets"],
    },
    {
        "macro_id": "oil",
        "label": "Oil",
        "definition": "Crude oil prices and energy complex.",
        "why_investors_care": "Impacts CAD, inflation, OMCs and consumer discretionary.",
        "affected_sectors": ["energy", "auto", "fmcg", "aviation adjacency"],
        "leading_indicators": ["Brent", "Geopolitical risk", "OPEC+"],
        "lagging_indicators": ["Fuel retail prices", "CPI transport"],
        "historical_episodes": ["2022 oil spike"],
    },
    {
        "macro_id": "currency",
        "label": "Currency",
        "definition": "INR / USD and broader FX moves.",
        "why_investors_care": "Translation impact for IT exporters; import costs for others.",
        "affected_sectors": ["it_services", "energy", "pharma", "metals"],
        "leading_indicators": ["DXY", "FII flows", "CAD"],
        "lagging_indicators": ["Import inflation"],
        "historical_episodes": ["INR depreciation cycles"],
    },
    {
        "macro_id": "bond_yields",
        "label": "Bond Yields",
        "definition": "Government and corporate bond yield levels/curve.",
        "why_investors_care": "Discount rates for equities and funding costs.",
        "affected_sectors": ["banking", "financial_services", "real_estate"],
        "leading_indicators": ["Inflation", "RBI policy", "Global yields"],
        "lagging_indicators": ["Credit spreads"],
        "historical_episodes": ["Global yield shocks"],
    },
    {
        "macro_id": "employment",
        "label": "Employment",
        "definition": "Labour market and wage conditions.",
        "why_investors_care": "Supports consumption and services demand.",
        "affected_sectors": ["fmcg", "retail", "auto", "it_services"],
        "leading_indicators": ["Hiring surveys", "EPFO"],
        "lagging_indicators": ["Wage growth"],
        "historical_episodes": ["Post-COVID labour normalisation"],
    },
    {
        "macro_id": "trade",
        "label": "Trade",
        "definition": "Exports, imports and trade balances.",
        "why_investors_care": "Signals global demand and CAD pressure.",
        "affected_sectors": ["metals", "pharma", "it_services", "chemicals"],
        "leading_indicators": ["Export orders", "Shipping rates"],
        "lagging_indicators": ["CAD prints"],
        "historical_episodes": ["Global trade slowdowns"],
    },
    {
        "macro_id": "geopolitics",
        "label": "Geopolitics",
        "definition": "Geopolitical risk and strategic policy shifts.",
        "why_investors_care": "Affects defence, energy, trade and supply chains.",
        "affected_sectors": ["defence", "energy", "chemicals"],
        "leading_indicators": ["Conflict risk", "Sanctions", "Alliances"],
        "lagging_indicators": ["Defence budgets", "Trade rerouting"],
        "historical_episodes": ["Russia-Ukraine", "Red Sea disruptions"],
    },
]
