"""Macro DNA — institutional identity of each macro variable."""

from __future__ import annotations

from typing import Any

from knowledge_factory.macro_intelligence.schema import MACRO_UNIVERSE

_RICH: dict[str, dict[str, Any]] = {
    "interest_rates": {
        "display_name": "Interest Rates",
        "description": "Policy / market cost of capital",
        "business_impact": "Reprices funding costs, discount rates, and credit demand",
        "primary_transmission": "discount_rate_and_credit_demand",
        "secondary_transmission": "asset_duration_and_valuations",
        "economic_drivers": ["inflation", "growth", "liquidity", "fx_stability"],
        "leading_indicators": ["policy_guidance", "core_cpi", "wage_growth"],
        "lagging_indicators": ["credit_growth", "housing"],
        "historical_behaviour": ["Hiking cycles compress duration assets", "Cuts unlock credit-sensitive demand"],
        "typical_duration": "12-36 months",
        "typical_volatility": "moderate",
        "valuation_impact": "Higher rates raise discount rates; favour shorter-duration cash flows",
        "portfolio_impact": "Reduce duration / leverage in hiking cycles",
        "risk_impact": "Liquidity and refinancing risk rise with rates",
    },
    "inflation": {
        "display_name": "Inflation",
        "description": "General price-level growth",
        "business_impact": "Compresses real margins until pricing power catches up",
        "primary_transmission": "input_costs_and_real_incomes",
        "secondary_transmission": "policy_rate_response",
        "economic_drivers": ["commodities", "wages", "demand", "fx"],
        "leading_indicators": ["commodity_prices", "pmi_prices", "wages"],
        "lagging_indicators": ["core_cpi", "services_inflation"],
        "historical_behaviour": ["High inflation → rate hikes → multiple compression"],
        "typical_duration": "6-24 months",
        "typical_volatility": "moderate_high",
        "valuation_impact": "Favours pricing-power and hard-asset earners",
        "portfolio_impact": "Tilt to quality / real assets; cut long-duration growth",
        "risk_impact": "Margin and policy shock risk",
    },
    "oil": {
        "display_name": "Oil",
        "description": "Global crude price level",
        "business_impact": "Input cost for transport/chemicals; revenue for producers",
        "primary_transmission": "energy_cost_and_terms_of_trade",
        "secondary_transmission": "inflation_and_policy",
        "economic_drivers": ["opec", "global_growth", "inventories", "geopolitics"],
        "leading_indicators": ["inventories", "spare_capacity"],
        "lagging_indicators": ["cpi_energy"],
        "historical_behaviour": ["Oil shocks create sector rotation within weeks"],
        "typical_duration": "variable",
        "typical_volatility": "high",
        "valuation_impact": "Mid-cycle normalisation for energy; margin stress for consumers",
        "portfolio_impact": "Energy overweight vs airlines/paint/logistics underweight",
        "risk_impact": "Inflation pass-through and demand destruction",
    },
    "usd_inr": {
        "display_name": "USD/INR",
        "description": "INR exchange rate vs USD",
        "business_impact": "Export realisation vs import costs",
        "primary_transmission": "fx_translation_and_competitiveness",
        "secondary_transmission": "imported_inflation",
        "economic_drivers": ["rate_differentials", "cad", "risk_sentiment", "oil"],
        "leading_indicators": ["dxy", "oil", "fii_flows"],
        "lagging_indicators": ["imported_cpi"],
        "historical_behaviour": ["USD strength supports IT exporters in INR terms"],
        "typical_duration": "months_to_years",
        "typical_volatility": "moderate",
        "valuation_impact": "IT/pharma exporters benefit from INR weakness",
        "portfolio_impact": "Export tilt when USD strengthens",
        "risk_impact": "Import-heavy and USD debt vulnerability",
    },
    "gdp": {
        "display_name": "GDP Growth",
        "description": "Real economic growth",
        "business_impact": "Demand backdrop for cyclical earnings",
        "primary_transmission": "aggregate_demand",
        "secondary_transmission": "credit_and_capex",
        "economic_drivers": ["consumption", "investment", "exports", "government"],
        "leading_indicators": ["pmi", "credit_growth", "tax_collections"],
        "lagging_indicators": ["unemployment"],
        "historical_behaviour": ["Growth troughs precede equity recoveries"],
        "typical_duration": "years",
        "typical_volatility": "low_moderate",
        "valuation_impact": "Cyclicals re-rate into recoveries",
        "portfolio_impact": "Raise cyclical beta into recovery",
        "risk_impact": "Recession earnings risk",
    },
    "liquidity": {
        "display_name": "Liquidity",
        "description": "System financial conditions / money ease",
        "business_impact": "Funding availability and risk appetite",
        "primary_transmission": "financial_conditions",
        "secondary_transmission": "asset_multiples",
        "economic_drivers": ["policy", "fx_intervention", "deficit_financing"],
        "leading_indicators": ["policy_corridor", "surplus_liquidity"],
        "lagging_indicators": ["credit_growth"],
        "historical_behaviour": ["Tight liquidity compresses multiples broadly"],
        "typical_duration": "quarters",
        "typical_volatility": "moderate",
        "valuation_impact": "Loose liquidity supports duration/growth",
        "portfolio_impact": "Risk-on when expanding; quality when tightening",
        "risk_impact": "Funding and rollover risk",
    },
    "credit_growth": {
        "display_name": "Credit Growth",
        "description": "Banking system credit expansion",
        "business_impact": "Funds consumption, housing, and corporate capex",
        "primary_transmission": "credit_availability",
        "secondary_transmission": "asset_quality_lag",
        "economic_drivers": ["rates", "capital", "demand", "regulation"],
        "leading_indicators": ["loan_growth", "deposit_growth"],
        "lagging_indicators": ["npa_formation"],
        "historical_behaviour": ["Credit booms precede asset-quality cycles"],
        "typical_duration": "years",
        "typical_volatility": "moderate",
        "valuation_impact": "Supports banks/NBFCs and cyclicals",
        "portfolio_impact": "Financials overweight in expansion",
        "risk_impact": "Late-cycle credit quality",
    },
    "yield_curve": {
        "display_name": "Yield Curve",
        "description": "Term structure of rates",
        "business_impact": "Signals growth/inflation outlook; bank NIMs",
        "primary_transmission": "expectations_and_bank_spreads",
        "secondary_transmission": "duration_pricing",
        "economic_drivers": ["policy_path", "growth", "term_premium"],
        "leading_indicators": ["2s10s", "policy_guidance"],
        "lagging_indicators": ["recession_prints"],
        "historical_behaviour": ["Inversion historically precedes growth stress"],
        "typical_duration": "months_to_years",
        "typical_volatility": "moderate",
        "valuation_impact": "Inversion → defensive tilt; steepener → financials",
        "portfolio_impact": "Bank sensitivity to steepness",
        "risk_impact": "Recession probability signal",
    },
    "pmi": {
        "display_name": "PMI",
        "description": "Purchasing managers' activity pulse",
        "business_impact": "Near-term manufacturing/services momentum",
        "primary_transmission": "activity_surprise",
        "secondary_transmission": "earnings_revisions",
        "economic_drivers": ["orders", " inventories", "employment"],
        "leading_indicators": ["new_orders"],
        "lagging_indicators": ["employment_subindex"],
        "historical_behaviour": ["PMI troughs often lead equity cyclicals"],
        "typical_duration": "months",
        "typical_volatility": "moderate",
        "valuation_impact": "Rising PMI supports industrials/metals",
        "portfolio_impact": "Cyclical tilt on sustained >50",
        "risk_impact": "Sudden sub-50 prints cut growth beta",
    },
    "dxy": {
        "display_name": "DXY",
        "description": "US dollar index",
        "business_impact": "Global financial conditions and EM FX",
        "primary_transmission": "global_liquidity_and_fx",
        "secondary_transmission": "commodity_dollar_prices",
        "economic_drivers": ["us_rates", "risk_sentiment", "growth_differentials"],
        "leading_indicators": ["us_real_rates"],
        "lagging_indicators": ["em_flows"],
        "historical_behaviour": ["Strong USD pressures EM and commodities"],
        "typical_duration": "months_to_years",
        "typical_volatility": "moderate",
        "valuation_impact": ["IT INR translation positive when USD up"],
        "portfolio_impact": "Export tilt / commodity caution",
        "risk_impact": "EM funding stress",
    },
}

_TEMPLATE = {
    "description": "Institutional macro variable",
    "business_impact": "Affects demand, costs, or financial conditions",
    "primary_transmission": "prices_and_expectations",
    "secondary_transmission": "policy_and_flows",
    "economic_drivers": ["growth", "policy", "global_conditions"],
    "leading_indicators": ["surveys", "prices"],
    "lagging_indicators": ["official_prints"],
    "historical_behaviour": ["Mean-reverting with regime shifts"],
    "typical_duration": "variable",
    "typical_volatility": "moderate",
    "valuation_impact": "Context-dependent via sector transmission",
    "portfolio_impact": "Adjust beta and quality tilts",
    "risk_impact": "Regime-dependent",
}


def macro_dna(macro_id: str) -> dict[str, Any]:
    key = macro_id.strip().lower()
    base = {**_TEMPLATE, **(_RICH.get(key, {}))}
    base.setdefault("display_name", key.replace("_", " ").title())
    base["macro_id"] = key
    required = (
        "description",
        "business_impact",
        "primary_transmission",
        "historical_behaviour",
        "valuation_impact",
        "portfolio_impact",
        "risk_impact",
    )
    ok = sum(1 for r in required if base.get(r))
    base["dna_completeness"] = round(100.0 * ok / len(required), 2)
    return base


def all_macro_dna() -> dict[str, dict[str, Any]]:
    return {m: macro_dna(m) for m in MACRO_UNIVERSE}
