"""Canonical institutional entity seed — ERE registry soft fallback when IKG sparse."""

from __future__ import annotations

from typing import Any

# Each record is a canonical institutional entity.
SEED_ENTITIES: list[dict[str, Any]] = [
    # Companies
    {
        "id": "COMP_HDFCBANK",
        "canonical_name": "HDFC Bank Limited",
        "entity_type": "Company",
        "ticker": "HDFCBANK",
        "exchange": "NSE",
        "country": "India",
        "sector": "Banking",
        "industry": "Private Bank",
        "aliases": [
            "hdfc bank",
            "hdfc bank ltd",
            "hdfc bank limited",
            "hdfcbank",
            "nse:hdfcbank",
        ],
        "status": "active",
        "parent": "SECTOR_BANKING",
        "children": [],
        "knowledge_graph_id": "HDFCBANK",
        "peers": ["COMP_ICICIBANK", "COMP_KOTAKBANK", "COMP_AXISBANK", "COMP_SBIN", "COMP_IDBI"],
        "indexes": ["IDX_NIFTY50", "IDX_NIFTYBANK"],
    },
    {
        "id": "COMP_IDBI",
        "canonical_name": "IDBI Bank Limited",
        "entity_type": "Company",
        "ticker": "IDBI",
        "exchange": "NSE",
        "country": "India",
        "sector": "Banking",
        "industry": "Bank",
        "aliases": [
            "idbi",
            "idbi bank",
            "idbi bank ltd",
            "idbi bank limited",
            "idbibank",
            "nse:idbi",
        ],
        "status": "active",
        "parent": "SECTOR_BANKING",
        "children": [],
        "knowledge_graph_id": "IDBI",
        "peers": ["COMP_SBIN", "COMP_HDFCBANK", "COMP_ICICIBANK", "COMP_AXISBANK"],
        "indexes": ["IDX_NIFTY500"],
    },
    {
        "id": "COMP_HDFCLIFE",
        "canonical_name": "HDFC Life Insurance",
        "entity_type": "Company",
        "ticker": "HDFCLIFE",
        "exchange": "NSE",
        "country": "India",
        "sector": "Financials",
        "industry": "Life Insurance",
        "aliases": ["hdfc life", "hdfclife", "hdfc life insurance"],
        "status": "active",
        "parent": "SECTOR_FINANCIALS",
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "COMP_HDFCAMC",
        "canonical_name": "HDFC Asset Management Company",
        "entity_type": "Company",
        "ticker": "HDFCAMC",
        "exchange": "NSE",
        "country": "India",
        "sector": "Financials",
        "industry": "Asset Management",
        "aliases": ["hdfc amc", "hdfcamc", "hdfc asset management"],
        "status": "active",
        "parent": "SECTOR_FINANCIALS",
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "COMP_HDFC_HIST",
        "canonical_name": "HDFC Limited (Historical)",
        "entity_type": "Company",
        "ticker": "HDFC",
        "exchange": "NSE",
        "country": "India",
        "sector": "Financials",
        "industry": "Housing Finance",
        "aliases": ["hdfc ltd", "hdfc limited", "old hdfc", "housing development finance"],
        "status": "historical",
        "parent": "SECTOR_FINANCIALS",
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "COMP_ICICIBANK",
        "canonical_name": "ICICI Bank Limited",
        "entity_type": "Company",
        "ticker": "ICICIBANK",
        "exchange": "NSE",
        "country": "India",
        "sector": "Banking",
        "industry": "Private Bank",
        "aliases": ["icici bank", "icici", "icicibank", "icici bank ltd", "icici bank limited"],
        "status": "active",
        "parent": "SECTOR_BANKING",
        "children": [],
        "knowledge_graph_id": "ICICIBANK",
        "peers": ["COMP_HDFCBANK", "COMP_AXISBANK", "COMP_KOTAKBANK"],
        "indexes": ["IDX_NIFTY50", "IDX_NIFTYBANK"],
    },
    {
        "id": "COMP_ICICIGI",
        "canonical_name": "ICICI Lombard General Insurance",
        "entity_type": "Company",
        "ticker": "ICICIGI",
        "exchange": "NSE",
        "country": "India",
        "sector": "Financials",
        "industry": "General Insurance",
        "aliases": ["icici lombard", "icicigi", "icici lombard general insurance"],
        "status": "active",
        "parent": "SECTOR_FINANCIALS",
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "COMP_INFY",
        "canonical_name": "Infosys Limited",
        "entity_type": "Company",
        "ticker": "INFY",
        "exchange": "NSE",
        "country": "India",
        "sector": "Information Technology",
        "industry": "IT Services",
        "aliases": ["infosys", "infy", "infosys ltd", "infosys limited", "nse:infy"],
        "status": "active",
        "parent": "SECTOR_IT",
        "children": [],
        "knowledge_graph_id": "INFY",
        "peers": ["COMP_TCS", "COMP_WIPRO", "COMP_HCLTECH"],
        "indexes": ["IDX_NIFTY50", "IDX_NIFTYIT"],
    },
    {
        "id": "COMP_TCS",
        "canonical_name": "Tata Consultancy Services Limited",
        "entity_type": "Company",
        "ticker": "TCS",
        "exchange": "NSE",
        "country": "India",
        "sector": "Information Technology",
        "industry": "IT Services",
        "aliases": ["tcs", "tata consultancy", "tata consultancy services", "tata consultancy services ltd"],
        "status": "active",
        "parent": "SECTOR_IT",
        "children": [],
        "knowledge_graph_id": "TCS",
        "peers": ["COMP_INFY", "COMP_WIPRO", "COMP_HCLTECH"],
        "indexes": ["IDX_NIFTY50", "IDX_NIFTYIT"],
    },
    {
        "id": "COMP_RELIANCE",
        "canonical_name": "Reliance Industries Limited",
        "entity_type": "Company",
        "ticker": "RELIANCE",
        "exchange": "NSE",
        "country": "India",
        "sector": "Energy",
        "industry": "Oil & Gas Conglomerate",
        "aliases": ["reliance", "ril", "reliance industries", "reliance industries ltd", "reliance industries limited"],
        "status": "active",
        "parent": "SECTOR_ENERGY",
        "children": [],
        "knowledge_graph_id": "RELIANCE",
        "peers": [],
        "indexes": ["IDX_NIFTY50"],
    },
    {
        "id": "COMP_SBIN",
        "canonical_name": "State Bank of India",
        "entity_type": "Company",
        "ticker": "SBIN",
        "exchange": "NSE",
        "country": "India",
        "sector": "Banking",
        "industry": "Public Bank",
        "aliases": ["sbi", "sbin", "state bank", "state bank of india"],
        "status": "active",
        "parent": "SECTOR_BANKING",
        "children": [],
        "knowledge_graph_id": "SBIN",
        "peers": ["COMP_HDFCBANK", "COMP_ICICIBANK"],
        "indexes": ["IDX_NIFTY50", "IDX_NIFTYBANK"],
    },
    {
        "id": "COMP_AXISBANK",
        "canonical_name": "Axis Bank Limited",
        "entity_type": "Company",
        "ticker": "AXISBANK",
        "exchange": "NSE",
        "country": "India",
        "sector": "Banking",
        "industry": "Private Bank",
        "aliases": ["axis bank", "axis", "axisbank"],
        "status": "active",
        "parent": "SECTOR_BANKING",
        "children": [],
        "knowledge_graph_id": "AXISBANK",
        "peers": ["COMP_HDFCBANK", "COMP_ICICIBANK"],
        "indexes": ["IDX_NIFTY50", "IDX_NIFTYBANK"],
    },
    {
        "id": "COMP_KOTAKBANK",
        "canonical_name": "Kotak Mahindra Bank Limited",
        "entity_type": "Company",
        "ticker": "KOTAKBANK",
        "exchange": "NSE",
        "country": "India",
        "sector": "Banking",
        "industry": "Private Bank",
        "aliases": ["kotak", "kotak bank", "kotak mahindra", "kotak mahindra bank", "kotakbank"],
        "status": "active",
        "parent": "SECTOR_BANKING",
        "children": [],
        "knowledge_graph_id": "KOTAKBANK",
        "peers": ["COMP_HDFCBANK", "COMP_ICICIBANK"],
        "indexes": ["IDX_NIFTY50", "IDX_NIFTYBANK"],
    },
    {
        "id": "COMP_WIPRO",
        "canonical_name": "Wipro Limited",
        "entity_type": "Company",
        "ticker": "WIPRO",
        "exchange": "NSE",
        "country": "India",
        "sector": "Information Technology",
        "industry": "IT Services",
        "aliases": ["wipro", "wipro ltd", "wipro limited"],
        "status": "active",
        "parent": "SECTOR_IT",
        "children": [],
        "knowledge_graph_id": "WIPRO",
        "peers": ["COMP_TCS", "COMP_INFY"],
        "indexes": ["IDX_NIFTYIT"],
    },
    {
        "id": "COMP_HCLTECH",
        "canonical_name": "HCL Technologies Limited",
        "entity_type": "Company",
        "ticker": "HCLTECH",
        "exchange": "NSE",
        "country": "India",
        "sector": "Information Technology",
        "industry": "IT Services",
        "aliases": ["hcl", "hcltech", "hcl technologies", "hcl tech"],
        "status": "active",
        "parent": "SECTOR_IT",
        "children": [],
        "knowledge_graph_id": "HCLTECH",
        "peers": ["COMP_TCS", "COMP_INFY"],
        "indexes": ["IDX_NIFTYIT"],
    },
    {
        "id": "COMP_TATAMOTORS",
        "canonical_name": "Tata Motors Limited",
        "entity_type": "Company",
        "ticker": "TATAMOTORS",
        "exchange": "NSE",
        "country": "India",
        "sector": "Automobile",
        "industry": "Auto OEM",
        "aliases": ["tata motors", "tatamotors"],
        "status": "active",
        "parent": "SECTOR_AUTO",
        "children": [],
        "knowledge_graph_id": "TATAMOTORS",
        "peers": [],
        "indexes": ["IDX_NIFTY50"],
    },
    {
        "id": "COMP_TATASTEEL",
        "canonical_name": "Tata Steel Limited",
        "entity_type": "Company",
        "ticker": "TATASTEEL",
        "exchange": "NSE",
        "country": "India",
        "sector": "Metals",
        "industry": "Steel",
        "aliases": ["tata steel", "tatasteel"],
        "status": "active",
        "parent": "SECTOR_METALS",
        "children": [],
        "knowledge_graph_id": "TATASTEEL",
        "peers": [],
        "indexes": ["IDX_NIFTY50"],
    },
    {
        "id": "COMP_TATAPOWER",
        "canonical_name": "Tata Power Company Limited",
        "entity_type": "Company",
        "ticker": "TATAPOWER",
        "exchange": "NSE",
        "country": "India",
        "sector": "Power",
        "industry": "Utilities",
        "aliases": ["tata power", "tatapower"],
        "status": "active",
        "parent": "SECTOR_POWER",
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "COMP_TITAN",
        "canonical_name": "Titan Company Limited",
        "entity_type": "Company",
        "ticker": "TITAN",
        "exchange": "NSE",
        "country": "India",
        "sector": "Consumer Discretionary",
        "industry": "Jewellery & Watches",
        "aliases": ["titan", "titan company", "titan ltd"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": "TITAN",
        "peers": [],
        "indexes": ["IDX_NIFTY50"],
    },
    {
        "id": "COMP_AAPL",
        "canonical_name": "Apple Inc.",
        "entity_type": "Company",
        "ticker": "AAPL",
        "exchange": "NASDAQ",
        "country": "United States",
        "sector": "Technology",
        "industry": "Consumer Electronics",
        "aliases": ["apple", "aapl", "apple inc"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": ["COMP_MSFT"],
        "indexes": [],
    },
    {
        "id": "COMP_MSFT",
        "canonical_name": "Microsoft Corporation",
        "entity_type": "Company",
        "ticker": "MSFT",
        "exchange": "NASDAQ",
        "country": "United States",
        "sector": "Technology",
        "industry": "Software",
        "aliases": ["microsoft", "msft", "microsoft corporation"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": ["COMP_AAPL"],
        "indexes": [],
    },
    {
        "id": "COMP_META",
        "canonical_name": "Meta Platforms",
        "entity_type": "Company",
        "ticker": "META",
        "exchange": "NASDAQ",
        "country": "United States",
        "sector": "Technology",
        "industry": "Internet Content",
        "aliases": ["meta", "meta platforms", "facebook", "fb", "meta platforms inc"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": ["COMP_AAPL", "COMP_MSFT"],
        "indexes": [],
    },
    # Sectors
    {
        "id": "SECTOR_BANKING",
        "canonical_name": "Banking",
        "entity_type": "Sector",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": "Banking",
        "industry": None,
        "aliases": ["banking", "banks", "bank sector", "private banks", "financial services banks"],
        "status": "active",
        "parent": None,
        "children": ["COMP_HDFCBANK", "COMP_ICICIBANK"],
        "knowledge_graph_id": "sector_banks",
        "peers": [],
        "indexes": ["IDX_NIFTYBANK"],
    },
    {
        "id": "SECTOR_IT",
        "canonical_name": "Information Technology",
        "entity_type": "Sector",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": "Information Technology",
        "industry": "IT Services",
        "aliases": ["it", "information technology", "it sector", "software", "it services"],
        "status": "active",
        "parent": None,
        "children": ["COMP_TCS", "COMP_INFY"],
        "knowledge_graph_id": "sector_it",
        "peers": [],
        "indexes": ["IDX_NIFTYIT"],
    },
    {
        "id": "SECTOR_FMCG",
        "canonical_name": "FMCG",
        "entity_type": "Sector",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": "FMCG",
        "industry": None,
        "aliases": ["fmcg", "consumer staples", "fast moving consumer goods"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": "sector_fmcg",
        "peers": [],
        "indexes": [],
    },
    {
        "id": "SECTOR_PHARMA",
        "canonical_name": "Pharmaceuticals",
        "entity_type": "Sector",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": "Pharmaceuticals",
        "industry": None,
        "aliases": ["pharma", "pharmaceuticals", "healthcare pharma"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "SECTOR_AUTO",
        "canonical_name": "Automobile",
        "entity_type": "Sector",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": "Automobile",
        "industry": None,
        "aliases": ["auto", "automobile", "automobiles", "auto sector"],
        "status": "active",
        "parent": None,
        "children": ["COMP_TATAMOTORS"],
        "knowledge_graph_id": "sector_auto",
        "peers": [],
        "indexes": [],
    },
    {
        "id": "SECTOR_POWER",
        "canonical_name": "Power",
        "entity_type": "Sector",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": "Power",
        "industry": None,
        "aliases": ["power", "utilities", "power sector", "infrastructure power"],
        "status": "active",
        "parent": None,
        "children": ["COMP_TATAPOWER"],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "SECTOR_REALESTATE",
        "canonical_name": "Real Estate",
        "entity_type": "Sector",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": "Real Estate",
        "industry": None,
        "aliases": ["real estate", "realty", "property"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "SECTOR_ENERGY",
        "canonical_name": "Energy",
        "entity_type": "Sector",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": "Energy",
        "industry": None,
        "aliases": ["energy", "oil and gas", "oil & gas"],
        "status": "active",
        "parent": None,
        "children": ["COMP_RELIANCE"],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "SECTOR_METALS",
        "canonical_name": "Metals",
        "entity_type": "Sector",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": "Metals",
        "industry": None,
        "aliases": ["metals", "metal", "steel sector"],
        "status": "active",
        "parent": None,
        "children": ["COMP_TATASTEEL"],
        "knowledge_graph_id": "sector_metals",
        "peers": [],
        "indexes": [],
    },
    {
        "id": "SECTOR_FINANCIALS",
        "canonical_name": "Financial Services",
        "entity_type": "Sector",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": "Financials",
        "industry": None,
        "aliases": ["financial services", "financials", "finance sector"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    # Indexes
    {
        "id": "IDX_NIFTY50",
        "canonical_name": "Nifty 50",
        "entity_type": "Broad Index",
        "ticker": "NIFTY",
        "exchange": "NSE",
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["nifty", "nifty 50", "nifty50", "cnx nifty"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": "nifty50",
        "peers": ["IDX_SENSEX"],
        "indexes": [],
    },
    {
        "id": "IDX_SENSEX",
        "canonical_name": "BSE Sensex",
        "entity_type": "Broad Index",
        "ticker": "SENSEX",
        "exchange": "BSE",
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["sensex", "bse sensex"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": ["IDX_NIFTY50"],
        "indexes": [],
    },
    {
        "id": "IDX_NIFTYIT",
        "canonical_name": "Nifty IT",
        "entity_type": "Sector Index",
        "ticker": "NIFTYIT",
        "exchange": "NSE",
        "country": "India",
        "sector": "Information Technology",
        "industry": None,
        "aliases": ["nifty it", "nifty-it", "niftyit", "cnx it"],
        "status": "active",
        "parent": "SECTOR_IT",
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "IDX_NIFTYBANK",
        "canonical_name": "Nifty Bank",
        "entity_type": "Sector Index",
        "ticker": "BANKNIFTY",
        "exchange": "NSE",
        "country": "India",
        "sector": "Banking",
        "industry": None,
        "aliases": ["nifty bank", "bank nifty", "banknifty"],
        "status": "active",
        "parent": "SECTOR_BANKING",
        "children": [],
        "knowledge_graph_id": "banknifty",
        "peers": ["IDX_NIFTYFIN"],
        "indexes": [],
    },
    {
        "id": "IDX_NIFTYNEXT50",
        "canonical_name": "Nifty Next 50",
        "entity_type": "Broad Index",
        "ticker": "NIFTYNXT50",
        "exchange": "NSE",
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["nifty next 50", "nifty next50", "next 50", "niftynxt50"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": "nifty_next_50",
        "peers": ["IDX_NIFTY50", "IDX_NIFTY100"],
        "indexes": [],
    },
    {
        "id": "IDX_NIFTY100",
        "canonical_name": "Nifty 100",
        "entity_type": "Broad Index",
        "ticker": "NIFTY100",
        "exchange": "NSE",
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["nifty 100", "nifty100"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": "nifty_100",
        "peers": ["IDX_NIFTY50", "IDX_NIFTY200"],
        "indexes": [],
    },
    {
        "id": "IDX_NIFTY200",
        "canonical_name": "Nifty 200",
        "entity_type": "Broad Index",
        "ticker": "NIFTY200",
        "exchange": "NSE",
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["nifty 200", "nifty200"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": "nifty_200",
        "peers": ["IDX_NIFTY100", "IDX_NIFTY500"],
        "indexes": [],
    },
    {
        "id": "IDX_NIFTY500",
        "canonical_name": "Nifty 500",
        "entity_type": "Broad Index",
        "ticker": "NIFTY500",
        "exchange": "NSE",
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["nifty 500", "nifty500"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": "nifty_500",
        "peers": ["IDX_NIFTY200"],
        "indexes": [],
    },
    {
        "id": "IDX_NIFTYMIDCAPSELECT",
        "canonical_name": "Nifty Midcap Select",
        "entity_type": "Broad Index",
        "ticker": "MIDCPNIFTY",
        "exchange": "NSE",
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["nifty midcap select", "midcap select", "midcpnifty"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": "nifty_midcap_select",
        "peers": ["IDX_NIFTY500"],
        "indexes": [],
    },
    {
        "id": "IDX_NIFTYFIN",
        "canonical_name": "Nifty Financial Services",
        "entity_type": "Sector Index",
        "ticker": "FINNIFTY",
        "exchange": "NSE",
        "country": "India",
        "sector": "Financials",
        "industry": None,
        "aliases": [
            "nifty financial services",
            "nifty finance",
            "fin nifty",
            "finnifty",
            "financial services index",
        ],
        "status": "active",
        "parent": "SECTOR_FINANCIALS",
        "children": [],
        "knowledge_graph_id": "finnifty",
        "peers": ["IDX_NIFTYBANK"],
        "indexes": [],
    },
    {
        "id": "IDX_NASDAQ",
        "canonical_name": "Nasdaq Composite",
        "entity_type": "Broad Index",
        "ticker": "IXIC",
        "exchange": "NASDAQ",
        "country": "United States",
        "sector": None,
        "industry": None,
        "aliases": ["nasdaq", "nasdaq composite"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    # Macro / commodities / FX
    {
        "id": "MACRO_INFLATION",
        "canonical_name": "Inflation",
        "entity_type": "Macro Variable",
        "ticker": None,
        "exchange": None,
        "country": None,
        "sector": None,
        "industry": None,
        "aliases": ["inflation", "cpi", "wpi"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": ["MACRO_REPO"],
        "indexes": [],
    },
    {
        "id": "MACRO_REPO",
        "canonical_name": "Repo Rate",
        "entity_type": "Macro Variable",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["repo rate", "repo", "policy rate", "rbi rate"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": ["MACRO_INFLATION"],
        "indexes": [],
    },
    {
        "id": "MACRO_GDP",
        "canonical_name": "GDP",
        "entity_type": "Economic Indicator",
        "ticker": None,
        "exchange": None,
        "country": None,
        "sector": None,
        "industry": None,
        "aliases": ["gdp", "gross domestic product"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "MACRO_UNEMPLOYMENT",
        "canonical_name": "Unemployment",
        "entity_type": "Economic Indicator",
        "ticker": None,
        "exchange": None,
        "country": None,
        "sector": None,
        "industry": None,
        "aliases": ["unemployment", "jobless rate"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "CMD_OIL",
        "canonical_name": "Crude Oil",
        "entity_type": "Commodity",
        "ticker": "CL",
        "exchange": None,
        "country": None,
        "sector": "Energy",
        "industry": None,
        "aliases": ["oil", "crude", "crude oil"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": ["CMD_BRENT"],
        "indexes": [],
    },
    {
        "id": "CMD_BRENT",
        "canonical_name": "Brent Crude",
        "entity_type": "Commodity",
        "ticker": "BRN",
        "exchange": None,
        "country": None,
        "sector": "Energy",
        "industry": None,
        "aliases": ["brent", "brent crude"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": ["CMD_OIL"],
        "indexes": [],
    },
    {
        "id": "CMD_GOLD",
        "canonical_name": "Gold",
        "entity_type": "Commodity",
        "ticker": "XAU",
        "exchange": None,
        "country": None,
        "sector": None,
        "industry": None,
        "aliases": ["gold", "xau"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": ["CMD_SILVER"],
        "indexes": [],
    },
    {
        "id": "CMD_SILVER",
        "canonical_name": "Silver",
        "entity_type": "Commodity",
        "ticker": "XAG",
        "exchange": None,
        "country": None,
        "sector": None,
        "industry": None,
        "aliases": ["silver", "xag"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": ["CMD_GOLD"],
        "indexes": [],
    },
    {
        "id": "CMD_COPPER",
        "canonical_name": "Copper",
        "entity_type": "Commodity",
        "ticker": "HG",
        "exchange": None,
        "country": None,
        "sector": "Metals",
        "industry": None,
        "aliases": ["copper"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "CMD_NATGAS",
        "canonical_name": "Natural Gas",
        "entity_type": "Commodity",
        "ticker": "NG",
        "exchange": None,
        "country": None,
        "sector": "Energy",
        "industry": None,
        "aliases": ["natural gas", "natgas", "gas"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "FX_USDINR",
        "canonical_name": "USD/INR",
        "entity_type": "Currency",
        "ticker": "USDINR",
        "exchange": None,
        "country": None,
        "sector": None,
        "industry": None,
        "aliases": ["usdinr", "usd/inr", "dollar rupee", "rupee", "inr"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": ["FX_USD"],
        "indexes": [],
    },
    {
        "id": "FX_USD",
        "canonical_name": "US Dollar",
        "entity_type": "Currency",
        "ticker": "DXY",
        "exchange": None,
        "country": "United States",
        "sector": None,
        "industry": None,
        "aliases": ["dollar", "usd", "us dollar", "dxy"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": ["FX_USDINR"],
        "indexes": [],
    },
    # Portfolio / watchlist
    {
        "id": "PF_MY_PORTFOLIO",
        "canonical_name": "My Portfolio",
        "entity_type": "Portfolio",
        "ticker": None,
        "exchange": None,
        "country": None,
        "sector": None,
        "industry": None,
        "aliases": ["my portfolio", "portfolio", "my holdings"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "PF_MY_WATCHLIST",
        "canonical_name": "My Watchlist",
        "entity_type": "Watchlist",
        "ticker": None,
        "exchange": None,
        "country": None,
        "sector": None,
        "industry": None,
        "aliases": ["my watchlist", "watchlist"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "PF_MY_CORE",
        "canonical_name": "My Core Portfolio",
        "entity_type": "Portfolio",
        "ticker": None,
        "exchange": None,
        "country": None,
        "sector": None,
        "industry": None,
        "aliases": ["my core", "core portfolio", "agib core india"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    # Themes
    {
        "id": "THEME_AI",
        "canonical_name": "Artificial Intelligence",
        "entity_type": "Theme",
        "ticker": None,
        "exchange": None,
        "country": None,
        "sector": None,
        "industry": None,
        "aliases": ["ai", "artificial intelligence"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "THEME_EV",
        "canonical_name": "Electric Vehicles",
        "entity_type": "Theme",
        "ticker": None,
        "exchange": None,
        "country": None,
        "sector": "Automobile",
        "industry": None,
        "aliases": ["ev", "electric vehicles", "electric vehicle"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "THEME_DEFENCE",
        "canonical_name": "Defence",
        "entity_type": "Theme",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["defence", "defense"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "THEME_SEMI",
        "canonical_name": "Semiconductors",
        "entity_type": "Theme",
        "ticker": None,
        "exchange": None,
        "country": None,
        "sector": None,
        "industry": None,
        "aliases": ["semiconductor", "semiconductors", "chips"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "THEME_GREEN",
        "canonical_name": "Green Energy",
        "entity_type": "Theme",
        "ticker": None,
        "exchange": None,
        "country": None,
        "sector": "Power",
        "industry": None,
        "aliases": ["green energy", "renewables", "clean energy"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "THEME_PAYMENTS",
        "canonical_name": "Digital Payments",
        "entity_type": "Theme",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["digital payments", "upi", "payments"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    # People / institutions / events
    {
        "id": "PERSON_BUFFETT",
        "canonical_name": "Warren Buffett",
        "entity_type": "Person",
        "ticker": None,
        "exchange": None,
        "country": "United States",
        "sector": None,
        "industry": None,
        "aliases": ["warren buffett", "buffett"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "PERSON_RJ",
        "canonical_name": "Rakesh Jhunjhunwala",
        "entity_type": "Person",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["rakesh jhunjhunwala", "jhunjhunwala"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "PERSON_POWELL",
        "canonical_name": "Jerome Powell",
        "entity_type": "Person",
        "ticker": None,
        "exchange": None,
        "country": "United States",
        "sector": None,
        "industry": None,
        "aliases": ["jerome powell", "powell", "fed chair"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "PERSON_FM",
        "canonical_name": "Nirmala Sitharaman",
        "entity_type": "Person",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["nirmala sitharaman", "finance minister", "fm india"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "INST_FED",
        "canonical_name": "US Federal Reserve",
        "entity_type": "Institution",
        "ticker": None,
        "exchange": None,
        "country": "United States",
        "sector": None,
        "industry": None,
        "aliases": ["fed", "federal reserve", "the fed"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": ["INST_RBI"],
        "indexes": [],
    },
    {
        "id": "INST_RBI",
        "canonical_name": "Reserve Bank of India",
        "entity_type": "Institution",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["rbi", "reserve bank of india", "reserve bank"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": ["INST_FED"],
        "indexes": [],
    },
    {
        "id": "EVT_BUDGET",
        "canonical_name": "Union Budget",
        "entity_type": "Event",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["union budget", "budget", "india budget"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "EVT_FED",
        "canonical_name": "Fed Meeting",
        "entity_type": "Event",
        "ticker": None,
        "exchange": None,
        "country": "United States",
        "sector": None,
        "industry": None,
        "aliases": ["fed meeting", "fomc", "fomc meeting"],
        "status": "active",
        "parent": "INST_FED",
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "EVT_RBI_MPC",
        "canonical_name": "RBI MPC",
        "entity_type": "Event",
        "ticker": None,
        "exchange": None,
        "country": "India",
        "sector": None,
        "industry": None,
        "aliases": ["rbi mpc", "mpc", "monetary policy committee"],
        "status": "active",
        "parent": "INST_RBI",
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    # Metrics
    {
        "id": "METRIC_ROIC",
        "canonical_name": "ROIC",
        "entity_type": "Financial Metric",
        "ticker": None,
        "exchange": None,
        "country": None,
        "sector": None,
        "industry": None,
        "aliases": ["roic", "return on invested capital"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
    {
        "id": "METRIC_EVEBITDA",
        "canonical_name": "EV/EBITDA",
        "entity_type": "Financial Metric",
        "ticker": None,
        "exchange": None,
        "country": None,
        "sector": None,
        "industry": None,
        "aliases": ["ev/ebitda", "evebitda", "ev ebitda"],
        "status": "active",
        "parent": None,
        "children": [],
        "knowledge_graph_id": None,
        "peers": [],
        "indexes": [],
    },
]

# Bare stems that must NEVER auto-resolve without disambiguation
AMBIGUOUS_STEMS: dict[str, list[str]] = {
    "hdfc": ["COMP_HDFCBANK", "COMP_HDFCLIFE", "COMP_HDFCAMC", "COMP_HDFC_HIST"],
    "tata": ["COMP_TCS", "COMP_TATAMOTORS", "COMP_TATASTEEL", "COMP_TATAPOWER", "COMP_TITAN"],
    "icici": ["COMP_ICICIBANK", "COMP_ICICIGI"],
}
