"""Evidence-backed sector relationship catalog — Sprint 11.3.

Includes macro→sector, sector→sector, sector↔company, sector→market, global→sector.
Every entry requires supporting historical evidence.
"""

from __future__ import annotations

from typing import Any


def _ev(
    kind: str,
    summary: str,
    *,
    period: str | None = None,
    refs: list[str] | None = None,
    weight: float = 1.0,
) -> dict[str, Any]:
    return {
        "kind": kind,
        "summary": summary,
        "period": period,
        "source_refs": refs or [],
        "weight": weight,
    }


SECTOR_RELATIONSHIP_CATALOG: list[dict[str, Any]] = [
    # --- Macro → Sector ---
    {
        "source": "Repo Rate",
        "target": "Banking",
        "relationship": "Credit Expansion on Easing",
        "kind": "macro_to_sector",
        "direction": "Negative",
        "direction_note": "Repo ↓ historically associated with private bank credit acceleration",
        "evidence_strength": "High",
        "confidence_pct": 96,
        "historical_observations": 14,
        "average_lag": "2 Quarters",
        "first_observed": "2003",
        "last_confirmed": "2025",
        "chain": ["Banking", "NBFC", "Real Estate", "Auto", "Capital Goods"],
        "supporting_layers": ["Historical Macro", "Historical Sector", "MRI tip"],
        "evidence": [
            _ev(
                "historical_macro",
                "RBI easing cycles precede private bank credit acceleration",
                period="2003-2020",
                refs=["hmip:Repo Rate:2020", "hsip:banking:Revenue Growth"],
                weight=1.6,
            ),
            _ev(
                "historical_sector",
                "Banking sector timelines show NIM/volume trade-off with easing windows",
                period="2015-2025",
                refs=["hsip:banking:timeline", "cskp:banking"],
                weight=1.4,
            ),
        ],
    },
    {
        "source": "Repo Rate",
        "target": "Real Estate",
        "relationship": "Housing Affordability / Demand",
        "kind": "macro_to_sector",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 90,
        "historical_observations": 11,
        "average_lag": "2-3 Quarters",
        "first_observed": "2004",
        "last_confirmed": "2025",
        "chain": ["Banking", "Real Estate", "Cement"],
        "supporting_layers": ["Historical Macro", "Historical Sector"],
        "evidence": [
            _ev(
                "historical_sector",
                "Listed developers' pre-sales recover after easing cycles (2015–17, 2020)",
                period="2015-2025",
                refs=["hsip:real_estate:timeline", "hsip:real_estate:Key Event"],
                weight=1.5,
            ),
            _ev(
                "historical_macro",
                "Repo path anchors housing-finance affordability windows",
                period="2004-2025",
                refs=["hmip:Repo Rate:timeline"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Repo Rate",
        "target": "Auto",
        "relationship": "Vehicle Financing Impulse",
        "kind": "macro_to_sector",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 88,
        "historical_observations": 10,
        "average_lag": "1-2 Quarters",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["Banking", "NBFC", "Auto"],
        "supporting_layers": ["Historical Sector", "Historical Macro"],
        "evidence": [
            _ev(
                "historical_sector",
                "Auto demand recovers with credit availability after easing / BS-VI normalisation",
                period="2019-2025",
                refs=["hsip:auto:timeline", "hsip:auto:Key Event:BS-VI"],
                weight=1.4,
            ),
            _ev(
                "historical_macro",
                "Rate-sensitive PV / CV financing tracks repo cycle",
                period="2008-2025",
                refs=["hmip:Repo Rate:timeline", "hmip:Credit Growth"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "CPI",
        "target": "FMCG",
        "relationship": "Margin / Volume Pressure",
        "kind": "macro_to_sector",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 91,
        "historical_observations": 12,
        "average_lag": "1 Quarter",
        "first_observed": "2013",
        "last_confirmed": "2025",
        "chain": ["CPI", "FMCG", "Margins"],
        "supporting_layers": ["Historical Macro", "Historical Sector"],
        "evidence": [
            _ev(
                "historical_sector",
                "High CPI episodes (2013, 2022) coincide with FMCG margin stress then recovery",
                period="2013-2025",
                refs=["hsip:fmcg:EBITDA Margin", "hsip:fmcg:timeline"],
                weight=1.5,
            ),
            _ev(
                "historical_macro",
                "CPI spikes historically compress real rural demand and input costs",
                period="2013-2022",
                refs=["hmip:CPI:timeline"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "USDINR",
        "target": "IT Services",
        "relationship": "Exporter Revenue Support",
        "kind": "macro_to_sector",
        "direction": "Positive",
        "direction_note": "Weaker INR (higher USDINR) supports reported INR revenues",
        "evidence_strength": "High",
        "confidence_pct": 93,
        "historical_observations": 15,
        "average_lag": "Immediate / 1 Quarter",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["USDINR", "IT Services", "Pharma"],
        "supporting_layers": ["Historical Sector", "Historical Macro", "MRI tip"],
        "evidence": [
            _ev(
                "historical_sector",
                "IT Services revenue/margin regimes align with USDINR moves across GFC, COVID, AI cycle",
                period="2008-2025",
                refs=["hsip:it_services:timeline", "hsip:it_services:Revenue Growth"],
                weight=1.5,
            ),
            _ev(
                "historical_company",
                "INFY / TCS reported growth historically sensitive to USDINR translation",
                period="2010-2025",
                refs=["company:INFY", "company:TCS"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Fiscal Deficit",
        "target": "Capital Goods",
        "relationship": "Public Capex Transmission",
        "kind": "macro_to_sector",
        "direction": "Positive",
        "direction_note": "Higher government capex (even with elevated deficit) historically lifts order books",
        "evidence_strength": "High",
        "confidence_pct": 89,
        "historical_observations": 9,
        "average_lag": "2-4 Quarters",
        "first_observed": "2014",
        "last_confirmed": "2025",
        "chain": ["Fiscal Capex", "Capital Goods", "Infrastructure", "Cement"],
        "supporting_layers": ["Historical Macro", "Historical Sector"],
        "evidence": [
            _ev(
                "historical_sector",
                "Capital Goods order-book expansions track public infra spending cycles (2014+, 2022+)",
                period="2014-2025",
                refs=["hsip:capital_goods:timeline", "hsip:infrastructure:Key Event"],
                weight=1.5,
            ),
            _ev(
                "historical_macro",
                "Fiscal / budget tips coincide with engineering & construction activity",
                period="2014-2025",
                refs=["hmip:Fiscal Deficit:timeline"],
                weight=1.2,
            ),
        ],
    },
    # --- Sector → Sector ---
    {
        "source": "Banking",
        "target": "Real Estate",
        "relationship": "Credit Expansion",
        "kind": "sector_to_sector",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 95,
        "historical_observations": 18,
        "average_lag": "2 Quarters",
        "first_observed": "2004",
        "last_confirmed": "2026",
        "chain": ["Banking", "Housing Finance", "Real Estate", "Cement"],
        "supporting_layers": ["Historical Sector", "Historical Macro", "Research"],
        "evidence": [
            _ev(
                "historical_sector",
                "Banking credit growth episodes precede housing pre-sales and developer launches",
                period="2004-2025",
                refs=["hsip:banking:Revenue Growth", "hsip:real_estate:timeline"],
                weight=1.6,
            ),
            _ev(
                "research",
                "Institutional sector notes link mortgage / LAP growth to realty absorption",
                period="2016-2025",
                refs=["research:sector:real_estate", "cskp:banking"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "Banking",
        "target": "NBFC",
        "relationship": "Funding / Liquidity Spillovers",
        "kind": "sector_to_sector",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 90,
        "historical_observations": 12,
        "average_lag": "1 Quarter",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["Banking", "NBFC", "Auto", "Real Estate"],
        "supporting_layers": ["Historical Sector", "Research"],
        "evidence": [
            _ev(
                "historical_sector",
                "NBFC funding costs and growth track bank liquidity / wholesale conditions (2018 stress, 2020 recovery)",
                period="2018-2025",
                refs=["hsip:nbfc:timeline", "hsip:banking:Key Event"],
                weight=1.5,
            ),
            _ev(
                "historical_macro",
                "Banking liquidity tips transmit into NBFC incremental funding",
                period="2019-2025",
                refs=["hmip:Banking Liquidity"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "Real Estate",
        "target": "Cement",
        "relationship": "Construction Demand Pull",
        "kind": "sector_to_sector",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 92,
        "historical_observations": 14,
        "average_lag": "1-2 Quarters",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["Real Estate", "Cement", "Capital Goods"],
        "supporting_layers": ["Historical Sector"],
        "evidence": [
            _ev(
                "historical_sector",
                "Housing recovery cycles lift cement utilisation and pricing power",
                period="2008-2025",
                refs=["hsip:real_estate:timeline", "hsip:cement:Revenue Growth"],
                weight=1.5,
            ),
            _ev(
                "historical_sector",
                "Infra + housing mix explains cement demand elasticity vs GDP",
                period="2014-2025",
                refs=["hsip:cement:timeline", "hsip:infrastructure:Key Event"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Cement",
        "target": "Capital Goods",
        "relationship": "Capacity / Capex Cycle Link",
        "kind": "sector_to_sector",
        "direction": "Positive",
        "evidence_strength": "Medium",
        "confidence_pct": 82,
        "historical_observations": 8,
        "average_lag": "2-4 Quarters",
        "first_observed": "2010",
        "last_confirmed": "2025",
        "chain": ["Cement", "Capital Goods", "Infrastructure"],
        "supporting_layers": ["Historical Sector", "Research"],
        "evidence": [
            _ev(
                "historical_sector",
                "Cement capacity additions coincide with engineering order books in expansion phases",
                period="2010-2025",
                refs=["hsip:cement:timeline", "hsip:capital_goods:Revenue Growth"],
                weight=1.3,
            ),
            _ev(
                "research",
                "Sector notes link materials demand to industrial capex",
                period="2018-2025",
                refs=["research:sector:capital_goods"],
                weight=1.0,
            ),
        ],
    },
    {
        "source": "Oil & Gas",
        "target": "Chemicals",
        "relationship": "Feedstock Cost Transmission",
        "kind": "sector_to_sector",
        "direction": "Mixed",
        "evidence_strength": "High",
        "confidence_pct": 88,
        "historical_observations": 13,
        "average_lag": "1 Quarter",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["Oil & Gas", "Chemicals", "Specialty Chemicals", "Auto Ancillary"],
        "supporting_layers": ["Historical Sector", "Historical Macro"],
        "evidence": [
            _ev(
                "historical_sector",
                "Crude / naphtha regimes alter chemical input costs and spreads",
                period="2008-2025",
                refs=["hsip:oil_gas:timeline", "hsip:chemicals:EBITDA Margin"],
                weight=1.5,
            ),
            _ev(
                "historical_macro",
                "Global energy shocks (2022) transmit into WPI and chemical margins",
                period="2020-2023",
                refs=["hmip:WPI:2022"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "Oil & Gas",
        "target": "Aviation",
        "relationship": "ATF Cost Pressure",
        "kind": "sector_to_sector",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 94,
        "historical_observations": 16,
        "average_lag": "Immediate",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["Oil & Gas", "Aviation", "Logistics"],
        "supporting_layers": ["Historical Sector"],
        "evidence": [
            _ev(
                "historical_sector",
                "Airline margins compress when crude / ATF spikes; recover on fuel normalisation",
                period="2008-2025",
                refs=["hsip:aviation:timeline", "hsip:oil_gas:Key Event"],
                weight=1.6,
            ),
            _ev(
                "historical_sector",
                "IndiGo / sector notes repeatedly cite fuel as primary cost swing factor",
                period="2016-2025",
                refs=["hsip:aviation:EBITDA Margin", "cskp:aviation"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Metals",
        "target": "Capital Goods",
        "relationship": "Input Cost / Demand Mix",
        "kind": "sector_to_sector",
        "direction": "Mixed",
        "evidence_strength": "Medium",
        "confidence_pct": 80,
        "historical_observations": 9,
        "average_lag": "1-2 Quarters",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["Metals", "Capital Goods", "Infrastructure"],
        "supporting_layers": ["Historical Sector"],
        "evidence": [
            _ev(
                "historical_sector",
                "Steel boom supports infra/capex demand but raises input costs for engineering",
                period="2008-2025",
                refs=["hsip:metals:timeline", "hsip:capital_goods:timeline"],
                weight=1.3,
            ),
            _ev(
                "historical_sector",
                "2021 commodity boom lifted metals while pressuring some industrial margins",
                period="2021-2022",
                refs=["hsip:metals:Key Event", "hsip:capital_goods:EBITDA Margin"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "IT Services",
        "target": "Software Products",
        "relationship": "Demand / Talent Spillover",
        "kind": "sector_to_sector",
        "direction": "Positive",
        "evidence_strength": "Medium",
        "confidence_pct": 78,
        "historical_observations": 7,
        "average_lag": "2 Quarters",
        "first_observed": "2014",
        "last_confirmed": "2025",
        "chain": ["IT Services", "Software Products", "Digital"],
        "supporting_layers": ["Historical Sector", "Research"],
        "evidence": [
            _ev(
                "historical_sector",
                "Digital / AI spending waves lift both Tier-1 IT and product engineering peers",
                period="2014-2025",
                refs=["hsip:it_services:timeline", "hsip:software_products:Revenue Growth"],
                weight=1.3,
            ),
            _ev(
                "research",
                "Sector research links enterprise IT budgets across services and products",
                period="2020-2025",
                refs=["research:sector:it_services"],
                weight=1.0,
            ),
        ],
    },
    {
        "source": "Infrastructure",
        "target": "Capital Goods",
        "relationship": "Order Book Transmission",
        "kind": "sector_to_sector",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 93,
        "historical_observations": 11,
        "average_lag": "2 Quarters",
        "first_observed": "2014",
        "last_confirmed": "2025",
        "chain": ["Infrastructure", "Capital Goods", "Cement", "Metals"],
        "supporting_layers": ["Historical Sector", "Government Policy"],
        "evidence": [
            _ev(
                "historical_sector",
                "NIP / Gati Shakti era lifts engineering & construction order inflows",
                period="2014-2025",
                refs=["hsip:infrastructure:timeline", "hsip:capital_goods:Revenue Growth"],
                weight=1.5,
            ),
            _ev(
                "historical_sector",
                "Policy event anchors coincide with capital goods revenue acceleration",
                period="2022-2025",
                refs=["hsip:capital_goods:Key Event", "cskp:infrastructure"],
                weight=1.3,
            ),
        ],
    },
    # --- Sector → Company ---
    {
        "source": "IT Services",
        "target": "INFY",
        "relationship": "Sector Leadership / Demand Beta",
        "kind": "sector_to_company",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 92,
        "historical_observations": 16,
        "average_lag": "Concurrent",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["IT Services", "INFY", "TCS", "HCLTECH"],
        "supporting_layers": ["Historical Sector", "Historical Company"],
        "evidence": [
            _ev(
                "historical_company",
                "Infosys growth regimes track IT Services sector demand cycles",
                period="2008-2025",
                refs=["company:INFY", "hsip:it_services:Revenue Growth"],
                weight=1.5,
            ),
            _ev(
                "historical_sector",
                "Sector leadership list consistently includes INFY across HSIP periods",
                period="2014-2025",
                refs=["hsip:it_services:Sector Leader", "cskp:it_services"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Banking",
        "target": "HDFCBANK",
        "relationship": "Private Bank Credit Beta",
        "kind": "sector_to_company",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 94,
        "historical_observations": 15,
        "average_lag": "1-2 Quarters",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["Banking", "HDFCBANK", "Credit Growth"],
        "supporting_layers": ["Historical Sector", "Historical Company", "MRI tip"],
        "evidence": [
            _ev(
                "historical_company",
                "HDFC Bank loan growth historically aligns with private bank credit cycles",
                period="2008-2025",
                refs=["company:HDFCBANK", "hsip:banking:Revenue Growth"],
                weight=1.5,
            ),
            _ev(
                "historical_sector",
                "Banking sector leadership / credit tips map to HDFCBANK positioning",
                period="2016-2025",
                refs=["hsip:banking:Sector Leader", "cskp:banking"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Auto",
        "target": "MARUTI",
        "relationship": "PV Demand Leadership",
        "kind": "sector_to_company",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 90,
        "historical_observations": 12,
        "average_lag": "Concurrent",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["Auto", "MARUTI", "PV Mix"],
        "supporting_layers": ["Historical Sector", "Historical Company"],
        "evidence": [
            _ev(
                "historical_company",
                "Maruti volumes dominate PV recoveries and slowdowns in auto sector timelines",
                period="2008-2025",
                refs=["company:MARUTI", "hsip:auto:timeline"],
                weight=1.5,
            ),
            _ev(
                "historical_sector",
                "Auto sector leaders list anchors Maruti across BS-VI and recovery regimes",
                period="2019-2025",
                refs=["hsip:auto:Sector Leader", "cskp:auto"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "Capital Goods",
        "target": "LT",
        "relationship": "Infra Order Book Leadership",
        "kind": "sector_to_company",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 91,
        "historical_observations": 10,
        "average_lag": "1-2 Quarters",
        "first_observed": "2014",
        "last_confirmed": "2025",
        "chain": ["Capital Goods", "LT", "Order Book", "Revenue Growth"],
        "supporting_layers": ["Historical Sector", "Historical Company"],
        "evidence": [
            _ev(
                "historical_company",
                "L&T order inflows historically lead capital goods / infra spending cycles",
                period="2014-2025",
                refs=["company:LT", "hsip:capital_goods:Revenue Growth"],
                weight=1.5,
            ),
            _ev(
                "historical_sector",
                "Capital Goods leadership and public capex tips reference L&T",
                period="2014-2025",
                refs=["hsip:capital_goods:Sector Leader", "cskp:capital_goods"],
                weight=1.3,
            ),
        ],
    },
    # --- Company → Sector ---
    {
        "source": "RELIANCE",
        "target": "Oil & Gas",
        "relationship": "Index Weight / Sector Leadership",
        "kind": "company_to_sector",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 89,
        "historical_observations": 14,
        "average_lag": "Concurrent",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["RELIANCE", "Oil & Gas", "NIFTY Weight"],
        "supporting_layers": ["Historical Company", "Historical Market", "Historical Sector"],
        "evidence": [
            _ev(
                "historical_company",
                "Reliance O2C / energy cash flows dominate oil & gas sector earnings pool",
                period="2008-2025",
                refs=["company:RELIANCE", "hsip:oil_gas:timeline"],
                weight=1.5,
            ),
            _ev(
                "historical_market",
                "Index weight and sector leadership amplify Reliance moves into sector returns",
                period="2016-2025",
                refs=["market:nifty", "hsip:oil_gas:Sector Leader"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "TCS",
        "target": "IT Services",
        "relationship": "Sector Benchmark Leadership",
        "kind": "company_to_sector",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 90,
        "historical_observations": 16,
        "average_lag": "Concurrent",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["TCS", "IT Services", "NIFTY IT"],
        "supporting_layers": ["Historical Company", "Historical Sector"],
        "evidence": [
            _ev(
                "historical_company",
                "TCS scale and guidance historically set IT Services sector tone",
                period="2008-2025",
                refs=["company:TCS", "hsip:it_services:Revenue Growth"],
                weight=1.5,
            ),
            _ev(
                "historical_sector",
                "HSIP IT leadership lists and peer comparisons anchor TCS",
                period="2014-2025",
                refs=["hsip:it_services:Sector Leader"],
                weight=1.2,
            ),
        ],
    },
    # --- Sector → Market ---
    {
        "source": "Banking",
        "target": "NIFTY",
        "relationship": "Market Breadth / Index Leadership",
        "kind": "sector_to_market",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 87,
        "historical_observations": 12,
        "average_lag": "Concurrent",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["Banking", "NIFTY", "Market Breadth"],
        "supporting_layers": ["Historical Sector", "Historical Market"],
        "evidence": [
            _ev(
                "historical_market",
                "Banking weight and leadership historically drive NIFTY breadth in recoveries",
                period="2008-2025",
                refs=["market:nifty", "hsip:banking:timeline"],
                weight=1.4,
            ),
            _ev(
                "historical_sector",
                "Post-correction leadership often rotates through financials",
                period="2009-2021",
                refs=["hsip:banking:Key Event", "research:market:breadth"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "IT Services",
        "target": "NIFTY",
        "relationship": "Exporter / Growth Sleeve Influence",
        "kind": "sector_to_market",
        "direction": "Mixed",
        "evidence_strength": "Medium",
        "confidence_pct": 80,
        "historical_observations": 10,
        "average_lag": "Concurrent",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["IT Services", "NIFTY", "USDINR"],
        "supporting_layers": ["Historical Sector", "Historical Market"],
        "evidence": [
            _ev(
                "historical_market",
                "IT sleeve influences NIFTY during USD and global growth swings",
                period="2008-2025",
                refs=["market:nifty", "hsip:it_services:Average PE"],
                weight=1.3,
            ),
            _ev(
                "historical_sector",
                "IT valuation regimes (COVID surge, AI) alter index composition returns",
                period="2020-2025",
                refs=["hsip:it_services:timeline"],
                weight=1.2,
            ),
        ],
    },
    # --- Global → Sector ---
    {
        "source": "Federal Funds Rate",
        "target": "IT Services",
        "relationship": "USD / Global Demand Transmission",
        "kind": "global_to_sector",
        "direction": "Mixed",
        "evidence_strength": "High",
        "confidence_pct": 86,
        "historical_observations": 11,
        "average_lag": "2-3 Quarters",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["Federal Funds Rate", "USD", "IT Services", "Pharma"],
        "supporting_layers": ["Historical Macro", "Historical Sector", "MRI tip"],
        "evidence": [
            _ev(
                "historical_macro",
                "Fed hiking / easing cycles alter USD and US enterprise spend backdrop",
                period="2008-2025",
                refs=["hmip:Federal Funds Rate:timeline"],
                weight=1.4,
            ),
            _ev(
                "historical_sector",
                "IT Services demand soft patches often coincide with US policy tightening",
                period="2018-2023",
                refs=["hsip:it_services:Revenue Growth", "hsip:it_services:timeline"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Federal Funds Rate",
        "target": "Pharma",
        "relationship": "USD / Export Realisation Channel",
        "kind": "global_to_sector",
        "direction": "Mixed",
        "evidence_strength": "Medium",
        "confidence_pct": 78,
        "historical_observations": 8,
        "average_lag": "2 Quarters",
        "first_observed": "2013",
        "last_confirmed": "2025",
        "chain": ["Federal Funds Rate", "USD", "Pharma"],
        "supporting_layers": ["Historical Macro", "Historical Sector"],
        "evidence": [
            _ev(
                "historical_sector",
                "Pharma export realisations sensitive to USD regimes alongside US generics demand",
                period="2013-2025",
                refs=["hsip:pharma:timeline", "hsip:pharma:Revenue Growth"],
                weight=1.3,
            ),
            _ev(
                "historical_macro",
                "Fed / USD tips appear in exporter sector research during tightening cycles",
                period="2018-2023",
                refs=["hmip:Federal Funds Rate:2022"],
                weight=1.1,
            ),
        ],
    },
]


def all_catalog_entries() -> list[dict[str, Any]]:
    return list(SECTOR_RELATIONSHIP_CATALOG)
