"""Sector → ordered framework composition (primary, secondary, supporting)."""

from __future__ import annotations

# Each entry: list of (framework_id, role)
SECTOR_FRAMEWORKS: dict[str, list[tuple[str, str]]] = {
    "banks": [
        ("FW_RESIDUAL_INCOME", "primary"),
        ("FW_PB", "primary"),
        ("FW_ROE", "secondary"),
        ("FW_HISTORICAL_VALUATION", "supporting"),
        ("FW_MACRO_TRANSMISSION", "supporting"),
        ("FW_DDM", "supporting"),
        ("FW_RISK", "supporting"),
    ],
    "insurance": [
        ("FW_EMBEDDED_VALUE", "primary"),
        ("FW_PB", "primary"),
        ("FW_ROE", "secondary"),
        ("FW_HISTORICAL_VALUATION", "supporting"),
    ],
    "nbfc": [
        ("FW_RESIDUAL_INCOME", "primary"),
        ("FW_PB", "primary"),
        ("FW_ROE", "secondary"),
        ("FW_RISK", "secondary"),
        ("FW_HISTORICAL_VALUATION", "supporting"),
        ("FW_MACRO_TRANSMISSION", "supporting"),
        ("FW_SCENARIO", "supporting"),
    ],
    "it_services": [
        ("FW_DCF", "primary"),
        ("FW_EV_EBITDA", "primary"),
        ("FW_PE", "secondary"),
        ("FW_ROIC", "supporting"),
        ("FW_CASH_FLOW_QUALITY", "supporting"),
        ("FW_BUSINESS_QUALITY", "supporting"),
        ("FW_HISTORICAL_VALUATION", "supporting"),
        ("FW_PEER_COMPARISON", "supporting"),
    ],
    "consumer_staples": [
        ("FW_DCF", "primary"),
        ("FW_ROIC", "secondary"),
        ("FW_ECONOMIC_MOAT", "secondary"),
        ("FW_EV_EBITDA", "supporting"),
        ("FW_HISTORICAL_VALUATION", "supporting"),
    ],
    "hospitals": [
        ("FW_EV_EBITDA", "primary"),
        ("FW_HEALTHCARE_OPS", "primary"),
        ("FW_INDUSTRY_STRUCTURE", "supporting"),
        ("FW_HISTORICAL_VALUATION", "supporting"),
    ],
    "airlines": [
        ("FW_EV_EBITDAR", "primary"),
        ("FW_AVIATION_OPS", "primary"),
        ("FW_INDUSTRY_STRUCTURE", "secondary"),
        ("FW_MACRO_TRANSMISSION", "supporting"),
        ("FW_SCENARIO", "supporting"),
        ("FW_RISK", "supporting"),
        ("FW_HISTORICAL_VALUATION", "supporting"),
    ],
    "cement": [
        ("FW_EV_EBITDA", "primary"),
        ("FW_CEMENT_CAPACITY", "primary"),
        ("FW_REPLACEMENT_COST", "secondary"),
        ("FW_INDUSTRY_STRUCTURE", "supporting"),
    ],
    "steel": [
        ("FW_EV_EBITDA", "primary"),
        ("FW_COMMODITY_CYCLE", "primary"),
        ("FW_ROCE", "supporting"),
        ("FW_INDUSTRY_STRUCTURE", "supporting"),
    ],
    "conglomerates": [
        ("FW_SOTP", "primary"),
        ("FW_NAV", "secondary"),
        ("FW_CAPITAL_ALLOCATION", "supporting"),
        ("FW_HISTORICAL_VALUATION", "supporting"),
    ],
    "real_estate": [
        ("FW_NAV", "primary"),
        ("FW_HISTORICAL_VALUATION", "supporting"),
    ],
    "utilities": [
        ("FW_RAB", "primary"),
        ("FW_DDM", "secondary"),
        ("FW_HISTORICAL_VALUATION", "supporting"),
    ],
    "telecom": [
        ("FW_EV_EBITDA", "primary"),
        ("FW_TELECOM_SUBSCRIBER", "primary"),
        ("FW_DCF", "supporting"),
    ],
    "industrials": [
        ("FW_ROIC", "primary"),
        ("FW_CAPITAL_ALLOCATION", "primary"),
        ("FW_EV_EBITDA", "secondary"),
        ("FW_ROCE", "supporting"),
    ],
    "pharma": [
        ("FW_DCF", "primary"),
        ("FW_EV_EBITDA", "secondary"),
        ("FW_ECONOMIC_MOAT", "supporting"),
    ],
    "auto": [
        ("FW_EV_EBITDA", "primary"),
        ("FW_ROCE", "secondary"),
        ("FW_ROIC", "supporting"),
    ],
    "generic": [
        ("FW_PEER_COMPARISON", "supporting"),
        ("FW_HISTORICAL_VALUATION", "supporting"),
        ("FW_BUSINESS_QUALITY", "supporting"),
    ],
}

# Keyword → sector cues in free text (concept / industry questions)
SECTOR_KEYWORDS: dict[str, tuple[str, ...]] = {
    "banks": (
        "bank",
        "banks",
        "banking",
        "deposit",
        "nim",
        "npa",
        "p/b",
        "price-to-book",
        "residual income",
        "hdfcbank",
        "icicibank",
        "private bank",
        "psu bank",
    ),
    "insurance": ("insurance", "embedded value", "vnb", "life insurer"),
    "nbfc": ("nbfc", "nbfcs", "housing finance", "bajfinance", "cost of funds"),
    "it_services": (
        "it services",
        "software",
        "infosys",
        "tcs",
        "wipro",
        "ev/ebitda and dcf",
        "attrition",
        "deal wins",
        "tcv",
    ),
    "consumer_staples": ("fmcg", "consumer staples", "staples"),
    "hospitals": ("hospital", "hospitals", "arpob", "occupancy", "healthcare provider"),
    "airlines": ("airline", "airlines", "aviation", "load factor", "ask", "rpk", "ebitdar"),
    "cement": ("cement", "utilisation", "capacity addition"),
    "steel": ("steel", "commodity cycle", "hot rolled"),
    "conglomerates": ("conglomerate", "conglomerates", "sum of the parts", "sotp"),
    "real_estate": ("real estate", "realty", "nav", "developer"),
    "utilities": ("utility", "utilities", "regulated asset", "power grid"),
    "telecom": ("telecom", "arpu", "subscriber"),
    "industrials": ("industrial", "industrials", "capital allocation"),
    "pharma": ("pharma", "pharmaceutical"),
    "auto": ("auto", "automobile", "oem"),
}
