"""Macro / rate / inflation / liquidity cycle memories."""

from __future__ import annotations

from institutional_analog_intelligence.registry.models import memory

MEMORIES = [
    memory(
        "MEM_RBI_CUT_2009",
        memory_type="previous_rate_cycle",
        title="RBI easing after GFC — private bank credit recovery 2009",
        entities=["HDFCBANK", "ICICIBANK", "banks", "RBI"],
        time_period="2008-10 to 2010-03",
        available_from="2010-03-31",
        market_regime="rate_cutting_cycle",
        industry="banks",
        macro_regime=["rate_cutting_cycle", "recovery", "liquidity_expansion"],
        policy_context="RBI post-GFC rate cuts and liquidity support",
        confidence=0.88,
        outcome_summary="Private banks with strong liability franchises recovered credit growth faster; NIM compressed then expanded with recovery.",
        lessons_learned=[
            "Rate cuts help banks with CASA strength first via volume, not instantly via NIM",
            "Asset quality lag can offset early rate-cut optimism",
            "Second-order beneficiaries: housing, auto, NBFC funding conditions",
        ],
        cues=[
            "rate cut",
            "repo cut",
            "rbi cut",
            "easing cycle",
            "private banks after rate",
            "repo rate",
            "transmission",
            "basis points",
            "nbfc",
            "real estate",
        ],
        tags=["rbi", "banks", "rate_cycle", "2009"],
        financial_profile="bank_liability_franchise",
        risk_profile="credit_lag",
    ),
    memory(
        "MEM_RBI_TIGHTEN_2013",
        memory_type="previous_rate_cycle",
        title="2013 taper tantrum / INR stress — RBI defensive tightening",
        entities=["banks", "RBI", "fx", "SBIN"],
        time_period="2013-05 to 2014-01",
        available_from="2014-01-31",
        market_regime="fx_depreciation",
        industry="banks",
        macro_regime=["high_rates", "fx_depreciation", "liquidity_tightening"],
        policy_context="Emergency liquidity / rate defence around taper tantrum",
        confidence=0.86,
        outcome_summary="INR stress and defensive rates hurt rate-sensitive sectors; banks with FX/wholesale funding felt CoF pressure.",
        lessons_learned=[
            "Not all rate rises are domestic-cycle hikes — FX defence changes transmission",
            "NBFCs and real estate typically weaken first under sudden tightening",
        ],
        cues=["taper", "rupee", "rate hike", "tightening", "fx stress"],
        tags=["rbi", "2013", "fx", "rates"],
        commodity_exposure=[],
        risk_profile="funding_stress",
    ),
    memory(
        "MEM_RBI_COVID_CUT_2020",
        memory_type="previous_rate_cycle",
        title="COVID 2020 RBI emergency easing — banks and credit transmission",
        entities=["HDFCBANK", "ICICIBANK", "banks", "RBI"],
        time_period="2020-03 to 2021-06",
        available_from="2021-06-30",
        market_regime="pandemic",
        industry="banks",
        macro_regime=["pandemic", "rate_cutting_cycle", "liquidity_expansion", "recovery"],
        policy_context="Repo cuts, CRR/liquidity measures, moratorium overlays",
        confidence=0.9,
        outcome_summary="Cuts aided recovery but credit offtake lagged; private banks with digital/retail franchises recovered volumes earlier than wholesale-heavy peers.",
        lessons_learned=[
            "In pandemic shocks, rate cuts matter less than asset-quality visibility",
            "Transmission uneven — retail mortgages vs SME credit diverge",
            "Compare current cut cycles to 2020 only after adjusting for credit-cost regime",
        ],
        cues=[
            "rate cut",
            "covid",
            "2020",
            "rbi cut",
            "private banks",
            "repo",
            "repo rate",
            "transmission",
            "basis points",
            "nbfc",
            "auto",
        ],
        tags=["rbi", "2020", "pandemic", "banks"],
        financial_profile="bank_retail_franchise",
        risk_profile="asset_quality_uncertainty",
    ),
    memory(
        "MEM_RBI_HIKE_2022",
        memory_type="previous_rate_cycle",
        title="2022–23 inflation-fighting hike cycle",
        entities=["banks", "RBI", "nbfc", "real_estate"],
        time_period="2022-05 to 2023-12",
        available_from="2023-12-31",
        market_regime="rate_hiking_cycle",
        industry="banks",
        macro_regime=["high_inflation", "rate_hiking_cycle", "liquidity_tightening"],
        policy_context="Front-loaded repo hikes to anchor inflation",
        confidence=0.87,
        outcome_summary="NIM initially expanded for deposit-franchise banks; rate-sensitive demand (housing, autos) cooled with lag.",
        lessons_learned=[
            "Hike cycles can be NIM-positive short-term for banks with CASA",
            "Second-order demand destruction shows with lag in housing/auto",
        ],
        cues=["rate hike", "inflation", "tightening cycle", "repo hike"],
        tags=["rbi", "2022", "inflation", "hikes"],
    ),
    memory(
        "MEM_INFLATION_2010_11",
        memory_type="previous_inflation_cycle",
        title="2010–11 high CPI — staples pricing vs discretionary demand",
        entities=["HINDUNILVR", "ITC", "fmcg", "inflation"],
        time_period="2010-01 to 2011-12",
        available_from="2011-12-31",
        market_regime="high_inflation",
        industry="fmcg",
        macro_regime=["high_inflation", "high_rates"],
        confidence=0.8,
        outcome_summary="Staples with pricing power defended margins better; volume growth slowed in rural/discretionary categories.",
        lessons_learned=[
            "Separate volume vs value growth under inflation",
            "Pricing power is the first checklist item in high-CPI regimes",
        ],
        cues=["inflation", "cpi", "stagflation", "pricing power", "fmcg"],
        tags=["inflation", "fmcg", "2011"],
        financial_profile="staples_pricing_power",
    ),
    memory(
        "MEM_LIQUIDITY_TIGHT_2018",
        memory_type="liquidity_cycle",
        title="2018 NBFC / IL&FS liquidity stress",
        entities=["nbfc", "banks", "BAJFINANCE"],
        time_period="2018-09 to 2019-06",
        available_from="2019-06-30",
        market_regime="liquidity_tightening",
        industry="nbfc",
        macro_regime=["liquidity_tightening", "credit_stress"],
        confidence=0.9,
        outcome_summary="Wholesale-funded NBFCs faced CoF spikes and AUM slowdowns; bank-affiliated / retail-deposit-like franchises relatively resilient.",
        lessons_learned=[
            "NBFC stress is a liability-franchise story first",
            "Bank vs NBFC funding divergence widens in liquidity shocks",
        ],
        cues=["nbfc", "liquidity", "funding stress", "il&fs", "credit squeeze"],
        tags=["nbfc", "2018", "liquidity"],
        risk_profile="wholesale_funding",
    ),
]
