"""Company behaviour / earnings / guidance / capital allocation memories."""

from __future__ import annotations

from institutional_analog_intelligence.registry.models import memory

MEMORIES = [
    memory(
        "MEM_INFY_EARNINGS_REACTION_PATTERN",
        memory_type="previous_earnings",
        title="IT services beat-and-selloff pattern — guidance & valuation rich",
        entities=["INFY", "TCS", "WIPRO", "it_services"],
        time_period="2018-01 to 2024-12",
        available_from="2021-06-30",
        market_regime="bull_market",
        industry="it_services",
        macro_regime=["recovery"],
        confidence=0.84,
        outcome_summary="Stocks often fell after 'good' prints when guidance softened, deal TCV disappointed, or starting multiples were rich amid US demand worries.",
        lessons_learned=[
            "Check expectation miss on guidance/TCV before celebrating beats",
            "Rich starting valuation amplifies profit-booking after good results",
        ],
        cues=[
            "stock fell",
            "stock falls",
            "after results",
            "good results",
            "excellent quarterly earnings",
            "earnings",
            "beat",
            "guidance",
            "falls 8%",
            "fell 8%",
        ],
        tags=["earnings", "it", "reaction"],
        corporate_event_type="earnings_reaction",
        valuation_profile="rich_growth_multiple",
    ),
    memory(
        "MEM_INFY_COVID_REPLAY_2020",
        memory_type="historical_analog",
        title="Infosys as of March 2020 — available evidence vs later recovery",
        entities=["INFY"],
        time_period="2020-03",
        available_from="2020-03-31",
        known_outcome_as_of="2021-03-31",
        market_regime="pandemic",
        industry="it_services",
        macro_regime=["pandemic", "demand_slowdown"],
        confidence=0.92,
        outcome_summary="As of 31 Mar 2020, available evidence emphasised demand shock risk and digital delivery resilience; post-period recovery and AI narratives were not yet knowable.",
        lessons_learned=[
            "Replay must exclude post-cut-off guidance and AI strategy narratives",
            "Distinguish known pandemic risk from later outcome knowledge",
        ],
        cues=["replay", "as of", "31 march 2020", "2020-03-31", "infosys", "future leakage"],
        tags=["replay", "infy", "2020"],
        risk_profile="demand_shock",
    ),
    memory(
        "MEM_HDFC_MERGER_TRANSITION",
        memory_type="corporate_event_analog",
        title="HDFC Bank–HDFC Ltd merger — ROE/book transition watch",
        entities=["HDFCBANK"],
        time_period="2022-04 to 2024-06",
        available_from="2023-07-31",
        market_regime="rate_hiking_cycle",
        industry="banks",
        macro_regime=["rate_hiking_cycle"],
        confidence=0.85,
        outcome_summary="Merger changed book/ROE trajectory and near-term comparability; market debated dilution vs franchise accretion.",
        lessons_learned=[
            "Corporate actions can dominate P/B reading vs organic ROE",
            "Use residual-income bridge carefully across merger accounting",
        ],
        cues=["hdfc", "merger", "price to book", "residual income"],
        tags=["hdfcbank", "merger"],
        corporate_event_type="merger",
        financial_profile="bank_liability_franchise",
        valuation_profile="pb_roe",
    ),
    memory(
        "MEM_TCS_MARGIN_DEFENSE",
        memory_type="previous_management_commentary",
        title="TCS margin defence through wage/utilisation cycles",
        entities=["TCS", "INFY", "it_services"],
        time_period="2019-01 to 2023-12",
        available_from="2022-06-30",
        industry="it_services",
        macro_regime=["recovery"],
        confidence=0.8,
        outcome_summary="TCS historically defended industry-leading margins via utilisation, pyramid, and deal mix; peers' margin gaps mattered more than revenue growth alone.",
        lessons_learned=[
            "For IT peers at similar P/E, retrieve margin quality and deal mix first",
            "Wage inflation episodes test management commentary credibility",
        ],
        cues=["tcs", "infosys", "wipro", "similar p/e", "margins", "compare"],
        tags=["tcs", "margins", "it"],
        financial_profile="high_margin_it",
        valuation_profile="quality_premium",
    ),
    memory(
        "MEM_RELIANCE_SOTP_DISCOUNT",
        memory_type="historical_analog",
        title="Reliance SOTP / holdco discount episodes",
        entities=["RELIANCE"],
        time_period="2018-01 to 2024-12",
        available_from="2020-03-31",
        industry="conglomerates",
        macro_regime=["oil_spike", "oil_collapse", "pandemic"],
        confidence=0.82,
        outcome_summary="Market repeatedly debated O2C vs Jio/Retail sum-of-parts and holdco discount; single-multiple valuation repeatedly failed.",
        lessons_learned=[
            "Prepare segment evidence package before any valuation",
            "Oil regime swings hit O2C while consumer digital may diverge",
        ],
        cues=["reliance", "sotp", "investment committee", "evidence package", "conglomerate"],
        tags=["reliance", "sotp"],
        valuation_profile="sotp",
        financial_profile="conglomerate",
    ),
    memory(
        "MEM_ASIANPAINT_MOAT_TEST",
        memory_type="historical_analog",
        title="Asian Paints distribution moat vs competitive intensity decades",
        entities=["ASIANPAINT", "BERGER"],
        time_period="2010-01 to 2024-12",
        available_from="2018-12-31",
        industry="paint",
        macro_regime=["oil_spike", "oil_collapse", "recovery"],
        confidence=0.8,
        outcome_summary="Long distribution/brand advantage supported premium multiples; oil feedstock and competitive intensity periodically tested pricing power.",
        lessons_learned=[
            "Moat evidence must include pricing power and dealer reach, not brand alone",
            "Commodity input regimes interact with moat durability",
        ],
        cues=["asian paints", "moat", "competitive", "decade"],
        tags=["asianpaint", "moat"],
        commodity_exposure=["crude_oil"],
        valuation_profile="quality_premium",
    ),
    memory(
        "MEM_TITAN_GROWTH_CASH_GAP",
        memory_type="previous_earnings",
        title="Discretionary retail growth vs working-capital cash gaps",
        entities=["TITAN"],
        time_period="2017-01 to 2023-12",
        available_from="2020-03-31",
        industry="consumer_discretionary",
        macro_regime=["recovery", "pandemic", "demand_slowdown"],
        confidence=0.78,
        outcome_summary="High revenue growth episodes sometimes coincided with inventory/WC drag; cash conversion was the quality gate.",
        lessons_learned=[
            "Investigate OCF vs growth before concluding quality deterioration",
            "Jewellery inventory cycles can distort quarterly cash",
        ],
        cues=["titan", "operating cash flow", "revenue growth", "cash"],
        tags=["titan", "cash", "growth"],
        financial_profile="wc_intensive_retail",
    ),
    memory(
        "MEM_PREMIUM_MULTIPLE_QUALITY",
        memory_type="historical_analog",
        title="When Indian quality compounders earned sustained premiums",
        entities=["ASIANPAINT", "HDFCBANK", "TCS", "INFY"],
        time_period="2012-01 to 2021-12",
        available_from="2019-12-31",
        market_regime="bull_market",
        macro_regime=["recovery", "low_rates"],
        confidence=0.8,
        outcome_summary="Sustained premiums tracked ROIC/ROE spreads, reinvestment runway, and governance — not growth alone. Premiums compressed when quality evidence weakened.",
        lessons_learned=[
            "Deserving a premium requires checklist evidence, not observing a premium",
            "Historical premium persistence is a clue, not proof",
        ],
        cues=["premium valuation", "premium multiple", "deserves a premium", "twice the valuation", "expensive"],
        tags=["premium", "quality"],
        valuation_profile="quality_premium",
        financial_profile="high_roic",
    ),
    memory(
        "MEM_BANK_PB_RI_ANALOG",
        memory_type="historical_analog",
        title="Why banks are read on P/B and residual income — multi-cycle evidence",
        entities=["HDFCBANK", "ICICIBANK", "SBIN", "banks"],
        time_period="2009-01 to 2024-12",
        available_from="2015-12-31",
        industry="banks",
        macro_regime=["rate_cutting_cycle", "rate_hiking_cycle", "credit_stress"],
        confidence=0.9,
        outcome_summary="Across cycles, P/B tracked ROE–COE and asset-quality regimes; EV/EBITDA remained structurally inappropriate due to financial firm economics.",
        lessons_learned=[
            "Always bridge book → ROE → COE → residual income → asset quality",
            "Never apply industrial EV/EBITDA to banks/insurers",
        ],
        cues=["price to book", "residual income", "banks", "ev/ebitda", "insurance"],
        tags=["banks", "valuation"],
        valuation_profile="pb_roe",
        financial_profile="bank_liability_franchise",
    ),
]
