"""Commodity / oil / steel shock memories."""

from __future__ import annotations

from institutional_analog_intelligence.registry.models import memory

MEMORIES = [
    memory(
        "MEM_OIL_SPIKE_2008",
        memory_type="commodity_shock",
        title="2008 crude spike — airlines / paint / tyre cost shock",
        entities=["INDIGO", "ASIANPAINT", "crude_oil", "airlines", "paint"],
        time_period="2007-01 to 2008-07",
        available_from="2008-12-31",
        market_regime="oil_spike",
        industry="airlines",
        macro_regime=["oil_spike", "high_inflation"],
        confidence=0.85,
        outcome_summary="Fuel-intensive industries saw margin compression; pricing power determined pass-through lag. Demand second-order hit followed.",
        lessons_learned=[
            "Map first-order cost victims before second-order demand victims",
            "Integrated energy names can partially offset downstream pain",
        ],
        cues=["crude", "oil price", "oil spike", "atf", "fuel cost"],
        tags=["oil", "2008", "commodity"],
        commodity_exposure=["crude_oil"],
    ),
    memory(
        "MEM_OIL_COLLAPSE_2014_15",
        memory_type="commodity_shock",
        title="2014–15 oil collapse — OMCs / paint / airline margin relief",
        entities=["RELIANCE", "BPCL", "INDIGO", "ASIANPAINT", "crude_oil"],
        time_period="2014-06 to 2015-12",
        available_from="2015-12-31",
        market_regime="oil_collapse",
        industry="paint",
        macro_regime=["oil_collapse", "low_inflation"],
        confidence=0.86,
        outcome_summary="Downstream and fuel users saw delayed margin relief; upstream / integrated cash flows weakened. CAD / inflation improved for India macro.",
        lessons_learned=[
            "Oil down helps paint/airlines with lag — inventory lags matter",
            "Upstream producers and refiners diverge under oil collapses",
        ],
        cues=["oil fall", "crude fall", "oil prices fall", "oil collapse", "25%"],
        tags=["oil", "2015", "commodity"],
        commodity_exposure=["crude_oil"],
    ),
    memory(
        "MEM_OIL_COVID_2020",
        memory_type="commodity_shock",
        title="2020 oil crash during COVID demand destruction",
        entities=["RELIANCE", "ONGC", "INDIGO", "crude_oil"],
        time_period="2020-03 to 2020-06",
        available_from="2020-06-30",
        market_regime="pandemic",
        industry="airlines",
        macro_regime=["pandemic", "oil_collapse", "demand_slowdown"],
        confidence=0.88,
        outcome_summary="Demand destruction dominated; airlines hurt by traffic more than helped by fuel; upstream severely stressed.",
        lessons_learned=[
            "Do not apply a normal oil-down playbook in a demand-collapse regime",
            "Separate price shock from volume shock",
        ],
        cues=["covid", "oil", "demand destruction", "2020"],
        tags=["oil", "2020", "pandemic"],
        commodity_exposure=["crude_oil"],
    ),
    memory(
        "MEM_STEEL_CYCLE_2016",
        memory_type="sector_cycle",
        title="Mid-2010s steel capacity / China dump cycle",
        entities=["TATASTEEL", "JSWSTEEL", "steel"],
        time_period="2015-01 to 2017-06",
        available_from="2017-06-30",
        market_regime="demand_slowdown",
        industry="steel",
        macro_regime=["demand_slowdown", "import_shock"],
        policy_context="Trade remedies / MIP episodes",
        confidence=0.8,
        outcome_summary="Utilisation and spreads drove multiples ahead of reported earnings troughs; policy support affected relative winners.",
        lessons_learned=[
            "Cement/steel multiples often discount mid-cycle utilisation, not trailing EPS",
            "Import duties change relative domestic pricing power",
        ],
        cues=["steel", "import duty", "capacity", "utilisation", "spreads"],
        tags=["steel", "cycle", "2016"],
        commodity_exposure=["steel"],
    ),
    memory(
        "MEM_CEMENT_PRE_EARNINGS_RERATE",
        memory_type="sector_cycle",
        title="Cement valuation expansion before earnings — utilisation lead",
        entities=["ULTRACEMCO", "AMBUJACEM", "cement"],
        time_period="2016-01 to 2018-12",
        available_from="2018-12-31",
        market_regime="recovery",
        industry="cement",
        macro_regime=["recovery", "fiscal_expansion"],
        confidence=0.82,
        outcome_summary="Multiples expanded as utilisation and pricing outlook improved, often before reported EPS inflection.",
        lessons_learned=[
            "Track capacity additions and regional pricing before earnings",
            "Do not capitalise peak-cycle EPS as mid-cycle",
        ],
        cues=["cement", "valuation expansion", "utilisation", "before earnings"],
        tags=["cement", "cycle"],
        valuation_profile="cycle_leading_multiple",
    ),
]
