"""Policy / government decision memories."""

from __future__ import annotations

from institutional_analog_intelligence.registry.models import memory

MEMORIES = [
    memory(
        "MEM_GST_2017",
        memory_type="government_decision_analog",
        title="GST rollout 2017 — formalisation vs near-term disruption",
        entities=["fmcg", "gst", "fiscal"],
        time_period="2017-07 to 2018-06",
        available_from="2018-06-30",
        market_regime="fiscal_expansion",
        industry="fmcg",
        macro_regime=["fiscal_expansion"],
        policy_context="GST introduction and rate rationalisation phase",
        confidence=0.84,
        outcome_summary="Near-term channel disruption in trade-heavy categories; longer-term formalisation benefited organised players. GST collections alone never proved growth quality.",
        lessons_learned=[
            "Record GST prints ≠ uniform demand strength",
            "Separate compliance/base effects from real activity",
        ],
        cues=["gst", "gst collections", "record high", "formalisation"],
        tags=["gst", "2017", "policy"],
    ),
    memory(
        "MEM_PLI_ELECTRONICS",
        memory_type="previous_policy_event",
        title="Electronics PLI — capex inducement vs ROIC durability",
        entities=["pli", "manufacturing"],
        time_period="2020-01 to 2023-12",
        available_from="2023-12-31",
        market_regime="fiscal_expansion",
        macro_regime=["fiscal_expansion", "export_boom"],
        policy_context="Production Linked Incentive schemes",
        confidence=0.78,
        outcome_summary="Capex and localisation rose where eligibility/economics worked; ROIC durability depended on global cost curves, not subsidy alone.",
        lessons_learned=[
            "Treat PLI as optionality on capex, not permanent ROIC uplift",
            "Check eligibility duration and competitive redistribution",
        ],
        cues=["pli", "production linked", "incentive", "localisation"],
        tags=["pli", "policy"],
    ),
    memory(
        "MEM_IMPORT_DUTY_STEEL",
        memory_type="government_decision_analog",
        title="Steel import duty / trade remedy episodes — winners and losers",
        entities=["TATASTEEL", "JSWSTEEL", "steel", "auto"],
        time_period="2015-01 to 2016-12",
        available_from="2016-12-31",
        market_regime="import_shock",
        industry="steel",
        macro_regime=["import_shock"],
        policy_context="MIP / duty actions on steel imports",
        confidence=0.83,
        outcome_summary="Domestic steel producers benefited on pricing; auto/engineering users faced input-cost pressure with lag.",
        lessons_learned=[
            "Duty hikes create producer vs user splits — map both",
            "Implementation lag and circumvention risk matter",
        ],
        cues=["import duty", "import duties", "steel duty", "trade remedy"],
        tags=["steel", "duties", "policy"],
        commodity_exposure=["steel"],
    ),
    memory(
        "MEM_DEMONETISATION_2016",
        memory_type="government_decision_analog",
        title="Demonetisation 2016 — cash economy shock",
        entities=["fmcg", "banks", "SBIN"],
        time_period="2016-11 to 2017-06",
        available_from="2017-06-30",
        market_regime="demand_slowdown",
        macro_regime=["demand_slowdown", "liquidity_tightening"],
        policy_context="Currency demonetisation",
        confidence=0.85,
        outcome_summary="Cash-heavy retail/FMCG volumes dipped; bank deposits surged temporarily; recovery uneven by category.",
        lessons_learned=[
            "Policy shocks can look like demand destruction temporarily",
            "Deposit surge ≠ credit quality improvement",
        ],
        cues=["demonetisation", "cash", "currency shock"],
        tags=["2016", "policy", "shock"],
    ),
    memory(
        "MEM_BUDGET_CAPEX_PUSH",
        memory_type="previous_policy_event",
        title="Union Budget capex pushes — cement / capital goods lead",
        entities=["cement", "capital_goods", "fiscal"],
        time_period="2021-02 to 2024-02",
        available_from="2024-02-29",
        market_regime="fiscal_expansion",
        industry="cement",
        macro_regime=["fiscal_expansion", "recovery"],
        policy_context="Elevated central capex in successive budgets",
        confidence=0.8,
        outcome_summary="Infra-linked cement/capital goods saw demand visibility improve; private capex lag remained a risk.",
        lessons_learned=[
            "Budget capex helps materials with lag via project execution",
            "Watch deficit path alongside scheme headlines",
        ],
        cues=["budget", "capex", "fiscal", "infra"],
        tags=["budget", "capex", "policy"],
    ),
]
