"""Canonical ratio definitions (FKB-01). Knowledge only — no calculations."""

from __future__ import annotations

from typing import Any


def _r(
    id_: str,
    name: str,
    *,
    formula: str,
    meaning: str,
    interpretation: str,
    limitations: str,
    required: list[str],
    higher_is: str,
    lower_is: str,
    units: str = "ratio",
) -> dict[str, Any]:
    return {
        "id": id_,
        "display_name": name,
        "formula": formula,
        "meaning": meaning,
        "typical_interpretation": interpretation,
        "limitations": limitations,
        "required_metrics": required,
        "higher_is_generally": higher_is,
        "lower_is_generally": lower_is,
        "units": units,
        "performs_analysis": False,
    }


RATIOS: dict[str, dict[str, Any]] = {
    "gross_margin": _r(
        "gross_margin",
        "Gross Margin",
        formula="Gross Profit / Revenue",
        meaning="Share of revenue remaining after direct costs.",
        interpretation="Indicates pricing power and cost of goods efficiency.",
        limitations="Mix shifts and accounting classification of COGS can distort comparisons.",
        required=["gross_profit", "revenue"],
        higher_is="Stronger product economics",
        lower_is="Cost or pricing pressure",
        units="percent",
    ),
    "ebitda_margin": _r(
        "ebitda_margin",
        "EBITDA Margin",
        formula="EBITDA / Revenue",
        meaning="Operating earnings intensity before D&A, interest and tax.",
        interpretation="Common operating profitability benchmark.",
        limitations="Ignores capex needs; not a cash measure.",
        required=["ebitda", "revenue"],
        higher_is="Stronger operating profitability",
        lower_is="Weaker operating profitability",
        units="percent",
    ),
    "operating_margin": _r(
        "operating_margin",
        "Operating Margin",
        formula="EBIT / Revenue",
        meaning="Operating profit as a share of revenue.",
        interpretation="Core franchise profitability after D&A.",
        limitations="Affected by depreciation policy and one-offs.",
        required=["ebit", "revenue"],
        higher_is="Stronger operating leverage / efficiency",
        lower_is="Margin pressure",
        units="percent",
    ),
    "net_margin": _r(
        "net_margin",
        "Net Margin",
        formula="PAT / Revenue",
        meaning="Bottom-line profitability per unit of revenue.",
        interpretation="Captures full P&L after interest and tax.",
        limitations="Sensitive to financing, tax and non-operating items.",
        required=["pat", "revenue"],
        higher_is="Stronger bottom-line conversion",
        lower_is="Profitability pressure",
        units="percent",
    ),
    "roe": _r(
        "roe",
        "ROE",
        formula="PAT / Equity",
        meaning="Return generated on shareholders' equity.",
        interpretation="Equity efficiency; sector norms differ materially.",
        limitations="Leverage can inflate ROE; accounting equity can be distorted.",
        required=["pat", "total_equity"],
        higher_is="Stronger equity returns (context-dependent)",
        lower_is="Weaker equity returns",
        units="percent",
    ),
    "roce": _r(
        "roce",
        "ROCE",
        formula="EBIT (or NOPAT) / Capital Employed",
        meaning="Return on capital employed in the business.",
        interpretation="Preferred for capital-intensive industries.",
        limitations="Definition of capital employed varies across practitioners.",
        required=["ebit", "capital_employed"],
        higher_is="Better capital efficiency",
        lower_is="Weaker capital efficiency",
        units="percent",
    ),
    "roic": _r(
        "roic",
        "ROIC",
        formula="NOPAT / Invested Capital",
        meaning="Return on invested capital after tax operating lens.",
        interpretation="Economic return on capital independent of financing mix.",
        limitations="Requires consistent invested-capital definition.",
        required=["ebit", "total_equity", "net_debt"],
        higher_is="Value-creative capital deployment",
        lower_is="Value-destructive or low-return capital use",
        units="percent",
    ),
    "current_ratio": _r(
        "current_ratio",
        "Current Ratio",
        formula="Current Assets / Current Liabilities",
        meaning="Short-term liquidity coverage.",
        interpretation="Ability to meet near-term obligations.",
        limitations="Inventory quality and receivable collectability matter.",
        required=["total_assets", "total_liabilities"],
        higher_is="Stronger liquidity (up to a point)",
        lower_is="Tighter liquidity",
    ),
    "quick_ratio": _r(
        "quick_ratio",
        "Quick Ratio",
        formula="(Cash + Receivables) / Current Liabilities",
        meaning="Liquidity excluding inventory.",
        interpretation="More conservative liquidity test.",
        limitations="Still ignores receivable quality.",
        required=["cash", "receivables"],
        higher_is="Stronger near-cash liquidity",
        lower_is="Weaker near-cash liquidity",
    ),
    "debt_to_ebitda": _r(
        "debt_to_ebitda",
        "Debt / EBITDA",
        formula="Total Debt / EBITDA",
        meaning="Leverage relative to operating earnings.",
        interpretation="Common credit metric; sector thresholds differ.",
        limitations="EBITDA is not cash; cyclical earnings distort the ratio.",
        required=["total_debt", "ebitda"],
        higher_is="Higher leverage / credit risk",
        lower_is="Lower leverage",
    ),
    "debt_to_equity": _r(
        "debt_to_equity",
        "Debt / Equity",
        formula="Total Debt / Equity",
        meaning="Capital structure leverage.",
        interpretation="Balance between creditor and owner financing.",
        limitations="Book equity may not reflect economic equity.",
        required=["total_debt", "total_equity"],
        higher_is="Higher financial leverage",
        lower_is="Lower financial leverage",
    ),
    "interest_coverage": _r(
        "interest_coverage",
        "Interest Coverage",
        formula="EBIT / Interest Expense",
        meaning="Ability of operating profit to cover interest.",
        interpretation="Solvency / credit comfort indicator.",
        limitations="Ignores principal amortisation and refinancing risk.",
        required=["ebit"],
        higher_is="Greater interest-service comfort",
        lower_is="Greater refinancing / solvency concern",
    ),
    "asset_turnover": _r(
        "asset_turnover",
        "Asset Turnover",
        formula="Revenue / Average Total Assets",
        meaning="Revenue generated per unit of assets.",
        interpretation="Capital intensity / efficiency signal.",
        limitations="Asset age and revaluation policies affect comparability.",
        required=["revenue", "total_assets"],
        higher_is="Higher asset efficiency",
        lower_is="Higher capital intensity",
    ),
    "inventory_turnover": _r(
        "inventory_turnover",
        "Inventory Turnover",
        formula="COGS / Average Inventory",
        meaning="How quickly inventory is sold.",
        interpretation="Critical in manufacturing and retail.",
        limitations="Seasonality can distort point-in-time readings.",
        required=["cogs", "inventory"],
        higher_is="Faster inventory conversion",
        lower_is="Slower-moving inventory",
    ),
    "receivable_days": _r(
        "receivable_days",
        "Receivable Days",
        formula="Receivables / Revenue * Days",
        meaning="Average collection period.",
        interpretation="Customer credit and collection efficiency.",
        limitations="Revenue recognition timing affects the metric.",
        required=["receivables", "revenue"],
        higher_is="Slower collections / more credit",
        lower_is="Faster collections",
        units="days",
    ),
    "payable_days": _r(
        "payable_days",
        "Payable Days",
        formula="Payables / COGS * Days",
        meaning="Average payment period to suppliers.",
        interpretation="Supplier financing intensity.",
        limitations="COGS may be a poor denominator for service businesses.",
        required=["payables", "cogs"],
        higher_is="More supplier financing",
        lower_is="Faster supplier payment",
        units="days",
    ),
    "cash_conversion_cycle": _r(
        "cash_conversion_cycle",
        "Cash Conversion Cycle",
        formula="Receivable Days + Inventory Days - Payable Days",
        meaning="Net days cash is tied in the operating cycle.",
        interpretation="Working capital efficiency summary.",
        limitations="Not meaningful for all sectors (e.g. banks).",
        required=["receivables", "inventory", "payables"],
        higher_is="More cash tied in WC",
        lower_is="Faster cash conversion",
        units="days",
    ),
    "fcf_conversion": _r(
        "fcf_conversion",
        "FCF Conversion",
        formula="Free Cash Flow / PAT",
        meaning="Share of accounting profit converted to free cash flow.",
        interpretation="Earnings quality / cash conversion lens.",
        limitations="Capex timing and growth phase affect the ratio.",
        required=["free_cash_flow", "pat"],
        higher_is="Stronger cash conversion",
        lower_is="Weaker cash conversion",
        units="percent",
    ),
    "dividend_payout": _r(
        "dividend_payout",
        "Dividend Payout",
        formula="Dividends / PAT",
        meaning="Share of earnings distributed as dividends.",
        interpretation="Distribution policy relative to earnings.",
        limitations="Should be cross-checked against FCF, not only PAT.",
        required=["dividends", "pat"],
        higher_is="Higher distribution of earnings",
        lower_is="Greater earnings retention",
        units="percent",
    ),
}


def all_ratios() -> list[dict[str, Any]]:
    return [RATIOS[k] for k in sorted(RATIOS)]


def get_ratio(key: str) -> dict[str, Any] | None:
    k = key.strip().lower().replace(" ", "_").replace("-", "_")
    aliases = {
        "operatingmargin": "operating_margin",
        "debt_ebitda": "debt_to_ebitda",
        "debt/ebitda": "debt_to_ebitda",
        "d_e": "debt_to_equity",
        "ccc": "cash_conversion_cycle",
    }
    k = aliases.get(k, k)
    # camelCase → snake
    if k not in RATIOS and k.lower() != k:
        import re

        k2 = re.sub(r"(?<!^)(?=[A-Z])", "_", key).lower()
        k = aliases.get(k2, k2)
    row = RATIOS.get(k)
    return dict(row) if row else None
