"""Configuration-driven MEE taxonomies and impact chains."""

from __future__ import annotations

EVENT_CATEGORIES: list[str] = [
    "corporate",
    "macro",
    "economic",
    "government",
    "policy",
    "central_bank",
    "commodity",
    "currency",
    "interest_rate",
    "geopolitical",
    "legal",
    "technology",
    "climate",
    "esg",
    "capital_markets",
    "healthcare",
    "energy",
    "infrastructure",
    "supply_chain",
    "cyber",
    "natural_disaster",
    "global_markets",
]

EVENT_STATUSES: list[str] = [
    "detected",
    "verified",
    "published",
    "updated",
    "superseded",
    "resolved",
    "archived",
    "cancelled",
]

SEVERITY_LEVELS: list[str] = ["critical", "high", "medium", "low", "informational"]

# Canonical event type taxonomy: aliases → canonical type
EVENT_TAXONOMY: dict[str, str] = {
    "share buyback": "buyback",
    "repurchase": "buyback",
    "buy-back": "buyback",
    "buyback": "buyback",
    "ceo resigned": "executive_change",
    "managing director resigned": "executive_change",
    "md resigned": "executive_change",
    "executive change": "executive_change",
    "management change": "executive_change",
    "quarterly results": "quarterly_results",
    "q1 results": "quarterly_results",
    "q2 results": "quarterly_results",
    "q3 results": "quarterly_results",
    "q4 results": "quarterly_results",
    "earnings": "quarterly_results",
    "annual results": "annual_results",
    "annual report": "annual_results",
    "dividend": "dividend",
    "interim dividend": "dividend",
    "final dividend": "dividend",
    "rights issue": "rights_issue",
    "bonus": "bonus",
    "stock split": "split",
    "split": "split",
    "merger": "merger",
    "acquisition": "acquisition",
    "joint venture": "joint_venture",
    "jv": "joint_venture",
    "large order": "large_order",
    "order win": "large_order",
    "plant expansion": "capacity_increase",
    "capacity increase": "capacity_increase",
    "capacity expansion": "capacity_increase",
    "plant commissioning": "plant_commissioned",
    "plant commissioned": "plant_commissioned",
    "debt raise": "debt_raise",
    "equity raise": "equity_raise",
    "promoter stake": "promoter_stake_change",
    "rating upgrade": "rating_upgrade",
    "rating downgrade": "rating_downgrade",
    "credit downgrade": "rating_downgrade",
    "litigation": "litigation",
    "regulatory action": "regulatory_action",
    "product launch": "product_launch",
    "guidance": "guidance",
    "repo rate": "repo_rate",
    "repo rate cut": "repo_rate",
    "repo rate hike": "repo_rate",
    "gdp": "gdp",
    "inflation": "inflation",
    "pmi": "pmi",
    "budget": "budget",
    "oil": "oil_price",
    "oil prices": "oil_price",
    "oil shock": "oil_price",
    "usd/inr": "usd_inr",
    "rupee": "usd_inr",
    "cyber attack": "cyber_attack",
    "sanction": "sanctions",
    "sanctions": "sanctions",
    "tariff": "tariffs",
    "tariffs": "tariffs",
}

EVENT_TYPE_CATEGORY: dict[str, str] = {
    "buyback": "corporate",
    "executive_change": "corporate",
    "quarterly_results": "corporate",
    "annual_results": "corporate",
    "dividend": "corporate",
    "rights_issue": "corporate",
    "bonus": "corporate",
    "split": "corporate",
    "merger": "corporate",
    "acquisition": "corporate",
    "joint_venture": "corporate",
    "large_order": "corporate",
    "capacity_increase": "corporate",
    "plant_commissioned": "corporate",
    "debt_raise": "corporate",
    "equity_raise": "corporate",
    "promoter_stake_change": "corporate",
    "rating_upgrade": "capital_markets",
    "rating_downgrade": "capital_markets",
    "litigation": "legal",
    "regulatory_action": "policy",
    "product_launch": "technology",
    "guidance": "corporate",
    "repo_rate": "central_bank",
    "gdp": "macro",
    "inflation": "macro",
    "pmi": "economic",
    "budget": "government",
    "oil_price": "commodity",
    "usd_inr": "currency",
    "cyber_attack": "cyber",
    "sanctions": "geopolitical",
    "tariffs": "policy",
}

# Macro / policy impact propagation chains
IMPACT_CHAINS: dict[str, list[str]] = {
    "repo_rate": [
        "banking",
        "financial_services",
        "real_estate",
        "infrastructure",
        "capital_goods",
        "chemicals",
        "consumer_durables",
    ],
    "oil_price": ["energy", "auto", "chemicals", "aviation", "logistics"],
    "usd_inr": ["it_services", "pharma", "metals", "auto"],
    "budget": ["infrastructure", "defence", "railways", "power", "capital_goods"],
    "inflation": ["fmcg", "banking", "consumer_staples"],
    "gdp": ["banking", "auto", "capital_goods", "real_estate"],
}

# Keyword hints for detection from evidence / IIE / FLE text
DETECTION_KEYWORDS: dict[str, list[str]] = {
    "buyback": ["buyback", "buy-back", "repurchase"],
    "dividend": ["dividend"],
    "quarterly_results": ["quarterly result", "q1 ", "q2 ", "q3 ", "q4 ", "earnings"],
    "guidance": ["guidance"],
    "acquisition": ["acquisition", "acquire", "acquired"],
    "merger": ["merger", "merge with"],
    "executive_change": ["ceo resign", "md resign", "appointed ceo", "new ceo", "management change"],
    "capacity_increase": ["capacity", "expansion", "capex"],
    "large_order": ["order win", "large order", "contract win"],
    "rating_downgrade": ["downgrade", "rating cut"],
    "rating_upgrade": ["upgrade", "rating upgrade"],
    "repo_rate": ["repo rate", "policy rate", "mpc"],
    "oil_price": ["oil price", "crude", "brent"],
    "budget": ["union budget", "fiscal budget"],
    "inflation": ["inflation", "cpi"],
    "gdp": ["gdp", "gross domestic"],
    "cyber_attack": ["cyber attack", "ransomware", "data breach"],
}

MIN_EVIDENCE_CONFIDENCE = 0.45
