"""Frozen golden answer references v1 — checklists, not wording. IMMUTABLE."""

from __future__ import annotations

from academy.regression.schema import GoldenAnswerRef

GOLDEN_ANSWERS: list[GoldenAnswerRef] = [
    GoldenAnswerRef(
        "gq_biz_hdfc_great",
        "Great franchise if deposit franchise, underwriting culture and returns durability hold; trajectory matters.",
        evidence_checklist=["deposit franchise", "asset quality", "returns", "trajectory"],
        framework_checklist=["porter", "moat"],
        concept_checklist=["moat", "franchise", "pricing" ],
        reasoning_checklist=["business quality", "conclusion", "not slogan"],
        must_not=["pe =", "cheap", "dcf terminal"],
    ),
    GoldenAnswerRef(
        "gq_biz_nestle_premium",
        "Premium linked to brand, pricing power, distribution and ROIC — not the multiple alone.",
        evidence_checklist=["brand", "pricing", "distribution", "roic"],
        framework_checklist=["pricing_power", "margin_of_safety"],
        concept_checklist=["pricing power", "moat"],
        reasoning_checklist=["why premium", "conditions", "conclusion"],
        must_not=["guaranteed", "always cheap"],
    ),
    GoldenAnswerRef(
        "gq_biz_nokia_moat",
        "Moat lost via ecosystem/platform disruption and innovation lag.",
        evidence_checklist=["ecosystem", "disruption", "innovation"],
        framework_checklist=["creative_destruction", "moat"],
        concept_checklist=["moat", "network"],
        reasoning_checklist=["why lost", "lesson", "conclusion"],
    ),
    GoldenAnswerRef(
        "gq_biz_amzn_costco",
        "Compare flywheel/reinvestment vs membership warehouse economics; different engines.",
        evidence_checklist=["flywheel", "membership", "customer"],
        framework_checklist=["flywheel", "switching_costs"],
        concept_checklist=["platform", "retention"],
        reasoning_checklist=["similar", "differ", "lesson"],
    ),
    GoldenAnswerRef(
        "gq_fin_tcs_cash",
        "Judge cash conversion of earnings; FCF vs NI over cycle.",
        evidence_checklist=["cash", "earnings", "conversion", "fcf"],
        framework_checklist=["cash_conversion", "earnings_quality"],
        concept_checklist=["earnings quality", "fcf"],
        reasoning_checklist=["supports", "conclusion"],
        must_not=["moat", "brand strategy"],
    ),
    GoldenAnswerRef(
        "gq_fin_ultratech_ev",
        "Economic value if ROIC > WACC on normalized cycle capital.",
        evidence_checklist=["roic", "wacc", "cycle", "capacity"],
        framework_checklist=["economic_profit", "capital_cycle", "roic"],
        concept_checklist=["economic profit", "roic"],
        reasoning_checklist=["value creation", "conclusion"],
    ),
    GoldenAnswerRef(
        "gq_fin_apple_roic",
        "High ROIC from ecosystem, pricing, asset-light services mix and capital returns discipline.",
        evidence_checklist=["roic", "ecosystem", "cash", "services"],
        framework_checklist=["roic", "cash_conversion"],
        concept_checklist=["roic", "pricing power"],
        reasoning_checklist=["durability", "conclusion"],
    ),
    GoldenAnswerRef(
        "gq_val_apple_premium",
        "Premium justified only if expectations match durable cash returns and MOS remains.",
        evidence_checklist=["expectations", "cash", "roic"],
        framework_checklist=["reverse_dcf", "margin_of_safety"],
        concept_checklist=["intrinsic value", "margin of safety"],
        reasoning_checklist=["premium conditional", "conclusion"],
        must_not=["moat analysis deep dive without valuation"],
    ),
    GoldenAnswerRef(
        "gq_val_nvidia_exp",
        "Debate embedded growth/margin expectations via reverse DCF — not cheap/expensive slogans.",
        evidence_checklist=["implied", "growth", "expectation"],
        framework_checklist=["reverse_dcf", "scenario_analysis"],
        concept_checklist=["expectations", "reverse dcf"],
        reasoning_checklist=["what is priced", "conclusion"],
    ),
    GoldenAnswerRef(
        "gq_val_asian_growth",
        "Extract implied growth from price; compare to industry runway.",
        evidence_checklist=["implied", "growth", "price"],
        framework_checklist=["reverse_dcf"],
        concept_checklist=["expectations"],
        reasoning_checklist=["embedded growth", "conclusion"],
    ),
    GoldenAnswerRef(
        "gq_risk_eternal",
        "Thesis breaks if unit economics, retention or funding path fails.",
        evidence_checklist=["unit economics", "retention", "funding", "promotion"],
        framework_checklist=["scenario_analysis", "stress"],
        concept_checklist=["tail risk"],
        reasoning_checklist=["break points", "conclusion"],
        must_not=["intrinsic value =", "dcf ="],
    ),
    GoldenAnswerRef(
        "gq_mgmt_brk",
        "Capital allocation judged by incremental returns, discipline and complexity control.",
        evidence_checklist=["capital allocation", "discipline", "returns"],
        framework_checklist=["capital_allocation"],
        concept_checklist=["capital allocation"],
        reasoning_checklist=["evaluate", "conclusion"],
    ),
    GoldenAnswerRef(
        "gq_macro_hdfc_rates",
        "Rates transmit via NIM, credit demand, funding costs and asset quality.",
        evidence_checklist=["nim", "rates", "funding", "credit"],
        framework_checklist=["transmission"],
        concept_checklist=["interest rates", "transmission"],
        reasoning_checklist=["transmission", "conclusion"],
        must_not=["porter five", "brand moat deep"],
    ),
    GoldenAnswerRef(
        "gq_sec_indian_it",
        "Structural strength depends on demand, pricing, talent and automation — not slogans.",
        evidence_checklist=["demand", "pricing", "talent", "automation"],
        framework_checklist=["industry_structure", "capacity_cycle"],
        concept_checklist=["industry structure"],
        reasoning_checklist=["structural", "conclusion"],
    ),
    GoldenAnswerRef(
        "gq_port_diversified",
        "Portfolio fit via diversification, factor, concentration, correlation, drawdown.",
        evidence_checklist=["diversif", "correlation", "concentration", "drawdown"],
        framework_checklist=["portfolio"],
        concept_checklist=["diversification", "risk"],
        reasoning_checklist=["improve portfolio", "conclusion"],
    ),
    GoldenAnswerRef(
        "gq_ret_roic",
        "Unified multi-author institutional ROIC object — cash, cycle, MOS.",
        evidence_checklist=["roic", "cash", "wacc"],
        framework_checklist=["roic", "margin_of_safety"],
        concept_checklist=["roic", "economic profit"],
        reasoning_checklist=["damodaran", "graham", "institutional"],
    ),
    GoldenAnswerRef(
        "gq_xfer_nokia_bb",
        "Platform disruption lessons transfer; local specifics differ.",
        evidence_checklist=["similar", "differ", "lesson", "disruption"],
        framework_checklist=["creative_destruction"],
        concept_checklist=["moat"],
        reasoning_checklist=["transfer", "lesson"],
    ),
    GoldenAnswerRef(
        "gq_xfer_nestle_hul",
        "Brand/distribution pricing lessons transfer across staples.",
        evidence_checklist=["similar", "differ", "lesson", "brand"],
        framework_checklist=["pricing_power"],
        concept_checklist=["pricing power"],
        reasoning_checklist=["transfer", "lesson"],
    ),
    GoldenAnswerRef(
        "gq_xfer_amzn_meli",
        "Flywheel/unit-economics lessons transfer to regional platforms.",
        evidence_checklist=["similar", "differ", "lesson", "flywheel"],
        framework_checklist=["flywheel", "network_effects"],
        concept_checklist=["platform"],
        reasoning_checklist=["transfer", "lesson"],
    ),
    GoldenAnswerRef(
        "gq_xfer_wirecard",
        "Accounting/governance failure signals transfer to similar fraud patterns.",
        evidence_checklist=["similar", "differ", "lesson", "governance"],
        framework_checklist=["stress"],
        concept_checklist=["governance risk"],
        reasoning_checklist=["transfer", "lesson"],
    ),
]


def answers_by_id() -> dict[str, GoldenAnswerRef]:
    return {a.question_id: a for a in GOLDEN_ANSWERS}
