"""Blueprint registry — report types with purpose, audience, sections, owners."""

from __future__ import annotations

from typing import Any

# Section key → default owner (analyst / office role)
DEFAULT_SECTION_OWNERS: dict[str, str] = {
    "executive_summary": "Research Writer",
    "investment_thesis": "CIO",
    "business_quality": "Business",
    "financial_quality": "Financial",
    "valuation": "Valuation",
    "risk": "Risk",
    "forecast": "Forecast",
    "portfolio_fit": "Portfolio",
    "committee_opinion": "Committee",
    "cio_summary": "CIO",
    "appendix": "Research Writer",
    "business_comparison": "Business",
    "financial_comparison": "Financial",
    "competitive_position": "Sector",
    "valuation_comparison": "Valuation",
    "historical_comparison": "Valuation",
    "risk_comparison": "Risk",
    "conclusion": "Research Writer",
    "definition": "Academy",
    "importance": "Academy",
    "calculation": "Financial",
    "examples": "Academy",
    "common_mistakes": "Academy",
    "case_study": "Academy",
    "summary": "Research Writer",
    "historical_valuation": "Valuation",
    "historical_percentiles": "Valuation",
    "peer_comparison": "Sector",
    "macro_drivers": "Macro",
    "market_expectations": "Market",
    "scenario_analysis": "Forecast",
    "policy": "Macro",
    "transmission": "Macro",
    "risks": "Risk",
    "sector_structure": "Sector",
    "industry_dynamics": "Sector",
    "company_overview": "Business",
    "accounting_quality": "Accounting",
    "management_assessment": "Management",
    "news_digest": "News",
    "portfolio_construction": "Portfolio",
    "stress_scenarios": "Risk",
    "recommendation": "CIO",
    "key_levels": "Market",
    "overnight_developments": "News",
    "session_recap": "Market",
    "screening_criteria": "Financial",
    "screening_results": "Valuation",
}

REPORT_BLUEPRINTS: dict[str, dict[str, Any]] = {
    "institutional_investment_report": {
        "report_name": "Institutional Investment Report",
        "purpose": "Full institutional buy/sell decision support",
        "audience": "Investment Committee / CIO / Portfolio Office",
        "mandatory_sections": [
            "executive_summary",
            "investment_thesis",
            "business_quality",
            "financial_quality",
            "valuation",
            "risk",
            "forecast",
            "portfolio_fit",
            "committee_opinion",
            "cio_summary",
        ],
        "optional_sections": ["appendix", "macro_drivers", "management_assessment"],
        "suppress_default": [],
        "max_length_words": 4500,
        "output_style": "institutional_memo",
        "max_sections": 14,
        "max_tables": 8,
        "max_charts": 6,
    },
    "company_research_report": {
        "report_name": "Company Research Report",
        "purpose": "Deep company fundamental research",
        "audience": "Analyst desk / CIO",
        "mandatory_sections": [
            "executive_summary",
            "company_overview",
            "business_quality",
            "financial_quality",
            "valuation",
            "risk",
            "conclusion",
        ],
        "optional_sections": ["management_assessment", "forecast", "appendix"],
        "suppress_default": ["portfolio_fit", "committee_opinion"],
        "max_length_words": 3500,
        "output_style": "company_note",
        "max_sections": 12,
        "max_tables": 6,
        "max_charts": 4,
    },
    "sector_research_report": {
        "report_name": "Sector Research Report",
        "purpose": "Sector attractiveness and structure",
        "audience": "Sector desk / Portfolio Office",
        "mandatory_sections": [
            "executive_summary",
            "sector_structure",
            "competitive_position",
            "macro_drivers",
            "valuation",
            "risk",
            "conclusion",
        ],
        "optional_sections": ["forecast", "peer_comparison", "appendix"],
        "suppress_default": ["portfolio_fit", "management_assessment", "accounting_quality"],
        "max_length_words": 3000,
        "output_style": "sector_note",
        "max_sections": 11,
        "max_tables": 5,
        "max_charts": 4,
    },
    "industry_report": {
        "report_name": "Industry Report",
        "purpose": "Industry structure and dynamics",
        "audience": "Strategy / Sector desk",
        "mandatory_sections": [
            "executive_summary",
            "industry_dynamics",
            "sector_structure",
            "competitive_position",
            "macro_drivers",
            "conclusion",
        ],
        "optional_sections": ["valuation", "risk", "appendix"],
        "suppress_default": ["portfolio_fit", "committee_opinion", "cio_summary"],
        "max_length_words": 2800,
        "output_style": "industry_brief",
        "max_sections": 10,
        "max_tables": 5,
        "max_charts": 3,
    },
    "historical_valuation_report": {
        "report_name": "Historical Valuation Report",
        "purpose": "Valuation versus history and peers",
        "audience": "Valuation desk / CIO",
        "mandatory_sections": [
            "executive_summary",
            "historical_valuation",
            "historical_percentiles",
            "peer_comparison",
            "macro_drivers",
            "market_expectations",
            "scenario_analysis",
            "conclusion",
        ],
        "optional_sections": ["appendix"],
        "suppress_default": [
            "business_quality",
            "portfolio_fit",
            "committee_opinion",
            "management_assessment",
        ],
        "max_length_words": 2500,
        "output_style": "valuation_note",
        "max_sections": 10,
        "max_tables": 6,
        "max_charts": 5,
    },
    "macro_intelligence_report": {
        "report_name": "Macro Intelligence Report",
        "purpose": "Macro drivers, policy, and transmission",
        "audience": "Macro desk / CIO",
        "mandatory_sections": [
            "executive_summary",
            "macro_drivers",
            "policy",
            "transmission",
            "forecast",
            "risks",
            "conclusion",
        ],
        "optional_sections": ["scenario_analysis", "appendix"],
        "suppress_default": [
            "business_quality",
            "financial_quality",
            "portfolio_fit",
            "management_assessment",
            "committee_opinion",
        ],
        "max_length_words": 2200,
        "output_style": "macro_brief",
        "max_sections": 10,
        "max_tables": 4,
        "max_charts": 4,
    },
    "portfolio_memorandum": {
        "report_name": "Portfolio Memorandum",
        "purpose": "Portfolio construction and fit",
        "audience": "Portfolio Office",
        "mandatory_sections": [
            "executive_summary",
            "portfolio_construction",
            "risk",
            "portfolio_fit",
            "recommendation",
            "conclusion",
        ],
        "optional_sections": ["valuation", "macro_drivers", "appendix"],
        "suppress_default": ["management_assessment", "accounting_quality"],
        "max_length_words": 2000,
        "output_style": "portfolio_memo",
        "max_sections": 10,
        "max_tables": 5,
        "max_charts": 3,
    },
    "investment_committee_memo": {
        "report_name": "Investment Committee Memo",
        "purpose": "Concise IC decision memo",
        "audience": "Investment Committee",
        "mandatory_sections": [
            "executive_summary",
            "investment_thesis",
            "valuation",
            "risk",
            "portfolio_fit",
            "committee_opinion",
            "cio_summary",
        ],
        "optional_sections": ["forecast", "appendix"],
        "suppress_default": ["definition", "calculation", "common_mistakes"],
        "max_length_words": 1800,
        "output_style": "committee_memo",
        "max_sections": 9,
        "max_tables": 4,
        "max_charts": 2,
    },
    "scenario_analysis": {
        "report_name": "Scenario Analysis",
        "purpose": "Bull / base / bear scenarios",
        "audience": "Forecast / Risk / CIO",
        "mandatory_sections": [
            "executive_summary",
            "scenario_analysis",
            "forecast",
            "risks",
            "valuation",
            "conclusion",
        ],
        "optional_sections": ["macro_drivers", "appendix"],
        "suppress_default": ["portfolio_fit", "committee_opinion", "definition"],
        "max_length_words": 2200,
        "output_style": "scenario_note",
        "max_sections": 9,
        "max_tables": 4,
        "max_charts": 3,
    },
    "stress_test": {
        "report_name": "Stress Test",
        "purpose": "Downside stress and resilience",
        "audience": "Risk / Portfolio Office",
        "mandatory_sections": [
            "executive_summary",
            "stress_scenarios",
            "risk",
            "financial_quality",
            "portfolio_fit",
            "conclusion",
        ],
        "optional_sections": ["macro_drivers", "appendix"],
        "suppress_default": ["investment_thesis", "committee_opinion", "management_assessment"],
        "max_length_words": 1800,
        "output_style": "stress_memo",
        "max_sections": 8,
        "max_tables": 4,
        "max_charts": 3,
    },
    "comparison_report": {
        "report_name": "Comparison Report",
        "purpose": "Head-to-head peer comparison",
        "audience": "Sector / Valuation desk",
        "mandatory_sections": [
            "executive_summary",
            "business_comparison",
            "financial_comparison",
            "competitive_position",
            "valuation_comparison",
            "historical_comparison",
            "risk_comparison",
            "conclusion",
        ],
        "optional_sections": ["appendix"],
        "suppress_default": ["portfolio_fit", "committee_opinion", "management_assessment"],
        "max_length_words": 2800,
        "output_style": "comparison_note",
        "max_sections": 10,
        "max_tables": 7,
        "max_charts": 4,
    },
    "forecast_report": {
        "report_name": "Forecast Report",
        "purpose": "Earnings and path forecasts",
        "audience": "Forecast desk / CIO",
        "mandatory_sections": [
            "executive_summary",
            "forecast",
            "macro_drivers",
            "scenario_analysis",
            "risks",
            "conclusion",
        ],
        "optional_sections": ["valuation", "appendix"],
        "suppress_default": ["portfolio_fit", "committee_opinion", "definition"],
        "max_length_words": 2000,
        "output_style": "forecast_note",
        "max_sections": 9,
        "max_tables": 4,
        "max_charts": 3,
    },
    "risk_report": {
        "report_name": "Risk Report",
        "purpose": "Risk identification and severity",
        "audience": "Risk / CIO",
        "mandatory_sections": [
            "executive_summary",
            "risk",
            "financial_quality",
            "macro_drivers",
            "stress_scenarios",
            "conclusion",
        ],
        "optional_sections": ["portfolio_fit", "appendix"],
        "suppress_default": ["investment_thesis", "committee_opinion", "definition"],
        "max_length_words": 2000,
        "output_style": "risk_memo",
        "max_sections": 9,
        "max_tables": 4,
        "max_charts": 2,
    },
    "accounting_review": {
        "report_name": "Accounting Review",
        "purpose": "Accounting quality and red flags",
        "audience": "Accounting / Financial desk",
        "mandatory_sections": [
            "executive_summary",
            "accounting_quality",
            "financial_quality",
            "risk",
            "conclusion",
        ],
        "optional_sections": ["appendix"],
        "suppress_default": [
            "portfolio_fit",
            "committee_opinion",
            "valuation",
            "management_assessment",
        ],
        "max_length_words": 1800,
        "output_style": "accounting_note",
        "max_sections": 7,
        "max_tables": 5,
        "max_charts": 2,
    },
    "management_review": {
        "report_name": "Management Review",
        "purpose": "Management quality and capital allocation",
        "audience": "Management / Business desk",
        "mandatory_sections": [
            "executive_summary",
            "management_assessment",
            "business_quality",
            "financial_quality",
            "risk",
            "conclusion",
        ],
        "optional_sections": ["appendix"],
        "suppress_default": ["portfolio_fit", "committee_opinion", "historical_percentiles"],
        "max_length_words": 1800,
        "output_style": "management_note",
        "max_sections": 8,
        "max_tables": 3,
        "max_charts": 2,
    },
    "news_brief": {
        "report_name": "News Brief",
        "purpose": "Rapid news impact briefing",
        "audience": "News desk / CIO",
        "mandatory_sections": [
            "executive_summary",
            "news_digest",
            "risk",
            "market_expectations",
            "conclusion",
        ],
        "optional_sections": ["forecast"],
        "suppress_default": [
            "portfolio_fit",
            "committee_opinion",
            "business_quality",
            "definition",
        ],
        "max_length_words": 900,
        "output_style": "news_brief",
        "max_sections": 6,
        "max_tables": 2,
        "max_charts": 1,
    },
    "educational_guide": {
        "report_name": "Educational Guide",
        "purpose": "Teach a concept clearly",
        "audience": "Learners / Academy",
        "mandatory_sections": [
            "definition",
            "importance",
            "calculation",
            "examples",
            "common_mistakes",
            "case_study",
            "summary",
        ],
        "optional_sections": [],
        "suppress_default": [
            "portfolio_fit",
            "committee_opinion",
            "forecast",
            "valuation",
            "investment_thesis",
            "cio_summary",
            "risk",
        ],
        "max_length_words": 1600,
        "output_style": "educational",
        "max_sections": 8,
        "max_tables": 2,
        "max_charts": 1,
    },
    "screening_report": {
        "report_name": "Screening Report",
        "purpose": "Screen and rank candidates",
        "audience": "Quant / Valuation desk",
        "mandatory_sections": [
            "executive_summary",
            "screening_criteria",
            "screening_results",
            "valuation",
            "risk",
            "conclusion",
        ],
        "optional_sections": ["peer_comparison", "appendix"],
        "suppress_default": ["committee_opinion", "management_assessment", "definition"],
        "max_length_words": 1600,
        "output_style": "screening_note",
        "max_sections": 8,
        "max_tables": 6,
        "max_charts": 2,
    },
    "market_open_brief": {
        "report_name": "Market Open Brief",
        "purpose": "Pre-open situational awareness",
        "audience": "Market desk / CIO",
        "mandatory_sections": [
            "executive_summary",
            "overnight_developments",
            "key_levels",
            "macro_drivers",
            "market_expectations",
            "conclusion",
        ],
        "optional_sections": ["risk"],
        "suppress_default": [
            "portfolio_fit",
            "committee_opinion",
            "business_quality",
            "financial_quality",
        ],
        "max_length_words": 800,
        "output_style": "market_brief",
        "max_sections": 7,
        "max_tables": 2,
        "max_charts": 2,
    },
    "market_close_brief": {
        "report_name": "Market Close Brief",
        "purpose": "End-of-day recap",
        "audience": "Market desk / CIO",
        "mandatory_sections": [
            "executive_summary",
            "session_recap",
            "key_levels",
            "news_digest",
            "market_expectations",
            "conclusion",
        ],
        "optional_sections": ["risk"],
        "suppress_default": [
            "portfolio_fit",
            "committee_opinion",
            "business_quality",
            "accounting_quality",
        ],
        "max_length_words": 800,
        "output_style": "market_brief",
        "max_sections": 7,
        "max_tables": 2,
        "max_charts": 2,
    },
}


def get_blueprint(report_type: str) -> dict[str, Any] | None:
    return REPORT_BLUEPRINTS.get(report_type)


def all_report_types() -> list[str]:
    return list(REPORT_BLUEPRINTS.keys())


def registry_stats() -> dict[str, Any]:
    return {
        "report_type_count": len(REPORT_BLUEPRINTS),
        "report_types": all_report_types(),
        "section_owner_defaults": len(DEFAULT_SECTION_OWNERS),
    }
