"""Evidence-backed market relationship catalog — Sprint 12.3.

Covers macro→market, market→sector, sector→market, market→company,
cross-asset, institutional flows and volatility transmission.
Every entry requires supporting historical evidence.
"""

from __future__ import annotations

from typing import Any


def _ev(
    kind: str,
    summary: str,
    *,
    period: str | None = None,
    refs: list[str] | None = None,
    weight: float = 1.0,
) -> dict[str, Any]:
    return {
        "kind": kind,
        "summary": summary,
        "period": period,
        "source_refs": refs or [],
        "weight": weight,
    }


MARKET_RELATIONSHIP_CATALOG: list[dict[str, Any]] = [
    # --- Macro → Market ---
    {
        "source": "Repo Rate",
        "target": "Market Liquidity",
        "relationship": "Easing Expands Liquidity",
        "kind": "macro_to_market",
        "direction": "Negative",
        "direction_note": "Repo ↓ historically associated with higher market liquidity",
        "evidence_strength": "High",
        "confidence_pct": 94,
        "historical_observations": 16,
        "average_lag": "1-2 Months",
        "first_observed": "2003",
        "last_confirmed": "2025",
        "chain": ["Repo Rate", "Market Liquidity", "Market Breadth", "Equity Valuation"],
        "supporting_layers": ["Historical Macro", "Historical Market"],
        "evidence": [
            _ev(
                "historical_macro",
                "RBI easing cycles expand banking and market liquidity",
                period="2003-2025",
                refs=["hmip:Repo Rate:timeline", "hmkip:liquidity"],
                weight=1.6,
            ),
            _ev(
                "historical_market",
                "HMKIP liquidity series rises after easing windows (2020, prior cycles)",
                period="2008-2025",
                refs=["hmkip:liquidity:Trading Volume Index", "cmktp:liquidity"],
                weight=1.4,
            ),
        ],
    },
    {
        "source": "Repo Rate",
        "target": "Market Breadth",
        "relationship": "Easing Broadens Participation",
        "kind": "macro_to_market",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 91,
        "historical_observations": 13,
        "average_lag": "1-3 Months",
        "first_observed": "2003",
        "last_confirmed": "2025",
        "chain": ["Repo Rate", "Market Liquidity", "Market Breadth"],
        "supporting_layers": ["Historical Macro", "Historical Market"],
        "evidence": [
            _ev(
                "historical_market",
                "Advance/decline participation improves after liquidity injections in easing cycles",
                period="2003-2021",
                refs=["hmkip:breadth:Advance Decline", "hmkip:india_equity:timeline"],
                weight=1.5,
            ),
            _ev(
                "historical_macro",
                "Repo path anchors credit availability that feeds breadth",
                period="2003-2025",
                refs=["hmip:Repo Rate:timeline"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "CPI",
        "target": "Equity Valuation",
        "relationship": "Inflation Compresses Multiples",
        "kind": "macro_to_market",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 90,
        "historical_observations": 12,
        "average_lag": "1-2 Quarters",
        "first_observed": "2013",
        "last_confirmed": "2022",
        "chain": ["CPI", "Bond Yields", "Equity Valuation", "Risk Appetite"],
        "supporting_layers": ["Historical Macro", "Historical Market"],
        "evidence": [
            _ev(
                "historical_macro",
                "CPI spikes (2013, 2022) coincide with valuation compression episodes",
                period="2013-2022",
                refs=["hmip:CPI:timeline"],
                weight=1.5,
            ),
            _ev(
                "historical_market",
                "2022 Inflation Shock marks distribution / multiple compression in HMKIP regimes",
                period="2022",
                refs=["hmkip:india_equity:2022 Inflation Shock", "cmktp:market_health"],
                weight=1.4,
            ),
        ],
    },
    {
        "source": "US Treasury Yield",
        "target": "India Equities",
        "relationship": "Global Yield Pressure on EM",
        "kind": "macro_to_market",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 89,
        "historical_observations": 11,
        "average_lag": "5-15 Trading Days",
        "first_observed": "2013",
        "last_confirmed": "2022",
        "chain": ["US Treasury Yield", "USD Index", "FII Flows", "India Equities"],
        "supporting_layers": ["Historical Macro", "Historical Market", "Cross Asset"],
        "evidence": [
            _ev(
                "historical_market",
                "2013 Taper Tantrum and 2022 inflation shock show EM equity pressure with rising US yields",
                period="2013-2022",
                refs=["hmkip:india_equity:2013 Taper Tantrum", "hmkip:institutional_flows"],
                weight=1.5,
            ),
            _ev(
                "historical_macro",
                "US yield spikes historically tighten global financial conditions for India",
                period="2013-2022",
                refs=["hmip:US Treasury Yield", "mri:US Treasury Yield"],
                weight=1.3,
            ),
        ],
    },
    # --- Market → Sector ---
    {
        "source": "Bull Market",
        "target": "Capital Goods",
        "relationship": "Early-Cycle Capex Leadership",
        "kind": "market_to_sector",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 92,
        "historical_observations": 10,
        "average_lag": "1-2 Quarters",
        "first_observed": "2003",
        "last_confirmed": "2021",
        "chain": ["Bull Market", "Capital Goods", "Banks", "Auto", "Midcaps"],
        "supporting_layers": ["Historical Market", "Historical Sector"],
        "evidence": [
            _ev(
                "historical_market",
                "2003 Bull and 2021 Recovery show capital-goods / cyclicals leading breadth expansion",
                period="2003-2021",
                refs=["hmkip:india_equity:2003 Bull Market", "hmkip:leadership"],
                weight=1.5,
            ),
            _ev(
                "historical_sector",
                "Capital Goods HSIP timelines expand with public/private capex in bull phases",
                period="2014-2025",
                refs=["hsip:capital_goods:timeline", "sri:Capital Goods"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Bull Market",
        "target": "Banks",
        "relationship": "Credit Cycle Leadership",
        "kind": "market_to_sector",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 93,
        "historical_observations": 14,
        "average_lag": "1 Quarter",
        "first_observed": "2003",
        "last_confirmed": "2021",
        "chain": ["Bull Market", "Banks", "NBFC", "Auto"],
        "supporting_layers": ["Historical Market", "Historical Sector"],
        "evidence": [
            _ev(
                "historical_sector",
                "Banking leadership coincides with bull / recovery regimes in HSIP and SRI graphs",
                period="2003-2025",
                refs=["hsip:banking:timeline", "sri:Banking"],
                weight=1.5,
            ),
            _ev(
                "historical_market",
                "HMKIP leadership history lists Banks among recovery leaders",
                period="2003-2021",
                refs=["hmkip:leadership", "cmktp:leadership"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Bear Market",
        "target": "Defensive Sectors",
        "relationship": "Flight to Defensives",
        "kind": "market_to_sector",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 90,
        "historical_observations": 9,
        "average_lag": "Immediate / 1 Month",
        "first_observed": "2008",
        "last_confirmed": "2020",
        "chain": ["Bear Market", "Defensive Sectors", "FMCG", "Pharma"],
        "supporting_layers": ["Historical Market", "Historical Sector"],
        "evidence": [
            _ev(
                "historical_market",
                "GFC and COVID crash regimes show defensive leadership in HMKIP",
                period="2008-2020",
                refs=["hmkip:india_equity:2008 GFC", "hmkip:india_equity:2020 COVID Crash"],
                weight=1.5,
            ),
            _ev(
                "historical_sector",
                "FMCG / Pharma relative resilience in stress windows",
                period="2008-2020",
                refs=["hsip:fmcg:timeline", "hsip:pharma:timeline"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Market Recovery",
        "target": "Midcaps",
        "relationship": "Risk Appetite Broadening",
        "kind": "market_to_sector",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 88,
        "historical_observations": 8,
        "average_lag": "1-3 Months",
        "first_observed": "2009",
        "last_confirmed": "2021",
        "chain": ["Market Recovery", "Large Caps", "Mid Caps", "Small Caps"],
        "supporting_layers": ["Historical Market"],
        "evidence": [
            _ev(
                "historical_market",
                "Post-crash recoveries show midcap catch-up after large-cap stabilisation",
                period="2009-2021",
                refs=["hmkip:india_equity:2021 Recovery", "hmkip:breadth"],
                weight=1.5,
            ),
            _ev(
                "research",
                "Institutional notes describe recovery rotation from large to mid/small",
                period="2009-2021",
                refs=["research:market:recovery_rotation"],
                weight=1.1,
            ),
        ],
    },
    # --- Sector → Market ---
    {
        "source": "Banking Leadership",
        "target": "Market Breadth",
        "relationship": "Banking Leadership Broadens Index",
        "kind": "sector_to_market",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 91,
        "historical_observations": 12,
        "average_lag": "2-4 Weeks",
        "first_observed": "2003",
        "last_confirmed": "2025",
        "chain": ["Banking Leadership", "Market Breadth", "Index Performance"],
        "supporting_layers": ["Historical Sector", "Historical Market"],
        "evidence": [
            _ev(
                "historical_market",
                "Breadth improves when banking leads in HMKIP / CMKTP leadership states",
                period="2003-2025",
                refs=["hmkip:breadth", "cmktp:leadership", "cmktp:breadth"],
                weight=1.5,
            ),
            _ev(
                "historical_sector",
                "Banking sector strength historically correlates with NIFTY participation",
                period="2008-2025",
                refs=["hsip:banking:timeline", "sri:Banking:NIFTY"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Banking",
        "target": "NIFTY",
        "relationship": "Index Transmission",
        "kind": "sector_to_market",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 95,
        "historical_observations": 20,
        "average_lag": "Immediate / 5 Trading Days",
        "first_observed": "2000",
        "last_confirmed": "2026",
        "chain": ["Banking", "NIFTY", "Index Performance"],
        "supporting_layers": ["Historical Sector", "Historical Market", "Research"],
        "evidence": [
            _ev(
                "historical_sector",
                "Banking weight and leadership transmit directly into NIFTY returns",
                period="2000-2026",
                refs=["hsip:banking:timeline", "sri:Banking"],
                weight=1.6,
            ),
            _ev(
                "historical_market",
                "India equity regimes in HMKIP track banking stress/recovery episodes",
                period="2008-2021",
                refs=["hmkip:india_equity:timeline"],
                weight=1.4,
            ),
        ],
    },
    # --- Market → Company ---
    {
        "source": "Market Recovery",
        "target": "RELIANCE",
        "relationship": "Large-Cap Recovery Leadership",
        "kind": "market_to_company",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 87,
        "historical_observations": 9,
        "average_lag": "Immediate / 1 Month",
        "first_observed": "2009",
        "last_confirmed": "2021",
        "chain": ["Market Recovery", "Large Caps", "RELIANCE", "Mid Caps", "Small Caps"],
        "supporting_layers": ["Historical Market", "Historical Company"],
        "evidence": [
            _ev(
                "historical_market",
                "Recovery regimes historically start with large-cap liquidity magnets",
                period="2009-2021",
                refs=["hmkip:india_equity:2021 Recovery", "hmkip:liquidity"],
                weight=1.4,
            ),
            _ev(
                "historical_company",
                "RELIANCE appears among early recovery large-cap leadership sets",
                period="2009-2021",
                refs=["company:RELIANCE", "cskp:oil_gas"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "Market Recovery",
        "target": "HDFCBANK",
        "relationship": "Banking Large-Cap Transmission",
        "kind": "market_to_company",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 90,
        "historical_observations": 11,
        "average_lag": "1-4 Weeks",
        "first_observed": "2009",
        "last_confirmed": "2021",
        "chain": ["Market Recovery", "Banking Sector", "HDFCBANK"],
        "supporting_layers": ["Historical Market", "Historical Sector", "Historical Company"],
        "evidence": [
            _ev(
                "historical_sector",
                "Private bank leaders transmit recovery into index and breadth",
                period="2009-2025",
                refs=["hsip:banking:timeline", "sri:Banking:HDFCBANK"],
                weight=1.5,
            ),
            _ev(
                "historical_market",
                "HMKIP recovery windows coincide with banking leadership",
                period="2009-2021",
                refs=["hmkip:leadership", "hmkip:india_equity:2021 Recovery"],
                weight=1.3,
            ),
        ],
    },
    # --- Cross Asset ---
    {
        "source": "US Treasury Yield",
        "target": "USD Index",
        "relationship": "Yield Support for USD",
        "kind": "cross_asset",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 92,
        "historical_observations": 15,
        "average_lag": "Immediate / 5 Trading Days",
        "first_observed": "2008",
        "last_confirmed": "2022",
        "chain": ["US Treasury Yield", "USD Index", "Gold", "Emerging Markets", "India Equities"],
        "supporting_layers": ["Historical Macro", "Historical Market", "Cross Asset"],
        "evidence": [
            _ev(
                "historical_macro",
                "Rising US yields historically support USD strength",
                period="2008-2022",
                refs=["hmip:US Treasury Yield", "mri:US Treasury Yield"],
                weight=1.5,
            ),
            _ev(
                "historical_market",
                "HMKIP cross-asset state marks USD strong in taper / inflation shocks",
                period="2013-2022",
                refs=["hmkip:cross_asset", "cmktp:cross_asset"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "USD Index",
        "target": "Gold",
        "relationship": "USD Strength Pressures Gold",
        "kind": "cross_asset",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 88,
        "historical_observations": 14,
        "average_lag": "5 Trading Days",
        "first_observed": "2008",
        "last_confirmed": "2022",
        "chain": ["USD Index", "Gold", "Commodities"],
        "supporting_layers": ["Historical Market", "Cross Asset"],
        "evidence": [
            _ev(
                "historical_market",
                "Cross-asset history shows gold bid when USD soft / risk-off, pressure when USD strong",
                period="2008-2022",
                refs=["hmkip:cross_asset", "cmktp:cross_asset"],
                weight=1.4,
            ),
            _ev(
                "research",
                "Institutional cross-asset notes document inverse USD–gold episodes",
                period="2010-2022",
                refs=["research:cross_asset:usd_gold"],
                weight=1.1,
            ),
        ],
    },
    {
        "source": "USD Index",
        "target": "India Equities",
        "relationship": "Strong USD Pressures EM Equities",
        "kind": "cross_asset",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 90,
        "historical_observations": 12,
        "average_lag": "5-10 Trading Days",
        "first_observed": "2013",
        "last_confirmed": "2022",
        "chain": ["USD Index", "FII Flows", "India Equities"],
        "supporting_layers": ["Historical Market", "Historical Macro"],
        "evidence": [
            _ev(
                "historical_market",
                "Taper Tantrum and 2022 inflation shock show India equity stress with strong USD",
                period="2013-2022",
                refs=["hmkip:india_equity:2013 Taper Tantrum", "hmkip:cross_asset"],
                weight=1.5,
            ),
            _ev(
                "historical_macro",
                "USDINR / DXY pressure windows coincide with EM risk-off",
                period="2013-2022",
                refs=["hmip:USDINR:timeline"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Oil",
        "target": "Market Leadership",
        "relationship": "Energy Shock Rotates Leadership",
        "kind": "cross_asset",
        "direction": "Mixed",
        "evidence_strength": "High",
        "confidence_pct": 86,
        "historical_observations": 10,
        "average_lag": "2-6 Weeks",
        "first_observed": "2008",
        "last_confirmed": "2022",
        "chain": ["Oil", "Energy", "Banks", "Market Leadership"],
        "supporting_layers": ["Historical Market", "Historical Sector"],
        "evidence": [
            _ev(
                "historical_market",
                "2022 Inflation Shock leadership tips Energy / Banks / Commodities",
                period="2022",
                refs=["hmkip:leadership", "hmkip:india_equity:2022 Inflation Shock"],
                weight=1.5,
            ),
            _ev(
                "historical_sector",
                "Oil & Gas HSIP timelines track energy-crisis leadership windows",
                period="2008-2022",
                refs=["hsip:oil_gas:timeline"],
                weight=1.2,
            ),
        ],
    },
    # --- Institutional Flows ---
    {
        "source": "FII Buying",
        "target": "Market Liquidity",
        "relationship": "Foreign Inflows Add Liquidity",
        "kind": "flows",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 93,
        "historical_observations": 18,
        "average_lag": "Immediate / 5 Trading Days",
        "first_observed": "2003",
        "last_confirmed": "2025",
        "chain": ["FII Buying", "Liquidity", "Market Breadth", "Large Cap Leadership"],
        "supporting_layers": ["Historical Market", "Research"],
        "evidence": [
            _ev(
                "historical_market",
                "HMKIP flow history links FII inflow tone to liquidity and breadth improvement",
                period="2003-2025",
                refs=["hmkip:institutional_flows", "hmkip:liquidity", "cmktp:flows"],
                weight=1.6,
            ),
            _ev(
                "research",
                "Institutional flow notes document FII buying as liquidity impulse",
                period="2010-2025",
                refs=["research:flows:fii"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "FII Buying",
        "target": "Market Breadth",
        "relationship": "Inflows Broaden Participation",
        "kind": "flows",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 90,
        "historical_observations": 15,
        "average_lag": "5 Trading Days",
        "first_observed": "2003",
        "last_confirmed": "2025",
        "chain": ["FII Buying", "Liquidity", "Market Breadth", "Large Cap Leadership"],
        "supporting_layers": ["Historical Market"],
        "evidence": [
            _ev(
                "historical_market",
                "Positive FII episodes historically coincide with improving advance/decline",
                period="2003-2025",
                refs=["hmkip:institutional_flows", "hmkip:breadth"],
                weight=1.5,
            ),
            _ev(
                "historical_market",
                "COVID FII selling episode shows inverse — outflow with breadth collapse",
                period="2020",
                refs=["hmkip:institutional_flows:COVID FII selling", "hmkip:breadth"],
                weight=1.4,
            ),
        ],
    },
    {
        "source": "FII Selling",
        "target": "Large Cap Leadership",
        "relationship": "Outflows Concentrate Leadership",
        "kind": "flows",
        "direction": "Mixed",
        "evidence_strength": "Medium",
        "confidence_pct": 84,
        "historical_observations": 10,
        "average_lag": "1-2 Weeks",
        "first_observed": "2013",
        "last_confirmed": "2022",
        "chain": ["FII Selling", "Liquidity Stress", "Large Cap Leadership", "Midcap Underperformance"],
        "supporting_layers": ["Historical Market"],
        "evidence": [
            _ev(
                "historical_market",
                "Taper and inflation flow-stress episodes show large-cap relative resilience vs mid/small",
                period="2013-2022",
                refs=["hmkip:institutional_flows:FII taper episode", "hmkip:leadership"],
                weight=1.4,
            ),
            _ev(
                "research",
                "Flow research notes large-cap preference during FII selling",
                period="2013-2022",
                refs=["research:flows:fii_selling"],
                weight=1.1,
            ),
        ],
        "contradictory_evidence": [
            "DII cushion eras (2023+) can partially offset FII selling impact on breadth",
        ],
    },
    {
        "source": "DII Buying",
        "target": "Market Breadth",
        "relationship": "Domestic Cushion Supports Breadth",
        "kind": "flows",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 87,
        "historical_observations": 8,
        "average_lag": "1-4 Weeks",
        "first_observed": "2020",
        "last_confirmed": "2026",
        "chain": ["DII Buying", "Liquidity", "Market Breadth"],
        "supporting_layers": ["Historical Market", "Research"],
        "evidence": [
            _ev(
                "historical_market",
                "DII cushion era in HMKIP coincides with more resilient domestic breadth",
                period="2023-2026",
                refs=["hmkip:institutional_flows:DII cushion era", "hmkip:breadth"],
                weight=1.4,
            ),
            _ev(
                "research",
                "SIP / mutual-fund flow research documents domestic bid under FII volatility",
                period="2020-2026",
                refs=["research:flows:dii"],
                weight=1.2,
            ),
        ],
    },
    # --- Volatility ---
    {
        "source": "India VIX",
        "target": "Risk Appetite",
        "relationship": "Vol Spike Suppresses Risk Appetite",
        "kind": "volatility",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 95,
        "historical_observations": 21,
        "average_lag": "Immediate / 5 Trading Days",
        "first_observed": "2008",
        "last_confirmed": "2022",
        "chain": ["India VIX", "Risk Appetite", "Small Caps", "Defensive Sectors"],
        "supporting_layers": ["Historical Market", "Research"],
        "evidence": [
            _ev(
                "historical_market",
                "GFC / COVID vol spikes in HMKIP coincide with risk-off and breadth collapse",
                period="2008-2020",
                refs=["hmkip:volatility:GFC vol spike", "hmkip:volatility:COVID vol spike", "cmktp:risk_sentiment"],
                weight=1.7,
            ),
            _ev(
                "research",
                "Volatility regime research links India VIX spikes to risk appetite compression",
                period="2008-2022",
                refs=["research:volatility:india_vix"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "India VIX",
        "target": "Small Cap Index",
        "relationship": "Inverse Risk Transmission",
        "kind": "volatility",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 94,
        "historical_observations": 21,
        "average_lag": "5 Trading Days",
        "first_observed": "2008",
        "last_confirmed": "2022",
        "chain": ["India VIX", "Risk Appetite", "Small Cap Index", "Defensive Sectors"],
        "supporting_layers": ["Historical Market"],
        "evidence": [
            _ev(
                "historical_market",
                "Small/mid underperform during elevated realised-vol regimes in HMKIP",
                period="2008-2022",
                refs=["hmkip:volatility", "hmkip:leadership", "hmkip:breadth"],
                weight=1.6,
            ),
            _ev(
                "historical_market",
                "Vol compression eras show improved small-cap relative participation",
                period="2023-2026",
                refs=["hmkip:volatility:Vol compression", "hmkip:breadth"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "India VIX",
        "target": "Defensive Sectors",
        "relationship": "Vol Spike Favours Defensives",
        "kind": "volatility",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 89,
        "historical_observations": 12,
        "average_lag": "Immediate / 2 Weeks",
        "first_observed": "2008",
        "last_confirmed": "2020",
        "chain": ["India VIX", "Risk Appetite", "Defensive Sectors"],
        "supporting_layers": ["Historical Market", "Historical Sector"],
        "evidence": [
            _ev(
                "historical_market",
                "Crash / vol-spike regimes list Defensives among leaders",
                period="2008-2020",
                refs=["hmkip:leadership", "hmkip:volatility"],
                weight=1.4,
            ),
            _ev(
                "historical_sector",
                "FMCG / Pharma relative resilience in stress windows",
                period="2008-2020",
                refs=["hsip:fmcg:timeline", "hsip:pharma:timeline"],
                weight=1.3,
            ),
        ],
    },
    # --- Leading indicators / correction precursors ---
    {
        "source": "Market Breadth Deterioration",
        "target": "Correction Risk",
        "relationship": "Narrowing Breadth Precedes Corrections",
        "kind": "macro_to_market",
        "direction": "Positive",
        "direction_note": "Breadth deterioration historically precedes corrective regimes",
        "evidence_strength": "High",
        "confidence_pct": 88,
        "historical_observations": 10,
        "average_lag": "2-8 Weeks",
        "first_observed": "2000",
        "last_confirmed": "2022",
        "chain": ["Market Breadth Deterioration", "Liquidity Stress", "Correction Risk"],
        "supporting_layers": ["Historical Market", "Research"],
        "evidence": [
            _ev(
                "historical_market",
                "Breadth collapse precedes COVID crash and other corrective episodes in HMKIP",
                period="2000-2022",
                refs=["hmkip:breadth", "hmkip:india_equity:timeline"],
                weight=1.5,
            ),
            _ev(
                "research",
                "Market structure research treats deteriorating A/D as a leading caution signal",
                period="2000-2022",
                refs=["research:market:breadth_leading"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "Bond Yields",
        "target": "Equities",
        "relationship": "Rising Yields Pressure Equities",
        "kind": "cross_asset",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 91,
        "historical_observations": 14,
        "average_lag": "5-15 Trading Days",
        "first_observed": "2013",
        "last_confirmed": "2022",
        "chain": ["Bond Yields", "Discount Rates", "Equity Valuation", "Equities"],
        "supporting_layers": ["Historical Macro", "Historical Market"],
        "evidence": [
            _ev(
                "historical_macro",
                "Yield spikes tighten discount rates and compress equity multiples",
                period="2013-2022",
                refs=["hmip:US Treasury Yield", "hmip:CPI:timeline"],
                weight=1.5,
            ),
            _ev(
                "historical_market",
                "2013 / 2022 HMKIP regimes show equity stress with rising yields",
                period="2013-2022",
                refs=["hmkip:india_equity:2013 Taper Tantrum", "hmkip:india_equity:2022 Inflation Shock"],
                weight=1.4,
            ),
        ],
    },
    {
        "source": "FII Flows",
        "target": "Banks",
        "relationship": "Foreign Flows Hit Financials First",
        "kind": "flows",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 89,
        "historical_observations": 13,
        "average_lag": "1-3 Weeks",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["FII Flows", "Banks", "NIFTY", "Market Breadth"],
        "supporting_layers": ["Historical Market", "Historical Sector"],
        "evidence": [
            _ev(
                "historical_market",
                "Institutional flow episodes transmit quickly into banking and index leadership",
                period="2008-2025",
                refs=["hmkip:institutional_flows", "hmkip:leadership"],
                weight=1.4,
            ),
            _ev(
                "historical_sector",
                "Banking sector relative performance tracks FII risk-on/off windows",
                period="2008-2025",
                refs=["hsip:banking:timeline", "sri:Banking"],
                weight=1.3,
            ),
        ],
    },
]


def all_catalog_entries() -> list[dict[str, Any]]:
    return list(MARKET_RELATIONSHIP_CATALOG)
