"""Institutional sector catalog — leaders, drivers, risks, macro sensitivity."""

from __future__ import annotations

from typing import Any

from continuous_sector_knowledge.schema import SECTOR_UNIVERSE

# Seeded institutional tips. Soft-overlaid from company/macro/market/event layers at build time.
SECTOR_CATALOG: dict[str, dict[str, Any]] = {
    "banking": {
        "label": "Banking",
        "leaders": ["HDFCBANK", "ICICIBANK", "SBIN", "AXISBANK", "KOTAKBANK"],
        "growth_drivers": ["Credit growth", "Liability franchise", "Fee income", "Digital adoption"],
        "key_risks": ["NIM compression", "Asset quality", "Deposit competition", "Unsecured stress"],
        "government_policy": ["RBI monetary policy", "Priority sector lending", "Capital norms"],
        "macro_sensitivity": {
            "Repo Rate": "High",
            "Liquidity": "High",
            "GDP": "Medium",
            "Inflation": "Medium",
        },
        "valuation_note": "Premium for private banks; PSU discount persists",
        "market_share_notes": ["Private banks gaining credit share vs PSUs"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Stable",
        "group": "Financials",
    },
    "financial_services": {
        "label": "Financial Services",
        "leaders": ["BAJFINANCE", "HDFCAMC", "SBILIFE"],
        "growth_drivers": ["Financialisation", "AUM growth", "Protection demand"],
        "key_risks": ["Market volatility", "Regulatory changes", "Credit costs"],
        "government_policy": ["SEBI / IRDAI / RBI frameworks"],
        "macro_sensitivity": {"Liquidity": "High", "Repo Rate": "Medium", "GDP": "Medium"},
        "valuation_note": "Growth premium varies by sub-segment",
        "market_share_notes": ["Diversified NBFCs and AMCs lead flows"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Stable",
        "group": "Financials",
    },
    "nbfc": {
        "label": "NBFC",
        "leaders": ["BAJFINANCE", "CHOLAFIN", "SHRIRAMFIN"],
        "growth_drivers": ["Retail credit", "Vehicle finance", "SME lending"],
        "key_risks": ["Funding costs", "Asset-liability mismatch", "Regulatory tightening"],
        "government_policy": ["RBI scale-based regulation"],
        "macro_sensitivity": {"Repo Rate": "High", "Liquidity": "High", "GDP": "Medium"},
        "valuation_note": "Funding-quality differential drives multiples",
        "market_share_notes": ["Top NBFCs consolidate share in retail credit"],
        "default_outlook": "Neutral",
        "revenue_trend": "Stable",
        "margin_trend": "Mixed",
        "group": "Financials",
    },
    "insurance": {
        "label": "Insurance",
        "leaders": ["SBILIFE", "HDFCLIFE", "ICICIPRULI"],
        "growth_drivers": ["Protection gap", "Annuity demand", "Bancassurance"],
        "key_risks": ["Persistency", "VNB margins", "Equity market beta"],
        "government_policy": ["IRDAI product / capital rules"],
        "macro_sensitivity": {"GDP": "Medium", "Inflation": "Low", "Liquidity": "Medium"},
        "valuation_note": "Embedded value / VNB multiples",
        "market_share_notes": ["Private life insurers gaining vs LIC in new business"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Stable",
        "group": "Financials",
    },
    "it_services": {
        "label": "IT Services",
        "leaders": ["TCS", "INFY", "HCLTECH", "WIPRO", "TECHM"],
        "growth_drivers": ["Enterprise digital", "Cloud", "AI services", "Cost takeout deals"],
        "key_risks": ["US discretionary spend", "Pricing pressure", "Visa / talent", "FX translation"],
        "government_policy": ["Digital India", "Data protection"],
        "macro_sensitivity": {"USDINR": "High", "US GDP": "High", "Repo Rate": "Low"},
        "valuation_note": "Quality premium vs historical mid-cycle",
        "market_share_notes": ["Tier-1 Indian IT retains large-deal share"],
        "default_outlook": "Neutral",
        "revenue_trend": "Stable",
        "margin_trend": "Stable",
        "group": "Technology",
    },
    "software_products": {
        "label": "Software Products",
        "leaders": ["PERSISTENT", "COFORGE", "LTIM"],
        "growth_drivers": ["Product engineering", "SaaS platforms", "AI tooling"],
        "key_risks": ["Deal concentration", "Global tech budgets"],
        "government_policy": ["Startup / digital public infrastructure"],
        "macro_sensitivity": {"USDINR": "High", "US GDP": "High"},
        "valuation_note": "Growth multiples sensitive to bookings",
        "market_share_notes": ["Mid-tier engineers gaining niche share"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Stable",
        "group": "Technology",
    },
    "pharma": {
        "label": "Pharma",
        "leaders": ["SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB"],
        "growth_drivers": ["US generics", "Specialty", "API / CDMO", "Domestic formulations"],
        "key_risks": ["FDA observations", "Price erosion", "API cost inflation"],
        "government_policy": ["Drug pricing", "PLI for API"],
        "macro_sensitivity": {"USDINR": "Medium", "Inflation": "Medium"},
        "valuation_note": "Specialty mix commands premium",
        "market_share_notes": ["Large-cap Indian pharma leads US ANDA filings"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Stable",
        "group": "Healthcare",
    },
    "healthcare": {
        "label": "Healthcare",
        "leaders": ["APOLLOHOSP", "MAXHEALTH", "FORTIS"],
        "growth_drivers": ["Hospital capacity", "Diagnostics", "Medical tourism"],
        "key_risks": ["Capex intensity", "Talent costs", "Regulatory tariffs"],
        "government_policy": ["Ayushman Bharat", "Health infra"],
        "macro_sensitivity": {"GDP": "Medium", "Inflation": "Medium"},
        "valuation_note": "Hospital EV/EBITDA elevated vs history",
        "market_share_notes": ["Organised chains gaining vs unorganised"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Improving",
        "group": "Healthcare",
    },
    "fmcg": {
        "label": "FMCG",
        "leaders": ["HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA"],
        "growth_drivers": ["Rural recovery", "Premiumisation", "Distribution reach"],
        "key_risks": ["Input cost inflation", "Volume softness", "Competition"],
        "government_policy": ["GST on staples", "Rural schemes"],
        "macro_sensitivity": {"CPI": "High", "GDP": "Medium", "Rural demand": "High"},
        "valuation_note": "Quality staples trade at premium multiples",
        "market_share_notes": ["HUL / ITC dominate urban + rural shelves"],
        "default_outlook": "Neutral",
        "revenue_trend": "Stable",
        "margin_trend": "Mixed",
        "group": "Consumer",
    },
    "retail": {
        "label": "Retail",
        "leaders": ["DMART", "TRENT", "RELIANCE"],
        "growth_drivers": ["Store expansion", "Private label", "Omnichannel"],
        "key_risks": ["Same-store sales", "Real estate costs", "Competition"],
        "government_policy": ["FDI in retail", "GST"],
        "macro_sensitivity": {"GDP": "High", "Inflation": "Medium", "Liquidity": "Medium"},
        "valuation_note": "Growth retailers command high multiples",
        "market_share_notes": ["Organised retail share rising steadily"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Stable",
        "group": "Consumer",
    },
    "auto": {
        "label": "Auto",
        "leaders": ["MARUTI", "M&M", "TATAMOTORS", "BAJAJ-AUTO"],
        "growth_drivers": ["PV demand", "SUV mix", "EV transition", "Exports"],
        "key_risks": ["Commodity costs", "Rate-sensitive demand", "EV disruption"],
        "government_policy": ["FAME / EV PLI", "Emission norms"],
        "macro_sensitivity": {"Repo Rate": "High", "GDP": "High", "CPI": "Medium"},
        "valuation_note": "Cyclical multiples; EV optionality premium",
        "market_share_notes": ["Maruti leads PV; M&M strong in UV / tractor"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Stable",
        "group": "Industrials",
    },
    "auto_ancillary": {
        "label": "Auto Ancillary",
        "leaders": ["MOTHERSON", "BOSCHLTD", "BHARATFORG"],
        "growth_drivers": ["OEM volumes", "Content per vehicle", "Export platforms"],
        "key_risks": ["OEM concentration", "Raw material volatility"],
        "government_policy": ["Auto PLI", " localisation"],
        "macro_sensitivity": {"GDP": "High", "Repo Rate": "Medium"},
        "valuation_note": "Content-growth stories preferred",
        "market_share_notes": ["Tier-1 suppliers consolidate platforms"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Stable",
        "group": "Industrials",
    },
    "capital_goods": {
        "label": "Capital Goods",
        "leaders": ["LT", "SIEMENS", "ABB", "BHEL"],
        "growth_drivers": ["Public capex", "Private investment", "Power T&D", "Industrial automation"],
        "key_risks": ["Order delays", "Working capital", "Execution"],
        "government_policy": ["Capex thrust", "Make in India"],
        "macro_sensitivity": {"GDP": "High", "Fiscal": "High", "Repo Rate": "Medium"},
        "valuation_note": "Order-book visibility supports premiums",
        "market_share_notes": ["L&T leads large infra / industrial orders"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Improving",
        "group": "Industrials",
    },
    "industrials": {
        "label": "Industrials",
        "leaders": ["LT", "ADANIENT", "SIEMENS"],
        "growth_drivers": ["Infra cycle", "Manufacturing PLI", "Exports"],
        "key_risks": ["Cycle downturn", "Commodity costs"],
        "government_policy": ["PLI schemes", "Infra pipeline"],
        "macro_sensitivity": {"GDP": "High", "IIP": "High"},
        "valuation_note": "Conglomerate / industrial mix discounts vary",
        "market_share_notes": ["Diversified industrials span multiple end-markets"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Stable",
        "group": "Industrials",
    },
    "cement": {
        "label": "Cement",
        "leaders": ["ULTRACEMCO", "AMBUJACEM", "SHREECEM"],
        "growth_drivers": ["Housing", "Infra demand", "Capacity additions"],
        "key_risks": ["Pricing discipline", "Fuel costs", "Overcapacity"],
        "government_policy": ["Infra / housing schemes"],
        "macro_sensitivity": {"GDP": "High", "Infrastructure spend": "High"},
        "valuation_note": "EV/tonne sensitive to utilisation",
        "market_share_notes": ["Top 3 control large all-India capacity share"],
        "default_outlook": "Neutral",
        "revenue_trend": "Stable",
        "margin_trend": "Mixed",
        "group": "Materials",
    },
    "metals": {
        "label": "Metals",
        "leaders": ["TATASTEEL", "JSWSTEEL", "HINDALCO", "VEDL"],
        "growth_drivers": ["Domestic steel demand", "Global spreads", "Aluminium"],
        "key_risks": ["Commodity price swings", "China demand", "Energy costs"],
        "government_policy": ["Import duties", "Infra steel demand"],
        "macro_sensitivity": {"Global growth": "High", "USDINR": "Medium"},
        "valuation_note": "Deeply cyclical multiples",
        "market_share_notes": ["Integrated steel majors dominate flat products"],
        "default_outlook": "Neutral",
        "revenue_trend": "Mixed",
        "margin_trend": "Mixed",
        "group": "Materials",
    },
    "mining": {
        "label": "Mining",
        "leaders": ["COALINDIA", "NMDC", "VEDL"],
        "growth_drivers": ["Coal volumes", "Iron ore", "Critical minerals"],
        "key_risks": ["Commodity prices", "ESG / environmental clearances"],
        "government_policy": ["Auction regime", "Commercial mining"],
        "macro_sensitivity": {"Global growth": "High", "Energy prices": "High"},
        "valuation_note": "Volume / realisation driven",
        "market_share_notes": ["PSU miners dominate bulk commodities"],
        "default_outlook": "Neutral",
        "revenue_trend": "Stable",
        "margin_trend": "Mixed",
        "group": "Materials",
    },
    "oil_gas": {
        "label": "Oil & Gas",
        "leaders": ["RELIANCE", "ONGC", "IOC", "BPCL"],
        "growth_drivers": ["Refining margins", "Marketing", "Gas / petrochem", "O2C integration"],
        "key_risks": ["Crude volatility", "Marketing margins", "Geopolitics"],
        "government_policy": ["Fuel pricing", "Gas reforms", "Strategic reserves"],
        "macro_sensitivity": {"Crude Oil": "High", "USDINR": "High", "Inflation": "Medium"},
        "valuation_note": "Conglomerate / refining cycle mix",
        "market_share_notes": ["OMC + RIL dominate downstream"],
        "default_outlook": "Neutral",
        "revenue_trend": "Mixed",
        "margin_trend": "Mixed",
        "group": "Energy",
    },
    "chemicals": {
        "label": "Chemicals",
        "leaders": ["PIDILITIND", "SRF", "UPL"],
        "growth_drivers": ["Specialty shift", "China+1", "Agchem"],
        "key_risks": ["Input costs", "Global demand", "Regulatory"],
        "government_policy": ["PLI chemicals", "Environment norms"],
        "macro_sensitivity": {"Global growth": "High", "USDINR": "Medium"},
        "valuation_note": "Specialty > commodity multiples",
        "market_share_notes": ["Specialty players gaining export share"],
        "default_outlook": "Positive",
        "revenue_trend": "Stable",
        "margin_trend": "Stable",
        "group": "Materials",
    },
    "specialty_chemicals": {
        "label": "Specialty Chemicals",
        "leaders": ["SRF", "NAVINFLUOR", "CLEAN"],
        "growth_drivers": ["Fluorochemicals", "CDMO", "Import substitution"],
        "key_risks": ["Customer concentration", "Capex timing", "Global inventory"],
        "government_policy": ["PLI / China+1 industrial policy"],
        "macro_sensitivity": {"Global growth": "High", "USDINR": "Medium"},
        "valuation_note": "High growth premiums when utilisation rises",
        "market_share_notes": ["Niche leaders in fluorines / agro intermediates"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Stable",
        "group": "Materials",
    },
    "defence": {
        "label": "Defence",
        "leaders": ["HAL", "BEL", "MAZDOCK", "BDL"],
        "growth_drivers": ["Indigenisation", "Export orders", "Capex pipeline"],
        "key_risks": ["Order timing", "Execution", "Working capital"],
        "government_policy": ["Atmanirbhar defence", "Positive indigenisation lists"],
        "macro_sensitivity": {"Fiscal": "High", "GDP": "Low"},
        "valuation_note": "Order-book visibility supports elevated multiples",
        "market_share_notes": ["DPSUs dominate platforms; private share rising"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Improving",
        "group": "Industrials",
    },
    "power": {
        "label": "Power",
        "leaders": ["NTPC", "POWERGRID", "TATAPOWER"],
        "growth_drivers": ["Capacity additions", "T&D", "RE transition"],
        "key_risks": ["Discom stress", "Fuel availability", "Tariff regulation"],
        "government_policy": ["National Electricity Plan", "RE targets"],
        "macro_sensitivity": {"GDP": "Medium", "Fiscal": "Medium"},
        "valuation_note": "Regulated utilities vs merchant / RE mix",
        "market_share_notes": ["NTPC / PGCIL anchor generation and transmission"],
        "default_outlook": "Neutral",
        "revenue_trend": "Stable",
        "margin_trend": "Stable",
        "group": "Utilities",
    },
    "utilities": {
        "label": "Utilities",
        "leaders": ["POWERGRID", "NTPC", "GAIL"],
        "growth_drivers": ["Regulated returns", "Network expansion"],
        "key_risks": ["Regulatory lag", "Capex funding"],
        "government_policy": ["Tariff frameworks"],
        "macro_sensitivity": {"Inflation": "Medium", "Fiscal": "Medium"},
        "valuation_note": "Bond-proxy characteristics",
        "market_share_notes": ["Natural monopolies by geography / network"],
        "default_outlook": "Neutral",
        "revenue_trend": "Stable",
        "margin_trend": "Stable",
        "group": "Utilities",
    },
    "renewable_energy": {
        "label": "Renewable Energy",
        "leaders": ["ADANIGREEN", "TATAPOWER", "NTPC"],
        "growth_drivers": ["Solar / wind capacity", "Green hydrogen optionality", "Storage"],
        "key_risks": ["Execution", "Module costs", "PPA tariffs"],
        "government_policy": ["500 GW RE target", "Green hydrogen mission"],
        "macro_sensitivity": {"Fiscal": "Medium", "Global rates": "Medium"},
        "valuation_note": "Growth / NAV frameworks",
        "market_share_notes": ["Adani / Tata / NTPC scale RE portfolios"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Stable",
        "group": "Utilities",
    },
    "telecom": {
        "label": "Telecom",
        "leaders": ["BHARTIARTL", "RJIO", "IDEA"],
        "growth_drivers": ["ARPU repair", "5G monetisation", "Enterprise"],
        "key_risks": ["Capex intensity", "Competition", "Spectrum liabilities"],
        "government_policy": ["Spectrum auctions", "AGR legacy"],
        "macro_sensitivity": {"GDP": "Medium", "Inflation": "Low"},
        "valuation_note": "ARPU / subscriber trajectory drives multiples",
        "market_share_notes": ["Duopoly-plus structure; Jio / Airtel lead"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Improving",
        "group": "Communication",
    },
    "infrastructure": {
        "label": "Infrastructure",
        "leaders": ["LT", "IRB", "ADANIPORTS"],
        "growth_drivers": ["Roads", "Ports", "Airports", "Urban infra"],
        "key_risks": ["Execution", "Funding", "Land / clearances"],
        "government_policy": ["NIP", "Gati Shakti"],
        "macro_sensitivity": {"Fiscal": "High", "GDP": "High"},
        "valuation_note": "Asset / order-book frameworks",
        "market_share_notes": ["EPC + asset owners split value chain"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Stable",
        "group": "Industrials",
    },
    "real_estate": {
        "label": "Real Estate",
        "leaders": ["DLF", "GODREJPROP", "OBEROIRLTY", "PRESTIGE"],
        "growth_drivers": ["Housing demand", "Office leasing", "Premium launches"],
        "key_risks": ["Rate sensitivity", "Inventory", "Regulatory"],
        "government_policy": ["RERA", "Affordable housing incentives"],
        "macro_sensitivity": {"Repo Rate": "High", "Liquidity": "High", "GDP": "Medium"},
        "valuation_note": "NAV / pre-sales growth",
        "market_share_notes": ["Listed developers gaining share in top cities"],
        "default_outlook": "Neutral",
        "revenue_trend": "Stable",
        "margin_trend": "Stable",
        "group": "Real Estate",
    },
    "aviation": {
        "label": "Aviation",
        "leaders": ["INDIGO", "AIRINDIA"],
        "growth_drivers": ["Traffic recovery", "Fleet expansion", "International"],
        "key_risks": ["ATF costs", "FX", "Competition", "Airport charges"],
        "government_policy": ["UDAN", "Airport privatisation"],
        "macro_sensitivity": {"Crude Oil": "High", "USDINR": "High", "GDP": "High"},
        "valuation_note": "Traffic / yield / cost per ASK frameworks",
        "market_share_notes": ["IndiGo dominates domestic ASKs"],
        "default_outlook": "Neutral",
        "revenue_trend": "Improving",
        "margin_trend": "Mixed",
        "group": "Industrials",
    },
    "logistics": {
        "label": "Logistics",
        "leaders": ["CONCOR", "TCI", "DELHIVERY"],
        "growth_drivers": ["Formalisation", "E-commerce", "Multimodal"],
        "key_risks": ["Fuel costs", "Utilisation", "Fragmentation"],
        "government_policy": ["National Logistics Policy", "Gati Shakti"],
        "macro_sensitivity": {"GDP": "High", "Crude Oil": "Medium"},
        "valuation_note": "Volume growth vs asset intensity",
        "market_share_notes": ["Organised players gaining vs unorganised"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Stable",
        "group": "Industrials",
    },
    "textiles": {
        "label": "Textiles",
        "leaders": ["PAGEIND", "KPRMILL", "TRIDENT"],
        "growth_drivers": ["Exports", "Domestic brands", "Cotton cycle"],
        "key_risks": ["Global demand", "Cotton prices", "Competition"],
        "government_policy": ["PLI textiles", "RoDTEP"],
        "macro_sensitivity": {"USDINR": "High", "Global growth": "High"},
        "valuation_note": "Brand / export mix differentials",
        "market_share_notes": ["Branded apparel outgrowing commodity textiles"],
        "default_outlook": "Neutral",
        "revenue_trend": "Stable",
        "margin_trend": "Mixed",
        "group": "Consumer",
    },
    "consumer_durables": {
        "label": "Consumer Durables",
        "leaders": ["TITAN", "DIXON", "VOLTAS", "HAVELLS"],
        "growth_drivers": ["Premiumisation", "Housing cycle", "Electronics manufacturing"],
        "key_risks": ["Input costs", "Competition", "Channel inventory"],
        "government_policy": ["PLI electronics", "BIS norms"],
        "macro_sensitivity": {"GDP": "High", "Repo Rate": "Medium", "CPI": "Medium"},
        "valuation_note": "Brand / EMS growth premiums",
        "market_share_notes": ["Organised brands gaining vs unorganised"],
        "default_outlook": "Positive",
        "revenue_trend": "Improving",
        "margin_trend": "Stable",
        "group": "Consumer",
    },
}


def assert_catalog_complete() -> None:
    missing = [s for s in SECTOR_UNIVERSE if s not in SECTOR_CATALOG]
    if missing:
        raise RuntimeError(f"SECTOR_CATALOG missing: {missing}")


def all_sector_keys() -> list[str]:
    return list(SECTOR_UNIVERSE)


def get_catalog(sector_key: str) -> dict[str, Any]:
    return dict(SECTOR_CATALOG.get(sector_key) or {})
