"""Layer registry — purpose, I/O, cost, never-answers."""

from __future__ import annotations

from typing import Any

from layer_router.schema import REGISTERED_LAYERS

LAYER_DEFS: dict[str, dict[str, Any]] = {
    "FIL": {
        "purpose": "Extract evidence from official filings",
        "answers": ["Financial facts", "Management guidance", "Risks", "Capital allocation"],
        "never": ["Portfolio", "Macro", "Valuation"],
        "inputs": ["Filings", "Ticker"],
        "outputs": ["Filing Evidence"],
        "dependencies": [],
        "cost_units": 8,
        "latency_ms": 120,
        "confidence_contribution": 0.18,
        "parallel_group": "A",
    },
    "FDI": {
        "purpose": "Diff filings across periods",
        "answers": ["What changed in filings"],
        "never": ["Portfolio sizing"],
        "inputs": ["FIL"],
        "outputs": ["Filing Diff"],
        "dependencies": [],
        "cost_units": 5,
        "latency_ms": 80,
        "confidence_contribution": 0.06,
        "parallel_group": "A",
    },
    "MII": {
        "purpose": "Management intelligence",
        "answers": ["Management quality", "Tone", "Credibility"],
        "never": ["DCF"],
        "inputs": ["Transcripts", "FIL"],
        "outputs": ["Management Evidence"],
        "dependencies": [],
        "cost_units": 6,
        "latency_ms": 90,
        "confidence_contribution": 0.05,
        "parallel_group": "A",
    },
    "ACI": {
        "purpose": "Accounting intelligence / earnings quality",
        "answers": ["Earnings quality", "Accounting flags"],
        "never": ["Macro"],
        "inputs": ["FIL", "Financials"],
        "outputs": ["Accounting Flags"],
        "dependencies": ["FIL"],
        "cost_units": 6,
        "latency_ms": 70,
        "confidence_contribution": 0.07,
        "parallel_group": "B",
    },
    "EIL": {
        "purpose": "Evidence ranking and verification",
        "answers": ["Evidence quality", "Source ranking"],
        "never": ["Portfolio"],
        "inputs": ["FIL", "FDI", "MII"],
        "outputs": ["Ranked Evidence"],
        "dependencies": ["FIL"],
        "cost_units": 7,
        "latency_ms": 100,
        "confidence_contribution": 0.12,
        "parallel_group": "B",
    },
    "PIL": {
        "purpose": "Relative / peer comparison",
        "answers": ["Peer ranking", "Historical percentile", "Competitive positioning"],
        "never": ["Accounting", "Portfolio"],
        "inputs": ["EIL", "Market data"],
        "outputs": ["Peer Intelligence"],
        "dependencies": ["EIL"],
        "cost_units": 6,
        "latency_ms": 90,
        "confidence_contribution": 0.10,
        "parallel_group": "C",
    },
    "CIG": {
        "purpose": "Causal / macro transmission graph",
        "answers": ["Macro transmission", "Causal links"],
        "never": ["Technical charting"],
        "inputs": ["Macro", "EIL"],
        "outputs": ["Causal Graph"],
        "dependencies": ["EIL"],
        "cost_units": 5,
        "latency_ms": 70,
        "confidence_contribution": 0.06,
        "parallel_group": "C",
    },
    "IKG": {
        "purpose": "Institutional knowledge graph links",
        "answers": ["Entity relationships", "Ownership / supply links"],
        "never": ["Live tape"],
        "inputs": ["Entity"],
        "outputs": ["Graph Links"],
        "dependencies": ["EIL"],
        "cost_units": 4,
        "latency_ms": 50,
        "confidence_contribution": 0.05,
        "parallel_group": "C",
    },
    "FIE": {
        "purpose": "Forecast intelligence / forward paths",
        "answers": ["Base case", "Sensitivities"],
        "never": ["Final buy/sell"],
        "inputs": ["EIL", "PIL", "CIG"],
        "outputs": ["Forecast Paths"],
        "dependencies": ["EIL", "PIL"],
        "cost_units": 7,
        "latency_ms": 110,
        "confidence_contribution": 0.08,
        "parallel_group": "D",
    },
    "ILM": {
        "purpose": "Historical learning / prior thesis",
        "answers": ["Previous thesis", "Forecast accuracy", "Lessons"],
        "never": ["Live valuation"],
        "inputs": ["IKG", "Memory"],
        "outputs": ["Learning Memory"],
        "dependencies": ["IKG"],
        "cost_units": 3,
        "latency_ms": 40,
        "confidence_contribution": 0.04,
        "parallel_group": "D",
    },
    "SSL": {
        "purpose": "Decision simulation / stress",
        "answers": ["Portfolio impact", "Stress testing", "Scenario outcomes"],
        "never": ["Business quality"],
        "inputs": ["FIE", "Portfolio"],
        "outputs": ["Simulation"],
        "dependencies": ["FIE"],
        "cost_units": 9,
        "latency_ms": 150,
        "confidence_contribution": 0.05,
        "parallel_group": "E",
    },
    "Business": {
        "purpose": "Business quality / moat judgement",
        "answers": ["Moat", "Business model"],
        "never": ["PE", "DCF"],
        "inputs": ["EIL", "MII"],
        "outputs": ["Business Opinion"],
        "dependencies": ["EIL", "ILM"],
        "cost_units": 5,
        "latency_ms": 60,
        "confidence_contribution": 0.10,
        "parallel_group": "F",
    },
    "Financial": {
        "purpose": "Financial quality judgement",
        "answers": ["ROIC", "Cash conversion", "Balance sheet"],
        "never": ["Brand"],
        "inputs": ["EIL", "ACI"],
        "outputs": ["Financial Opinion"],
        "dependencies": ["EIL", "ACI"],
        "cost_units": 5,
        "latency_ms": 60,
        "confidence_contribution": 0.11,
        "parallel_group": "F",
    },
    "Valuation": {
        "purpose": "Valuation judgement",
        "answers": ["DCF", "Multiples", "Margin of safety"],
        "never": ["Moat narrative"],
        "inputs": ["PIL", "Financial", "Business"],
        "outputs": ["Valuation Opinion"],
        "dependencies": ["PIL", "Financial", "Business"],
        "cost_units": 6,
        "latency_ms": 80,
        "confidence_contribution": 0.10,
        "parallel_group": "G",
    },
    "Risk": {
        "purpose": "Risk map",
        "answers": ["Downside", "Stress risks"],
        "never": ["Buy call"],
        "inputs": ["Financial", "Macro", "EIL"],
        "outputs": ["Risk Opinion"],
        "dependencies": ["Financial"],
        "cost_units": 4,
        "latency_ms": 50,
        "confidence_contribution": 0.06,
        "parallel_group": "G",
    },
    "Sector": {
        "purpose": "Sector attractiveness",
        "answers": ["Sector outlook", "Cycle"],
        "never": ["Company DCF"],
        "inputs": ["PIL", "CIG"],
        "outputs": ["Sector Opinion"],
        "dependencies": ["PIL"],
        "cost_units": 4,
        "latency_ms": 45,
        "confidence_contribution": 0.05,
        "parallel_group": "F",
    },
    "Macro": {
        "purpose": "Macro impulse",
        "answers": ["Rates", "Inflation", "Policy"],
        "never": ["Business model"],
        "inputs": ["CIG"],
        "outputs": ["Macro Opinion"],
        "dependencies": ["CIG"],
        "cost_units": 4,
        "latency_ms": 45,
        "confidence_contribution": 0.05,
        "parallel_group": "F",
    },
    "Management": {
        "purpose": "Management assessment",
        "answers": ["Leadership quality"],
        "never": ["Portfolio sizing"],
        "inputs": ["MII"],
        "outputs": ["Management Opinion"],
        "dependencies": ["MII"],
        "cost_units": 3,
        "latency_ms": 40,
        "confidence_contribution": 0.03,
        "parallel_group": "F",
    },
    "Ownership": {
        "purpose": "Ownership / shareholding",
        "answers": ["Promoter", "FII/DII"],
        "never": ["DCF"],
        "inputs": ["IKG"],
        "outputs": ["Ownership Opinion"],
        "dependencies": ["IKG"],
        "cost_units": 2,
        "latency_ms": 30,
        "confidence_contribution": 0.02,
        "parallel_group": "F",
    },
    "Portfolio": {
        "purpose": "Portfolio fit / sizing",
        "answers": ["Sizing", "Diversification"],
        "never": ["Company valuation"],
        "inputs": ["Risk", "Valuation", "FIE"],
        "outputs": ["Portfolio Fit"],
        "dependencies": ["Risk", "Valuation", "Committee"],
        "cost_units": 5,
        "latency_ms": 55,
        "confidence_contribution": 0.05,
        "parallel_group": "H",
    },
    "Committee": {
        "purpose": "Institutional synthesis",
        "answers": ["Committee view", "Disagreement"],
        "never": ["Raw data dump"],
        "inputs": ["Business", "Financial", "Valuation", "Risk"],
        "outputs": ["Committee View"],
        "dependencies": ["Business", "Financial", "Valuation", "Risk"],
        "cost_units": 4,
        "latency_ms": 50,
        "confidence_contribution": 0.07,
        "parallel_group": "H",
    },
    "IDE V2": {
        "purpose": "Institutional decision engine",
        "answers": ["Decision framing"],
        "never": ["Primary research"],
        "inputs": ["Committee", "Portfolio"],
        "outputs": ["Decision Package"],
        "dependencies": ["Committee", "Portfolio"],
        "cost_units": 5,
        "latency_ms": 60,
        "confidence_contribution": 0.06,
        "parallel_group": "I",
    },
    "CIO": {
        "purpose": "CIO decision note",
        "answers": ["Final decision", "Reversal conditions"],
        "never": ["Raw filings"],
        "inputs": ["IDE V2"],
        "outputs": ["CIO Note"],
        "dependencies": ["IDE V2"],
        "cost_units": 3,
        "latency_ms": 40,
        "confidence_contribution": 0.04,
        "parallel_group": "I",
    },
    "Research Writer": {
        "purpose": "Institutional report writing",
        "answers": ["Report sections"],
        "never": ["Independent research without inputs"],
        "inputs": ["CIO", "Committee"],
        "outputs": ["Research Report"],
        "dependencies": ["CIO"],
        "cost_units": 6,
        "latency_ms": 90,
        "confidence_contribution": 0.03,
        "parallel_group": "J",
    },
}


def get_layer(name: str) -> dict[str, Any] | None:
    return LAYER_DEFS.get(name)


def all_layers() -> list[str]:
    return list(REGISTERED_LAYERS)


def registry_stats() -> dict[str, Any]:
    return {
        "count": len(REGISTERED_LAYERS),
        "defined": len(LAYER_DEFS),
        "complete": set(REGISTERED_LAYERS).issubset(set(LAYER_DEFS)),
    }
