"""Evidence-backed macro relationship catalog — Sprint 10.3.

Every entry includes supporting historical evidence. Nothing is published
without evidence records (historical macro / company / sector / market).
"""

from __future__ import annotations

from typing import Any


def _ev(
    kind: str,
    summary: str,
    *,
    period: str | None = None,
    refs: list[str] | None = None,
    weight: float = 1.0,
) -> dict[str, Any]:
    return {
        "kind": kind,
        "summary": summary,
        "period": period,
        "source_refs": refs or [],
        "weight": weight,
    }


MACRO_RELATIONSHIP_CATALOG: list[dict[str, Any]] = [
    # --- Monetary Policy ---
    {
        "source": "Repo Rate",
        "target": "Private Banks",
        "relationship": "Positive Credit Growth",
        "kind": "macro_to_sector",
        "direction": "Negative",  # rate down → credit up; stored as rate↑ hurts growth; see note
        "direction_note": "Repo ↓ historically associated with credit expansion for private banks",
        "evidence_strength": "High",
        "confidence_pct": 96,
        "historical_observations": 11,
        "average_lag": "2 Quarters",
        "first_observed": "2003",
        "last_confirmed": "2025",
        "chain": ["Credit Growth", "Housing Demand", "Auto Loans", "Consumption"],
        "supporting_layers": ["Historical Macro", "Historical Sectors", "Historical Companies"],
        "evidence": [
            _ev(
                "historical_macro",
                "RBI easing cycles (2003, 2019–2020) preceded private bank credit acceleration",
                period="2003-2020",
                refs=["hmip:Repo Rate:2003", "hmip:Repo Rate:2020", "hmip:Credit Growth"],
                weight=1.6,
            ),
            _ev(
                "historical_sector",
                "Private banks show NIM / volume trade-off but loan growth rises with policy easing lag",
                period="2015-2025",
                refs=["sector:financials", "company:HDFCBANK"],
                weight=1.4,
            ),
            _ev(
                "historical_company",
                "HDFC Bank credit growth episodes align with easing windows after 2-quarter lag",
                period="2016-2025",
                refs=["company:HDFCBANK", "hmip:Credit Growth:2022"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Repo Rate",
        "target": "HDFCBANK",
        "relationship": "Loan Growth Sensitivity",
        "kind": "macro_to_company",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 92,
        "historical_observations": 9,
        "average_lag": "2 Quarters",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["Private Banks", "Credit Growth"],
        "supporting_layers": ["Historical Macro", "Historical Companies"],
        "evidence": [
            _ev(
                "historical_company",
                "HDFC Bank loan book growth historically improves after RBI easing phases",
                period="2008-2025",
                refs=["company:HDFCBANK", "hmip:Repo Rate:2020"],
                weight=1.5,
            ),
            _ev(
                "historical_macro",
                "Repo timeline anchors (2019–2020 easing, 2022 hiking) map to bank volume regimes",
                period="2019-2025",
                refs=["hmip:Repo Rate:timeline"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Repo Rate",
        "target": "Housing",
        "relationship": "Affordability / Demand Impulse",
        "kind": "macro_to_sector",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 90,
        "historical_observations": 8,
        "average_lag": "2-3 Quarters",
        "first_observed": "2003",
        "last_confirmed": "2025",
        "chain": ["Housing Demand", "Auto Loans", "Consumption"],
        "supporting_layers": ["Historical Macro", "Historical Sectors"],
        "evidence": [
            _ev(
                "historical_macro",
                "Policy rate declines transmit to mortgage rates and housing volumes with lag",
                period="2003-2025",
                refs=["hmip:Repo Rate", "sector:housing"],
                weight=1.4,
            ),
            _ev(
                "historical_sector",
                "Auto / housing credit cycles correlate with RBI easing windows",
                period="2015-2021",
                refs=["sector:autos", "hmip:Credit Growth"],
                weight=1.2,
            ),
        ],
    },
    # --- Inflation ---
    {
        "source": "CPI",
        "target": "FMCG",
        "relationship": "Margin / Pricing Power Pressure",
        "kind": "macro_to_sector",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 91,
        "historical_observations": 10,
        "average_lag": "1-2 Quarters",
        "first_observed": "2013",
        "last_confirmed": "2025",
        "chain": ["Margins", "Pricing Power", "Demand"],
        "supporting_layers": ["Historical Macro", "Historical Sectors"],
        "evidence": [
            _ev(
                "historical_macro",
                "High CPI episodes (2013, 2022) coincide with FMCG input-cost and volume stress",
                period="2013-2022",
                refs=["hmip:CPI:2013", "hmip:CPI:2022", "sector:fmcg"],
                weight=1.5,
            ),
            _ev(
                "historical_sector",
                "Staples protect volumes better than discretionary; margins still compress on food inflation",
                period="2020-2023",
                refs=["sector:fmcg", "hmip:CPI:2020"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "CPI",
        "target": "ITC",
        "relationship": "Input Cost / Mix Sensitivity",
        "kind": "macro_to_company",
        "direction": "Mixed",
        "evidence_strength": "Medium",
        "confidence_pct": 78,
        "historical_observations": 6,
        "average_lag": "1 Quarter",
        "first_observed": "2015",
        "last_confirmed": "2025",
        "chain": ["FMCG", "Margins"],
        "supporting_layers": ["Historical Macro", "Historical Companies"],
        "evidence": [
            _ev(
                "historical_company",
                "ITC FMCG mix faces cost inflation; cigarettes pricing power partially offsets",
                period="2015-2025",
                refs=["company:ITC", "hmip:CPI"],
                weight=1.2,
            ),
        ],
    },
    # --- Currency ---
    {
        "source": "USDINR",
        "target": "IT Services",
        "relationship": "Revenue Translation Benefit on INR Weakness",
        "kind": "macro_to_sector",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 94,
        "historical_observations": 14,
        "average_lag": "1 Quarter",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["Exporters", "Reported Growth"],
        "supporting_layers": ["Historical Macro", "Historical Sectors", "Historical Companies"],
        "evidence": [
            _ev(
                "historical_sector",
                "IT services revenues largely USD-linked; INR depreciation lifts reported growth",
                period="2008-2025",
                refs=["sector:information_technology", "macro:USDINR"],
                weight=1.6,
            ),
            _ev(
                "historical_company",
                "Infosys / TCS report FX benefit in INR-weak periods across multiple cycles",
                period="2013-2025",
                refs=["company:INFY", "company:TCS"],
                weight=1.4,
            ),
        ],
    },
    {
        "source": "USDINR",
        "target": "INFY",
        "relationship": "USD Revenue Sensitivity",
        "kind": "macro_to_company",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 95,
        "historical_observations": 15,
        "average_lag": "1 Quarter",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["IT Services", "Revenue Growth"],
        "supporting_layers": ["Historical Macro", "Historical Companies"],
        "evidence": [
            _ev(
                "historical_company",
                "Majority of Infosys revenue USD-denominated; INR moves transmit to reported growth",
                period="FY2015-FY2025",
                refs=["company:INFY", "macro:USDINR"],
                weight=1.5,
            ),
            _ev(
                "historical_macro",
                "USD strength / INR weakness episodes align with IT exporter relative outperformance",
                period="2013-2022",
                refs=["macro:USDINR", "sector:information_technology"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "USDINR",
        "target": "Pharma",
        "relationship": "Exporter Benefit / API Import Mix",
        "kind": "macro_to_sector",
        "direction": "Mixed",
        "evidence_strength": "Medium",
        "confidence_pct": 80,
        "historical_observations": 7,
        "average_lag": "1-2 Quarters",
        "first_observed": "2013",
        "last_confirmed": "2025",
        "chain": ["Exporters", "Importers"],
        "supporting_layers": ["Historical Macro", "Historical Sectors"],
        "evidence": [
            _ev(
                "historical_sector",
                "Formulation exporters benefit from weak INR; API importers face cost headwinds",
                period="2013-2025",
                refs=["sector:pharma", "macro:USDINR"],
                weight=1.3,
            ),
        ],
    },
    # --- Commodities / Crude ---
    {
        "source": "Crude Oil",
        "target": "Airlines",
        "relationship": "Fuel Cost Shock",
        "kind": "macro_to_sector",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 93,
        "historical_observations": 12,
        "average_lag": "1 Quarter",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["Fuel Costs", "Margins"],
        "supporting_layers": ["Historical Macro", "Historical Sectors"],
        "evidence": [
            _ev(
                "historical_macro",
                "Crude spikes (2008, 2022) historically compress airline operating margins",
                period="2008-2022",
                refs=["macro:crude_oil", "sector:airlines"],
                weight=1.5,
            ),
            _ev(
                "historical_sector",
                "ATF pass-through incomplete in competitive Indian aviation",
                period="2018-2023",
                refs=["sector:airlines"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "Crude Oil",
        "target": "OMCs",
        "relationship": "Marketing Margin / Inventory Swing",
        "kind": "macro_to_sector",
        "direction": "Mixed",
        "evidence_strength": "High",
        "confidence_pct": 88,
        "historical_observations": 10,
        "average_lag": "1 Quarter",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": ["Upstream Energy", "Paint Companies", "Tyres"],
        "supporting_layers": ["Historical Macro", "Historical Sectors", "Historical Companies"],
        "evidence": [
            _ev(
                "historical_sector",
                "OMC marketing margins swing with crude and regulated pricing regimes",
                period="2008-2025",
                refs=["sector:oil_marketing", "macro:crude_oil", "company:RELIANCE"],
                weight=1.4,
            ),
            _ev(
                "historical_macro",
                "Paint / tyre input costs rise with crude; upstream energy benefits",
                period="2018-2022",
                refs=["sector:paints", "sector:tyres", "sector:upstream_energy"],
                weight=1.2,
            ),
        ],
    },
    # --- Bond markets ---
    {
        "source": "10Y G-Sec Yield",
        "target": "Banks",
        "relationship": "Duration / Treasury Portfolio Sensitivity",
        "kind": "macro_to_sector",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 90,
        "historical_observations": 9,
        "average_lag": "1 Quarter",
        "first_observed": "2013",
        "last_confirmed": "2025",
        "chain": ["NBFCs", "Real Estate", "Utilities"],
        "supporting_layers": ["Historical Macro", "Historical Sectors", "Historical Markets"],
        "evidence": [
            _ev(
                "historical_macro",
                "Yield spikes (2013 taper, 2022 hiking) pressure bank treasury MTM and NBFC funding",
                period="2013-2022",
                refs=["macro:gsec_10y", "sector:banks", "sector:nbfc"],
                weight=1.5,
            ),
            _ev(
                "historical_market",
                "Rate-sensitive sectors underperform NIFTY in sharp yield-up regimes",
                period="2022",
                refs=["market:nifty", "macro:gsec_10y"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "10Y G-Sec Yield",
        "target": "Real Estate",
        "relationship": "Funding Cost / Affordability Drag",
        "kind": "macro_to_sector",
        "direction": "Negative",
        "evidence_strength": "Medium",
        "confidence_pct": 84,
        "historical_observations": 7,
        "average_lag": "2 Quarters",
        "first_observed": "2013",
        "last_confirmed": "2025",
        "chain": ["Utilities"],
        "supporting_layers": ["Historical Macro", "Historical Sectors"],
        "evidence": [
            _ev(
                "historical_sector",
                "Higher gilt yields lift mortgage and developer funding costs with lag",
                period="2013-2025",
                refs=["sector:real_estate", "macro:gsec_10y"],
                weight=1.3,
            ),
        ],
    },
    # --- Fiscal ---
    {
        "source": "Infrastructure Spending",
        "target": "Capital Goods",
        "relationship": "Order / Capex Impulse",
        "kind": "macro_to_sector",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 89,
        "historical_observations": 8,
        "average_lag": "2-4 Quarters",
        "first_observed": "2015",
        "last_confirmed": "2025",
        "chain": ["Cement", "Engineering", "Railways"],
        "supporting_layers": ["Historical Macro", "Historical Sectors"],
        "evidence": [
            _ev(
                "historical_macro",
                "Union Budget capex thrusts historically lift capital goods and cement order books",
                period="2015-2025",
                refs=["hmip:Union Budget", "hmip:Fiscal Deficit", "sector:capital_goods"],
                weight=1.5,
            ),
            _ev(
                "historical_sector",
                "Cement / engineering / railways beneficiaries of public infra cycles",
                period="2018-2025",
                refs=["sector:cement", "sector:engineering", "sector:railways"],
                weight=1.3,
            ),
        ],
    },
    # --- Macro → Macro ---
    {
        "source": "Repo Rate",
        "target": "CPI",
        "relationship": "Monetary Transmission to Inflation",
        "kind": "macro_to_macro",
        "direction": "Negative",
        "evidence_strength": "Medium",
        "confidence_pct": 82,
        "historical_observations": 8,
        "average_lag": "3-5 Quarters",
        "first_observed": "2016",
        "last_confirmed": "2025",
        "chain": ["GDP", "Employment"],
        "supporting_layers": ["Historical Macro"],
        "evidence": [
            _ev(
                "historical_macro",
                "MPC-era hiking cycles associated with subsequent CPI moderation with long lag",
                period="2016-2025",
                refs=["hmip:Repo Rate:timeline", "hmip:CPI:timeline"],
                weight=1.4,
            ),
            _ev(
                "timeline",
                "2022 hiking → 2025 CPI moderation sequence visible in HMIP timelines",
                period="2022-2025",
                refs=["hmip:Repo Rate:2022", "hmip:CPI:2025"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "CPI",
        "target": "GDP",
        "relationship": "Real Demand / Growth Drag when Inflation Elevated",
        "kind": "macro_to_macro",
        "direction": "Negative",
        "evidence_strength": "Medium",
        "confidence_pct": 76,
        "historical_observations": 6,
        "average_lag": "2-4 Quarters",
        "first_observed": "2013",
        "last_confirmed": "2022",
        "chain": ["Employment"],
        "supporting_layers": ["Historical Macro"],
        "evidence": [
            _ev(
                "historical_macro",
                "High inflation episodes historically coincide with growth soft patches",
                period="2013-2022",
                refs=["hmip:CPI:2013", "hmip:GDP:timeline"],
                weight=1.2,
            ),
        ],
    },
    # --- Macro → Market ---
    {
        "source": "Banking Liquidity",
        "target": "NIFTY",
        "relationship": "Liquidity-Supported Risk Appetite",
        "kind": "macro_to_market",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 87,
        "historical_observations": 9,
        "average_lag": "1 Quarter",
        "first_observed": "2009",
        "last_confirmed": "2025",
        "chain": [],
        "supporting_layers": ["Historical Macro", "Historical Markets"],
        "evidence": [
            _ev(
                "historical_market",
                "Surplus liquidity regimes historically support NIFTY breadth and multiples",
                period="2009-2021",
                refs=["hmip:Banking Liquidity", "market:nifty"],
                weight=1.4,
            ),
            _ev(
                "historical_macro",
                "COVID liquidity expansion (2020) preceded strong equity recovery",
                period="2020-2021",
                refs=["hmip:Banking Liquidity:2020", "hmip:GDP:2021"],
                weight=1.3,
            ),
        ],
    },
    # --- Global → India ---
    {
        "source": "Federal Funds Rate",
        "target": "USDINR",
        "relationship": "Rate Differential / Dollar Strength Transmission",
        "kind": "global_to_india",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 91,
        "historical_observations": 10,
        "average_lag": "1 Quarter",
        "first_observed": "2013",
        "last_confirmed": "2025",
        "chain": ["FII Flows", "NIFTY"],
        "supporting_layers": ["Historical Macro", "Historical Markets"],
        "evidence": [
            _ev(
                "historical_macro",
                "Fed hiking cycles (2013 taper, 2022) historically pressure EM FX including INR",
                period="2013-2022",
                refs=["hmip:Federal Funds Rate:timeline", "macro:USDINR"],
                weight=1.5,
            ),
            _ev(
                "historical_market",
                "FII outflows and NIFTY volatility rise in Fed tightening windows",
                period="2013-2022",
                refs=["market:nifty", "macro:fii_flows"],
                weight=1.3,
            ),
        ],
    },
    {
        "source": "Federal Funds Rate",
        "target": "NIFTY",
        "relationship": "Global Liquidity / Risk-Off Transmission",
        "kind": "global_to_india",
        "direction": "Negative",
        "evidence_strength": "High",
        "confidence_pct": 86,
        "historical_observations": 8,
        "average_lag": "1-2 Quarters",
        "first_observed": "2013",
        "last_confirmed": "2022",
        "chain": ["USDINR", "FII Flows", "IT Services", "INFY", "Revenue Growth"],
        "supporting_layers": ["Historical Macro", "Historical Markets", "Historical Sectors"],
        "evidence": [
            _ev(
                "historical_market",
                "Fed hiking historically associated with EM equity drawdowns via USD and FII channels",
                period="2013-2022",
                refs=["hmip:Federal Funds Rate", "market:nifty"],
                weight=1.4,
            ),
            _ev(
                "historical_macro",
                "Transmission chain: Fed → USDINR → IT exporters relative performance mixed vs beta",
                period="2018-2022",
                refs=["macro:USDINR", "sector:information_technology", "company:INFY"],
                weight=1.2,
            ),
        ],
    },
    {
        "source": "US CPI",
        "target": "Federal Funds Rate",
        "relationship": "Inflation → Policy Response",
        "kind": "macro_to_macro",
        "direction": "Positive",
        "evidence_strength": "High",
        "confidence_pct": 93,
        "historical_observations": 8,
        "average_lag": "1-3 Quarters",
        "first_observed": "2008",
        "last_confirmed": "2025",
        "chain": [],
        "supporting_layers": ["Historical Macro"],
        "evidence": [
            _ev(
                "historical_macro",
                "US CPI spikes historically precede Fed hiking (notably 2021–2022)",
                period="2021-2022",
                refs=["hmip:US CPI:2022", "hmip:Federal Funds Rate:2022"],
                weight=1.6,
            ),
            _ev(
                "timeline",
                "HMIP US CPI and Fed Funds timelines confirm sequential relationship",
                period="2008-2025",
                refs=["hmip:US CPI:timeline", "hmip:Federal Funds Rate:timeline"],
                weight=1.2,
            ),
        ],
    },
]


def all_catalog_entries() -> list[dict[str, Any]]:
    return list(MACRO_RELATIONSHIP_CATALOG)
