"""Commodity intelligence objects — evidence-backed major users/producers only."""

from __future__ import annotations

from typing import Any

from knowledge_factory.economic_relationship_intelligence.provenance import provenance
from knowledge_factory.economic_relationship_intelligence.schema import IERI_VERSION, UNKNOWN

COMMODITY_CATALOG: dict[str, dict[str, Any]] = {
    "crude_oil": {
        "name": "Crude Oil",
        "major_users": ["airlines", "paint", "tyres", "petrochemicals", "refining"],
        "major_producers": ["ONGC", "OIL"],
        "import_dependence": "high",
        "export_dependence": "low",
        "pricing_drivers": ["OPEC+", "geopolitics", "USD", "global demand"],
        "affected_industries": ["airlines", "paint", "tyres", "petrochemicals", "logistics", "packaging"],
        "affected_companies": ["INDIGO", "ASIANPAINT", "APOLLOTYRE", "RELIANCE"],
        "source": "official_commodity_data",
        "evidence": "public_trade_and_sector_dna_oil_sensitivity",
        "available_from": "2015-01-01",
        "confidence": 0.9,
    },
    "natural_gas": {
        "name": "Natural Gas",
        "major_users": ["fertilisers", "power", "city_gas", "petrochemicals"],
        "major_producers": ["ONGC", "GAIL"],
        "import_dependence": "high",
        "export_dependence": "low",
        "pricing_drivers": ["LNG spot", "long-term contracts", "domestic APM"],
        "affected_industries": ["fertilisers", "power", "city_gas"],
        "affected_companies": ["GAIL", "PETRONET"],
        "source": "ministry_reports",
        "evidence": "PNG_LNG_public_stats",
        "available_from": "2016-01-01",
        "confidence": 0.85,
    },
    "coal": {
        "name": "Coal",
        "major_users": ["power", "cement", "steel", "aluminium"],
        "major_producers": ["COALINDIA"],
        "import_dependence": "moderate",
        "export_dependence": "low",
        "pricing_drivers": ["domestic linkage", "imports", "power demand"],
        "affected_industries": ["power", "cement", "steel"],
        "affected_companies": ["COALINDIA", "NTPC", "ULTRACEMCO", "TATASTEEL"],
        "source": "ministry_reports",
        "evidence": "coal_india_and_power_linkage",
        "available_from": "2014-01-01",
        "confidence": 0.88,
    },
    "iron_ore": {
        "name": "Iron Ore",
        "major_users": ["steel"],
        "major_producers": ["NMDC", "TATASTEEL", "JSWSTEEL"],
        "import_dependence": "low",
        "export_dependence": "moderate",
        "pricing_drivers": ["China steel demand", "domestic mining"],
        "affected_industries": ["steel", "mining"],
        "affected_companies": ["NMDC", "TATASTEEL", "JSWSTEEL"],
        "source": "industry_associations",
        "evidence": "steel_value_chain_iivi",
        "available_from": "2015-01-01",
        "confidence": 0.9,
    },
    "steel": {
        "name": "Steel",
        "major_users": ["passenger_vehicles", "construction", "capital_goods", "infra"],
        "major_producers": ["TATASTEEL", "JSWSTEEL", "SAIL", "JINDALSTEL"],
        "import_dependence": "low_to_moderate",
        "export_dependence": "moderate",
        "pricing_drivers": ["spreads", "iron_ore", "coking_coal", "China"],
        "affected_industries": ["passenger_vehicles", "construction", "capital_goods", "engineering"],
        "affected_companies": ["TATASTEEL", "JSWSTEEL", "MARUTI", "LT"],
        "source": "industry_associations",
        "evidence": "steel_iivi_and_auto_demand",
        "available_from": "2015-01-01",
        "confidence": 0.9,
    },
    "copper": {
        "name": "Copper",
        "major_users": ["electrical_equipment", "power", "electronics", "autos"],
        "major_producers": ["HINDCOPPER", "VEDL"],
        "import_dependence": "high",
        "export_dependence": "low",
        "pricing_drivers": ["LME", "China demand", "energy transition"],
        "affected_industries": ["electrical_equipment", "electronics", "power"],
        "affected_companies": ["HINDCOPPER", "POLYCAB", "HAVELLS"],
        "source": "public_trade_statistics",
        "evidence": "india_copper_import_dependence",
        "available_from": "2016-01-01",
        "confidence": 0.85,
    },
    "aluminium": {
        "name": "Aluminium",
        "major_users": ["autos", "packaging", "power", "construction"],
        "major_producers": ["HINDALCO", "NATIONALUM"],
        "import_dependence": "moderate",
        "export_dependence": "moderate",
        "pricing_drivers": ["LME", "power costs", "alumina"],
        "affected_industries": ["aluminium", "packaging", "autos"],
        "affected_companies": ["HINDALCO", "NATIONALUM"],
        "source": "official_commodity_data",
        "evidence": "aluminium_sector_public",
        "available_from": "2015-01-01",
        "confidence": 0.85,
    },
    "zinc": {
        "name": "Zinc",
        "major_users": ["galvanizing", "construction", "autos"],
        "major_producers": ["HINDZINC"],
        "import_dependence": "low",
        "export_dependence": "moderate",
        "pricing_drivers": ["LME", "mine supply"],
        "affected_industries": ["metals", "construction"],
        "affected_companies": ["HINDZINC"],
        "source": "official_commodity_data",
        "evidence": "zinc_producer_disclosures",
        "available_from": "2015-01-01",
        "confidence": 0.8,
    },
    "nickel": {
        "name": "Nickel",
        "major_users": ["stainless_steel", "batteries", "electronics"],
        "major_producers": [],
        "import_dependence": "high",
        "export_dependence": "low",
        "pricing_drivers": ["LME", "EV batteries", "Indonesia supply"],
        "affected_industries": ["stainless_steel", "electronics", "ev"],
        "affected_companies": [],
        "source": "public_trade_statistics",
        "evidence": "import_dependence_public",
        "available_from": "2018-01-01",
        "confidence": 0.75,
    },
    "lithium": {
        "name": "Lithium",
        "major_users": ["ev_batteries", "electronics"],
        "major_producers": [],
        "import_dependence": "high",
        "export_dependence": "low",
        "pricing_drivers": ["EV demand", "mine supply"],
        "affected_industries": ["ev", "electronics"],
        "affected_companies": [],
        "source": "ministry_reports",
        "evidence": "battery_materials_import_dependence",
        "available_from": "2020-01-01",
        "confidence": 0.75,
    },
    "gold": {
        "name": "Gold",
        "major_users": ["jewellery", "investment"],
        "major_producers": [],
        "import_dependence": "high",
        "export_dependence": "jewellery_exports",
        "pricing_drivers": ["USD", "real rates", "jewellery demand"],
        "affected_industries": ["jewellery"],
        "affected_companies": ["TITAN"],
        "source": "rbi",
        "evidence": "india_gold_import_demand",
        "available_from": "2014-01-01",
        "confidence": 0.9,
    },
    "silver": {
        "name": "Silver",
        "major_users": ["jewellery", "industrial", "solar"],
        "major_producers": ["HINDZINC"],
        "import_dependence": "moderate",
        "export_dependence": "low",
        "pricing_drivers": ["industrial demand", "precious metals"],
        "affected_industries": ["jewellery", "solar"],
        "affected_companies": ["HINDZINC", "TITAN"],
        "source": "official_commodity_data",
        "evidence": "silver_industrial_jewellery",
        "available_from": "2015-01-01",
        "confidence": 0.8,
    },
    "cotton": {
        "name": "Cotton",
        "major_users": ["textiles", "apparel"],
        "major_producers": [],
        "import_dependence": "variable",
        "export_dependence": "yarn_fabric",
        "pricing_drivers": ["monsoon", "MSP", "global cotton"],
        "affected_industries": ["textiles"],
        "affected_companies": ["PAGEIND", "KPRMILL"],
        "source": "ministry_reports",
        "evidence": "textile_input_public",
        "available_from": "2015-01-01",
        "confidence": 0.8,
    },
    "sugar": {
        "name": "Sugar",
        "major_users": ["fmcg", "ethanol"],
        "major_producers": ["BALRAMCHIN", "DALBHARAT"],
        "import_dependence": "low",
        "export_dependence": "policy_linked",
        "pricing_drivers": ["cane FRP", "ethanol blending", "exports"],
        "affected_industries": ["sugar", "fmcg"],
        "affected_companies": ["BALRAMCHIN"],
        "source": "ministry_reports",
        "evidence": "sugar_ethanol_policy_public",
        "available_from": "2016-01-01",
        "confidence": 0.8,
    },
    "wheat": {
        "name": "Wheat",
        "major_users": ["fmcg", "food_processing"],
        "major_producers": [],
        "import_dependence": "low",
        "export_dependence": "policy_linked",
        "pricing_drivers": ["MSP", "monsoon", "buffer stocks"],
        "affected_industries": ["fmcg", "food_processing"],
        "affected_companies": ["BRITANNIA", "NESTLEIND"],
        "source": "ministry_reports",
        "evidence": "foodgrain_public_stats",
        "available_from": "2015-01-01",
        "confidence": 0.75,
    },
    "rice": {
        "name": "Rice",
        "major_users": ["food_processing", "exports"],
        "major_producers": [],
        "import_dependence": "low",
        "export_dependence": "high_basmati",
        "pricing_drivers": ["monsoon", "export policy"],
        "affected_industries": ["agriculture", "exports"],
        "affected_companies": [],
        "source": "ministry_reports",
        "evidence": "rice_export_public",
        "available_from": "2015-01-01",
        "confidence": 0.75,
    },
    "palm_oil": {
        "name": "Palm Oil",
        "major_users": ["fmcg", "edible_oils"],
        "major_producers": [],
        "import_dependence": "very_high",
        "export_dependence": "low",
        "pricing_drivers": ["Indonesia/Malaysia supply", "import duty"],
        "affected_industries": ["edible_oils", "fmcg"],
        "affected_companies": ["MARICO", "HINDUNILVR"],
        "source": "public_trade_statistics",
        "evidence": "india_edible_oil_imports",
        "available_from": "2015-01-01",
        "confidence": 0.88,
    },
    "natural_rubber": {
        "name": "Natural Rubber",
        "major_users": ["tyres"],
        "major_producers": [],
        "import_dependence": "high",
        "export_dependence": "low",
        "pricing_drivers": ["tyre demand", "SE Asia supply", "oil synthetics"],
        "affected_industries": ["tyres"],
        "affected_companies": ["APOLLOTYRE", "MRF"],
        "source": "industry_associations",
        "evidence": "tyre_input_public",
        "available_from": "2015-01-01",
        "confidence": 0.85,
    },
    "electricity": {
        "name": "Electricity",
        "major_users": ["aluminium", "cement", "steel", "data_centers", "manufacturing"],
        "major_producers": ["NTPC", "POWERGRID"],
        "import_dependence": "low",
        "export_dependence": "low",
        "pricing_drivers": ["coal", "renewables", "demand", "tariffs"],
        "affected_industries": ["aluminium", "cement", "steel", "manufacturing"],
        "affected_companies": ["NTPC", "HINDALCO", "ULTRACEMCO"],
        "source": "ministry_reports",
        "evidence": "power_cost_industrial_users",
        "available_from": "2014-01-01",
        "confidence": 0.9,
    },
    "semiconductors": {
        "name": "Semiconductors",
        "major_users": ["electronics", "auto_electronics", "consumer_durables", "it_hardware"],
        "major_producers": [],
        "import_dependence": "very_high",
        "export_dependence": "low",
        "pricing_drivers": ["global foundry capacity", "tech cycle", "China/Taiwan supply"],
        "affected_industries": ["electronics", "consumer_durables", "auto_electronics"],
        "affected_companies": ["DIXON", "KAYNES", "SYRMA"],
        "source": "ministry_reports",
        "evidence": "semiconductor_import_dependence_pli",
        "available_from": "2020-01-01",
        "confidence": 0.88,
    },
}


def build_commodity_objects() -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for cid, raw in COMMODITY_CATALOG.items():
        obj = {
            "commodity_id": cid,
            "name": raw["name"],
            "major_users": list(raw.get("major_users") or []),
            "major_producers": list(raw.get("major_producers") or []),
            "import_dependence": raw.get("import_dependence") or UNKNOWN,
            "export_dependence": raw.get("export_dependence") or UNKNOWN,
            "pricing_drivers": list(raw.get("pricing_drivers") or []),
            "affected_industries": list(raw.get("affected_industries") or []),
            "affected_companies": list(raw.get("affected_companies") or []),
            "historical_relationships": [],
            "available_from": raw.get("available_from") or "2015-01-01",
            "confidence": raw.get("confidence", 0.75),
            "evidence": raw.get("evidence"),
            "source": raw.get("source"),
            "provenance": provenance(
                source=str(raw.get("source") or "official_commodity_data"),
                collector="ieri.commodity_catalog",
                confidence=float(raw.get("confidence") or 0.75),
                derived_from=[str(raw.get("evidence") or "public")],
            ),
            "version": IERI_VERSION,
            "fabricated": False,
        }
        out.append(obj)
    return out
