"""Deterministic investment profiles — consume BI/II; do not invent prices."""

from __future__ import annotations

from typing import Any, Optional

# Map free-text / aliases → profile key
ENTITY_ALIASES: dict[str, str] = {
    "reliance": "reliance",
    "reliance industries": "reliance",
    "ril": "reliance",
    "tcs": "tcs",
    "tata consultancy": "tcs",
    "infosys": "infosys",
    "infy": "infosys",
    "hdfc bank": "hdfc_bank",
    "hdfcbank": "hdfc_bank",
    "hdfc": "hdfc_bank",
    "asian paints": "asian_paints",
    "berger": "berger",
    "berger paints": "berger",
    "dmart": "dmart",
    "avenue supermarts": "dmart",
    "jsw steel": "jsw_steel",
    "jswsteel": "jsw_steel",
    "jsw": "jsw_steel",
    "indigo": "indigo",
    "interglobe": "indigo",
    "interglobe aviation": "indigo",
    "hospitals": "hospitals_industry",
    "indian hospitals": "hospitals_industry",
    "hospital sector": "hospitals_industry",
    "banks": "banks_industry",
    "banking": "banks_industry",
    "airlines": "airlines_industry",
    "fmcg": "fmcg_industry",
    "software": "software_industry",
    "saas": "software_industry",
    "cement": "cement_industry",
    "it services": "it_services_industry",
    "telecom": "telecom_industry",
    "utilities": "utilities_industry",
    "nbfc": "nbfc_industry",
}


def _p(
    *,
    key: str,
    name: str,
    industry: str,
    business_quality: str,
    industry_position: str,
    competitive_advantage: str,
    capital_allocation: str,
    financial_strength: str,
    growth_drivers: list[str],
    valuation_drivers: list[str],
    key_risks: list[str],
    catalysts_pos: list[str],
    catalysts_neg: list[str],
    monitoring: list[str],
    unknowns: list[str],
    quality_scores: dict[str, int],
    evidence_strength: str = "medium",
) -> dict[str, Any]:
    return {
        "key": key,
        "name": name,
        "industry": industry,
        "business_quality": business_quality,
        "industry_position": industry_position,
        "competitive_advantage": competitive_advantage,
        "capital_allocation": capital_allocation,
        "financial_strength": financial_strength,
        "growth_drivers": growth_drivers,
        "valuation_drivers": valuation_drivers,
        "key_risks": key_risks,
        "catalysts_pos": catalysts_pos,
        "catalysts_neg": catalysts_neg,
        "monitoring": monitoring,
        "unknowns": unknowns,
        "quality_scores": quality_scores,
        "evidence_strength": evidence_strength,
        "fabricated": False,
    }


PROFILES: dict[str, dict[str, Any]] = {
    "reliance": _p(
        key="reliance",
        name="Reliance Industries",
        industry="oil_gas",
        business_quality="Diversified O2C + Retail + Digital franchise with scale advantages",
        industry_position="Conglomerate leader across energy, retail, and telecom adjacency",
        competitive_advantage="Integration (O2C), retail density, Jio network scale",
        capital_allocation="Heavy organic/inorganic growth capex; portfolio recycling over cycles",
        financial_strength="Large cash generation at group level; leverage managed around growth projects",
        growth_drivers=["Retail expansion", "Digital/Jio services", "O2C optimization", "New energy optionality"],
        valuation_drivers=["Segment mix", "Retail/digital multiples", "Refining margins", "Capex intensity"],
        key_risks=["Execution on large projects", "Commodity/GRM swings", "Regulatory", "Capital intensity"],
        catalysts_pos=["Retail SSSG/store productivity", "Jio ARPU/engagement", "O2C margin recovery", "Asset monetization"],
        catalysts_neg=["Prolonged GRM weakness", "Capex overruns", "Regulatory constraints on digital/energy"],
        monitoring=["Segment EBIT mix", "Net debt / EBITDA", "Retail productivity", "Jio KPI trends", "Capex guidance"],
        unknowns=["Exact new-energy returns", "Retail unit economics by format", "Regulatory timing"],
        quality_scores={
            "business_quality": 78,
            "management_quality": 72,
            "financial_quality": 70,
            "capital_allocation": 68,
            "competitive_position": 80,
            "industry_structure": 65,
            "cash_conversion": 66,
            "balance_sheet": 68,
            "governance": 62,
            "evidence_strength": 70,
        },
        evidence_strength="medium",
    ),
    "tcs": _p(
        key="tcs",
        name="TCS",
        industry="it_services",
        business_quality="Large-scale IT services franchise with diversified client base",
        industry_position="Global tier-1 IT services; India cost + delivery scale",
        competitive_advantage="Scale, delivery excellence, client stickiness, brand",
        capital_allocation="High FCF return via dividends/buybacks; disciplined organic investment",
        financial_strength="Asset-light, strong FCF, net cash typical",
        growth_drivers=["Deal wins", "Digital mix", "Cloud/AI services", "Pricing/utilization"],
        valuation_drivers=["EPS growth", "Utilization", "Margin trajectory", "Deal TCV"],
        key_risks=["Client concentration", "Wage inflation/attrition", "FX", "Tech disruption pace"],
        catalysts_pos=["Large deal wins", "Margin expansion via utilization/offshore mix", "AI service attach"],
        catalysts_neg=["Demand slowdown in US/EU", "Attrition spike", "Pricing pressure"],
        monitoring=["Utilization", "Attrition", "Deal wins/TCV", "Vertical growth", "EBIT margin"],
        unknowns=["Duration of client spending pause", "AI monetization timing"],
        quality_scores={
            "business_quality": 82,
            "management_quality": 78,
            "financial_quality": 85,
            "capital_allocation": 84,
            "competitive_position": 80,
            "industry_structure": 72,
            "cash_conversion": 88,
            "balance_sheet": 90,
            "governance": 80,
            "evidence_strength": 78,
        },
        evidence_strength="high",
    ),
    "infosys": _p(
        key="infosys",
        name="Infosys",
        industry="it_services",
        business_quality="Global IT services with digital transformation focus",
        industry_position="Tier-1 peer to TCS; strong digital/cloud positioning",
        competitive_advantage="Delivery scale, digital offerings, client relationships",
        capital_allocation="Shareholder returns + organic capability investment",
        financial_strength="Strong FCF and balance sheet",
        growth_drivers=["Large deals", "Digital/cloud", "Pricing", "Utilization"],
        valuation_drivers=["Growth vs peers", "Margins", "Deal pipeline", "Utilization"],
        key_risks=["Demand cyclicality", "Attrition", "FX", "Competitive intensity"],
        catalysts_pos=["Deal TCV acceleration", "Margin recovery", "AI/automation productivity"],
        catalysts_neg=["Guided growth cuts", "Utilization softness", "Wage pressure"],
        monitoring=["Guidance", "Utilization", "Attrition", "Large deal wins", "EBIT margin"],
        unknowns=["Client discretionary spend recovery path"],
        quality_scores={
            "business_quality": 80,
            "management_quality": 76,
            "financial_quality": 84,
            "capital_allocation": 82,
            "competitive_position": 78,
            "industry_structure": 72,
            "cash_conversion": 86,
            "balance_sheet": 88,
            "governance": 82,
            "evidence_strength": 76,
        },
        evidence_strength="high",
    ),
    "hdfc_bank": _p(
        key="hdfc_bank",
        name="HDFC Bank",
        industry="banks",
        business_quality="Leading private bank franchise with deposit and retail strength",
        industry_position="Top private bank; merger integration with HDFC Ltd is structural",
        competitive_advantage="CASA/distribution, underwriting culture, brand",
        capital_allocation="Retain for loan growth and CET1; dividends when buffers allow",
        financial_strength="Strong deposit franchise; capital adequacy is key constraint/opportunity",
        growth_drivers=["Loan growth", "CASA", "Fee income", "Credit cost normalization"],
        valuation_drivers=["P/B vs ROE", "NIM", "Asset quality", "CET1 trajectory"],
        key_risks=["Credit cycle", "NIM compression", "Merger integration", "Regulatory"],
        catalysts_pos=["CASA recovery", "Credit cost stability", "Fee income growth", "CET1 rebuild"],
        catalysts_neg=["Asset quality stress", "Deposit cost rise", "Regulatory capital asks"],
        monitoring=["CASA ratio", "NIM", "GNPA/NNPA", "Credit cost", "CET1", "Loan growth"],
        unknowns=["Pace of deposit franchise normalization post-merger"],
        quality_scores={
            "business_quality": 84,
            "management_quality": 80,
            "financial_quality": 78,
            "capital_allocation": 76,
            "competitive_position": 85,
            "industry_structure": 74,
            "cash_conversion": 72,
            "balance_sheet": 75,
            "governance": 78,
            "evidence_strength": 80,
        },
        evidence_strength="high",
    ),
    "asian_paints": _p(
        key="asian_paints",
        name="Asian Paints",
        industry="fmcg",
        business_quality="Dominant decorative paints franchise with distribution and brand moat",
        industry_position="Clear industry leader in Indian decorative paints",
        competitive_advantage="Brand, dealer network, supply chain, pricing power",
        capital_allocation="Organic capacity + brand; consistent dividends",
        financial_strength="High ROCE franchise; strong cash conversion",
        growth_drivers=["Volume", "Premiumization", "Rural/urban mix", "Capacity"],
        valuation_drivers=["Volume growth", "Gross margin", "Competitive intensity", "ROCE"],
        key_risks=["Competitive intensity", "Input cost spikes", "Demand slowdown"],
        catalysts_pos=["Volume recovery", "Gross margin expansion", "Premium mix"],
        catalysts_neg=["Price wars", "Crude/TiO2 cost shocks"],
        monitoring=["Volume growth", "Gross margin", "Dealer additions", "Capacity utilization"],
        unknowns=["Duration of competitive pricing pressure"],
        quality_scores={
            "business_quality": 88,
            "management_quality": 82,
            "financial_quality": 86,
            "capital_allocation": 80,
            "competitive_position": 90,
            "industry_structure": 70,
            "cash_conversion": 85,
            "balance_sheet": 84,
            "governance": 80,
            "evidence_strength": 78,
        },
        evidence_strength="high",
    ),
    "berger": _p(
        key="berger",
        name="Berger Paints",
        industry="fmcg",
        business_quality="Strong #2 paints franchise improving distribution and brand",
        industry_position="Challenger to Asian Paints with share-gain ambition",
        competitive_advantage="Distribution expansion, brand investment, product mix",
        capital_allocation="Capacity and brand investment to gain share",
        financial_strength="Solid returns; typically more growth-investment heavy than leader",
        growth_drivers=["Share gains", "Volume", "Premiumization", "Network"],
        valuation_drivers=["Volume vs leader", "Margins", "Share trajectory"],
        key_risks=["Competitive response", "Input costs", "Execution on network"],
        catalysts_pos=["Share gain evidence", "Margin recovery", "Network productivity"],
        catalysts_neg=["Price competition", "Cost inflation"],
        monitoring=["Volume vs industry", "Gross margin", "Dealer network", "Ad spends"],
        unknowns=["Sustainable share-gain rate vs leader response"],
        quality_scores={
            "business_quality": 74,
            "management_quality": 72,
            "financial_quality": 72,
            "capital_allocation": 70,
            "competitive_position": 68,
            "industry_structure": 70,
            "cash_conversion": 74,
            "balance_sheet": 72,
            "governance": 74,
            "evidence_strength": 68,
        },
        evidence_strength="medium",
    ),
    "dmart": _p(
        key="dmart",
        name="DMart",
        industry="retail",
        business_quality="Value retail model with high inventory turns and owned-store bias",
        industry_position="Leading value grocery/general merchandise retailer",
        competitive_advantage="Everyday low price, store ownership model, procurement scale",
        capital_allocation="Reinvest in stores and supply chain; limited dividends historically",
        financial_strength="Strong operating cash; growth consumes capex",
        growth_drivers=["Store expansion", "SSSG", "Ticket size", "Private label"],
        valuation_drivers=["SSSG", "Store productivity", "Gross margin", "Expansion pace"],
        key_risks=["Competitive intensity", "Real estate/capex", "Execution on new cities"],
        catalysts_pos=["SSSG recovery", "New store productivity", "Private label mix"],
        catalysts_neg=["Gross margin pressure", "Slower SSSG"],
        monitoring=["SSSG", "Store additions", "Gross margin", "Inventory days"],
        unknowns=["Long-run competitive response from organized/online retail"],
        quality_scores={
            "business_quality": 80,
            "management_quality": 78,
            "financial_quality": 76,
            "capital_allocation": 74,
            "competitive_position": 78,
            "industry_structure": 60,
            "cash_conversion": 70,
            "balance_sheet": 72,
            "governance": 76,
            "evidence_strength": 72,
        },
        evidence_strength="medium",
    ),
    "jsw_steel": _p(
        key="jsw_steel",
        name="JSW Steel",
        industry="metals",
        business_quality="Scale Indian steel producer with cost and capacity ambition",
        industry_position="Large domestic steel player; cycle- and capacity-sensitive",
        competitive_advantage="Scale, integration, domestic demand exposure",
        capital_allocation="Growth capex and capacity expansion through cycles",
        financial_strength="Leverage and cash conversion swing with steel spreads",
        growth_drivers=["Capacity", "Volume", "Realization", "Mix"],
        valuation_drivers=["Steel spreads", "Utilization", "Net debt", "Cycle position"],
        key_risks=["Commodity/spread cycle", "Leverage", "Demand shock", "Project execution"],
        catalysts_pos=["Spread recovery", "Utilization uplift", "Deleveraging evidence"],
        catalysts_neg=["Spread collapse", "Capex overrun", "Demand weakness"],
        monitoring=["Realizations/spreads", "Utilization", "Net debt/EBITDA", "Capex vs guide"],
        unknowns=["Exact cycle trough/peak timing", "Project return pathways"],
        quality_scores={
            "business_quality": 68,
            "management_quality": 70,
            "financial_quality": 62,
            "capital_allocation": 64,
            "competitive_position": 72,
            "industry_structure": 55,
            "cash_conversion": 58,
            "balance_sheet": 56,
            "governance": 66,
            "evidence_strength": 64,
        },
        evidence_strength="medium",
    ),
    "indigo": _p(
        key="indigo",
        name="IndiGo",
        industry="airlines",
        business_quality="Leading India LCC with scale, utilization, and cost discipline",
        industry_position="Dominant domestic airline; structurally thin airline ROIC industry",
        competitive_advantage="Fleet scale, utilization, cost control, network density",
        capital_allocation="Fleet growth and network; balance sheet sensitive to fuel/FX",
        financial_strength="Operating leverage high; fuel and FX drive earnings volatility",
        growth_drivers=["ASK growth", "Load factor", "Yield", "International expansion"],
        valuation_drivers=["Load factor", "Yield", "Fuel", "ASK growth", "Cost/ASK"],
        key_risks=["Fuel", "FX", "Regulatory", "Competitive capacity", "Structural low ROIC"],
        catalysts_pos=["Load/yield recovery", "Cost discipline evidence", "Network productivity"],
        catalysts_neg=["Fuel spike", "Yield pressure", "Capacity wars"],
        monitoring=["Load factor", "Yield", "Fuel cost", "CASK", "ASK growth"],
        unknowns=["Sustainable yields through capacity cycles", "International returns"],
        quality_scores={
            "business_quality": 72,
            "management_quality": 74,
            "financial_quality": 60,
            "capital_allocation": 66,
            "competitive_position": 82,
            "industry_structure": 40,
            "cash_conversion": 58,
            "balance_sheet": 55,
            "governance": 70,
            "evidence_strength": 68,
        },
        evidence_strength="medium",
    ),
}

# Industry-level investment lenses (no single ticker)
for _key, _name, _ind, _bq, _pos in (
    ("hospitals_industry", "Indian Hospitals", "hospitals",
     "Asset-heavy clinical capacity with ARPOB/occupancy leverage",
     "Fragmented with consolidating chains"),
    ("banks_industry", "Indian Banks", "banks",
     "Deposit-funded lending franchises; ROE vs CET1 is the constraint",
     "Oligopolistic at the top; long tail"),
    ("airlines_industry", "Airlines", "airlines",
     "Structurally thin ROIC; load factor and fuel dominate",
     "Competitive, price-sensitive oligopoly/fragmentation"),
    ("fmcg_industry", "FMCG", "fmcg",
     "Brand + distribution drive cash conversion and pricing power",
     "Brand leaders earn structural excess returns"),
    ("software_industry", "Software / SaaS", "software",
     "High gross margin recurring revenue; growth vs FCF trade-off",
     "Winner-take-most in many categories"),
    ("cement_industry", "Cement", "cement",
     "Regional oligopolies; utilization and power/fuel costs drive margins",
     "Cyclical, capacity-sensitive"),
    ("it_services_industry", "IT Services", "it_services",
     "Utilization and wage inflation set margins; deal wins set growth",
     "Global competitive tier-1 + long tail"),
    ("telecom_industry", "Telecom", "telecom",
     "Spectrum/network capital intensity; ARPU and leverage matter",
     "Oligopoly after consolidation"),
    ("utilities_industry", "Utilities", "utilities",
     "Regulated returns on RAB; leverage supported by cash flow visibility",
     "Regulated monopolies/oligopolies by geography"),
    ("nbfc_industry", "NBFCs", "nbfc",
     "Spread over wholesale funding; asset quality and leverage define outcomes",
     "Fragmented with a few national leaders"),
):
    PROFILES[_key] = _p(
        key=_key,
        name=_name,
        industry=_ind,
        business_quality=_bq,
        industry_position=_pos,
        competitive_advantage="See Industry DNA competitive structure and Porter forces",
        capital_allocation="Industry-typical capital allocation from Industry DNA",
        financial_strength="Varies by company; evaluate at name level for precision",
        growth_drivers=["Industry demand", "Pricing/mix", "Capacity/utilization", "Share shifts"],
        valuation_drivers=["Industry-appropriate multiples from Industry DNA", "Cycle position", "ROIC"],
        key_risks=["Industry cyclicality", "Regulatory", "Competitive intensity", "Input costs"],
        catalysts_pos=["Demand recovery", "Margin expansion", "Favorable regulation", "Consolidation"],
        catalysts_neg=["Demand shock", "Cost inflation", "Adverse regulation", "Overcapacity"],
        monitoring=["Industry KPIs from Industry DNA", "Cycle indicators", "Regulatory calendar"],
        unknowns=["Company-specific execution and capital allocation quality"],
        quality_scores={
            "business_quality": 65,
            "management_quality": 55,
            "financial_quality": 60,
            "capital_allocation": 58,
            "competitive_position": 62,
            "industry_structure": 68,
            "cash_conversion": 60,
            "balance_sheet": 58,
            "governance": 55,
            "evidence_strength": 55,
        },
        evidence_strength="medium",
    )


def resolve_entity(text: Optional[str]) -> Optional[str]:
    if not text:
        return None
    low = " ".join(str(text).strip().lower().split())
    if low in ENTITY_ALIASES:
        return ENTITY_ALIASES[low]
    # longest alias first
    for alias, key in sorted(ENTITY_ALIASES.items(), key=lambda kv: -len(kv[0])):
        if alias in low:
            return key
    return None


def get_profile(key: str) -> Optional[dict[str, Any]]:
    return PROFILES.get(key)


def list_profiles() -> list[str]:
    return sorted(PROFILES.keys())
