import { useMemo, useState } from 'react';
import { API_ORIGIN } from '@/config';

const YEARS = Array.from({ length: 11 }, (_, i) => 2016 + i);
const FIELDS = [['Revenue','revenue'],['Gross Profit','gross_profit'],['EBITDA','ebitda'],['EBIT','ebit'],['PBT','pbt'],['PAT','pat'],['EPS','eps'],['Cash & Equivalents','cash'],['Total Current Assets','current_assets'],['Total Assets','assets'],['Total Current Liabilities','current_liabilities'],['Total Debt','debt'],['Total Equity','equity'],['Working Capital','working_capital'],['Cash Flow from Operations','cfo'],['Capital Expenditure','capex'],['Free Cash Flow','free_cash_flow'],['Cash Flow from Investing','cfi'],['Cash Flow from Financing','cff']];
const money = (v) => v == null ? '—' : Number(v).toLocaleString(undefined,{maximumFractionDigits:1});

export default function CompanyFinancials() {
  const [symbol, setSymbol] = useState('TCS'); const [resolvedSymbol, setResolvedSymbol] = useState('TCS'); const [year, setYear] = useState(2024); const [rows, setRows] = useState([]); const [error, setError] = useState('');
  const load = async (e) => { e?.preventDefault(); setError(''); try { const query = symbol.trim(); const resolved = await fetch(`${API_ORIGIN}/api/intelligence/company/resolve?q=${encodeURIComponent(query)}`); const identity = await resolved.json(); if (!resolved.ok) throw new Error(identity?.error || 'Company not found'); const r = await fetch(`${API_ORIGIN}/api/intelligence/company/statements/${encodeURIComponent(identity.symbol)}`); const d = await r.json(); if (!r.ok) throw new Error(d?.detail || d?.error || 'Request failed'); setResolvedSymbol(identity.symbol); setSymbol(identity.company_name || identity.symbol); setRows((d.annual || []).filter(x => x.statement_version?.startsWith('capiq_workbook_'))); } catch (err) { setRows([]); setError(err.message || 'Could not load company financials. Please retry.'); } };
  const row = useMemo(() => rows.find(x => x.fiscal_year === `FY${year}`), [rows, year]);
  return <div className="min-h-full bg-slate-50 p-6 text-slate-900"><div className="mx-auto max-w-7xl"><p className="text-xs uppercase tracking-[.2em] font-semibold text-emerald-700">Capital IQ · reported financials</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Company Financials</h1><p className="mt-2 text-slate-600">11-year CapIQ view · INR million · consolidated annual statements</p><form onSubmit={load} className="mt-6 flex gap-2"><input value={symbol} onChange={e=>setSymbol(e.target.value)} className="rounded border border-slate-300 bg-white px-3 py-2 text-slate-950" placeholder="Company name or ticker — e.g. ICICI Bank"/><button className="rounded bg-emerald-700 px-4 py-2 font-semibold text-white">Load company</button></form>{error&&<p className="mt-3 text-red-700">{error}</p>}<div className="mt-6 flex flex-wrap gap-2">{YEARS.map(y=><button key={y} onClick={()=>setYear(y)} className={`rounded px-3 py-2 text-sm font-medium ${year===y?'bg-emerald-700 text-white':'bg-white text-slate-700 border border-slate-300'}`}>FY{y}</button>)}</div><div className="mt-6 overflow-x-auto rounded border border-slate-200 bg-white"><table className="w-full text-sm"><thead className="bg-slate-900 text-left text-white"><tr><th className="p-3">FY{year} · {resolvedSymbol}</th><th className="p-3">INR million</th></tr></thead><tbody>{FIELDS.map(([label,key])=><tr key={key} className="border-t border-slate-200"><td className="p-3 font-medium text-slate-800">{label}</td><td className="p-3 font-mono text-slate-950">{money(row?.[key])}</td></tr>)}</tbody></table></div>{row&&<p className="mt-3 text-xs text-slate-600">Source: Capital IQ workbook · {row.statement_version} · {row.statement_type}</p>}</div></div>;
}
